### ISSUE TITLE
Get 1000 users of PEcAn

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#1000]
Need to figure out a way to keep PEcAn growth and track the number of users we have. It would especially be interesting to see the number of users outside of the 4 research institutes (BU, BNL, UIUC, Wisc)

**Comment by serbinsh** [comment]
Cheater cheater 🎃 eater

**Comment by serbinsh** [comment]
👍 that for sure....though even within the 4 inst we dont have 100% adoption....I need to indoctrinate a few more of our postdocs.  That is my near-term goal

**Comment by tonygardella** [comment]
During today's PEcAn telecon we brainstormed some ides to better understand our users and communicate with them:
- [ ] Courtesy follow up emails: Thanking them for download, pointing them toward PEcAn Gitter, Send small tips and tricks with PEcAn, let them know we are willing/able to help 
- [ ] Add a setup wizard to PEcAn which will set unique machine/user id if they would like and sync options. It will also optionally ask for email registration to which we will send the courtesy emails
