### ISSUE TITLE
small typo in met.process.R

### ISSUE THREAD

**Issue by yan130** [PecanProject/pecan#1002]
Hi,

I think there is a small typo in met.process.R at line 229.

"outfolder2"  is not defined or used besides this line and I think it should be "outfolder".

thanks.

**Comment by mdietze** [comment]
1. Thanks for catching that
2. If you've stumbled across this bug, it suggests you're trying to run a model with NARR meteorology without using Brown Dog to process the met. I'd strongly suggest checking the "Use Brown Dog" button in the workflow -- downloading and processing NARR locally will probably take a couple days and 1.5TB, while working with the preprocessed met in the cloud takes a minute or two

**Comment by robkooper** [comment]
@mdietze the goal for @yan130 is to try and change the BrownDog code to leverage of the met.process code, instead of the hacked version I have.

**Comment by yan130** [comment]
@mdietze @robkooper thanks for reply. 

I do use Brown dog.

I happened to find that bug without executing that line.
