### ISSUE TITLE
job.sh on remote cluster doesn't have pecan libraries

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#101]
running job.sh on the BU geo cluster gave the following error

> require (PEcAn.ED2)
Loading required package: PEcAn.ED2
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'PEcAn.ED2'
> model2netcdf.ED2('/usr4/ugrad/mgianott/geoDemo//15', 71.3225, -156.626, '2000/01/01', '2001/01/01')
Error: could not find function "model2netcdf.ED2"
Execution halted
cp: cannot stat `/usr4/ugrad/mgianott/ED.r82/ED/run/15/README.txt': No such file or directory

**Comment by robkooper** [comment]
Is this still an issue?
