### ISSUE TITLE
met2CF.NARR missing PEcAn.utils library

### ISSUE THREAD

**Issue by yan130** [PecanProject/pecan#1025]
Hi, 

I am running met.process with 

input <- list(username = "pecan", source = "NARR")

and get the following error：

> remotefunc <- function() {
> +PEcAn.data.atmosphere::met2CF.NARR('/home/polyglot/cache/PEcAn/NARR/raw','NARR','/home/polyglot/cache/PEcAn/NARR_CF/','1994-01-01 00:00:00','2002-12-31 23:59:59',format=list(file_name = "NARR", mimetype = "x-netcdf", na.strings = c("-9999", "-6999", "9999"), site = 756, lat = 35.9782, lon = -79.0942))
> +}
> > remoteout <- remotefunc()
> Loading required package: ncdf4
> Loading required package: lubridate
> Loading required package: methods
> Error: could not find function "fqdn"
> Execution halted
> [1] 1
> [1] "RESULTS: Convert.Input"

compare met2CF.NARR with met2CF.met2CF.Ameriflux ( which is running correctly), I think it should require  
PEcAn.utils library

**Comment by mdietze** [comment]
Your assessment looks correct. Could you make that fix and include it in your next PR?

**Comment by yan130** [comment]
done. https://github.com/PecanProject/pecan/pull/1006
