### ISSUE TITLE
pecan docker container

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#1028]
Create a Dockerfile that will create a simple Docker container. This container should be usable with a compose file with BETY and PostgreSQL containers.

Right now we will only have SIPNET in this container. Later we can look at other models, or get the models somehow in the container, other container..

**Comment by yan130** [comment]
my understanding is to create a Dockerfile & docker-compose.yml ( link to PostgreSQL containers)  under contrib/browndog 

and using this docker container as a converter.

right

**Comment by robkooper** [comment]
yes, containers in yaml
- pecan
- postgres
- bety

**Comment by kapoorabhishek24** [comment]
Hi, I see this is listed as one the projects in GSOC'17. I wanted to know if this is still available or someone has already started working on it. I have good experience in Docker and wanted to know if I can pursue this.Let me know. Thanks

**Comment by yan130** [comment]
Hi, I am not clear about GSOC'17. I have some code but not finished. I can push in my fork next week.

**Comment by kapoorabhishek24** [comment]
Okay, I wanted to pursue this project, Let me know if its going to be considered under GSOC'17. I was already drafting the proposal.

**Comment by istfer** [comment]
@kapoorabhishek24 thanks for your interest, could you get in touch with @robkooper and check out our [application page](http://pecanproject.github.io/gsoc_apply.html)

**Comment by kapoorabhishek24** [comment]
@istfer Thanks for the heads-up. I already emailed Rob, just waiting for his reply. Meanwhile, I will proceed with the application and Proposal. Looking forward to be working on this project.

**Comment by yogeshdarji99** [comment]
I am interested in this project for GSOC 17, I have over 3 years of experience with Docker and have dockerized more than 50 applications. I have worked for Verizon Cloud for a year where my core task to containerize and orchestrate all the application for Verizon cloud and deploy it on DataCenters using Mesos and Marathon. Currently, I am Computer Science Graduate Student at the University of Texas at Dallas and doing part-time internship at Verizon Cloud. I look forward to working on this project full-time during Summer where my skills and expertise be made use of.

**Comment by dlebauer** [comment]
@robkooper since there seems to be so much interest perhaps worth flushing out the requirements. My understanding is that there will be a group of containers. A few questions:

* is there an existing BETYdb container? 
*  is there a draft of a pecan container?
* Should models be in separate containers?
* Where should all the data or whatever is blowing the VM go?

And to everyone else ... This would be awesome to have!

**Comment by yan130** [comment]
https://github.com/yan130/pecan/blob/dockerize-pecan/contrib/browndog/Dockerfile

I upload a Dockerfile which is not finish. 
Also we want to change "FROM ncsapolyglot/polyglot:develop" to ubuntu or r-base. 
the first one is debain system.

Thanks.

**Comment by kapoorabhishek24** [comment]
@yan130 Thanks for the update. I hope this project gets selected under GSOC.

**Comment by ashiklom** [comment]
PEcAn's Docker capabilities have been fairly solid for at least a year now, so I'm making the executive decision to close this. More specific problems and enhancements to the current system should be opened as new issues.
