### ISSUE TITLE
Odd ifs in  `run.biocro.R`

### ISSUE THREAD

**Issue by bpbond** [PecanProject/pecan#1044]
Lines 47-50 or thereabouts in `models/biocro/R/run.biocro.R` are odd...not sure what's going on here. The first is missing braces and weirdly formatted; the second should cause an error, because there's no `biocro.met` defined in scope, plus no assignment is made.

``` R
if(irrigation) met$
  biocro.met <- cf2biocro(met)

if(irrigation) biocro.met$precip
```

@dlebauer ?

**Comment by infotroph** [comment]
Removed this whole section in e3a90b0baa0bd0e7eed1651e288713cfb637d04b -- BioCro no longer attempts to simulate irrigation.
