### ISSUE TITLE
Comparison used in place of assignment in model2model.GDAY.R:143

### ISSUE THREAD

**Issue by bpbond** [PecanProject/pecan#1049]
Line 143 in `models/gday/R/model2model.GDAY.R` is clearly wrong - should be an assignment, not a comparison.

```R
 if(year %% 4 == 0) {
        ndays <= 366
      } else {
        ndays <- 365
      }
```

**Comment by robkooper** [comment]
Would this be better to use:
```
yearDays(as.POSIXct(paste0(year, "-01-01"))+1
```
(not sure why but it returns number of days - 1, so 365 for leapyear)

**Comment by dlebauer** [comment]
see also #801

**Comment by bpbond** [comment]
Yeah, FWIW I second the suggestion in #801 - take advantage of the existing `lubridate`function!
