### ISSUE TITLE
Multi-Site runs do not work if different PFTs

### ISSUE THREAD

**Issue by bcow** [PecanProject/pecan#1093]
@rykelly @mdietze In `read.settings` the multisettings object is passed directly to `check.settings` as opposed to passing it through `papply`. Thus when different sites involve different PFTs the `check.settings` function doesn't know how to find the PFTs in the list. 
Should `check.settings` be modified or should we change the section from `read.settings` 
from
```
  settings <- check.settings(settings)
```
to 
```
settings <- papply(settings, check.settings)
```

**Comment by rykelly** [comment]
Sorry @bcow I'm traveling and can't check right now, but that sounds right...

**Comment by mdietze** [comment]
Sounds like the papply route is the best best then, since that seems most likely to work and most likely to keep check.settings easier to maintain

**Comment by bcow** [comment]
I take it back - I missed a fundamental part of how a multisettings xml is written. It does work. I'm closing this issue.
