### ISSUE TITLE
met.process get error

### ISSUE THREAD

**Issue by yan130** [PecanProject/pecan#1114]
## Description

when I run met.process I get the following error which I did not enter a month ago:

[1] "start CHECK Convert.Inputs download.NARR NA localhost /home/polyglot/cache/PEcAn/NARR/ NARR application/x-netcdf 1135 2001-01-01 00:00:00 2001-12-31 23:59:59"
data frame with 0 columns and 0 rows
[1] "end CHECK"
Error in .parseArg(l[[i]]) : could not find function "is.POSIXt"
Calls: met.process ... .download.raw.met.module -> convert.input -> listToArgString -> .parseArg
Execution halted
## Possible Implementation

To me, listToArgString.R need to include lubridate package.  Or is it because I run something wrong?
@robkooper if you want to reproduce, just run: Rscript PEcAn.R example.xml US-Dk3.pecan.nc

**Comment by mdietze** [comment]
I think the fix to this is in my open pull request #1112

**Comment by yan130** [comment]
@mdietze I just saw it thanks.

**Comment by yan130** [comment]
additional bug I get when I just pull the newest branch:

Error in convert.input(input.id = NA, outfolder = outfolder, formatname = register$format$name,  : 
  object 'username' not found
Calls: met.process -> .download.raw.met.module -> convert.input
Execution halted

I checked there is no definition for "username" in modules/data.atmosphere/R/download.raw.met.module.R

thanks

**Comment by mdietze** [comment]
Probably an issue with the db connection argument -- that does have a username

**Comment by mdietze** [comment]
That sounds right, as str_ns was also missing from the download module. Would be happy to quickly process a Pull Request with that fix.

**Comment by yan130** [comment]
one more bug I enter after git pull.

line 97 in mat.process.R
 `   format.vars <- query.format.vars(con = con, format.id = register$format$id)  # query variable info from format id`

while this is the definition of query.format.vars:
```
query.format.vars <- function(input.id,bety,format.id=NA,var.ids=NA){
  con <- bety$con
  ......
}
```


so I get error:

Error in query.format.vars(con = con, format.id = register$format$id) : 
  unused argument (con = con)
Calls: met.process -> query.format.vars
Execution halted

**Comment by mdietze** [comment]
@bcow this is your bug, please submit a pull request ASAP
https://github.com/PecanProject/pecan/commit/6b151343f9c4bc1af90289370ad6898366f541a7

If you change the arguments to any function, you need to make sure to grep for all uses of that function! 

Also, I'm not sure we want to be mixing conventional and dplyr connections like this throughout the code, especially if it's ambiguous which needs to be passed or if it means we need to hold both connection objects open at the same time (that seems to invite problems when people forget to check / close both)

**Comment by serbinsh** [comment]
@bcow Just to provide an update.  I am hitting the same error as above:

```
> # Do conversions
> settings <- do.conversions(settings)
     scale siteid format.id    format.name      format.mimetype
1 regional   1160        33 CF Meteorology application/x-netcdf
  format.inputtype
1               nc
Error in query.format.vars(con = con, format.id = register$format$id) : 
  unused argument (con = con)
Calls: do.conversions -> <Anonymous> -> query.format.vars
> proc.time()
   user  system elapsed 
  3.535   0.220   3.843 

```

And the met issues are from met.process.R on lines 94-99 (that I know of at the moment):

```
  # first attempt at function that designates where to start met.process
  if (is.null(input_met$id)) {
    stage <- list(download.raw = TRUE, met2cf = TRUE, standardize = TRUE, met2model = TRUE)
    format.vars <- query.format.vars(con = con, format.id = register$format$id)  # query variable info from format id
  } else {
    stage <- met.process.stage(input_met$id, register$format$id, con)
    format.vars <- query.format.vars(input.id = input_met$id, con = con)  # query DB to get format variable information if available
```

and in query.formats.vars() we need a dplyr DB connection

```
query.format.vars <- function(input.id,bety,format.id=NA,var.ids=NA){

  con <- bety$con

```

So I think we just need to reconcile the mismatch on connections, as Mike mentioned.  I just wanted to help provide some more context.  Plus Mike also listed these as other potential problems on gitter:

calc.benchmark.R
pda.get.model.output.R
pda.load.data.R

**Comment by yan130** [comment]
@bcow can you fix this real quick? we  are having a important project review in next two weeks. 

Thanks.

**Comment by bcow** [comment]
@yan130 yes I'm currently working on it! Apologies for the delay!

**Comment by mchenry** [comment]
@bcow can we get something in today?  Just encountered this too while prepping for the review...

**Comment by mdietze** [comment]
@mchenry @yan130 don't know if you caught it but the relevant PR was merged and closed an hour or two ago. Could you check your code and verify whether you're still getting problems (and if not we can close this issue)

**Comment by yan130** [comment]
@mdietze Thanks. 

I just checked. Ameriflux works fine. 

I get a new bug:

> Error in ncdf4::nc_close(test_file) : object 'test_file' not found
> Calls: remotefunc -> <Anonymous> -> closest_xy -> <Anonymous>

this is closest_xy.R
```
  nc <- ncdf4::nc_open(test.file)
  lat <- ncdf4::ncvar_get(nc, "latitude")
  lon <- ncdf4::ncvar_get(nc, "longitude")
  ncdf4::nc_close(test_file)
```

it should be  ncdf4::nc_close(test.file)

**Comment by mdietze** [comment]
Ok, can you make the change and PR?

**Comment by yan130** [comment]
sure

**Comment by yan130** [comment]
https://github.com/PecanProject/pecan/pull/1181, please review

**Comment by mchenry** [comment]
This has been resolved, right?

**Comment by mdietze** [comment]
Yep, I pulled in #1181 fairly quickly after it was posted
