### ISSUE TITLE
benchmark package cleanup

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#1128]
Following #1116 @bcow will cleanup the benchmark package.

**Comment by bpbond** [comment]
Looks like benchmark makes use of [dplyr](https://cran.r-project.org/web/packages/dplyr/index.html). Be aware that dplyr evolved a lot in the last year, with both syntactical and functional changes. I'd suggest updating to the latest version (0.5 on CRAN), if possible, and test against that.

**Comment by bcow** [comment]
@tonygardella can we close this? It seems like the main cleanup is over and code will continue to get refined after AGU.

**Comment by tonygardella** [comment]
Cleanup isn't necessarily over, but it looks like you took care of this issue in #1186.
