### ISSUE TITLE
Implement NEON's JSON-based data API

### ISSUE THREAD

**Issue by ankurdesai** [PecanProject/pecan#1140]
## Description

NEON has a draft API based on JSON interface to query and download data products. We should work on implementing an interface to this in PEcAn, both for the met drivers and flux output, and more generally for all the bio products. Given the size/scope of data, may need to start on smaller examples first.
## Context

PEcAn is supposed to work for NEON - it's in the proposal. Now that Batelle Ecology CI team has a draft API and some data rolling in (50% of sites are up and running), would be cool to define all NEON sites and be able to run there!
## Possible Implementation

download.AmerifluxLBL and download.Fluxnet2015 are examples of how JSON queries work in R. It takes some trial and error to get it right but http://data.neonscience.org/data-api# provides a range of examples and test scripts.

**Comment by mdietze** [comment]
I think there's two useful first steps here:

1) As a place to get started, pick an example data type for ingest -- given our current technology and the state of NEON's current dataset, I think met is our best bet (i.e. a download.NEON function in data.atmosphere). After that I'd vote for veg and soil initial conditions, and then moving on to general data ingest for visualization / benchmarking / assimilation.

2) For the more general data ingest we should check with relevant folks (e.g. ROpenSci, NEON) to see if anyone is planning on writing an R wrapper to the API. Not only would an R wrapper be useful, but it might help guard us against changes in the API itself.

**Comment by ankurdesai** [comment]
Two examples, might be able to just directly use these:
1. Python: https://github.com/tquaife/neonApiExamples
2. R: https://github.com/ropenscilabs/nneo
