### ISSUE TITLE
PEcAn installation not working

### ISSUE THREAD

**Issue by Viskari** [PecanProject/pecan#1148]
When I downloaded the newest version of pecan and tried running make, I got the following error:

mkdir -p .install
echo `date` > .install/devtools
Rscript -e "devtools::document('"utils"')"
Updating PEcAn.utils documentation
Loading PEcAn.utils
Loading required package: XML
Loading required package: methods
Loading required package: ggplot2
Loading required package: randtoolbox
Loading required package: rngWELL
This is randtoolbox. For overview, type 'help("randtoolbox")'.
Loading required package: abind
Loading required package: RCurl
Loading required package: bitops
mkdir -p .doc
echo `date` > .doc/utils
Rscript -e "devtools::document('"db"')"
Updating PEcAn.DB documentation
Loading PEcAn.DB
Error in (function (dep_name, dep_ver = NA, dep_compare = NA)  :
  Dependency package PEcAn.utils not available.
Calls: <Anonymous> -> load_all -> load_depends -> mapply -> <Anonymous>
Execution halted

I also ran the install.dependencies script separately to no avail. Any help on the matter would be helpful.

**Comment by mdietze** [comment]
I got a similar issue the _second_ time I ran make  and resolved it by deleting the time stamp files in the .install directory

**Comment by Viskari** [comment]
I coulnd't find any time stamp files in the .install directory, only the devtool file and if I delete that, it still leads to the same error.

**Comment by ashiklom** [comment]
Try running just `make install` -- I think I need to set the dependencies for the documentation as well as the installation.

**Comment by ashiklom** [comment]
Also, @mdietze when you ran into that issue, what terminal were you running make from? Just a regular bash shell, or the terminal in RStudio? I think the `devtools::install` command may not be recognizing `R_LIBS_USER`, though I'm not 100% sure.

**Comment by ashiklom** [comment]
Some possible solutions:
* When and where `R_LIBS_USER` gets recognized depends on where it is set. If it is set in `.bashrc`, it will _only_ be recognized by the bash shell, and not other shells (like `sh`, a more basic shell which I _believe_ is what the Rstudio terminal runs). The more general solution is to set `R_LIBS_USER` in `.profile`, which is read by all shells ([source](http://serverfault.com/a/261807)).
* Alternatively, rather than setting an environment variable, you can create an R-specific file, `~/.Rprofile` and add a line like `.libPaths("/home/masi/Rlibs")` to it.

**Comment by mdietze** [comment]
@ashiklom Sorry, I don't recall whether I'd opened the terminal from ssh or RStudio

**Comment by Viskari** [comment]
Thanks for the suggestions, Alexey. I tried all of them and none of them worked. I'm going with the stronger option now and just removing pecan and trying to re-install it from scratch.

**Comment by Viskari** [comment]
Semi-good news, maybe?

Before doing the full new installation, I pulled the latest version of PEcAn and tried running the installation again. This it got farther, but then gave this error message:

* DONE (PEcAn.DB)
mkdir -p .install
echo `date` > .install/db
Rscript -e "devtools::install('settings');"
Installing PEcAn.settings
Error in isNamespaceLoaded(pkg) :
  attempt to use zero-length variable name
Calls: <Anonymous> ... mapply -> <Anonymous> -> find.package -> isNamespaceLoade                                                                                                                                                        d
Execution halted
make: *** [.install/settings] Error 1

Any thoughts on how to fix this?

**Comment by ashiklom** [comment]
@Viskari Looks like there's something up with the `NAMESPACE` file. Try running `make .doc/settings` and then `make install`.

**Comment by Viskari** [comment]
Okay, I ran make .doc/settings and got the following error message

Error: Failure in roxygen block beginning MultiSettings.R:1
@param requires a name and description
In addition: Warning message:
In (function (dep_name, dep_ver = NA, dep_compare = NA)  :
  Need XML >= 3.98-1.3 but loaded version is 3.98-1.1
Execution halted

**Comment by ashiklom** [comment]
Ah, I think your R packages may be outdated. You can check by running, in R...

```r
library(roxygen2)
library(devtools)
sessionInfo()
```

The latest versions are Roxygen2 5.0.1 and devtools 1.12.0. If you don't have those, it may be worth reinstalling (`install.packages("roxygen2", "devtools")`).

**Comment by Viskari** [comment]
Thanks for all the help @ashiklom.

So I updated the libraries and got further, but it is still hitting issues as now I get the following error message:

no function found corresponding to methods exports from ‘raster’ for: ‘overlay’
mkdir -p .doc
echo `date` > .doc/visualization
Rscript -e "devtools::document('"models/biocro"')"
Updating PEcAn.BIOCRO documentation
Loading PEcAn.BIOCRO
Error in (function (dep_name, dep_ver = NA, dep_compare = NA)  :
  Dependency package PEcAn.settings not available.
Calls: <Anonymous> -> load_all -> load_imports -> mapply -> <Anonymous>
Execution halted

In addition to get to that point, I need to run the make .doc/settings, which does give the following warnings

Warning messages:
1: @param [MultiSettings.R#6]: requires a value
2: @return [MultiSettings.R#7]: requires a value
3: @describeIn [MultiSettings.R#34]: requires a value
4: @return [Settings.R#14]: requires a value
5: @describeIn [Settings.R#29]: requires a value
6: In FUN(X[[i]], ...) :
  incomplete final line found on '/data/home/tviskari/pecan/settings/examples/examples.papply.R'
mkdir -p .doc

**Comment by ashiklom** [comment]
Grr, OK. Looks like I need to revise the Makefile logic in a pull request. In the meantime, a temporary fix is to just to run, from the command line, `Rscript -e "devtools::install('settings')"`.

**Comment by Viskari** [comment]
That command returns with this old error message

Installing PEcAn.settings
Error in isNamespaceLoaded(pkg) :
  attempt to use zero-length variable name
Calls: <Anonymous> ... mapply -> <Anonymous> -> find.package -> isNamespaceLoaded

I tried searching for that function to see if I could figure anything out, but couldn't find it in the pecan files.

**Comment by ashiklom** [comment]
Very weird. Try installing with `R CMD INSTALL settings` instead.

**Comment by ashiklom** [comment]
Oh, figured it out. There is a trailing comma in the `settings/DESCRIPTION` file in the `Depends` field that someone (probably me) forgot to remove. Drop that and it should install fine.

**Comment by Viskari** [comment]
Okay, so with make install it now ran the installation fine to finish. Now to test that everything works like it should.

Thanks again for all the help @ashiklom

**Comment by ashiklom** [comment]
Sure thing! I would run `make document install` just to make sure that all the NAMESPACE files and such are in order with the freshly installed pecan.
