### ISSUE TITLE
Switch "var" naming convention to "nc_var"

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#1154]
## Description
@serbinsh noticed we are using the object  ```var``` to store values even though ```var() is an internal function.  This needs a cleanup.
## Context
This will help keep code clean and clear.

## Possible Implementation
Change the object ```var``` to ```nc_var```.

**Comment by serbinsh** [comment]
I can take care of this if helpful

**Comment by rahul799** [comment]
@tonygardella , @dlebauer I wanted to know that, is this issue still open ? If yes,than please assign it to me.

**Comment by dlebauer** [comment]
I think it is still relevant and have assigned it to you - thanksFor taking this on!

**Comment by robkooper** [comment]
thanks @rahul799 closing issue since pull request was merged. Next time if you add keyword `fixes` issue number, this issue would automatically be closed when the pull request is merged. See https://github.com/gitbucket/gitbucket/wiki/How-to-Close-Reference-issues-and-pull-request

**Comment by rahul799** [comment]
@robkooper actually, I have kept it open intentionally as there are many instances in the codebase which are still using var. So I think the issue must not be closed.

**Comment by moki1202** [comment]
@robkooper does this issue still need further work or is it closed?

**Comment by nanu1605** [comment]
@robkooper can I work on this issue?

**Comment by mdietze** [comment]
@nanu1605 you can double check with @moki1202 and @infotroph, but I think all the remaining tasks to do are already in the open PR #2918

**Comment by moki1202** [comment]
@nanu1605 I will be pushing more commits to PR #2918 but I am sure we can use your help there :) i can help you get started with it if it's ok with @mdietze and @infotroph.

**Comment by nanu1605** [comment]
@moki1202 DMed you on slack

**Comment by dlebauer** [comment]
implemented in #2918
