### ISSUE TITLE
Proposed updates to read.settings

### ISSUE THREAD

**Issue by rykelly** [PecanProject/pecan#1156]
## Description
I'd like to suggest a few changes to read.settings that I've half-assed implemented for my own purposes. If people like them, I'd work on the other half ass and then push them. Two things:

#### Add a block to settings that keeps track of whether `check.settings`, `update.settings`, and `fix.deprecated.settings` have been run before. 

Those functions add a flag to the block when they've been run, and by default won't do anything next time if they see the flag. This is useful if you're testing or just coming back to a workflow that's been run before, so you don't have to wait for those functions to run again unnecessarily. You might be thinking "who cares?", to which I reply "the poor sucker whose `settings` object is actually a list of 600 settings." To which you might retort "well rewrite the functions so they work more efficiently with `MultiSettings`," and I'd then have to admit "yes, that would be a great idea too but I don't have time now."

#### Allow `read.settings` to read .rda

It's *much* faster than reading the XML (again, really noticeable for a big MultiSettings). My hacky version currently saves both the XML and a .rda file after running the first time. On subsequent calls it looks to see whether the .rda has been saved already, and if so reads that by default instead of XML. 

For a cleaner version, I'd suggest that `read.settings`:

* Adds argument `format` that can be 'xml', 'rda', or 'auto'. The latter is default and decides based on file extension. 
* Adds argument `use.rda.if.available`. If `TRUE` (default), the function will look for an existing `<inputfileWithExtensionStripped>.rda`, and read that in if it's found. 
* If `inputfile` has no extension (and `format='auto'`), the function looks for `<inputfile>.rda` and `<inputfile>.xml` in that order. 

In addition, I'd add:
* A corresponding `save.settings` function that would save to .rda by default but allow saving to .xml manually if desired. Or, if folks want .xml to continue to be default that's fine with me.  Might be a good place to have a global option (similar to the `.db.utils` variable used by `PEcAn.DB`, though I think there are preferred methods) so that users can set this behavior once if desired and forget about it. 
* A function `convert.settings` to convert between formats. 

## Context
As noted, basically the work of `read.settings` and associated functions becomes nontrivial for large MultiSettings files, and these changes would make things a lot quicker. 

## Possible Implementation
See above

**Comment by mdietze** [comment]
@rykelly I like the first part (adding indicator flags) but I'm worried that the latter change moves us in the wrong direction. Specifically, we've acknowledged in the past that PEcAn is overly reliant on R-specific formats for storing intermediates, and that we need to work these out of the system where we can. Allowing the main settings file to be software specific decidedly sends us in the wrong direction.

If we all see value in a quicker, binary representation of settings I'd suggest we go with netCDF. Furthermore, I'd advocate for writing list2nc and nc2list functions that would be generic and make it easier to go to/from the R list format to netCDF.

**Comment by rykelly** [comment]
That's a good point, @mdietze. I'll keep my (.rda) version for testing then, and work on a netCDF one if and when there's time.

**Comment by bcow** [comment]
Just FYI @rykelly I originally proposed that `read.settings` have and argument for format and Rob argued against it, preferring instead individual `read. settings.format` functions. I'm on my phone so I can't type out everything we talked about but it's something that's been on my mind too.

**Comment by rykelly** [comment]
Yeah, I'd say there's no harm in having the ability to read/write to various formats, even if some (like .rda) are counter to the PEcAn paradigm. Keeping these versions as separate functions seems fine to me.

**Comment by rykelly** [comment]
#1157 took care of the first suggestion, and the second was vetoed, at least for now.
