### ISSUE TITLE
Allow groups of runs to be split into chunks to be run separately then recombined

### ISSUE THREAD

**Issue by rykelly** [PecanProject/pecan#1183]
Currently PEcAn runs for a single workflow are all handled together, but sometimes you might want to be able to split them up into subgroups to be run separately. It wouldn't be too hard to implement, so probably worth the trouble at some point. 

## Description

As far as I know, different PEcAn run strategies (local, remote, qsub, modellauncher) all revolve around getting the full list of run ids into the single runs.txt file, which then is fed into one of the several algorithms for actually getting the runs done. But in some situations (example below), you might want to chunk up the runs in some way or another and run each group separately. 

## Context
The context in which this would help me presently is doing batches of 400+ runs on geo. I'm using modellauncher which on geo can run on a maximum of 16 processors (one node). So it would be handy to be able to divide the 400-run group into smaller chunks and farm them out to multiple nodes. There are probably other use cases too. 

## Possible Implementation
As a first pass the easiest thing might be to just have the option to write separate runs.txt files (runs1.txt, etc.), store the filenames in `settings`, and then the only other change needed to existing code is to have it look for the right file. Actually, if we did that then we could give all the runs.txt files unique file names (e.g. runs_<ensembleid>_<optional_chunk_id>.txt), which would be good for provenance (because I think currently if you add runs to a workflow runs.txt just gets overwritten, right?). I could also see arguments for trying to pass around this information some other way, like within `settings` or by pulling from the db. 

The other piece to keep track of is retrieving results from all the groups and putting them back together again. I haven't worked with `get.results` for awhile so off the top of my head I don't know if there are any major hurdles. Don't think it should be too hard though.

**Comment by mdietze** [comment]
Clarification: it seems like you're just asking for better batch scheduling, not specifically for blocking or splitting up runs.txt. Is this something modellauncher can handle internally? Alternatively, start.model.runs should be handle it on it's own internally without asking run.write.configs to first break runs.txt up into chunks.

**Comment by rykelly** [comment]
It's correct that we'd want start.model.runs to handle this, not run.write.configs. But my thinking was that if it's handled at the runs.txt level, then less code needs to change downstream. So perhaps if start.model.runs is told to do so, it splits runs.txt into separate files before proceeding. Entirely possible that that's not the cleanest or easiest solution, but I thought it might be the latter at least.

(I don't think modellauncher can handle this internally, because I think the issue is the modellauncher executable only has access to the cores on its node.)

**Comment by robkooper** [comment]
You should be able to run modellauncher on multiple nodes. It is an MPI program. You might have to add the right arguments to the qsub command for example:

```
<modellauncher>
     <binary>/home/dlebauer/dev/pecan/utils/modellauncher/modellauncher</binary>
     <qsub.extra>-l ncpus=10</qsub.extra>
</modellauncher>
```

**Comment by rykelly** [comment]
Hm. I thought modellauncher is OMP, not MPI. I don't fully understand the differences, but in practice on geo at least the former is restricted to a single node. Can you clarify, @robkooper?

**Comment by mdietze** [comment]
Alternatively, is there just a way to have qsub handle this batching? For example, if you need to do 900 runs you might use modellauncher to efficiently block 10 runs/submission, but that still leaves you dumping 90 things into the queue at once. But let's say you only want to use 16 nodes at a time because dumping 90 jobs would go over your free capacity and/or cause you to get bumped far down in priority -- can you ask the queue itself to manage this? Seems odd that we have to ask start.model.runs to become a queue scheduler scheduler (meta-scheduler?)

**Comment by rykelly** [comment]
OK, so @robkooper is of course right about his own modellauncher code, and replacing my omp flag with his ncpus one (plus following BU's guidelines for requesting nodes for an MPI job) seems to have worked. 

Should I close this, or leave it open because perhaps the issue still applies to non-modellauncher methods?

**Comment by rykelly** [comment]
Though for the record, on BU the actual flag you want to use is 

```
settings$host$modellauncher$qsub.extra="-pe mpi_16_tasks_per_node 64" 
```

Where the last number is a multiple of 16 giving the total number of cores you want. More info [here](http://www.bu.edu/tech/support/research/system-usage/running-jobs/parallel-batch/).

**Comment by dlebauer** [comment]
Closing- requests a feature already supported by modellauncher
