### ISSUE TITLE
Re-organize PEcAn packages to have more precise purposes

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#1191]
I think that we currently have too few packages that each do too many things. So I wanted to start a discussion about specific functionality from certain packages that can and should be isolated. Here are some initial ideas:

* Put all `logger.*` functions to a `pecan.logger` package
* Create a small set of date-related functions, and put them in a `pecan.dates` package that can be used by `met.process` and other date-related packages.
* Pull functions related to MCMC analysis (e.g. convergence checking, burnin calculation, distributions) out of the `rtm`, `assim.batch`, and `utils` packages (and wherever else they are hiding) into a `pecan.mcmctools` package.

From [Hadley's package recommendations](http://r-pkgs.had.co.nz/namespace.html#exports)...

> I believe that packages that have a wide audience should strive to do one thing and do it well. All functions in a package should be related to a single problem (or a set of closely related problems).

From the [UNIX philosophy](https://en.wikipedia.org/wiki/Unix_philosophy):

> Write programs that do one thing and do it well.

**Comment by mdietze** [comment]
Yeah, I agree that utils in particular has gotten broad and unwieldy -- I'm open to someone going through that bit in particular post-AGU.  I think most of the others aren't bad in terms of focus.

**Comment by mdietze** [comment]
A related thing I've been thinking about is a slight re-organization of the packages in the root directory (utils, db, vis, etc) -- I think there should be a folder that's explicitly for 'core' tools so that all packages are in one of core, modules, and models. I think it might make it easier for new users to follow our conceptual organization

**Comment by ashiklom** [comment]
Closing this because I think we've actually done a decent job of this.
