### ISSUE TITLE
BUG Running SIPNET during MODEL stage

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#1198]
Both SIPNET(unk&136) failed with workflow.Rout showing:
```
2016-11-25 16:21:20 SEVERE [start.model.runs] : 
   Model run aborted, with error.  ERROR IN MODEL RUN Logfile is located at 
   '/home/carya/output//PEcAn_99000000005/out/99000000001/logfile.txt' 
> proc.time()
   user  system elapsed 
 42.000   6.504  64.712 
```
and the logfile.txt showing:
```
/home/carya/output//PEcAn_99000000005/run/99000000001/job.sh: line 34: 14635 Killed                  "/usr/local/bin/sipnet.r136"
mv: cannot stat '/home/carya/output//PEcAn_99000000005/run/99000000001/sipnet.out': No such file or directory
```
## Description
I don't think this is related to the met bug I was fixing because a valid met file was created and the correct path was in the job.sh. Something is just going wrong during model execution

**Comment by robkooper** [comment]
What site/pft/met range is this? I managed to do a sipnet v136 run for 2004 on niwot that finished correctly.

**Comment by tonygardella** [comment]
Bartlett/populus/ameriflux,  2005-2006. It will not get past met for you though until you I push my changes. I'll do that in a bit.

**Comment by jsimkins2** [comment]
I received the same error for Willow Creek/temperate deciduous/cruncep, 1999-2000. The corresponding error that I got within the VM was ```Out of memory: kill process 1960 (sipnet.runk) score 866```

**Comment by robkooper** [comment]
I have seen the problem with the out of memory issue with sipnet if the met file is not valid.

**Comment by jsimkins2** [comment]
Getting the same error in RStudio now without the 'out of memory' tag in the VM. This time was with Willow Creek/temperate deciduous/GFDL, 2006.

**Comment by jsimkins2** [comment]
```Error opening sipnet.clim for r
mv: cannot stat '/home/carya/Cheas/WCr_output/PEcAn_99000000005/run/99000005870/sipnet.out': No such file or directory```

There is no sipnet.out in any of the 'run' folders

**Comment by jsimkins2** [comment]
There is no 'sipnet.out' in any of the 'run' folders

**Comment by ankurdesai** [comment]
If sipnet fails to run, then no sipnet.out is produced. Instead, look at sipnet.clim and look for bad values, unreasonable values, missing values, NAs. Any of those will cause Sipnet to crash in a way that it just uses up memory.

**Comment by jsimkins2** [comment]
@ankurdesai ah ok that makes sense, unfortunately there is no 'sipnet.clim' in the run folders either

**Comment by tonygardella** [comment]
@jsimkins2 the job.sh in the run folder should have this line:
```
# see if application needs running
if [ ! -e "/home/carya/output//PEcAn_99000000039/out/99000000006/sipnet.out" ]; then
  cd "/home/carya/output//PEcAn_99000000039/run/99000000006"
  ln -s "/home/carya/output/dbfiles/Ameriflux_SIPNET_site_0-796/US-Bar.2005-01-01.2006-12-31.clim" sipnet.clim
```
The path after where the symbolic link is created ```ln -s``` is where the clim file should be.

**Comment by jsimkins2** [comment]
@tonygardella ah ok thanks!
