### ISSUE TITLE
Web Interface, Adding new site question.

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#1221]
When adding a new site from the web interface it seems you double click anywhere on the map to open up the window. Double clicking on the map also functions as a way to zoom in on a location, so it if I just want to just zoom in on a location it will open up the window to add a new site needlessly. Is it possible to change this so that the window opens up on a right-click or something?

**Comment by ch1eroe1** [comment]
I am looking into this.  I see that there is a way to handle the right, left, double click logic, so I will implement so we can look to see how this is behaving.  I am not sure how intuitive this will be for our end users but it is nothing they couldn't learn.

**Comment by mdietze** [comment]
Is anyone else double clicking to zoom? It'd never occurred to me to do this. 

Whatever route we go, we want it to be both intuitive and something that works cross platform (e.g. Mac, tablet, and phones don't have a right click button)

**Comment by ankurdesai** [comment]
I always double left click to zoom and center on maps with mice (pinch on touchscreens). I would assume right click context menu would be the place for more advanced things like add a site.

**Comment by mdietze** [comment]
@ankurdesai the latter bit makes sense to me -- that's what I do too in other apps but just hadn't thought about it.

So in addition to switching the behavior to right-click, could we add a note to the bottom of the page (but above the "PEcAn project is supported by NSF...") that says something like "To add a new site right-click (Mac: ctrl-click, phone/tablet: long click) on the new location"?

While your there, that footer is way out-of-date and should list all the grants that are listed on our webpage:
Acknowledgements: The PEcAn project is supported by the National Science Foundation (ABI #1062547, ABI #1458021, DIBBS #1261582, ARC #1023477, EF #1318164, EF #1241894, EF #1241891), NASA Terrestrial Ecosystems, the Energy Biosciences Institute, and an Amazon AWS in Education Grant.

**Comment by robkooper** [comment]
Updated acknowledgements as part of the version dump 1.4.9

**Comment by serbinsh** [comment]
I also double click to zoom and would rather have a right click option (just weighing in too).  Also with tablets/phones dont you just touch and hold to bring up the right click options?  On a mac laptop you can use two fingers on the track or a mouse (or whatever you ahve setup as your right click option).  

Anyway I know this is basically sorted but wanted to voice support for right click

**Comment by ch1eroe1** [comment]
Made the changes and submitted a pull request.
