### ISSUE TITLE
'standalone' R packages won't install

### ISSUE THREAD

**Issue by crollinson** [PecanProject/pecan#1258]
## Description

Many/most of the R packages [listed here](http://pecanproject.github.io/tutorials.html) will not install because of unavailable dependencies: 
`ERROR: dependencies ‘PEcAn.utils’, ‘PEcAn.DB’ are not available for package ‘PEcAn.data.atmosphere’`

I'm not sure if this is from updates to the scripts and broken dependencies or if there are additional steps for installing Pecan Packages that I'm missing that need to be clarified or more easily found in the online documentation.  The allometry module works as a stand-alone, but all of the others that I tried (data.atmosphere, "all", and meta.analysis) had the same/similar errors.

## Context

I want to stop hacking my own versions of Pecan scripts when I want a tool that I know y'all have (mostly meteorology at the moment), but the directions for installing R packages of Pecan appear to be out-of date.  I don't want to have to interface with the VM to leverage Pecan's tools.

**Comment by tonygardella** [comment]
Within the main PEcAn directory you should be able to run ```make``` and all pecan packages will download. Look [here](https://pecan.gitbooks.io/pecan-documentation/content/users_guide/maintaining_pecan/update_pecan_code.html) for options on using ```make```.

**Comment by dlebauer** [comment]
While Tony is correct, This is a known issue. A user should not have to
install all of PEcAn. We are actively working on this.

A few notes

* could installing 'all' call make?
* can PEcAn.MA run without BETYdb and PEcAn.DB (at one point the function
single.MA ran the vignette in that package- not clear if this is still
useful)
* data.atmosphere has many useful stand-alone functions

Is there an open issue for this @askilom?

**Comment by mdietze** [comment]
@crollinson could you clarify how you were trying to build? e.g. what specific command(s) were you using.

Also, while it's not super documented yet you already can build just certain parts, so I'm not sure what David meant by 'This is a known issue'. For example, if you just need data.atmosphere then you should be able to ```make .install/modules/data.atmosphere``` and it will just build that module and the modules within PEcAn that data.atmosphere depends upon. It will also only install the other R packages that those modules need.

@dlebauer I don't understand the question "could installing 'all' call make?"  do you mean you really want to type ```all``` at the command line rather than ```make``` ?

**Comment by dlebauer** [comment]
@mdietze the known issue is the lack of independence of many packages. I have never used make so I didn't know that it had gotten easier to install a package like data.atmosphere. 

What I meant by 'could installing all call make' was aimed at whether adding a makefile to the PEcAn.all package allow `R CMD INSTALL all` to trigger the PEcAn make stuff. But it sounds like the make functionality is more sophisticated than I thought making such hacks unnecessary.

**Comment by dlebauer** [comment]
Maybe it would be more clear if I said 'something we have been actively working to improve' rather than a 'known issue'

**Comment by tonygardella** [comment]
Hey Christy, I wanted to follow up with you on this. Are you still having issues with PEcAn packages?
