### ISSUE TITLE
No new NARR met files are being created

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#1259]
I can get NARR to run as a met source when a file for a spesific range of years has been created in the past, but it won't create a new file.  Examples are runs  [1000003259](http://128.197.168.115/pecan_tmccabe/08-finished.php?workflowid=1000003259), [1000003260](http://128.197.168.115/pecan_tmccabe/08-finished.php?workflowid=1000003260), [1000003296](http://128.197.168.115/pecan_tmccabe/08-finished.php?workflowid=1000003296) & [1000003297](http://128.197.168.115/pecan_tmccabe/08-finished.php?workflowid=1000003297).  It gives the error: 
"Cannot open file /projectnb/dietzelab/pecan.data/output/tmccabe/BD-4cf913d64702/ed.zip" despite the fact that the file "BD-4cf913d64702" doesn't exist, and the file "/projectnb/dietzelab/pecan.data/output/tmccabe" doesn't have restricted permissions. 

This is just one of the errors I've gotten trying to run different met drivers. If you'd like to see a summary of all the errors, I've put them into a google doc [here](https://docs.google.com/spreadsheets/d/1zGwLAkCBOABzjJZhEjZsfCVrr9zpJBTasZwyuOc69xI/edit?usp=sharing). 

@robkooper

**Comment by robkooper** [comment]
looking at the pecan.xml you are doing runs on geo, but the browndog part of the conversion is running locally, with the output path of the remote system (/projectnb/dietzelab/pecan.data/output/tmccabe).
```
 settings <- do.conversions(settings)
Error in CFILE(file, mode = "wb") :
  Cannot open file /projectnb/dietzelab/pecan.data/output/tmccabe/BD-4d3a43220be/ed.zip
Calls: do.conversions ... <Anonymous> -> browndog.met -> download.url -> CFILE -> .Call
```

**Comment by robkooper** [comment]
Looks like we need to make sure that [browndog.met](https://github.com/PecanProject/pecan/blob/master/modules/data.atmosphere/R/met.process.R#L281) runs remotely as needed.
