### ISSUE TITLE
Wiki updates - Mac OSX Install

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#128]
Some minor updates:

OpenMPI
curl -o openmpi-1.8.1.tar.gz http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.1.tar.gz
tar zxf openmpi-1.8.1.tar.gz 
cd openmpi-1.8.1
./configure --prefix=/usr/local
make all
sudo make install
cd ..

HDF5 (now v 1.8.13)
curl -o hdf5-1.8.13.tar.gz http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.13.tar.gz
tar zxf hdf5-1.8.13.tar.gz
cd hdf5-1.8.13
sed -i -e 's/-O3/-O0/g' config/gnu-flags 
./configure --prefix=/usr/local/hdf5 --enable-fortran --enable-cxx --with-szlib=/usr/local/szip
make
# make check
sudo make install
# sudo make check-install
cd ..

**ED2 needs updating to reflect GitHub changes

**Comment by robkooper** [comment]
@serbinsh can this be closed?

**Comment by serbinsh** [comment]
Closed
