### ISSUE TITLE
Repository/directory Structure of PEcAn Documentation

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#1282]
Currently, the source .Rmd files for PEcAn Documentation are held in the "book_source" directory of the main `PecanProject/pecan` repository. The `deploy.sh` script currently is configured to render html files and commit/push those files to a separate repository called `PecanProject/pecan-documentation`.

## Description
Is this the best way to organize the .Rmd files and html files? or should we keep all files in the main repository and push html files to a separate branch?

## Context
Going forward, our documentation will get more complex and the size of the pages will increase as we integrate more tools and media types into the documentation (i.e. shiny apps, videos, vignettes, tables from BETY, etc.). We need to think about what's the best way to store and organize documentation without making it hard to edit or navigate.

## Possible Implementation
We could possibly split documentation into BETYdb docs or separate out sections of the PEcAn docs (e.g. tutorials / demos, or users vs developers).

**Comment by ashiklom** [comment]
I think we should continue to push documentation to a different repository.

I think our `.Rmd` file organization should mirror the structure of the actual book:

```
documentation_source/
| 01.basic_users_guide/
|   | 01.getting_started/
|   |   | 01.section_1.Rmd <--- Chapters with multiple sub-sections in separate files
|   |   | 02.section_2.Rmd
| 02.advanced_user_guide_web/
|   | 01.using_browndog.Rmd   <--- Chapters that are a single file
...etc...
```

**Comment by dlebauer** [comment]
When I raised the question I didn't realize that the source was in the pecan repository... I misunderstood and thought there were separate source and publish documentation repositories.

But for organization I think it could be easier to maintain some parts like shiny apps etc if vignettes, readmes and other docs could be incorporated from their current homes in their respective packages.

**Comment by ashiklom** [comment]
@dlebauer I think that can be readily accommodated. In bookdown, you can specify a list of target files in the `_bookdown.yml` file, so we can just point some of those to any PEcAn directory.

**Comment by mdietze** [comment]
👍  sounds good @ashiklom.  Could you or @tonygardella provide an example -- I agree with David that it makes sense to keep the vignettes, etc. in place.  As a starting point you could just create a section of the book called "Package Vignettes" or something like that.

@tonygardella is there anything else we need to discuss in this issue?

**Comment by tonygardella** [comment]
@mdietze @dlebauer @ashiklom Makes sense! If we get a GSOC student for documentation I believe this will be part of the project so I'll make sure vignettes and apps are stored this way.

**Comment by ashiklom** [comment]
We've pretty significantly overhauled the documentation over the last 2-ish years, so I'm going to make the executive decision to close this. If there are more specific problems with the documentation, we should address those in separate, more precise issues.
