### ISSUE TITLE
Update BioCro module to use the PEcAn met workflow 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#1283]
## Description

Currently the BioCro module is written to read files in PEcAn CF format directly, and has custom functions for downscaling and conversion to the BioCro input format. 

* Reading is done by the function [`PEcAn.data.atmosphere::load.cfmet`](https://github.com/PecanProject/pecan/blob/master/modules/data.atmosphere/R/load.cfmet.R) that is called from with the [`PEcAn.BIOCRO::run.biocro()`  on line 31](https://github.com/PecanProject/pecan/blob/master/models/biocro/R/run.biocro.R#L31)
* Downscaling is done by the function [`PEcAn.data.atmosphere::cfmet.downscale.time`](https://github.com/PecanProject/pecan/blob/master/modules/data.atmosphere/R/temporal.downscaling.R) 

However, these functions assume that there is already a PEcAn-CF compliant file existing on disk. 

It also does the downscaling within the BioCro specific functions.The met downscaling should be done outside of the `run.biocro()` function, but either @ankurdesai, @jsimkins2, or @bcow would be the ones to ask about that (it is not clear in documentation). 

Helpful documentation:

* [Adding an ecosystem model](https://pecanproject.github.io/pecan_bookdown/adding-an-ecosystem-model.html)
* [Met Data](https://pecanproject.github.io/pecan_bookdown/met-data.html)

## Completion Criteria

* [ ] BioCro should work from within the website for at least two sites for a few met products
  * NARR
  * CRUNCEP
  * AMERIFLUX-LBL
* [ ] To be determined

**Comment by infotroph** [comment]
TODO:
- [ ] Remove all met conversion code from run.biocro, just read a CSV per year
- [ ] Make met2model.BIOCRO write converted met to CSV instead of returning it
- [ ] Fix existing tests that assume CF met input
- [ ] Test new conversion code
- [ ] Move load.cfmet (and maybe others?) from modules/data.atmosphere to models/biocro

**Comment by infotroph** [comment]
I think this is complete. @dlebauer please open new issues if you find any remaining problems.
