### ISSUE TITLE
Conversion checkbox on 02-modelsite.php page hidden behind label (and not clickable)

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#1290]
Summary: When viewed in Safari, the "conversion" checkbox in `web/02-modelsite.php` is rendered overlapping its label text, and therefore unclickable.

## Description
Expected alignment, shown here in Chrome 56.0.2924.87 on OS X 10.11.6:
<img width="110" alt="screen shot 2017-03-22 at 10 55 37 am" src="https://cloud.githubusercontent.com/assets/1256435/24204194/205b9b6c-0eee-11e7-91e3-3b69d60e67ef.png">

Buggy alignment in Safari 10.0.3 on OS X 10.11.6: 
<img width="144" alt="screen shot 2017-03-21 at 8 15 01 pm" src="https://cloud.githubusercontent.com/assets/1256435/24204135/f6fddba4-0eed-11e7-9025-62b5a752e9bc.png">

The checkbox still works in every other respect and can still be toggled by keyboard, so this is merely annoying and doesn't prevent me from running any models. 

## Possible Implementation
Brief, amateur experimentation suggests the overlap is caused by how Safari handles the combination of `label, input{display:block;}` and `#stylized label{float:left;}`. Removing either directive is sufficient to remove the overlap in Safari with little change to its appearance in Chrome, but IANAWebDeveloper and I make no claim whether this is the correct approach for aesthetics or cross-browser functionality.

**Comment by dlebauer** [comment]
Just to clarify this can't be toggled by the mouse pointer, so it is a non-trivial bug.

**Comment by infotroph** [comment]
Bump because newer builds of Safari make this worse instead of better:

When I originally reported this, an easy workaround was to select the Site Group menu, press tab to select the conversion checkbox, then toggle it using the space bar. 

Tab still works in Safari 10.1.1 (11603.2.5) on OS X 10.11.6, but in Safari 10.1.1 (12603.2.4) on OS X 10.12.5 the conversion box isn't present in the tab order at all. The easiest workaround I've found is to reload the page appending '?conversion=true' to the URL.

**Comment by infotroph** [comment]
Fix from @mdietze works! Still can't tab to the checkbox in Safari/Sierra, but I now see that's true for *all* the checkboxes, so that's a different issue.
