### ISSUE TITLE
Biocro: Detect and report errors from job.sh

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#1307]
As [discussed](https://github.com/PecanProject/pecan/issues/794#issuecomment-290406049) in #794, during BioCro runs any errors-- or in fact any console output --from job.sh are not reported back to the user, so status.check("OUTPUT") always returns 0 and the first sign of possible trouble in workflow.Rout is from read.output:

 ```
2017-03-30 09:31:12 INFO   [read.ensemble.output] : 
   reading ensemble output from run id: 99000000007 
2017-03-30 09:31:12 WARN   [read.output] : 
   read.output: no netCDF files of model output present for runid = 
   99000000007 in /home/carya/output//PEcAn_99000000015/out/99000000007 
   will return NA 
```

The promised NA then produces an obvious plotting error at the end of the file:

```
Error in hist.default(my.dat, xlab = units, main = "", cex.axis = 1.1,  : 
  invalid number of 'breaks'
Calls: runModule.run.ensemble.analysis -> run.ensemble.analysis -> hist -> hist.default
```

## Description

To fix, capture errors from job.sh and relay them back to the user.

## Context

Note that biocro.Rscript *does* generate useful error messages and that job.sh *does* send these to stderr, they're just not captured by the PEcAn workflow. One workaround for debugging is to navigate to the run directory, invoke job.sh directly, and observe its output there.

## Possible Implementation

I see two possible ways to fix this. 

Local to BioCro: Improved error-handling in BioCro's job.sh, possibly combined with more vigorous output validation in model2netcdf.BIOCRO.

PEcAn-wide: It appears that PEcAn.utils::start.model.runs will only signal model failure if the captured output from job.sh contains the literal string "ERROR IN MODEL RUN". Should this be generalized to detect a wider range of conditions?

**Comment by dlebauer** [comment]
@robkooper what are your suggestions for handling errors in job.sh? Are there any conventions for this? ,

**Comment by infotroph** [comment]
Looks like #1308 fixed the immediate issue here -- closing unless there's more to discuss.
