### ISSUE TITLE
Clean up biocro check output

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#1309]
`devtools::check("models/biocro")` currently produces a mess of NOTES about documentation and imports/depends problems. Should clean these up at least to the point of being able to see more important warnings.

## Description

- [x] convert in-function `library()` calls to `@import`, qualify out-of-package functions with `::`, etc. 
- [x] Add missing @param descriptions, fix misc Roxygen errors
- [ ] ? suppress "global variable" notes from data.table calls? The messages are spurious (all variables are defined in the table they're operating on), but annoying. May not be worth the trouble unless anyone's planning a CRAN submission.

I'll tackle this after the changes for #1283 are completed.

**Comment by infotroph** [comment]
Most of these have been fixed piecemeal since I opened this, but four NOTEs remain:

```
R CMD check results
0 errors | 0 warnings | 4 notes
checking package dependencies ... NOTE
Package suggested but not available for checking: ‘RNCEP’

checking DESCRIPTION meta-information ... NOTE
License components with restrictions not permitted:
  FreeBSD + file LICENSE

checking top-level files ... NOTE
Non-standard file/directory found at top level:
  ‘BioCro_demo.Rmd’

checking R code for possible problems ... NOTE
cf2biocro: no visible binding for global variable ‘relative_humidity’
cf2biocro: no visible binding for global variable ‘air_temperature’
cf2biocro: no visible binding for global variable ‘precipitation_flux’
convert.samples.BIOCRO: no visible binding for global variable ‘b0’
convert.samples.BIOCRO: no visible binding for global variable ‘Sp’
convert.samples.BIOCRO: no visible binding for global variable ‘vmax’
convert.samples.BIOCRO: no visible binding for global variable ‘Rd’
model2netcdf.BIOCRO: no visible binding for global variable ‘Year’
run.biocro: no visible binding for global variable ‘doy’
... 10 lines ...
run.biocro: no visible binding for global variable ‘CanopyTrans’
run.biocro: no visible binding for global variable ‘Grain’
run.biocro: no visible binding for global variable ‘LAI’
run.biocro: no visible binding for global variable ‘precip’
Undefined global functions or variables:
  AboveLitter BelowLitter BioGro CanopyTrans Grain LAI Leaf Rd Rhizome
  Root SoilEvaporation Sp Stem Temp Year air_temperature b0 doy precip
  precipitation_flux relative_humidity vmax
Consider adding
  importFrom("datasets", "precip")
to your NAMESPACE file.
```

I propose to:

- [ ] Remove RNCEP from Suggests -- all functions that use it appear to have been removed
- [ ] Ignore license note -- this is the same wording used by the rest of PEcAn
- [ ] Delete BioCro_demo.Rmd -- vignettes/C4grass_sa_vd.Rmd covers essentially the same ground
- [ ] Ignore `no visible binding` -- my understanding is that fixing them would require making the offending `data.table` calls WAY uglier. Note that the "consider adding..." suggestion is spurious -- R is guessing, wrongly, that "precip" might mean the build-in precip dataset. 

Thoughts @dlebauer ?

**Comment by mdietze** [comment]
1) Remove RNCEP: sounds good
2) Licence: I don't know why this says "FreeBSD + file LICENSE", which doesn't appear to be a valid entry (it can't both be FreeBSD and under another license listed in the file), nor accurate because the LICENCE file itself, and almost every file header in the system, says it's under NCSA license. I'm curious, does this note go away if you change this line to ```License: NCSA```?
3) 👍 
4) probably fine

**Comment by dlebauer** [comment]
Agreed to all except 2. FreeBSD+ file LICENSE is a convention that @robkooper implemented and is used by most packages. I'm not sure  of the rationale, but it seems to be used in most  PEcAn packages.

**Comment by infotroph** [comment]
On a cursory inspection, it looks as if "BSD_3_clause + file LICENSE" does quiet the warning, but 

- IANAL and specifically I don't know if "FreeBSD" and "BSD 3 clause" are equivalent statements.
- Recall that this note exists purely to enforce a CRAN policy. If we're not planning to be on CRAN and the current phrasing is clearer or more legally correct, I favor ignoring the note.

**Comment by mdietze** [comment]
@infotroph, does "NCSA" without the "+ file LICENSE" work?

**Comment by infotroph** [comment]
@mdietze Nope. The check only accepts licenses that match an entry in https://svn.r-project.org/R/trunk/share/licenses/license.db

**Comment by bpbond** [comment]
>Ignore no visible binding

The problem is that these can obscure more important notes and warnings. One solution to this is to use dummy variables, e.g. near the top of the `convert.samples.BIOCRO` function add

```R
b0 <- Sp <- vmax <- Rd <- NULL  # silence packages check notes
```
