### ISSUE TITLE
Unable to install RPostgreSQL on R 3.1.0 and Mac OSX 10.9

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#131]
Installed postgres using Rob's suggestion for a binary (includes PostGIS)

Trying to install RPostgreSQL driver from source.  Fails:

```
> install.packages("~/Downloads/RPostgreSQL_0.4.tar.gz", repos = NULL, type="source")
...
...console output...
...
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c RS-DBI.c -o RS-DBI.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c RS-PQescape.c -o RS-PQescape.o
In file included from RS-PQescape.c:7:
./RS-PostgreSQL.h:23:14: fatal error: 'libpq-fe.h' file not found
#    include "libpq-fe.h"
             ^
1 error generated.
make: *** [RS-PQescape.o] Error 1
ERROR: compilation failed for package ‘RPostgreSQL’
* removing ‘/Users/sserbin/R/library/RPostgreSQL’
Warning in install.packages :
  installation of package ‘/Users/sserbin/Downloads/RPostgreSQL_0.4.tar.gz’ had non-zero exit status
```

**Comment by codegordi** [comment]
For anyone searching on this error, note that you might also have to 
`sudo ln -s /usr/local/Cellar/postgresql /usr/local/opt/postgresql`
or similar if you install using homebrew. Otherwise you may see the error
`Library not loaded: /usr/local/opt/postgresql/lib/libpq.5.dylib` because of reason `image not found`.
even after successfully resolving the `libpq-fe.h not found` error noted at the top of this thread.

**Comment by nelsonauner** [comment]
I fixed this with: 
`> install.packages('DBI')`
`$ brew install postgresql` (possible unnecessary)
`$ sudo ln -s /usr/local/Cellar/postgresql /usr/local/opt/postgresql`

Not sure which one did the trick, but it works now

**Comment by norrishd** [comment]
I had the same issue and just needed to install `libqp-dev` to solve the issue:

`sudo apt-get install libpq-dev`

**Comment by AbrahamHuitron** [comment]
> I had the same issue and just needed to install `libqp-dev` to solve the issue:
> 
> `sudo apt-get install libpq-dev`

Thanks for this!
