### ISSUE TITLE
Biocro: undefined variable 'SoilP'

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#1317]
[run.biocro.R, line 56](https://github.com/PecanProject/pecan/blob/master/models/biocro/R/run.biocro.R#L56):

```tmp.result <- caneGro(WetDat = WetDat, lat = lat, soilControl = soilP)```

`soilP` is not defined anywhere else in the file. Should it be replaced with `l2n(config$pft$soilControl)` as in the Miscanthus and Salix calls, or does caneGro take a different set of soil control parameters?

**Comment by infotroph** [comment]
cc @dlebauer for BioCro model specifics

**Comment by dlebauer** [comment]
Yes this is a typo. Please update the soil parameters.
