### ISSUE TITLE
Add ability to add notes from web

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#134]
As the production databases start to get up and running (and start to fill with runs) it would be great if the user had the option to put information about a run (why they were doing it) into the ensembles.notes field at some point in the web workflow. It would also be great if those showed up in the History page so that we can search for them.

**Comment by robkooper** [comment]
does it make sense to add this to the ensemble or the workflow.  To me it makes more sense to add it to the workflow since the note entered in the web interface is the same for all the ensemble runs. While the notes per ensemble are more uniquer for each ensemble run.

**Comment by robkooper** [comment]
Talked with @ankurdesai and decided to have web page add notes to workflow. This allows user to specify specific ensemble notes.

**Comment by robkooper** [comment]
See https://github.com/PecanProject/bety/pull/358
