### ISSUE TITLE
Add user.id to either ensembles or workflows

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#135]
If we're all writing to the same database, and additionally are mirroring across systems, it seems like knowing WHO did a set of runs would be helpful when sorting and searching.  For systems that require login from the web we then know the user, for anonymous runs I guess this is 'carya' or something like that (or we could just leave the field NULL). For command-line runs we can add user to the pecan.xml if it's not already there.

I'm not 100% sure whether a user.id should be associated with the ensembles or the workflows. workflows seems more in keeping with the fact that site_id, model_id, and hostname are all stored with workflows rather than ensembles (but we're already displaying that info in the History table)

**Comment by mdietze** [comment]
@robkooper can this be closed?

**Comment by robkooper** [comment]
need to still add code to add user_id to ensembles.

**Comment by mdietze** [comment]
@robkooper did the user_id issue in workflows and ensembles make it into BETY yet? Or does this need to be punted to the next release?

**Comment by robkooper** [comment]
workflows has user.id and is already filled in if a user.id is known.
ensembles currently does not have user.id nor is it filled in.

**Comment by robkooper** [comment]
@mdietze do we need a user.id with ensembles/runs?

**Comment by mdietze** [comment]
I don't think so, just Workflows should be fine.
