### ISSUE TITLE
Loading data from machine 6 (terra-ref) is broken.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/pecan#1355]
## Description
Attempting `./load.bety.sh -r 6 ...` most likely will result in a schema mismatch error.

## Context
Some slight differences in the schema being used for the the terra-ref site from those used on the EBI site were implemented using Rails migrations not checked into the Git repository.  At the time I decided to implement things this way I did not fully understand how the `load.bety.sh` script checks the schemas to see that they are compatible.

## Possible Implementation
Since the migrations used on machine 6 that are not used elsewhere do not affect table structure (they only add constraints and change the views to materialized ones), it would seem that the schema on machine 6 should still be compatible with the "official" schema used elsewhere.  A possible (slightly hackish) fix might be to simply remove a few rows from the `schema_migrations` table in the database used by machine 6.

**Comment by gsrohde** [comment]
For now, I've removed the "extra" rows from the `schema_migrations` table to see if this resolves the immediate problem.  In the long term, it is to be hoped that exactly the same schema can be used everywhere.

**Comment by robkooper** [comment]
This is a problem with this specific installation BETY. The version of BETY running on bety6 is not compliant with the latest version of the source code from BETY.

**Comment by gsrohde** [comment]
@robkooper Yes, I think so.
