### ISSUE TITLE
csv delimiters for use with `data()`

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#1384]
## Description

Is modules/data.atmosphere/met.lookup.csv intended for loading via `data()`?
If yes, should it be converted to semicolon-delimited?

## Context
In `met2CF.*`, it would be convenient to have a lookup table of standard CF variable names/units to use when validating the incoming data. I'm guessing that `modules/data.atmosphere/data/met.lookup.csv` is intended to be exactly that, and that the intended usage is something like:

```
met2CF.whatever <- function(whatever_dat, ...){

    utils::data("met.lookup", package = "PEcAn.data.atmosphere", envir = environment())

    for ( var in names(whatever_dat$vars)) {
        if (!(var %in% met.lookup$CF_standard_name)) {
            # ...convert to a standard name if possible or throw error if not...
        }
        ...
   }
   ...
}
```

The catch is that `utils::data` [treats *.csv as **semicolon** delimited](https://github.com/wch/r-source/blob/trunk/src/library/utils/man/data.Rd#L54) (?!?), and thus returns a dataframe with 1 instead of 7 columns.

@mdietze You edited `met.lookup.csv` last -- is the use case above compatible with the file's original purpose, and is a delimiter change the sensible approach?

**Comment by infotroph** [comment]
Looks like the only current reference to met.lookup is [this commented-out line](https://github.com/PecanProject/pecan/blob/develop/db/R/query.format.vars.R#L74) in `query.format.vars`. How do we feel about `read.csv(system.file("/data/met.lookup.csv", package = "PEcAn.data.atmosphere"), ...)` instead of `data`?

**Comment by dlebauer** [comment]
@infotroph we generally prefer `read.csv(system.file(...` to `data(...` because the semi-colon delimited format required by `data` is archaic and more finicky than `read.csv`.

**Comment by infotroph** [comment]
@dlebauer Great, I think that sorts this.
