### ISSUE TITLE
Develop Branch and PR #1353 Failing for similair reason

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#1396]
PR #1353 and DEVELOP Branch are both failing TRAVIS with similar errors: 
#1353 [build log is here](https://travis-ci.org/PecanProject/pecan/builds/231213871?utm_source=github_status&utm_medium=notification)
```
Rscript -e "devtools::install('modules/data.atmosphere', Ncpus = 1);"
Installing PEcAn.data.atmosphere
Using GitHub PAT from envvar GITHUB_PAT
Using GitHub PAT from envvar GITHUB_PAT
Downloading GitHub repo ropenscilabs/nneo@master
from URL https://api.github.com/repos/ropenscilabs/nneo/zipball/master
Error in stop(github_error(request)) : Bad credentials (401)
Calls: <Anonymous> ... remote_download -> remote_download.github_remote -> download_github
Execution halted
make: *** [.install/modules/data.atmosphere] Error 1
```
Develop [Build log is here](https://travis-ci.org/PecanProject/pecan/builds/231199176)
```
Rscript -e "devtools::install('modules/data.atmosphere');"
Installing PEcAn.data.atmosphere
Using GitHub PAT from envvar GITHUB_PAT
Downloading GitHub repo ropenscilabs/nneo@master
from URL https://api.github.com/repos/ropenscilabs/nneo/zipball/master
Error in stop(github_error(request)) : Bad credentials (401)
Calls: <Anonymous> ... remote_download -> remote_download.github_remote -> download_github
Execution halted
make: *** [.install/modules/data.atmosphere] Error 1
```
## Description
Looks like something is wrong with the GITHUB_PAT Travis environment variable but that's only used in the rendering of documentation so I'm not sure.

**Comment by robkooper** [comment]
GITHUB_PAT is used by devtools to pull down anything from github. This to get around the rate limiter that github has for anonymous fetching of  data from github. I generated a new token and replaced GITHUB_PAT with this.

**Comment by tonygardella** [comment]
@robkooper I did that about 7 minutes ago. That's why I closed it. Thanks though!
