### ISSUE TITLE
Enable PEcAn to run BioCro v>= 1.0

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#1400]
The new version of BioCro has different inputs and outputs.

It is run thus: 

```r
library(BioCro)
Gro(initial_state              = sorghum_initial_state, 
       parameters              = sorghum_parameters, 
       varying_parameters = weather05, 
       modules                   = sorghum_modules)
```

Key changes:

1. No longer crop-specific functions
2. parameters are now two lists: initial conditions and parameters (instead of many, as before)
3. 'WetDat' changed to varying_parameters 
   * this is pretty cool because parameters can be moved from parameters to varying_parameters if, e.g., they vary.
4. Output is different. Need to check names 

I _think_ everything can be handled by just updating the `run.biocro` function to check if the version is < or >= to 1.0

### TODO

* [x] need to register new version of BioCro in models page
    * can be linked to same biocro.Rscript files
* [ ] update run.biocro to handle new parameterization

**Comment by justinmcgrath** [comment]
Another big difference is that the `Gro` function does not change the time period in the weather data. `BioGro` and `willowGro` would truncate the period, and you could use `day1` and `dayn` to specifiy which days are truncated. With `Gro`, you pass only the times at which you want a solution, so you would truncate first. The number of rows in the result is always the same as the number of rows in varying_parameters. To reproduce the default behavior of `BioGro`, the function `get_growing_season_climate` is provided for convenience.

```
Gro(initial_state              = sorghum_initial_state, 
       parameters              = sorghum_parameters, 
       varying_parameters = get_growing_season_climate(weather05), 
       modules                   = sorghum_modules)
```

**Comment by dlebauer** [comment]
@infotroph do you have a reproducible workflow for download,Geostreams met2CF.Geostreams and met2model.BIOCRO?

I've got this so far. 

```r
library("PEcAn.data.atmosphere")
library("dplyr")

ne <- download.Geostreams(
  outfolder="~/gstest",
  sitename="UIUC Energy Farm - NE",
  start_date="2016-03-01",
  end_date="2016-03-31")

met2CF.Geostreams(in.path = "~/gstest", 
                  in.prefix = "Clowder.UIUC Energy Farm - NE", 
                  outfolder = ".gstest/cf",
                  start_date = "2016-03-01 06:00:00", 
                  end_date = "2016-03-31 05:00:00")

```

which fails because date / time matching in the filename (is this fix on a fork/branch?)

**Comment by infotroph** [comment]
@dlebauer Getting 500 errors from Clowder right now, so this is untested, but after #1420 I think it should be something like this:

```
library("PEcAn.data.atmosphere")
library("PEcAn.BIOCRO")
library("dplyr")

ne <- download.Geostreams(
  outfolder="~/gstest",
  sitename="UIUC Energy Farm - NE",
  start_date="2016-02-28",
  end_date="2016-03-31")

ne_cf <- met2CF.Geostreams(
  in.path = "~/gstest", 
  in.prefix = "Clowder.UIUC Energy Farm - NE.2016-02-28.2016-03-31", 
  outfolder = ".gstest/cf",
  start_date = "2016-03-01", 
  end_date = "2016-03-31")

ne_bc <- met2model.BIOCRO(
  in.path = "~/gstest/cf", 
  in.prefix = "Clowder.UIUC Energy Farm - NE.2016-02-28.2016-03-31", 
  outfolder = ".gstest/biocromet",
  lat = 40,
  lon = 88,
  start_date = "2016-03-01", 
  end_date = "2016-03-31")
```

**Comment by robkooper** [comment]
Clowder was down at 9.20pm, up now.

**Comment by dlebauer** [comment]
Here is a sample config as .xml and as an R list https://gist.github.com/dlebauer/a8b9a9a4f2523c2937e9547475219c9e

**Comment by mdietze** [comment]
If the new version of BioCro has different inputs and outputs, it may make sense to register it as a different ModelType with a new PEcAn.BioCro package, rather than asking the current package to be backward compatible and handle two very different interfaces.

**Comment by dlebauer** [comment]
@mdietze I've been on the fence about this - the new version uses the same met workflow and there are relatively few changes to the parameters, and outputs. I think that only write.configs.BIOCRO and the function that actually calls BioCro needs to be changed. Each of these functions has an `if(packageVersion('BioCro') >=1.0` clause to handle the new case. A first draft is in the [biocro-v1](https://github.com/pecanproject/pecan/tree/biocro-v1) branch. 

Another option would be to deprecate support for earlier versions of BioCro once the new version is supported.

**Comment by dlebauer** [comment]
Here is a branch biocro-v1 with some draft changes that @justinmcgrath and I worked through a few months ago

**Comment by infotroph** [comment]
The biocro-v1 branch still has some rough edges, but is done enough to be ready for some feedback. Anyone willing to take it for a spin?

Currently failing on Travis, probably because it expects a numeric model revision and gets `"git"` instead. I think I can override this in the test files.

Here's how I set up a side-by-side run of the Bondville Miscanthus test in BioCro 0.9 and BioCro 1.0:

```
# Update these to match your system...
# export WORKDIR="$HOME"/biocro_version_comparison
# export PECAN_ROOT=~/pecan
# cd "$PECAN_ROOT" && git checkout biocro-v1 && git pull upstream biocro-v1 && make

mkdir -p "$WORKDIR"
cd "$WORKDIR"

mkdir -p Rlib_bc09
R_LIBS_USER=Rlib_bc09 Rscript -e 'devtools::install_github("ebimodeling/biocro")'

mkdir -p Rlib_bc1
R_LIBS_USER=Rlib_bc1 Rscript -e 'devtools::install_github("ebimodeling/biocro", ref="new-framework")'

# Let's pause to check whether the installation worked as expected --
# On some systems I have to set R_LIBS instead of R_LIBS_USER and I don't understand why
export R_LIBS_USER=Rlib_bc09
[[ `Rscript -e 'packageVersion("BioCro")'`  == "[1] ‘0.95’" ]] || echo "Wrong BioCro"
export R_LIBS_USER=Rlib_bc1
[[ `Rscript -e 'packageVersion("BioCro")'`  == "[1] ‘1.0’" ]] || echo "Wrong BioCro"


mkdir -p bc09_test
cp "$PECAN_ROOT"/tests/pecan64.biocro.xml bc09_test
sed -i '' \
	-e 's!StemBiom!AbvGrndWood!' \
	-e $'s!<type>BIOCRO</type>!&\\\n    <revision>0.95</revision>!' \
	-e 's!/home/carya/pecan!'"$PECAN_ROOT"'!' \
	bc09_test/pecan64.biocro.xml

mkdir -p bc1_test
cp "$PECAN_ROOT"/tests/pecan64.biocro.xml bc1_test
sed -i '' \
	-e 's!StemBiom!AbvGrndWood!' \
	-e $'s!<type>BIOCRO</type>!&\\\n    <revision>1.0</revision>!' \
	-e 's!/home/carya/pecan!'"$PECAN_ROOT"'!' \
	bc1_test/pecan64.biocro.xml

cd bc09_test
R_LIBS_USER="$WORKDIR"/Rlib_bc09 "$PECAN_ROOT"/web/workflow.R pecan64.biocro.xml

cd ../bc1_test
R_LIBS_USER="$WORKDIR"/Rlib_bc1 "$PECAN_ROOT"/web/workflow.R pecan64.biocro.xml
```

Both runs complete successfully, but `bc1_test` only has about half the biomass seen in `bc09_test`!

**Comment by justinmcgrath** [comment]
What parameters are used?

**Comment by infotroph** [comment]
For the 0.95 run: `models/biocro/inst/extdata/defaults/miscanthus_default.xml`. For the 1.0 run: `BioCro::miscanthus_x_giganteus_*`

**Comment by justinmcgrath** [comment]
When I run

BioCro 0.9
data(weather05)
result = BioGro(weather05)

BioCro 1.0
new_result = Gro(miscanthus_x_giganteus_initial_state, miscanthus_x_giganteus_parameters, get_growing_season_climate(weather05), miscanthus_x_giganteus_modules)


I get 
result$Stem[4273] is 16.27821
new_result$Stem[4272] is 16.65367

The number of rows are different due to a bug in the old version, and the values are different for a variety of reasons, but they are pretty similar. 

The new version does not automatically clip the weather data. That would result in very different values, but I think it would make the new version larger, not smaller.

I'm looking at stem mass since that's what it looks like the above script is examining. Is that what you're looking at?

**Comment by infotroph** [comment]
Yeah, was looking at stem initially, but here's the full PEcAn output plus some quick comparison graphs: https://www.dropbox.com/sh/2ykr9xn2temm0en/AAAM3uDwptbOQhPKeGL7APRla?dl=0

**Comment by justinmcgrath** [comment]
It looks like it's probably related to the soil parameters or the soil models. In the versions you're using, the soil models should be identical, and I can't reproduce the difference, so I think different soil parameters are being used in the two models. There were a couple of name changes, so maybe it's using the wrong name for the new version. However, I can't figure out what parameters Pecan is using.
