### ISSUE TITLE
Enable dump/load.bety.sh to dump/load all data in a database regardless of source 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#1406]
Per https://github.com/terraref/computing-pipeline/issues/302#issuecomment-300935868

The TERRA REF project, we have transferred some but not all of the data from the PEcAn network. Therefore, it is not possible to use the current load.bety.sh functionality to sync. 

Some examples include
* variables
* pfts, priors
* a single species record

There are a few options. One that @robkooper agreed would work would be to 

1. dump all records from bety0, bety6, bety8 to separate files 
2. modify load.bety.sh so that the -r parameter can take an optional path to the dump. If it is an integer, it will find the default path but if it is a filepath or url it will load from there. 

### Discussion

* this doesn't solve the problem of keeping the existing records in sync with the database in which the record was created (e.g. if a record that I have imported from bety0 to bety6 is changed in bety0, bety6 will never get the updates. 
* for this reason, it may make more sense to just change all records in bety6 to the bety6 range (6-7billion). I could update these like `update sites set id = 6000000000+id where id < 1000000000`. This would keep the database networks separate.
* this would make it impossible for the PEcAn network to import data from, e.g., bety6 since the duplicate records would violate uniqueness constraints, but perhaps this could be fixed by removing all foreign records `where id like '61%'`

**Comment by dlebauer** [comment]
@robkooper when I try to run the following on bety8:

```sh
./scripts/load.bety.sh -d bety_mepp -a bety -m 99 -r 0 -w https://terraref.ncsa.illinois.edu/bety/dump/bety0/bety.tar.gz
./scripts/load.bety.sh -d bety_mepp -a bety -m 99 -r 6 -w https://terraref.ncsa.illinois.edu/bety/dump/bety6/bety.tar.gz
```

I get a lot of errors ([load.bety.errors.txt](https://github.com/PecanProject/pecan/files/1020704/load.bety.errors.txt)) related to constraints. Am I missing a step?

**Comment by robkooper** [comment]
looks like some of order in which rows are added removed break things, for example looks like formats is used by inputs, so you can't remove  a row from formats until it is removed from inputs.

**Comment by robkooper** [comment]
load-bety.sh now disables constraints and has option for -w parameter to specify path to dump file.
