### ISSUE TITLE
Make always installs all packages

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#1410]
## Description

```
git checkout develop
make
make
```

Expected: any changed packages are built once, second invocation of `make` reports "nothing to be done".

Observed: The whole install process runs twice, rebuilding all packages both times. 

## Context

I think this was introduced in f8810a0848831a6e40cc6a1769640c9af7dc7cee by the change from `.install/devtools` to `devtools` (and ditto `roxygen` etc.).

## Possible Implementation

Two possibilities:

1. Change back from `devtools`, `roxygen`, `testthat` to `.install/devtools`, `.install/roxygen`, `.install/testthat`. Tested locally, works for me.
2. <del>Add `devtools`, `roxygen`, `testthat` to .PHONY? Not yet</del> tested <ins>, doesn't fix the problem.

To verify fix:
* [ ] test that `make; make` in a VM updates all the changed packages, none of the unchanged packages, and does nothing on second invocation.
* [ ] confirm that Travis runs still behave correctly.

**Comment by mdietze** [comment]
@infotroph seems simple enough to reverse the changes made in f8810a0. You mind submitting that as a small PR?
