### ISSUE TITLE
Documentation Diagrams

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#1411]
I have gotten requests to include different diagrams of parts of PEcAn within documentation so I wanted to collect people's ideas or get materials if they already have diagrams.

## Description
I'll be using the [DiagrammeR](http://rich-iannone.github.io/DiagrammeR/) package to make diagrams.

## Possible Implementation
1. General Diagram of Workflow

**Comment by tonygardella** [comment]
@bcow I know you have some good diagrams so let me know what you have!

**Comment by dlebauer** [comment]
@robkooper had a script that generated a diagram of modules and inputs / outputs a few years ago. Can't find it now but I think it is in the repository.

**Comment by dlebauer** [comment]
It is here https://github.com/PecanProject/pecan/blob/develop/qaqc/vignettes/module_output.Rmd

**Comment by infotroph** [comment]
Closing as unactionable. If you have specific diagram requests, please open them as their own issues.
