### ISSUE TITLE
Error if pecan.xml specifies CRUNCEP with no site ID

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#1414]
## Context

I have a settings file with a minimal met section (other sections that I hope are irrelevant omitted):

```
    <inputs>
      <met>
        <source>CRUNCEP</source>
        <output>BIOCRO</output>
      </met>
    </inputs>
```

When run, this downloads raw data and then fails with a pretty cryptic error:

```
[...]
2017-05-23 11:18:55 DEBUG  [convert.input] : 
   Convert.Inputs met2model.BIOCRO localhost 
   /home/a-m/black11/.pecan/dbfiles/CRUNCEP_BIOCRO_site_8-4906 biocromet 
   text/csv 8000004906 2006-01-01 2006-12-31 
2017-05-23 11:18:55 INFO   [convert.input] : 
   start CHECK Convert.Inputs met2model.BIOCRO localhost 
   /home/a-m/black11/.pecan/dbfiles/CRUNCEP_BIOCRO_site_8-4906/ biocromet 
   text/csv 8000004906 2006-01-01 2006-12-31 
Warning in is.na(parentid) :
  is.na() applied to non-(list or vector) of type 'NULL'
Error in if (is.na(parentid)) { : argument is of length zero
Calls: do.conversions ... .met2model.module -> convert.input -> dbfile.input.check
```

Digging around in `met.process.R`, it appears that CRUNCEP and NARR are [special-cased](https://github.com/PecanProject/pecan/blob/develop/modules/data.atmosphere/R/met.process.R#L156) to skip the CF conversion and gapfill steps...

```
    if (met %in% c("CRUNCEP", "GFDL")) {
      ready.id <- raw.id
      stage$met2cf <- FALSE
      stage$standardize <- FALSE
    }
```

... but then at the standardize step, skipping gapfill leads to `ready.id` being [reassigned](https://github.com/PecanProject/pecan/blob/develop/modules/data.atmosphere/R/met.process.R#L214):

```
   if (stage$standardize) {
    [...]
  } else {
    ready.id = input_met$id
  }
```

In my case `input_met` == `list(source="CRUNCEP", output="BIOCRO")`, so we enter the met2model stage with ready.id as NULL. After getting passed from .met2model.module to convert.input to dbfile.input.check, this null eventually produces the visible error message.

## Possible Implementation

If the `ready.id <- raw.id` assignment on line 157 is the correct one to pass forward, the easiest patch is probably to add a condition to line 214:

```
} else {
  if (!exists("ready.id")){ # don't override if set in download.raw
    ready.id = input_met$id
  }
}
```

This was enough to let my test workflow run with no error, but please check my work for unwanted side effects.

**Comment by mdietze** [comment]
@infotroph I think your proposed fix looks good, could you PR?

This bug is my fault. I added the else case that sets ready.id to input.met$id in response to another bug -- if ```stage``` caused the download, met2cf, and standardize steps to be skipped, then the met2model stage was failing because ready.id was undefined (even though it's presence in input.met was what caused the preceding stages to be skipped). Your proposed fix shouldn't interfere with the edge case I was addressing.

**Comment by infotroph** [comment]
This might be fixed by https://github.com/PecanProject/pecan/pull/1436/commits/25557afad04fe9f660d5b553855d7c444aba6eb2 -- assigning myself so I remember to test and close.

**Comment by infotroph** [comment]
Just tried and failed to reproduce this, so I reckon it's fixed. Thanks!
