### ISSUE TITLE
Error in query.format.vars

### ISSUE THREAD

**Issue by eliandrotavares** [PecanProject/pecan#1432]
EDIT: first error "region site id is not defined" followed by "argument is of length 0"
I pulled the latest changes from develop branch and rebuilt pecan. Gave a run at Hubbard Brook, SIPNET, 2003-2005, with CRUNCEP and got an error:

```
> settings <- PEcAn.utils::do.conversions(settings)
2017-06-01 11:07:17 DEBUG  [PEcAn.utils::logger.debug] : 
   do.conversion outdir /fs/data1/pecan.data/dbfiles 
2017-06-01 11:07:17 INFO   [PEcAn.utils::logger.info] : PROCESSING:  met 
2017-06-01 11:07:17 INFO   [PEcAn.utils::logger.info] : 
   calling met.process: 
     scale format.id    format.name      format.mimetype format.inputtype
1 regional        33 CF Meteorology application/x-netcdf               nc
2017-06-01 11:07:17 ERROR  [read.register] : 
   Region site id is not defined 
Error in if (format$vars$storage_type[i] != "") { : 
  argument is of length zero
Calls: <Anonymous> -> <Anonymous> -> query.format.vars
```

Could it be related to the recent changes or am I missing something?

**Comment by mdietze** [comment]
Also note that the FIRST error you get is ```ERROR  [read.register] :  Region site id is not defined```. In general you want to sort out errors in the order they pop up because often later errors are caused by earlier errors.

**Comment by eliandrotavares** [comment]
Issue edited @mdietze

**Comment by eliandrotavares** [comment]
Error remains the same after updating pecan to the latest version. Ran all three Hubbard brook sites (LTER, Thorton, and Laconia) with the FATES model for Thorton and Laconia and SIPNET model for LTER, all for the years 2003-2004 (advanced settings applied 100 runs and -2,-1,1,2 sensitivity).

CRUNCEP used for all and then NARR used for Thorton (id: PEcAn_1000004894)

Error message for CRUNCEP runs:
```
2017-06-02 09:33:49 ERROR  [read.register] : 
   Region site id is not defined 
Error in if (format$vars$storage_type[i] != "") { : 
  argument is of length zero
Calls: <Anonymous> -> <Anonymous> -> query.format.vars
> proc.time()
```
Error for NARR - could not process model FATES

Workflow IDs:
PEcAn_1000004894
PEcAn_1000004893
PEcAn_1000004892

**Comment by mdietze** [comment]
1) As noted before, the first error is in the registry file, which can't find the met data product's site ID (which should be earth land surface for CRUNCEP). That needs to be fixed first.

2) Don't run FATES yet

3) walk before you run -- get a single site, non-ensemble, no SA run working first (Demo 1) before you try to do >100 runs (Demo 2)
