### ISSUE TITLE
Incomplete/inaccurate documentation for dbfile.insert* functions

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#1445]
A few of the ```dbfile*``` functions contain incomplete explanations of parameters passed, or in the case of ```dbfile.insert()```  explains parameters that aren't listed as a function option. 

## Description
```formatname``` is documented as a parameter in [dbfile.insert](https://github.com/PecanProject/pecan/blob/7cba8596cbb3d3a636a084be913a95a5dbd19ed4/db/R/dbfiles.R#L347), despite not being used in the code.  Parameters ```type```, ```id```, and ```reuse``` are not explained and ```in.path```, and ```in.prefix``` are not explained throughout. 

## Possible Implementation
A quick check that all variables documented are used, and that all used variables are documented.

**Comment by infotroph** [comment]
I believe the most urgent parts of this were done in #1809. Further cleanup is always welcome, but at least `R CMD check` no longer reports code-documentation mismatches.
