### ISSUE TITLE
PEcAnRTM: Algorithm ideas

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#1446]
## Description
* [ ] Set jump covariances to zero (i.e. use diagonal jump variance-covariance matrix) until after `n` iterations, as set by the user.
* [ ] Randomly shuffle jump covariance matrix among chains after every `n` iterations...or some other approach where information is periodically exchanged across chains. This may improve mixing.

## Context
These changes may improve convergence of Metropolis Hastings sample in PEcAn RTM, which is becoming more important as the sampler is put to more complex challenges (e.g. EDR inversion).

Attn: @serbinsh

**Comment by ashiklom** [comment]
One potential algorithm/approach: https://en.wikipedia.org/wiki/Parallel_tempering

**Comment by ashiklom** [comment]
A book containing valuable information on additional approaches: https://books.google.com/books?id=TRXrMWY_i2IC&lpg=PA89&ots=7h_rqnKtnx&dq=improve%20mcmc%20chain%20mixing&lr&pg=PA104#v=onepage&q=improve%20mcmc%20chain%20mixing&f=false

**Comment by mdietze** [comment]
1. Could you explain better exactly what the actual issue is?
2. Rather than monkeying around with alternative ways to adapt the adaptive M-H, why not try alternative algorithms that converge faster and are already implemented (e.g. DE and DREAM in BayesianTools, which is a package already being used in PEcAn)
3. I thought you were looking at trying a SMC approach?

**Comment by ashiklom** [comment]
1. Sorry, was just making a quick note before I forgot. Basically, @serbinsh and I were monitoring some EDR inversions and were seeing extremely slow/bad convergence -- chains were stuck in relatively narrow local minima for a very long time. (Shawn -- maybe you could link to one of the figures you had up?) .

2. Good idea. Every time I've tried to do PROSPECT inversion using any of those algorithms, I've been unable to get any good sampling, probably because of operator error. Now that the package is more mature (?), I would definitely be interested in trying again. I just wanted to throw up these ideas while they were fresh on my mind.

3. SMC is good for PROSPECT inversion, where the number of parameters is low, but I thought it might become less tractable for something like EDR, where the number of parameters is 7-12 x the number of unique PFTs (so for three cohorts, 21 - 36). But maybe not -- there may be a clever way of doing it that of which I'm not aware. You mentioned there were clever ways of leveraging Reimann integration (?) and similar interpolation techniques to reduce the number of samples required while still covering the likelihood space. Maybe we can discuss more in person tomorrow?

**Comment by ashiklom** [comment]
Closing because `BayesianTools` was implemented in #1569. Will re-open if this becomes a problem again.
