### ISSUE TITLE
NA strings field for formats record

### ISSUE THREAD

**Issue by bcow** [PecanProject/pecan#1460]
Add a text field to BETY formats that stores NA strings separated by commas.

**Comment by bcow** [comment]
Maybe something like this?

```
class AddNA_stringsformats < ActiveRecord::Migration
  def up
    add_column :formats, :NA_strings, :text,  :null => false
  end

  def down
    remove_column :formats, :NA_strings
  end
end
```

**Comment by mdietze** [comment]
Issues related to changes to database schema should be filed under https://github.com/PecanProject/bety
