### ISSUE TITLE
CRUNCEP download url changed to https

### ISSUE THREAD

**Issue by annethomas** [PecanProject/pecan#1465]
@ankurdesai @jsimkins2 

The thredds website just changed its url syntax from http to https. That results in a download error in PEcAn for CRUNCEP data.

I tried a run at US-Wkg for 1990-2009 and got these errors with at this point in the download:
```
> PEcAn.utils::logger.info(dap_file)
2017-06-13 17:00:46 INFO   [PEcAn.utils::logger.info] : 
   http://thredds.daac.ornl.gov/thredds/dodsC/ornldaac/1220/mstmip_driver_global_hd_climate_tair_1990_v1.nc4 
> dap <- ncdf4::nc_open(dap_file)
syntax error, unexpected WORD_STRING, expecting WORD_WORD
context: Error { code = 404; message = "ornldaac/1220/mstmip_driver_global_hd_climate_tair_1990_v1.nc4"^;};
Error in R_nc4_open: NetCDF: file not found
Error in ncdf4::nc_open(dap_file) : 
  Error in nc_open trying to open file http://thredds.daac.ornl.gov/thredds/dodsC/ornldaac/1220/mstmip_driver_global_hd_climate_tair_1990_v1.nc4
```
That url doesn't exist, but if you truncate it to https://thredds.daac.ornl.gov/thredds/catalog.html, you reach a notice that says "NOTICE: SDAT and THREDDS website and web service URLs will change to HTTPS on 2017-06-12. Read more."

I guess the download.CRUNCEP function needs to be updated.

**Comment by ankurdesai** [comment]
Thanks for pointing this out @annethomas Will get a fix soon.

**Comment by ankurdesai** [comment]
Uh oh, this looks more complicated. Looks like MSTIMIP CRUNCEP has moved to NASA, THREDDS catalog is empty! https://thredds.daac.ornl.gov/thredds/catalog/ornldaac/1220/catalog.html @jsimkins2 Know good contacts here?

**Comment by jsimkins2** [comment]
Just sent some emails out, hopefully we get a response soon!

**Comment by jsimkins2** [comment]
Contacted Deborah Huntzinger at NAU, she said their looking into it now

**Comment by jsimkins2** [comment]
Problem Solved. There was a glitch in the system. The new THREDDS server is up and running. I'll add the changes to my current PR

**Comment by ankurdesai** [comment]
Great. Glad it was simple.
