### ISSUE TITLE
How should we store URLs in the database?

### ISSUE THREAD

**Issue by LiamBurke24** [PecanProject/pecan#1474]
In approaching the longterm objective of building an automated data download/ ingest function for PEcAn, an immediate concern is how we should store URLs of data files that will not be automatically opened by our software (e.g. .pdf)

Generally speaking, the download/ ingest function will flag MIMEtypes that are unreadable like .pdfs and bin them in some sort of holding folder for the user to open manually. 

I'd appreciate any and all suggestions about how we should proceed here!

**Comment by tonygardella** [comment]
@LiamBurke24 Has this question been answered elsewhere yet?

**Comment by dlebauer** [comment]
@LiamBurke24 could you provide specific examples? 

* If they are documentation, can they be stored as citations?
* If they are data files, where you want to keep a local copy, what is wrong with storing them in the same way as other files?

**Comment by infotroph** [comment]
I agree with that citation or local file seems like it covers all the use cases, so I'll close and tag @dlebauer and @mdietze to object and reopen if needed.
