### ISSUE TITLE
Web interface returns error if PEcAn xml is edited in any way

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#1484]
If the pecan.xml is edited from the web interface it is saved with an additional space at the top, which means it cannot be read into settings. An example run is [1000007711 ](http://128.197.168.115/pecan_tmccabe/05-running.php?workflowid=1000007711). 

The steps to recreate this error are: 
- need to check "edit xml" option
- when you have the option, need to delete and retype at least one character, and hit save.

**Comment by mccabete** [comment]
@tonygardella  Would you say that's a good summary of what you found?

**Comment by mccabete** [comment]
@robkooper Any idea why this might be happening?

**Comment by tonygardella** [comment]
@mccabete @robkooper When it reads in the xml this is the error:
```
   Loading inpufile= pecan.xml 
XML declaration allowed only at the start of the document
Error: 1: XML declaration allowed only at the start of the document
Error during wrapup: object 'settings' not found
```
Comparing `pecan.xml` to `pecan.xml.orig` just revealed that an empty line was inserted at the top of `pecan.xml`. We'll make sure to test editing `pecan.xml` from the web interface on the release candidate.

**Comment by mccabete** [comment]
It looks the the empty line is introduced not at the saving step but at the presenting the pecan xml to be edited step. When the xml is displayed it already has the extra line at the top, which if you delete and then save it will work just fine.

**Comment by tonygardella** [comment]
@mccabete Is this still an issue? I havn't run into this since this was opened.

**Comment by mccabete** [comment]
It's still an issue in my latest pull. It could depend on my web configurations.

**Comment by serbinsh** [comment]
I also regularly edit the pecan.xml in the web interface and it seems to work OK for me as well….using master and dev branches.  Or at least I haven’t run into this issue yet.


On Jul 24, 2017, at 6:30 AM, Tess McCabe <notifications@github.com<mailto:notifications@github.com>> wrote:


It's still an issue in my latest pull. It could depend on my web configurations.

**Comment by tonygardella** [comment]
@bcow

**Comment by robkooper** [comment]
I can not recreate this issue, closing for now. Please open a new issue if this happens again.
