### ISSUE TITLE
Add db ID to machines

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#149]
Add an (optional, default NULL) column to the machines table that lists the database ID used in load.bety.sh to determine the ID range used on a specific machine. Would only be set on machines that have a database.

I think we should also add a variable that is the URL path to the update. For example on ebi-forecast the DUMPURL is stored at https://ebi-forecast.igb.illinois.edu/pecan/dump/bety.tar.gz so the path would be pecan/dump/bety.tar.gz.

These changes would allow us to modify load.bety.sh so that the ID's and DUMPURL are not hard coded into the script, which will make it easier to add machines.

**Comment by robkooper** [comment]
We should also add the start/end range of that host to the table so we no longer have a fixed range but can assign smaller/larger ranges. The load/dump scripts can use this table and the machine name to automatically find out what their site id is.

**Comment by robkooper** [comment]
Added to BETY https://github.com/PecanProject/bety/pull/217

Need to add hosts (can be fake) for Brookhaven, Purdue, Virginia Tech to BETY on EBI

**Comment by dlebauer** [comment]
The Brookhaven and Purdue hosts are listed in the BETYdb wiki: https://github.com/PecanProject/bety/wiki/Distributed-BETYdb (would be good to add BU host to the documentation)

Should these pages be combined?
* https://github.com/PecanProject/bety/wiki/Distributed-BETYdb
* https://github.com/PecanProject/pecan/wiki/Database-Synchronization

**Comment by mdietze** [comment]
I think the argument for keeping things separate is that the pecan page is intended to be linked off the User's Guide to explain the steps that a new user needs to do to set up their machine as part of the sync system. The bety page seems to be focused on the technical details.  Perhaps the content needs to be looked at more closely to avoid duplication, and the two pages should obviously be linked to one another. 

If we do merge the pages then these two purposes have to be VERY CLEAR since we don't want to bombard the general user with technical detail they won't need 99% of the time.

**Comment by dlebauer** [comment]
>  we don't want to bombard the general user with technical detail ...

(More generally) Perhaps we should consider dividing up the documentation more clearly along the lines of scientist / developer / database administrator. Of course there will be overlap, but at least we can make it clear where people can find the information they are looking for.

**Comment by mdietze** [comment]
I think that's basically  what we have already. Pecan wiki is divided into the user's guide and the developer's guide, and the database guide is the BETY qiki

**Comment by robkooper** [comment]
Waiting for https://github.com/PecanProject/bety/issues/217, once merged I can update the load/dump bety scripts

**Comment by mdietze** [comment]
@robkooper is this anything left to do here or can we close?

**Comment by robkooper** [comment]
Closing for now. Will add smarts later to get download url from database if possible.
