### ISSUE TITLE
Convert nested xml files into a searchable R-list

### ISSUE THREAD

**Issue by LiamBurke24** [PecanProject/pecan#1492]
In attempting to download data and metadata by doi using the rdataone package, the the output is consistently an xml file that contains url links to the metadata and data. These urls are also in xml format (hence nested xml). I'd greatly appreciate some guidance here!

## Ideal result
dataone::query function returns an R list containing the data and metadata

## Second best 
dataone::query returns an xml file that another function parses both it and its contents into an R list 

## Context
```{r}
options(dataone_token = "eyJhbGciOiJSUzI1NiJ9.eyJz...") # must have authentication token see below

doi <- "doi:10.6073/pasta/6b03a068eb72af9b2ba14d633c9cb60c" 
cn <- dataone::CNode("PROD")  # search whole data federation
queryParams <- list(q='id:"doi:10.6073/pasta/6b03a068eb72af9b2ba14d633c9cb60c"', rows="5")
result <- dataone::query(cn, solrQuery = queryParams, encode = TRUE, as = "data.frame", parse = TRUE)
result # display result 

dataUrl <- result[1, "dataUrl"] # get url where data are stored

# download file to home directory 
utils::download.file(dataUrl, "testdownload1", method = "auto", quiet = FALSE, mode = "w", 
                     cacheOK = TRUE)
```
AUTHENTICATION TOKEN: 
1. go to this address: https://search.dataone.org/#data
2. Sign in using BU kerberos login 
3. go to your profile
4. Settings tab
5. Click Authentication Token
6. click Token for Dataone R
7. Copy the token and paste in your R session 

The following converts the xml "testdownload1" into an R-list but the output is NOT user friendly and the urls contained in the list are still in xml:

```{r}
XML::xmlToList("testdownload1", addAttributes = TRUE)
```

Any suggestions would be greatly appreciated!!!

## Possible Implementation
Resolving this issue will allow me to finish a basic version of my upload by doi function that will allow users to search for and download data and metadata into R by doi. Ultimately, the download by doi function will be the first half of a function that allows users to download data and have the metadata automatically converted into pecan's native format thereby allowing users to circumvent the arduous process of manually ingesting datasets.

**Comment by tonygardella** [comment]
@LiamBurke24 I personally don't have experience working with reading in XML files but we use XML files a lot throughout PEcAn. A quick search of the repository resulted [in this](https://github.com/PecanProject/pecan/search?o=desc&q=%22XML%3A%3A%22&s=indexed&type=&utf8=%E2%9C%93). Also, this function in PEcAn [read.settings.R](https://github.com/PecanProject/pecan/blob/develop/settings/R/read.settings.R) reads in and turns the PEcAn xml settings file into a list object.

**Comment by mdietze** [comment]
As @tonygardella notes, we use XML throughout PEcAn and you just need to use the function ```XML::xmlToList(xml)``` to convert XML to an R list (which is the very first thing we do after reading via ```xml <- XML::xmlParse(inputfile)```)
