### ISSUE TITLE
Status of utils::mstmipvar function 

### ISSUE THREAD

**Issue by annethomas** [PecanProject/pecan#1504]
To go with the discussion of the pecan output standard table (#1496, #1498 ), can we clarify the status of the mstmipvar function in https://github.com/PecanProject/pecan/blob/develop/utils/R/utils.R? The function uses the within-package standard table to convert requested variables (including units and dimensions) to ncvar objects and is used in model2netcdf functions. I heard some discussion of it being deprecated, with the only documentation I could find of this discussion in #1019. In that pull request, it seemed like the conclusion between @dlebauer and @tonygardella  was that the table and the function were still useful and what needed to change was updating and building the table with the package on demand. Where are we at with this?

At the least, the function will need to be updated to reference the standard_vars table instead of the mstmip_vars table.

Also, in working on a standard IC input file, I wrote a pared down version of the function within my function but wondered if an updated version of mstmipvar would also make sense to use since it's already used elsewhere. @mdietze am I correct in understanding you thought this wasn't necessary? Can you clarify why?

**Comment by mdietze** [comment]
I've never liked the mstmipvar function and avoid it any time I couple a model to PEcAn. Personally, I don't think it saves time over just using ncvar_def directly, but has the negative side effect of obfuscating the units. This makes the code less clear and self-contained and potentially leads to unit errors. Current usage also leads to odd mixtures of calls to ncvar_def and mstmipvar, e.g. https://github.com/PecanProject/pecan/blob/e6e76a5ec36607eb3315f144e5465545ba6fb2e5/models/dalec/R/model2netcdf.DALEC.R#L94-L97 

I also really disliked its use of two different look up tables within the function, which was contributing to a proliferation of multiple, redundant look-up tables. I agree that at a minimum the function needs to be updated to use the one, renamed table that's also used in the documentation. 

But I'm still advocating for just replacing its use with direct calls to ncvar_def and then eliminating the function. Overall, I see real disadvantages of using this function and haven't heard any compelling arguments in its favor.

**Comment by annethomas** [comment]
Ok,@mdietze my questions are
1)  Assuming we streamline the table down to one standard output table, is there an advantage to having the units and dimensions in one place rather than having to hardcode them in multiple places in the code, given that they may change? But you're saying you'd rather have the units visible in the function than refer the user to the table?
2) With the goal of a more comprehensive standard output, would models still have variables that the standard_vars table and a function like mstmipvar couldn't provide? Wasn't the idea that they wouldn't? That could prevent the mixture of calls. I know that goal may be a ways off though.
3) In the context of my IC input function, I'm loading the ncvars dynamically and not hardcoding anything, so it's definitely useful in my context to have a lookup function. But if you prefer visibility for model output and know exactly what the variables are, maybe this is the only place it would be useful.

**Comment by infotroph** [comment]
Closing this, but the implementers of #1746 should come back and read the thread when considering use cases.
