### ISSUE TITLE
Using remote hosts causes errors; Cannot set hostname correctly 

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#1522]
This error was generated using the web interface and BU's computing cluster geo, but should cause problems for anyone attempting to use a remote host.  Example runs are [here](http://test-pecan.bu.edu/pecan_tmccabe/05-running.php?workflowid=1000007821), and[ here](http://test-pecan.bu.edu/pecan_tmccabe/05-running.php?workflowid=1000007819). This error is caused across machines and models. The issue seems to be that the hostname cannot be assigned an array. 

```
Error executing db query 'select id from machines where hostname = 
   'geo.bu.edu' and hostname = 'tmccabe' and hostname = 
   '/projectnb/dietzelab/pecan.data/output/tmccabe' and hostname = 'module 
   load udunits R/3.3.2' and hostname = "qsub -l h_rt=24:00:00 -pe omp 8 -q 
   'geo*' -V -v OMP_NUM_THREADS=8 -N @NAME@ -o @STDOUT@ -e @STDERR@ -S 
   /bin/bash" and hostname = 'Your job ([0-9]+) .*' and hostname = 'qstat 
   -j @JOBID@ || echo DONE' and hostname = 
   '/fs/data2/output//PEcAn_1000007821/tunnel/tunnel' and hostname = 
   '/projectnb/dietzelab/pecan.data/output/tmccabe/1000007821/run' and 
   hostname = 
   '/projectnb/dietzelab/pecan.data/output/tmccabe/1000007821/out' ;' 
   errorcode=0 message='ERROR: column "qsub -l h_rt=24:00:00 -pe omp 8 -q 
   'geo*' -V -v OMP_NUM_THREADS" does not exist LINE 1: ...me = 'module 
   load udunits R/3.3.2' and hostname = "qsub -l h...  ^ ' 
[1] "Killing tunnel with PID 23403"
```

## Context
This is an issue for complex or long runs, as it prevents the use of a computing cluster and slows down the local machine.

**Comment by mccabete** [comment]
The Workaround for this problem is to  wrap the array you were assigning to your hostname in another array. In my config.php file it looks like this :
```
 "geo.bu.edu" => array(
                    array("qsub"   => "qsub -l h_rt=24:00:00 -pe omp 8 -q 'geo*' -V -v OMP_NUM_THREADS=8 -N @NAME@ -o @STDOUT@ -e @STDERR@ -S /bin/bash",
                          "jobid"   => "Your job ([0-9]+) .*",
                          "qstat"   => "qstat -j @JOBID@ || echo DONE",
                          "prerun"  => "module load udunits R/3.3.2",
                          "folder" => "/projectnb/dietzelab/pecan.data/output",
                          "models"  => array("ED2" =>
                              array("prerun"  => "module purge; module load gcc/5.3.0 openmpi; LD_LIBRARY_PATH=/projectnb/dietzelab/ashiklom/.local/packages/hdf5/1.8.17_gcc5.3.0/lib/:/projectnb/dietzelab/ashiklom/.local/packages/openmpi-2.0.1/lib/:\$LD_LIBRARY_PATH")))));
```

**Comment by ashiklom** [comment]
Reopening because this isn't quite resolved. I don't need nested arrays to run ED successfully, and nested arrays don't actually solve the problem.

**Comment by ashiklom** [comment]
After running some tests, this _particular_ bug seems to be related to met processing. I hit this error anytime I do remote runs (on `geo`) with "Use NARR" or "Use CRUNCEP", and do _not_ hit the other when I use existing met.

**Comment by mdietze** [comment]
Right now avoid Use NARR altogether -- it's been ages since anyone's tested it locally on a machine that had NARR installed and the normal route (Brown Dog) is also misbehaving. The failure of CRUNCEP is more troubling since that's a simple THREDDS query -- can you post more details about the failure (and also verify that the run works when run local rather than remote and it's not just that the THREDDS server is temporarily down)

**Comment by ashiklom** [comment]
I don't think it's a CRUNCEP error specifically -- I suspect it's more an error in the way met.process parses the PEcAn.xml for remote connections. The error is basically the exact same one that @mccabete posted earlier. It's also accompanied by a bunch of warnings about `if (hostname == "localhost")` being a vector, which means that somewhere along the line, `hostname` is being read in as a vector. My guess is that there is code somewhere along the lines of `hostname <- settings$host`, whereas it should be `settings$host$name`.

Here are some example failed workflows:
- http://test-pecan.bu.edu/pecan/05-running.php?workflowid=1000008137
- http://test-pecan.bu.edu/pecan/05-running.php?workflowid=1000008139

**Comment by ashiklom** [comment]
Yeah, so the issue is that `do.conversiosn` calls `met.process` like this:

```r
        settings$run$inputs[[i]][['path']] <- 
          PEcAn.data.atmosphere::met.process(
            site       = settings$run$site, 
            input_met  = settings$run$inputs$met,
            start_date = settings$run$start.date,
            end_date   = settings$run$end.date,
            model      = settings$model$type,
            host       = settings$host,
            dbparms    = settings$database$bety, 
            dir        = dbfiles,
            browndog   = settings$browndog,
            spin       = settings$spin,
            overwrite  = overwrite.met)
```

However, `settings$host` is a list of a bunch of things. This should really be `settings$host$name`, because that's what `met.process` expects:

```r
met.process <- function(site, input_met, start_date, end_date, model,
                        host = "localhost", dbparms, dir, browndog = NULL, spin=NULL,
                        overwrite = FALSE) {
```
