### ISSUE TITLE
Incomplete path to Biocro.Rscript

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#1535]
In the current VM, the Bety entry for the path to biocro.Rscript is set to the nonexistant path "/PEcAn.BIOCRO".

This path is set by `add.models.sh`:

```
addModelFile "${FQDN}" "BioCro" "BIOCRO" "" "biocro.Rscript" "${R_LIBS_USER}/PEcAn.BIOCRO"
```

so  it looks as if the fix is to ensure that $R_LIBS_USER is correctly set before add.models.sh gets run.

**Comment by robkooper** [comment]
Since the script is dependent on the version of PEcAn (and not BIOCRO) it should probably look up the path using `system.file("biocro.Rscript", package="PEcAn.BIOCRO"")` inside the write.config.

**Comment by infotroph** [comment]
I'm not sure I follow -- Are you suggesting a change to write.config.BIOCRO so that it uses `system.file("biocro.Rscript", package="PEcAn.BIOCRO")` instead of `settings$model$binary`? Wouldn't that defeat the purpose of the settings file?

**Comment by infotroph** [comment]
@robkooper @dlebauer I'm inclined to say this is a non-issue now that Biocro is Dockerized and advertises itself via `model_info.json`. Agree?

**Comment by robkooper** [comment]
I agree
