### ISSUE TITLE
softwareserver-0002 error

### ISSUE THREAD

**Issue by yan130** [PecanProject/pecan#1551]
## Description
Error message:
 remotefunc <- function() {PEcAn.data.atmosphere::download.AmerifluxLBL(sitename='Duke Forest - loblolly pine (US-Dk3)', username='pecan', overwrite=FALSE, outfolder='/home/polyglot/cache/PEcAn/AmerifluxLBL_site_0-756/', start_date='1997-01-01', end_date='2009-12-31')}
> remoteout <- remotefunc()
Error in loadNamespace(name) : 
  there is no package called ‘PEcAn.data.atmosphere’
Calls: remotefunc ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
[1] 1
Error in file(tmpfile, "w") : cannot open the connection
Calls: met.process ... .download.raw.met.module -> convert.input -> remote.execute.R -> file
In addition: Warning message:
In file(tmpfile, "w") :
  cannot open file '/home/polyglot/cache/PEcAn/AmerifluxLBL_site_0-756//pecan-aad56b1bf18abf1735fccfcbcf1c0c': No such file or directory
2017-07-24 11:33:40 WARN   [db.close] : 
   Connection created outside of PEcAn.db package 
Execution halted

**Comment by robkooper** [comment]
are you running this as the correct user (i.e. polyglot in this case?)

**Comment by tonygardella** [comment]
@yan130 Looks like they only have data from 1998-2008 for that site: http://www.fluxdata.org:8080/sitepages/siteInfo.aspx?US-Dk3
