### ISSUE TITLE
postgres/postGIS trouble from Travis updates

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#1552]
Travis CI is [in the process of rolling out](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming) an upgrade to their default containers. Travis builds for my personal fork of PEcAn have already been bumped from Ubuntu/precise to Ubuntu/trusty, with some resulting confusion about Postgres and PostGIS version numbers. For example, here's the same commit [passing](https://travis-ci.org/PecanProject/pecan/builds/255691788) in the PEcAnProject Travis run but [failing](https://travis-ci.org/infotroph/pecan/builds/256931645) in mine. Note especially two suites of related-looking errors:

* `ERROR:  unrecognized configuration parameter "row_security"`. I'm guessing this is because .travis.yml currently specifies Postgres 9.4, but bety.sql was dumped from Postgres 9.5.6.

* A progression of errors that I think are PostGIS related:
  - one `ERROR:  could not access file "$libdir/postgis-2.3": No such file or directory`
  - one `ERROR:  extension "postgis" does not exist`
  - a few `ERROR:  type "geometry" does not exist`
  - a few `ERROR:  relation "sites" does not exist`
  - then thousands of `invalid command \N`
This is weird because .travis.yml currently specifies PostGIS 2.1, but it seems as if Trusty is ignoring that and attempting to use 2.3 anyway.

### Immediate patch that will only work until September

Add `dist: precise` to keep running jobs on the old systems.

### More permanent

Changing lines 28 and 29 of .travis.yml from 
```
      - postgresql-9.4-postgis-2.1
      - postgresql-9.4-postgis-2.1-scripts
```
to
```
      - postgresql-9.6-postgis-2.3
      - postgresql-9.6-postgis-2.3-scripts
```
appears to fix both these problems, but (1) maybe there are other fixes that don't require a major-version Postgres change, and (2) Travis drops caches after a configuration change and keeps exceeding the maximum allowed run time, so I don't actually have a green checkmark to show off yet.

**Comment by robkooper** [comment]
The VM itself uses xenial (16.04), which is newer than trusty, and postgres 9.5 so I don't see an issue with at least jumping to that version.
