### ISSUE TITLE
Proposal: move core packages into a 'base' folder

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#1555]
The root directory of pecan is a bit cluttered -- there's two large folders (models and modules) full of R packages, then a hodgepodge of scripts, documentation, web, shiny, and all other R packages that aren't in modules and models. By moving this latter group into a new folder 'base' it makes the organization of R packages more clear and easier to explain.

## Possible Implementation

Move the following into 'base':

db
qaqc
settings
utils
visualization

Then update make, all, etc so PEcAn builds successfully.

**Comment by dlebauer** [comment]
should 'all' also be included in base?

**Comment by mdietze** [comment]
That sounds good to me, but I don't know how that'd affect the make. @ashiklom @robkooper would it work to have the 'all' package in a 'base' folder?

**Comment by tonygardella** [comment]
Completed by #1591
