### ISSUE TITLE
Differences in ED2IN between the old and new versions of ED2

### ISSUE THREAD

**Issue by Viskari** [PecanProject/pecan#156]
Below is a list of namelist variables in the Git version of ED2 that were not present in the current PEcAn version of ED2.

NL%IADD_SITE_MEANS
NL%IADD_PATCH_MEANS
NL%IADD_COHORT_MEANS

The above values indicate will those means be written in the output and have only two values (0=NO, 1=YES)

NL%MIN_PATCH_AREA

Minumum patch area. Can be easily set to be the same as NL%MIN_SITE_AREA

**Comment by mdietze** [comment]
@ryankelly-uiuc I'm switching you to be in charge of this issue since I believe you were already working on a new ED2IN template for the git code.
