### ISSUE TITLE
Travis builds not working in new Linux environment

### ISSUE THREAD

**Issue by annethomas** [PecanProject/pecan#1575]
@infotroph @ashiklom @robkooper This most recent travis build is whacked out due to the environment change:
https://travis-ci.org/PecanProject/pecan/builds/261114254?utm_source=github_status&utm_medium=notification

Let me know if that link doesn't work.

**Comment by mdietze** [comment]
While we do need to fix this, PR #1577 should revert us back to the previous environment until we get the change sorted out.

**Comment by infotroph** [comment]
For those working on the Trusty upgrade, feel free to poke around in the [Travis logs of my PEcAn fork](https://travis-ci.org/infotroph/pecan) to see some of what we're up against. Short version is that dependency compilation time is killing us -- Note especially the "add-timings" branch, where I temporarily add timestamps for each package and find that just installing devtools+roxygen2+testthat takes ~5 minutes! Other major time-hogs: visualization, ed2.
