### ISSUE TITLE
Register run execution benchmark pecan.xml

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#1595]
Creating "does it run" benchmarks had been assigned to one of our summer undergrads (Elias) who deposited the pecan.xml for his tests on the BU server. Someone needs to go through these, figure out which are useful/usable, and then register them in the database via create_BRR. We also need to go through and figure out what other runs are needed so that we have good basic coverage of different models and drivers, and then add these additional runs. The end product should be a pecan.xml of the benchmark reference run (BRR) id's that, when combined with local db and host info, would run all these tests at once as a MultiSettings run. This xml would then be deposited in the _tests_ folder.

**Comment by infotroph** [comment]
@mdietze Did these get rolled into @tonygardella's integration test suite?

**Comment by infotroph** [comment]
Closing after conversation with @mdietze to the effect that these files may now be lost and the integration testing effort has now diverged from the benchmarking project enough that these would no longer be the most useful starting point.
