### ISSUE TITLE
Add check to load.bety.sh to check version before downloading

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#160]
Maybe add a file to the server called version.txt that can be downloaded quickly to check what version the remote server is at. If that version matches that of the local server we can update the database.

This would also allow us to create a simple webpage that shows all versions of all BETY databases deployed at known sites.

**Comment by mdietze** [comment]
@robkooper is this ready to close too?

**Comment by robkooper** [comment]
better versions implemented, no smart download yet to make sure we don't download if version is mismatch. Close issue for now since we have a good detection and all servers are on fixed network.
