### ISSUE TITLE
Reconcile `dplyr` and `DBI`-based database methods

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#1604]
## Description

The latest version of `dplyr` (and its child database package -- `dbplyr`) now allows the standard `dplyr` verbs to work with objects returned by `DBI`. In other words, it's no longer necessary to use the `src_postgres` and similar functions to create database connections to work with `dplyr`; instead, code like this should work:
```r
# Connect to database
con <- PEcAn.DB::db.open(...)
# Do dplyr stuff
tbl(con, "dbfiles") %>% select(id, machine_id) %>% <etc...>
```

## Context

See #1600 , particularly [this line](https://github.com/PecanProject/pecan/pull/1600/files#diff-3f7d8d26196fbd0b4986397299b910b6R17). This affects the `query.dplyr.R` code in `PEcAn.DB` and, I suspect, code in `PEcAn.benchmark`, `PEcAn.data.land`, and other places that use `dplyr` syntax.

**Comment by mccabete** [comment]
Are we deprecating the use of passed "bety" objects being generated by src_postgress as well? 

For example query.format.vars takes a "bety" object that will throw an error when it's passed PEcAn.DB::db.open(settings$database$bety).

**Comment by ashiklom** [comment]
Yes, that's exactly the idea. We need to be consistent about our database interfaces, so we should avoid using `dplyr::src_*` functions in favor of `PEcAn.DB::db.open` (which calls `DBI`-based functions).

**Comment by mccabete** [comment]
Great! Do I rewrite the function to take a "PEcAn.DB::db.open(settings$database$bety)", or is there a different function PEcAn.DB to set bety equal to? 

Also, what is the difference between "bety" vs "con"?

**Comment by ashiklom** [comment]
As far as I know, `bety` generally refers to things returned by `src_*` functions. The output of the `src_*` functions is a list containing `con` (a database connection, exactly the same as from `db.open` and some other information about the connection. In other words, `bety$con == con`.

Really, the change I was envisioning is to just change the `bety` argument of `query.format.vars` and other functions to `con`, and to remove any references inside those functions to `bety$con`. The `dplyr::tbl(bety, ...)` function should, with recent versions of `dplyr`, work exactly the sam as `dplyr::tbl(con, ...)`, so that's as easy as a find-replace. Otherwise, I think a lot of functions that take `bety` as an argument have a line like `con <- bety$con` somewhere near the beginning, which you can just remove once you replace the function argument.

Does that make sense?

**Comment by ashiklom** [comment]
Pretty sure this is done, since we haven't had issues with it in a while. Closing.
