### ISSUE TITLE
MODISTools removed from CRAN; call_MODIS broken

### ISSUE THREAD

**Issue by annethomas** [PecanProject/pecan#1606]
call_MODIS uses the R package MODISTools which wasn't maintained and was recently removed from CRAN. The call_MODIS function will have to be updated with a new R package or other option. 

Here are some possibilities:
Get the python code block working.
This R package: https://cran.r-project.org/web/packages/MODIS/MODIS.pdf
Somehow using online subsetting tools like https://modis.ornl.gov/data.html or https://lpdaac.usgs.gov/dataset_discovery/modis/modis_products_table/mcd15a3h_v006#tools
Using an archived version of MODISTools

**Comment by tonygardella** [comment]
Seems that someone has it on Github: https://github.com/seantuck12/MODISTools

**Comment by annethomas** [comment]
They haven't updated their github since before it was pulled from CRAN, so there may be bugs, but maybe it still works

**Comment by annethomas** [comment]
I tried installing their package via install_github and I'm running into the error I'm guessing @mccabete was  getting before it was pulled from CRAN:
```
Error in MODISTools::GetSubset(Lat = lat, Long = lon, Product = product,  : 
  Downloading from the web service is currently not working. Please try again later.
```
I'll keep looking into it though.

**Comment by annethomas** [comment]
This url MODISTools uses is broken. Anyone have an idea what it could be updated to?
https://daacmodis.ornl.gov/cgi-bin/MODIS/GLBVIZ_1_Glb_subset/MODIS_webservice.pl

**Comment by annethomas** [comment]
@ashiklom do you think it's equivalnet to this: https://daacmodis.ornl.gov/cgi-bin/MODIS/GLBVIZ_1_Glb_subset/MODIS_webservice.wsdl

**Comment by annethomas** [comment]
Hm, that url didn't return the web service down error but the results were empty.

**Comment by ashiklom** [comment]
@annethomas My understanding is the WSDL URL you posted above defines the web API functions, but then you actually have to call them somehow. For instance, see [this example](https://github.com/omegahat/SSOAP/blob/master/examples/weather.R), or the R example right on the ORNL DAAC MODIS web API website.

**Comment by annethomas** [comment]
Finished debugging the python script, which uses the web service. PR #1609
