### ISSUE TITLE
Post-model processing broken on geo. Causes infinite loop. 

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#1617]
When ED submits a job to geo, it runs just fine. If the model finished the job, the post-processing stage causes the remote to go on an infinite loop. 

Stay tuned for more detail on what is required to trigger this problem. It might have been hard to catch because ED very rarely gets through a successful run.  

Example run: http://test-pecan.bu.edu/pecan_tmccabe/05-running.php?workflowid=1000008292

**Comment by ashiklom** [comment]
I'm pretty sure this was resolved in #1665, so I'll go ahead and close it. If it pops up again, we should re-open it.
