### ISSUE TITLE
LINKAGES (R Version) and BioCro not on VM

### ISSUE THREAD

**Issue by araiho** [PecanProject/pecan#1627]
I just ran the VM version 1.5.0 and you cannot select linkages from the drop down menu.

This is probably my fault because I didn't specify a remote from github before my latest pull request.

But, I'm not sure how to get it into the VM drop down menu after that.

**Comment by mdietze** [comment]
Once the model's installed, you should just have to add a dbfile record pointing to the executable and then link that dbfile to the existing model record. Since LINKAGES is an R package, it looks like on other machines we've pointed to the package path (e.g. ~/R/library/linkages)

**Comment by infotroph** [comment]
To install BioCro: `Rscript -e 'devtools::install_github("ebimodeling/biocro")'`

**Comment by robkooper** [comment]
Mmm, need to check, this is what it is int he install script:

```
echo "######################################################################"
echo "BioCro"
echo "######################################################################"
echo 'devtools::install_github("ebimodeling/biocro")' | R --vanilla

echo "######################################################################"
echo "Linkages"
echo "######################################################################"
echo 'devtools::install_github("araiho/linkages_package")' | R --vanilla
```

**Comment by infotroph** [comment]
BioCro seems to be installed and working throughout the 1.5.3 RC process. @araiho is LINKAGES also working? If so, we can close this.
