### ISSUE TITLE
DALEC Soil input

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#1644]
Add capability to write to DALEC soil parameters.

## Description
Extend DALEC coupling scripts to be able to read in a DALEC processed soil parameters and write out DALEC parameters.

## Possible Implementation
Examples of implementation can be found here from other model coupling scripts:
[Jules](https://github.com/PecanProject/pecan/blob/develop/models/jules/R/write.config.JULES.R#L268-L314)

**Comment by annethomas** [comment]
@mdietze @tonygardella From what I can see, DALEC doesn’t seem to consider soil variables (or any others) at all outside of carbon. Am I missing anything? Does this mean soils data won't be useful here?

**Comment by mdietze** [comment]
Did you check this chunk of parameters
https://github.com/PecanProject/pecan/blob/develop/models/sipnet/inst/template.param#L57-L62

**Comment by annethomas** [comment]
@mdietze That's for sipnet; Dalec doesn't seem to have an equivalent

**Comment by mdietze** [comment]
Doh, I'm braindead today -- too many meetings.  Yes, DALEC takes all its plant and soil hydraulic parameters as prescribe inputs in the met file rather than calculating soil moisture variables from precip.

**Comment by mdietze** [comment]
I think close for now. In theory we could modify met2model.DALEC to read in the default soil parameters and run a stand-alone soil hydraulics calculation, but that'd end up being almost as much code as DALEC itself. It also wouldn't work if ```<met>``` got called before ```<soil>```

**Comment by annethomas** [comment]
Ok cool
