### ISSUE TITLE
Include run, ensemble, and workflow status in BETY

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#1660]
## Description

I propose adding a `run_status` column to the `runs` table, `total_runs` and `successful_runs` columns to the `ensembles` table (both calculated from the runs table by Postgres), and a `workflow_status` column to the `workflows` table.

The `workflows.workflow_status` column could be a JSON format to support a lot of information. 

## Context

- Web interface history table might render faster -- it should be considerably faster to run an SQL query than to scan a bunch of STATUS text files.
- It should make it easier to diagnose systematic errors with queries like `SELECT … WHERE run_status = ‘Failed’.

**Comment by robkooper** [comment]
I'd like to split the workflow_status into two columns, status_json, which is a json representation of the current status file, as well as a status column which is one of the following states: SUBMITTED, RUNNING, FINISHED, FAILED. This status can be calculated from the status_json field, but will be easier to query. Following is the status_json field (approximation):
```
{
  "TRAIT": {
    "start": "2017-07-18 16:35:18",
    "end": "2017-07-18 16:35:34",
    "status": "DONE"
  },
  "META": {
    "start": "2017-07-18 16:35:34",
    "end": "2017-07-18 16:36:45",
    "status": "DONE"
  },
  ...
}
```
The total status is computed using:
if status_json is EMPTY => status is SUBMITTED
elif "*.status" == ERROR => status = ERROR
elif "FINISHED.status" is "DONE" => status = DONE
else status = RUNNING

**Comment by dlebauer** [comment]
Would this be appropriate use case for the generic table proposed in https://github.com/PecanProject/bety/issues/505 ?

**Comment by robkooper** [comment]
I don't think since all workflows/runs will have this data. The generic table seems more for those cases where only a small subset of the table will have this data.

**Comment by mccabete** [comment]
@ashiklom Did you finish this issue? I'm asking mostly to see if this is something we could include in the bety GSoC task

**Comment by ashiklom** [comment]
@mccabete No, AFAIK this was never tackled.

**Comment by robkooper** [comment]
this is not that hard (I really need to make a sheet with my TODO's).

**Comment by mccabete** [comment]
No worries, my intention was not to rush anyone. I was gathering Bety-related issues to see if any could work  for GSoC.

**Comment by infotroph** [comment]
Closing in favor of #2488, which is a later duplicate but it collected a lot of useful discussion before we noticed. When implementing #2488, please refer back here to make sure it resolves this thread as well.
