### ISSUE TITLE
VM ISSUE - Linkages 

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#1695]
On the VM release candidate v1.5.1-RC2, Linkages **Models** record (id =99000000001) is associated with a **Model Type** record of "R_version".  

Needs to be corrected so that the  **Models** record is associated with  a **Model Type** = "LINKAGES" with a revision called "R_version". The **Model Type** record of "R_version" shouldn't exist.

**Comment by araiho** [comment]
Hey @tonygardella did I cause this problem? Do I need to fix it on BETY?

**Comment by tonygardella** [comment]
No. It's specific to the VM . I think Rob just needs to fix the records on the VM version of BETY.

**Comment by infotroph** [comment]
Closing because this was specific to an old release candidate. If this is still happening in any current installations, please open a fresh issue.
