### ISSUE TITLE
Shiny issues

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#1696]
When trying to access the SHINY pages on the VM, the pages load then if you try to click anything it automatically disconnects with a message: "Disconnected from the server". If you just let the page sit, it does the same thing after a couple seconds. 

I'm opening this issue as an Epic issue to sort out any issues that come up regarding SHINY apps. @serbinsh

**Comment by serbinsh** [comment]
On modex, workflow plots seem to be OK, but for some reason when I try to load global-sensitivity plots it will try to load the last run, even if its been deleted?  If I force it to run with a specific workflow, for example

```
https://modex.bnl.gov/shiny/global-sensitivity/?workflow_id=2000000573
```

It will work fine.  So for some reason it seems to see workflows that have been deleted?

**Comment by serbinsh** [comment]
![screen shot 2017-09-27 at 4 47 39 pm](https://user-images.githubusercontent.com/3067369/30937013-99189b46-a3a3-11e7-9e58-9372eb9b0683.png)

See in screenshot how it tries to load workflow 20...0589 which was deleted!

**Comment by robkooper** [comment]
I tried to run this on the VM using the http://localhost:6480/shiny/workflowPlot/ and it worked fine. Which shiny app is not working?

**Comment by tonygardella** [comment]
Awesome! That was one that was not working for me. I tried it on chrome and firefox and it just kept disconnecting. Maybe, it's something wrong with my personal machine.

**Comment by tonygardella** [comment]
![image](https://user-images.githubusercontent.com/8570691/31087824-7f4c816a-a76c-11e7-9119-0f1a2abf0740.png)

**Comment by tonygardella** [comment]
On firefox it looks like this:
![image](https://user-images.githubusercontent.com/8570691/31087874-b784f95e-a76c-11e7-82a9-a00344d7dca5.png)

**Comment by serbinsh** [comment]
Shiny was working for me but after a recent pull of develop I am having a new error.  If I try to open anything like workflow, global sensitivity, or elicitation I now get this error in both Chrome and Firefox

```
ERROR: An error has occurred. Check your logs or contact the app author for clarification.
```

The log
[workflowPlot-sserbin-20170912-163156-41875.log](https://github.com/PecanProject/pecan/files/1415095/workflowPlot-sserbin-20170912-163156-41875.log)

**Comment by serbinsh** [comment]
OK, so I recently updated Shiny server and made a little more progress.

![screen shot 2017-11-01 at 7 37 06 am](https://user-images.githubusercontent.com/3067369/32273133-961f0c6e-bed7-11e7-9eda-a8f2beef16e7.png)


But as you can see, still failing to plot workflows

**Comment by serbinsh** [comment]
OK, well I tried one of my older SIPNET runs and it seems to be working again 

![screen shot 2017-11-01 at 7 56 29 am](https://user-images.githubusercontent.com/3067369/32273785-43a7f8d0-beda-11e7-8543-35edadd6f2dc.png)


Question is, why doesnt it work for my dvm-dos-tem outputs?  Right now those outputs are annual, maybe the Shiny code doesn't work for a single number per year?
