### ISSUE TITLE
BioCro unit conversions

### ISSUE THREAD

**Issue by mollyaufforth** [PecanProject/pecan#1702]
BioCro at US-NE1 with Ameriflux met. Couldn't get a successful run. 

## Description
These were the warnings that I got for precipitation and soil water content.

Units not convertible for P with units of mm . Please make sure the 
varible has units that can be converted to kg m-2 s-1 

Units not convertible for SWC_1 with units of % . Please make sure the 
varible has units that can be converted to (-) 

## Possible Implementation
I feel like this would be a simple fix, I just don't know how to go about fixing it myself.

**Comment by mollyaufforth** [comment]
I ran it from a server.
tree.aos.wisc.edu:6480

I don’t know what release of PEcAn it is. How would I go about to find that?

The dates I used were from 2003/01/01 to 2003/12/31 and a PFT of C4.

- Molly

**Comment by infotroph** [comment]
> I don’t know what release of PEcAn it is. How would I go about to find that?
It's displayed in the footer text at the bottom right corner of the browser window, or in an R session you can run `packageVersion("PEcAn.all")`

**Comment by infotroph** [comment]
Having some (probably unrelated) trouble with Ameriflux data download, will report back soon.

**Comment by mollyaufforth** [comment]
It's version 1.5.0

**Comment by infotroph** [comment]
I now think this is an issue with the AmerifluxLBL format records and not specific to BioCro. From a SIPNET run 2004-01-01 to 2004-12-31 at site US-Ha2 :

```
> # Do conversions
> settings <- PEcAn.utils::do_conversions(settings)
2017-09-28 20:23:20 DEBUG  [PEcAn.logger::logger.debug] : 
   do.conversion outdir /home/carya/output/dbfiles 
2017-09-28 20:23:20 INFO   [PEcAn.logger::logger.info] : PROCESSING:  met 
2017-09-28 20:23:20 INFO   [PEcAn.logger::logger.info] : 
   calling met.process: 
  scale  format.id       format.name format.mimetype format.inputtype
1  site 5000000002 AMERIFLUX_BASE_HH        text/csv              csv
2017-09-28 20:23:20 WARN   [PEcAn.logger::logger.warn] : 
   Units not convertible for P with units of mm .  Please make sure the 
   varible has units that can be converted to kg m-2 s-1 
2017-09-28 20:23:20 WARN   [PEcAn.logger::logger.warn] : 
   Units not convertible for SWC_1 with units of % .  Please make sure the 
   varible has units that can be converted to (-) 
2017-09-28 20:23:20 WARN   [PEcAn.logger::logger.warn] : 
   There are duplicate columns in format record AMERIFLUX_BASE_HH . If 
   format is not wide format, check column(s) NEE 
```

**Comment by ankurdesai** [comment]
Note: these are all warnings. The workflow should still continue. The code knows how to deal with precipitation in mm and SWC in %, even if udunits doesn't know what to do.

**Comment by infotroph** [comment]
The reference to format.id 5000000002 is a useful hint. In an R session with no model run at all:
```
> PEcAn.DB::query.format.vars(
    bety = list(con = PEcAn.DB::db.open(list(dbname = "bety", user = "bety"))),
    format.id = 5000000002)
2017-09-28 21:19:51 WARN   [PEcAn.logger::logger.warn] : 
   Units not convertible for P with units of mm .  Please make sure the 
   varible has units that can be converted to kg m-2 s-1 
2017-09-28 21:19:51 WARN   [PEcAn.logger::logger.warn] : 
   Units not convertible for SWC_1 with units of % .  Please make sure the 
   varible has units that can be converted to (-) 
2017-09-28 21:19:51 WARN   [PEcAn.logger::logger.warn] : 
   There are duplicate columns in format record AMERIFLUX_BASE_HH . If 
   format is not wide format, check column(s) NEE 
$file_name
[1] "AMERIFLUX_BASE_HH"

$mimetype
[1] "csv"

$vars
                                  bety_name variable_id      input_name    input_units storage_type column_number         bety_units   mstmip_name   mstmip_units        pecan_name    pecan_units
1                              air_pressure    5.54e+02              PA            kPa                         19                 Pa         Psurf             Pa             Psurf             Pa
2                                      airT    8.60e+01              TA        celsius                          4          degrees C          Tair              K              Tair              K
3                                    co2atm    1.35e+02           CO2_1     umol mol-1                         20 ppm (= umol mol-1)        CO2air micromol mol-1            CO2air micromol mol-1
4                                  datetime    5.00e+09 TIMESTAMP_START        ymd_hms   %Y%m%d%H%M             1            ymd_hms          <NA>           <NA>          datetime        ymd_hms
5                                        FC    1.00e+09              FC umol C m-2 s-1                          8     umol C m-2 s-1           NEE   kg C m-2 s-1               NEE   kg C m-2 s-1
6                                         H    2.99e+02               H          W m-2                         10              W m-2            Qh          W m-2                Qh          W m-2
7                                        LE    2.98e+02              LE          W m-2                         12              W m-2           Qle          W m-2               Qle          W m-2
8                                       NEE    2.97e+02          NEE_PI umol C m-2 s-1                          7     umol C m-2 s-1           NEE   kg C m-2 s-1               NEE   kg C m-2 s-1
9                                       PAR    1.36e+02         PPFD_IN   umol m-2 s-1                         26       umol m-2 s-1          <NA>           <NA>               PAR   umol m-2 s-1
10                       precipitation_flux    5.55e+02               P             mm                         17            Kg/m2/s         Rainf     kg m-2 s-1             Rainf     kg m-2 s-1
11                        relative_humidity    5.56e+02              RH        percent                         18                  %          <NA>           <NA> relative_humidity              %
12                                    soilM    3.91e+02           SWC_1              %                         23                  % SoilMoistFrac            (-)     SoilMoistFrac            (-)
13                                    soilT    3.79e+02            TS_1        celsius                         15          degrees C      SoilTemp              K          SoilTemp              K
14                          solar_radiation    5.47e+02           SW_IN          W m-2                         27              W/m^2        SWdown          W/m^2            SWdown          W/m^2
15                        specific_humidity    5.57e+02             H2O         g kg-1                         33              g g-1          Qair        kg kg-1              Qair        kg kg-1
16 surface_downwelling_longwave_flux_in_air    5.61e+02           LW_IN          W m-2                         31              W m-2        LWdown           W/m2            LWdown           W/m2
17                                      UST    1.00e+09           USTAR          m s-1                          3              m s-1          <NA>           <NA>               UST          m s-1
18                                      VPD    3.87e+02          VPD_PI            kPa                         22                 Pa          <NA>           <NA>               VPD             Pa
19                           wind_direction    5.60e+02              WD        degrees                          5            degrees          <NA>           <NA>    wind_direction        degrees
20                                     Wspd    3.90e+02              WS          m s-1                          6              m s-1          <NA>           <NA>              Wspd          m s-1

$skip
[1] 2

$header
[1] 1

$na.strings
[1] "-9999" "-6999" "9999"  "NA"   

$time.row
[1] 4

$site
NULL

$lat
NULL

$lon
NULL

$time_zone
NULL
>
```

So I think what's happening is that this variables table contains three inconsistencies that are passed on from here to `met2CF.csv`, which then gets confused and stops.

Of the three warnings, I think the precipitation units need to be handled by met2CF.csv, the SWC units could probably be fixed by updating the record to use "%" or "percent" everywhere, and I'm not sure what to do with the multiple-NEE warnings -- is it really appropriate for uncorrected turbulent flux ("FC" in the Ameriflux nomenclature) to be named as "NEE" in Bety?

**Comment by infotroph** [comment]
@ankurdesai Sorry, missed your comment before posting last one. Where is the unit conversion handled for AmerifluxLBL? For older Amerifluxes I see it in `met2CF.Ameriflux`, but this workflow calls met2CF.csv, and I don't see anything that handles precip conversion there...

**Comment by mdietze** [comment]
A few additional comments:

1) soil moisture: I think the format record is correct but the code is wrong in what it's trying to convert to. Here's what I got playing around with udunits2
```
> udunits2::ud.are.convertible("percent","proportion")
[1] FALSE
> udunits2::ud.are.convertible("percent","-")
[1] FALSE
> udunits2::ud.are.convertible("percent","1")
[1] TRUE
> udunits2::ud.convert(50, "percent", "1")
[1] 0.5
> udunits2::ud.convert(50, "%", "1")
[1] 0.5
```
Basically it tells us that proportion data should have units of "1" not units of "proportion" or "-"

2) precip: I suspect what Ankur means by "the code knows how to handle this" is that the precip is mm per timestep, but for a small subset of towers that timestep is 1 hr not 30 min, so we have to sort that out on the fly. That said, I do think this format record would be clearer if the units were "kg/m2" rather than "mm".  Depending on when the unit conversions are actually called, we might be able to handle them by updating the format record itself once we know the timestep and then just let udunits do it's job:
```
> udunits2::ud.convert(0.5, "kg/m2/hr", "kg/m2/s")
[1] 0.0001388889
> udunits2::ud.convert(0.5, "kg/m2/(30 minutes)", "kg/m2/s")
[1] 0.0002777778
```

3) NEE: so that check needs updating. There's a special case that allows FC to be used in lieu of NEE that's a legacy from the ORNL Ameriflux L2 product, which had FC but no NEE. One option is to make that check more sophisticated (don't use FC as NEE if there's already a NEE), the other would be to comment it out (which would break any code that uses old ORNL L2, but that's all deprecated in favor of the LBL and FLUXNET products)

**Comment by ankurdesai** [comment]
I can work on these next week. However, all of this will be depricated soon as Ameriflux now has moved to its new "FP" standard, with better automated QC checks and direct application of fluxnet u* screening and gap filling without manual intervention. Spent a good chunk of summer converting all my legacy flux data to this format.

**Comment by dlebauer** [comment]
To clarify - is this a BioCro problem or problem with the met workflow?

**Comment by ankurdesai** [comment]
@dlebauer workflow
