### ISSUE TITLE
Sort and document base/utils/data

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#1713]
## Description

Part of #1681. many of the files in `base/utils/data/` do not seem to be used in any code or examples, and several are large enough to trigger warnings from `R CMD check`. The whole folder should be reviewed and cleaned up as needed.

## Completion criteria:

* [x] Remove truly unused data files
* [x] Document all remaining datasets by editing base/utils/R/datasets.R
* [x] Confirm that all existing data calls work with lazy-loading
* [x] Recompress remaining files as needed to optimize installed package size

**Comment by mdietze** [comment]
Some of those (e.g. mstmip_*) can be deprecated, but I think a lot of the others are (or were) used in tests. So I'd take a close look at the tests to figure out what's 'truly unused' as well as whether certain tests could be streamlined to work with smaller datasets.

Do test datasets need to work with lazy-loading?

**Comment by infotroph** [comment]
> Do test datasets need to work with lazy-loading?

No if they're moved to the test directory, yes if they stay in `data/`. When lazy-loading is on, everything in data/ is converted to Rdata files at build time.

I expect we'll want to retain the raw form of everything used to test file-loading code. For datasets that get processed into an R object before we used them, lazy-loading will probably Just Work.

**Comment by infotroph** [comment]
Bumping this, because setting `LazyData: True` in #1684 puts all of these datasets into the package namespace, leading to nasty bugs like #1720, where PEcAn.utils::prior.distns was shadowing a local `prior.distns` when the workflow deleted it. 

There could well be more bugs like this. To verify that there aren't, would need to look up all the variable names stored inside `base/utils/data/*.RData` and see where else those names are used in the PEcAn code at times `PEcAn.utils` might be loaded.

**Comment by infotroph** [comment]
(assigning myself, but help welcome)

**Comment by infotroph** [comment]
- [ ] `base/utils/data/madata.RData` is not used anywhere. Delete, or move to `modules/meta.analysis/tests/testthat/data/` and write tests that use it?
- [ ] `base/utils/data/output.RData` is not used anywhere, AND is binary-identical to `modules/uncertainty/data/output.RData`. Delete.
- [ ] `base/utils/data/samples.RData` is not used anywhere, AND is binary-identical to `modules/uncertainty/data/samples.RData`. Delete.
- [ ] `base/utils/data/sensitivity.analysis.RData` is not used anywhere. Delete, or move to `modules/uncertainty/tests/testthat/data/` and write tests that use it?
- [ ] `base/utils/data/settings.RData is not used anywhere, and not clear that any test would need it (most seem to read their settings from XML instead of loading a premade list). Delete?

**Comment by mdietze** [comment]
If those are used anywhere it would be in tests. If they're not used in any tests then I'm in favor of deleting -- it's quite possible that many of those are out of date anyway.

**Comment by dlebauer** [comment]
yep 👍 to delete unused files

**Comment by infotroph** [comment]
- [ ] `base/utils/data/time.constants.RData` is referenced from one commented-out line in `models/ed/inst/timeutils.R` and has been thoroughly replaced by `lubridate`. Delete.
- [ ] `base/utils/data/trait.data.RData` is not used anywhere that I can tell. Delete.
- [ ] `base/utils/data/trait.mcmc.RData`:
    * contains a variable that shadows a name used in `get_parameter_samples.R`, i.e. it has high potential for a bug near-identical to #1720
    * is very large (6 MB!), because it contains 4*5021 MCMC samples for between 2 and 17 parameters from each of 7 traits
    * is used by `modules/meta.analysis/tests/testthat/test.approx.posterior.R`, but I don't see anything in the tests that requires all 5000 samples.
    * ==> Delete, and add a MUCH SMALLER replacement version to `modules/meta.analysis/tests/testthat/data/`?

**Comment by infotroph** [comment]
And to wrap it up, the CSVs:
- [ ] mstmip_local.csv and mstmip_vars.csv are deprecated in our hearts but still used by some packages. Keep for now.
- [ ] standard_vars.csv and standard_vars.R are workhorses. Keep.
- [ ] trait.dictionary.csv is used in a number of places in PEcAn.DB, PEcAn.utils, and PEcAn.assim.batch. I'm unclear what its role is, but it doesn't seem to be hurting anything. Keep?

**Comment by mdietze** [comment]
* Agree to deleting time.constants.RData and trait.data.RData. 
* Check whether downsizing trait.mcmc.RData would actually make the download smaller (since the history of the file would still stay in the repository).
* Why don't we just fix the few function that still use mstmip_*.csv and then delete?
* I disagree about trait.dictionary not hurting anything -- I think it should be deleted too. It's basically a look up table of 'pretty' names, but maintaining that list as we add more and more models with more and more parameters has proven unsustainable and thus is a bad idea. Variable names should come directly from the BETY variables table. The presence of this look up table causes an ugly, but nonfatal, error whereby non-matching variable names become NA -- for some models the Sensitivity Analysis figure is just labeled NA on ever panel, rendering it useless. A while back the Uncertainty Analysis viz code was switched to use the variable name directly and no one has complained.

**Comment by infotroph** [comment]
> Check whether downsizing trait.mcmc.RData would actually make the download smaller (since the history of the file would still stay in the repository).

Probably won't reduce the size of a whole-repo clone, but will reduce the installed size of the utils package and the size of shallow clones (notably including Travis runs).

**Comment by infotroph** [comment]
To remove trait.dictionary.csv, probably need to edit the following files (as determined by `$(grep -R 'trait.dictionary' pecan/)`:
- [ ] base/db/R/get.trait.data.R: Remove option to use trait.dictionary
- [ ] base/utils/R/utils.R: Delete trait.lookup function entirely? Make it perform a bety query?
- [ ] base/utils/tests/testthat/test.trait.dictionary.R: Remove or rewrite to match updated function
- [ ] book_source/developers_guide/Package-data.Rmd, modules/assim.batch/vignettes/AssimBatchVignette.Rmd: Update documentation to match current practice

**Comment by infotroph** [comment]
To remove `mstmip*.csv`, probably need to edit the following files (as determined by `$(grep -R 'mstmip' pecan/)`, and should probably deprecate for a release before removing:

- [ ] base/db/inst/bety_mstmip_lookup.csv: Is this file used in conjunction with the utils mstmip tables, or separately? Any changes needed?
- [ ] base/db/R/query.format.vars.R uses bety_mstmip_lookup; see questions above
- [ ] base/utils/inst/get_mstmip_vars.R: Deprecate mstmipvar function
- [ ] base/utils/inst/get_mstmip_vars.R: Delete entire file
- [ ] book_source/models/variables.Rmd: Update docs to show current practice
- [ ] models/ed/R/model2netcdf.ED2.R: Convert 42 `mstmipvar()` calls into standard_vars lookups
- [ ] models/ed/tests/testthat/test.model2netcdf.ED2.R: Update tests to match above
- [ ] models/lpjguess/R/model2netcdf.LPJGUESS.R: Remove apparently unused assignment `mstmipvar <- PEcAn.utils::mstmipvar`
- [ ] models/maat/R/model2netcdf.MAAT.R: Remove apparently unused `@importFrom PEcAn.utils mstmipvar`
- [ ] models/maat/R/model2netcdf.MAAT.R: Remove apparently unused assignment `mstmipvar <- PEcAn.utils::mstmipvar`
- [ ] modules/benchmark/R/format_wide2long.R: ?? Will the "mstmip_name" and "mstmip_units" columns of new_var still be needed? Update if necessary
- [ ] modules/data.atmosphere/R/load.cfmet.R: Figure out how to replace mstmip with standard_vars in the section labeled "pressure naming hack"
- [ ] modules/uncertainty/R/run.ensemble.analysis.R: Get units from standard_vars instead of mstmipvar

...Do we want to move forward with this one right now, or bounce it to another issue? If now, I'll want help from folks who who know the relevant packages.

**Comment by infotroph** [comment]
The two remaining unchecked boxes have their own issues, linked above. Closing this one.
