### ISSUE TITLE
Deprecation warnings from moved utils functions

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#1719]
Found a few tools moved from utils that still need to be cleaned up

```
2017-10-09 15:11:37 DEBUG  [PEcAn.logger::logger.debug] : 
   Waiting for the following jobs: 105128 105129 105130 105131 105132 
Warning: '$.SafeList' is deprecated.
Use 'PEcAn.settings::$.SafeList' instead.
See help("Deprecated")
Warning: '$.SafeList' is deprecated.
Use 'PEcAn.settings::$.SafeList' instead.
See help("Deprecated")
Warning: '$.SafeList' is deprecated.
Use 'PEcAn.settings::$.SafeList' instead.

```

and 

```
2017-10-09 15:11:17 DEBUG  [PEcAn.logger::logger.debug] : 
   updated met path: 
   /data/Model_Output/pecan.output/dbfiles/CRUNCEP_SIPNET_site_2-5/CRUNCEP.1990-01-01.2010-12-31.clim 
Warning: 'listToXml.default' is deprecated.
Use 'PEcAn.settings::listToXml.default' instead.
See help("Deprecated")
Warning: 'listToXml' is deprecated.
Use 'PEcAn.settings::listToXml' instead.
See help("Deprecated")
Warning: 'listToXml.default' is deprecated.
Use 'PEcAn.settings::listToXml.default' instead.

```

## Description

Move to settings

**Comment by infotroph** [comment]
It appears that these deprecation warnings happen inside functions from PEcAn.utils, where the deprecated local copies of the method are always higher in the search path than the now-official PEcAn.settings copies. I see three possible resolutions:

1. Note that the deprecated functions still work, do nothing, and repeatedly assure users that these warnings are nothing to worry about.
2. Delete the copies in PEcAn.utils now, with no deprecation period.
3. Implement #1722 in a way that ensures all calls to SafeList, listToXml, etc occur in a namespace where the PEcAn.settings namespace is found before the PEcAn.utils namespace.

**Comment by infotroph** [comment]
Tentative plan is to remove the deprecated functions in v1.5.2.

**Comment by bcow** [comment]
One argument for resolving this sooner as opposed to later is that it makes the build output so long that it can't be displayed in 10000 lines and thus you can't get to the end the online log for a failed Travis build (I downloaded the raw log and it was over 14000 lines)

**Comment by serbinsh** [comment]
Yeah that is a good reason
