### ISSUE TITLE
met type doesn't show up in README file

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#1765]
Met source is always left blank in the automatically generated README file. This isn't a work-stopping bug, but it seems like either a quick-fix or if it isn't we could remove the ```met:``` field from the README.

**Comment by bcow** [comment]
I'd like this fixed. @mccabete @tonygardella anyone want to tackle this? I can give it a try too.

**Comment by infotroph** [comment]
Looks like at least in [write.ensemble.configs](https://github.com/PecanProject/pecan/blob/develop/base/utils/R/ensemble.R#L266) it may be as simple as pointing it toward a different element of settings -- None of my settings files have a `settings$run$site$met`. Should that be something like `settings$run$inputs$met$path`?

If so, probably also needs to be updated in write.sa.configs, pda.init.run, etc.

**Comment by mdietze** [comment]
I suspect that we moved met out of `site` and created `inputs` at some point and just didn't catch this one reference.

**Comment by infotroph** [comment]
@mccabete This seems to be working for me in current develop, though I'm not sure when or how it was fixed. Working for you too / OK to close?

**Comment by robkooper** [comment]
to me it looks like this is still wrong, see https://github.com/PecanProject/pecan/blame/develop/base/utils/R/sensitivity.R#L317

**Comment by infotroph** [comment]
More precisely: My README files now contain a populated `met data` line, even though the fix we discussed above doesn't seem to have been implemented. Just me?
<img width="690" alt="Screen Shot 2019-11-08 at 8 07 02 PM" src="https://user-images.githubusercontent.com/1256435/68503617-93a05e80-0263-11ea-9292-4aefc9f8c5fc.png">

**Comment by moki1202** [comment]
is this issue  still open?

**Comment by mccabete** [comment]
Yes! It is fixed!
