### ISSUE TITLE
Write.configs() not supplying ED2IN with expected defaults

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#1767]
There are two major issues with write.configs: 
- Supplying incorrect met paths (even when the correct path is in the pecan.xml, and correct in workflow up until write.configs())
- Not changing the initial condition flags in the ED2IN when an initial condition file is supplied.

**Comment by istfer** [comment]
could you elaborate:
- which IC paths? pss/css?
- which IC flags?
- could you provide a sample workflow that failed?

**Comment by mccabete** [comment]
@istfer The IC flag that wasn't being changed was the @INIT_MODEL@ flag.  I'm pretty sure the reason it wasn't being caught was because I was feeding it a combined css/pss/site input format (this one) that doesn't include css/pss/site in the file name, which was what write configs was using to check if a input file is provided.

**Comment by mccabete** [comment]
Update: the met path part of this issue is actually taking place in do_conversions.

**Comment by mccabete** [comment]
I'm closing this issue and linking it to an open issue that explains the ED ic format that caused the bug.
