### ISSUE TITLE
Sipnet met2model only runs 1 day in 1 year run

### ISSUE THREAD

**Issue by ankurdesai** [PecanProject/pecan#1769]
met2model.sipnet needs changing

## Description
When run for one year on web workflow using flux tower met, met2model.sipnet only runs the first 24 hours (1 day). When run with multiple years, it runs fine. Curious if it can be replicated by others, if it is met specific, or model specific?

## Context
People running models for just one year will be unhappy

## Possible Implementation
Either somewhere in convert.inputs or more likely in met2model.sipnet, there is some logic that needs changing when end_year==start_year. I did a quick scan and couldn't figure it out. 

No author information in met2model.sipnet, so I'm tagging a few folks here.

**Comment by tonygardella** [comment]
Recreated BUG at Fort Peck (US-FPe) for 2004. Looking into it now.

**Comment by istfer** [comment]
I encountered the same bug just now working on a separate issue

I happens because of [this chunk](https://github.com/PecanProject/pecan/blob/develop/models/sipnet/R/met2model.SIPNET.R#L217_L223)

**Comment by ankurdesai** [comment]
I see the problem now. end.row should not be subsetting from 1 but if < days_in_year, and then from 1:diy-end.row. need to go teach. Then can try to fix.

**Comment by ankurdesai** [comment]
I made the fix, testing it, and will make pull request after.
