### ISSUE TITLE
Replace `RPostgreSQL` with `RPostgres`

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#1799]
## Description

The latest version of `dbplyr` [recommends](https://github.com/tidyverse/dbplyr/blob/master/NEWS.md) switching from `RPostgreSQL` to the newer package [`RPostgres`](https://github.com/r-dbi/RPostgres), which is more DBI compliant. The way our stuff is designed, I think that would be mostly a drop-in replacement -- nothing structural would have to change.

## Context

Here are the advantages of `RPostgres` over `RPostgreSQL`, quoted from their `README`:
> * Has full support for parameterised queries via dbSendQuery(), and dbBind().
> * Automatically cleans up open connections and result sets, ensuring that you don't need to worry about leaking connections or memory.
> * Is a little faster, saving ~5 ms per query. (For reference, it takes around 5ms to retrive a 1000 x 25 result set from a local database, so this is decent speed up for smaller queries.)
> * A simplified build process that relies on system libpq.

Point 2 seems like it could be really useful -- we might be able to eliminate the need for explicit calls to `db.close()`, especially if this closes connections on garbage collection when variables are removed (i.e. connections specific to functions would not need to be closed). Parameterized queries (point 1) could be a plus too -- that's something we've discussed in the past. They may be implemented natively already in `dplyr/dbplyr`'s standard functions. The speed increase and simplified build could be helpful as well, especially for our continuous integration.

Given that it seems to cost relatively little to implement, and the benefits could accumulate as the R DBI package ecosystem continues to grow, seems like it might be worth it?

## Possible Implementation

As far as I can tell, all we would need to do is:
* Change the `db.open` function definition to use the `RPostgres` driver
* Change the `Depends/Imports` of `PEcAn.DB`
* Find any residual instances of using `RPostgreSQL` directly and change them (there shouldn't be many -- seems like we mostly use `db.open`).

**Comment by robkooper** [comment]
Thank you @ashiklom, 'Has full support for parameterised queries via dbSendQuery(), and dbBind().' is a major reason to change.

**Comment by ashiklom** [comment]
Re: Parameterized queries, it [looks like](https://github.com/r-dbi/RPostgres/blob/468ef77eb9617917bb1c7e89fb12983621b8d547/R/PqResult.R#L58-L61) syntax that's something like this might be supported:
```r
dbGetQuery(con, "SELECT id, var FROM tbl WHERE id = $1 AND var = $2", params = list(user$supplied, potentially$malicious))
```
(Caveat: Have not tested).

**Comment by ashiklom** [comment]
We aren't at 100% replacement yet, but I think we have fairly robust support for RPostgres as of #2318 and I've been successfully using PEcAn with RPostgres for a while now. So I'm closing this.
