### ISSUE TITLE
Allometry module install failed: pecan.logger error

### ISSUE THREAD

**Issue by andydawson** [PecanProject/pecan#1801]
### Allometry module install fails

Previously it has been possible to install the pecan allometry module according to instructions in the allometry module vignette:
```
library(devtools)
install_github("PecanProject/pecan",subdir="modules/allometry")
```

Now I get the error

```
ERROR: dependency ‘PEcAn.logger’ is not available for package ‘PEcAn.allometry’
```

Any ideas on how to resolve?

**Comment by mdietze** [comment]
Yeah, we moved logger and a bunch of similar utils into a “base” folder, so I need to update the install_github in those packages. At back-to-back basketball games for the kids this AM, but will try and get that pushed out over lunch
