### ISSUE TITLE
Build-breaker: bioconductor-mirror does not exist anymore

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#1806]
## Description

```
Rscript -e "devtools::document('"models/ed"')"
Updating PEcAn.ED2 documentation
Loading PEcAn.ED2
Loading required package: PEcAn.utils
Attaching package: ‘PEcAn.utils’
The following object is masked from ‘package:utils’:
    download.file
Loading required package: coda
Error in (function (dep_name, dep_ver = NA, dep_compare = NA)  : 
  Dependency package BiocInstaller not available.
Calls: <Anonymous> -> load_all -> load_imports -> mapply -> <Anonymous>
Execution halted
make: *** [.doc/models/ed] Error 1
```

## Context

`PEcAn.ED2` depends on `rhdf5`, which is only available from BioConductor. The current build system attempts to install it from https://github.com/bioconductor-mirror, which has been deleted. Builds without a cached copy of rhdf5 -- i.e. all of them as soon as our Travis cache gets clobbered for any reason -- now fail. Here's a sample [failing build](https://travis-ci.org/infotroph/pecan/builds/327282968) from my fork.

## Possible Implementations

1. Switch entirely from `rhdf5` to `h5 ` as proposed in #1797 
2. Change remote URLS, possibly to something like `github::bioconductor/BiocInstaller@RELEASE_3_5` and `git::https://git.biocondutor.org/packages/rhdf5.git`?
3. Temporary workaround: tell Travis to install the precompiled version of rhdf5 from [c2d4u](https://launchpad.net/~marutter/+archive/ubuntu/c2d4u/+packages?field.name_filter=rhdf5) and make users wrestle Bioconductor on their own until we deploy a more permanent fix
4. ???

**Comment by ashiklom** [comment]
`h5` is a more involved change. A shorter-term solution is just to use the native Bioconductor installation functionality [provided](https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html) by `remotes/devtools`. A line like this ought to do it:

```
Remotes:
<...>
bioc::release/rhdf5
```

**Comment by ashiklom** [comment]
Just kidding, that doesn't work because the `bioc` remote interface is outdated. A temporary fix I'm implementing is to point to this guy's forks of `rhdf5` and `Rhdf5lib`, which seem to be pretty up to date: https://github.com/grimbough
