### ISSUE TITLE
Is model2netcdf.ED2 built for backwards compatibility, and if so, do we still want it? 

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#1821]
Hello all, 

In model2netcdf.ED2 the output variable TotLivBiom is [commented out](https://github.com/PecanProject/pecan/blob/develop/models/ed/R/model2netcdf.ED2.R#L197). 

This tracks to [this commit](https://github.com/PecanProject/pecan/commit/4b6c9b8986e6d07bdda521b0af55443bc806f1bf). Which seems to be done for backwards compatibility. 
 For AGU I edited model2netcdf.ED2 to output TotLivBiom, a variable that is in our standard. I just wanted to see if I should push those changes?

**Comment by mdietze** [comment]
That's a good question -- the variables involved (BDEAD and BALIVE) have always been in ED2 output, so I think the issue about why this is commented out isn't backward compatibility. Indeed, I followed 'blame' back as far as it would take me and that bit of code seems to have ALWAYS been commented out:

https://github.com/PecanProject/pecan/blame/080ccc364c166079721f5bc946e1b929b7db8486/models/ed/R/model2netcdf.ED2.R

So, short answer -- PR your fix

Longer answer: the existing way of handling backward compatibility is unsustainable (doesn't handle any new variables being added) and results in massive code redundancy. Much better would be to put a wrapper around the current approach that would check to see if the variable exists in the hdf5 and then only add it to the netcdf if it exists.
