### ISSUE TITLE
Coordinate dependency version across packages?

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#1837]
## Description

*Generally:* When a dependency is used by multiple PEcAn packages, some of which care about its version and others don't, is it preferable to have the PEcAn packages specify the same minimum version or for each package to report its own requirements?

*Specifically:* I just added some tests to PEcAn.DB that rely on `testthat::teardown()`, which is new in testthat 2.0. I've already updated the DESCRIPTION for PEcAn.DB to say `Suggests: testthat (>= 2.0.0)`; does it makes sense to also update it for the many packages that currently specify `testthat (>= 1.0.2)`?

Pro of using the same spec everywhere: satisfying version requirement for one package satisfies it for all of them, less chance of version conflicts when updating individual packages. This might be especially important for packages listed in `Suggests`, where there is by default no version enforcement at install time.

Con: More work, dilutes the principle that DESCRIPTION tells you what *this package* needs, potentially forces dependency upgrades where not strictly needed. This last is probably only a concern if installing individual packages outside of PEcAn, though.

**Comment by ashiklom** [comment]
I would argue that each package should use its own. I would love to get to a point where individual PEcAn packages -- or, at least, the `models` and `modules` packages -- are more-or-less fully functional on their own, to the point of even being eligible to go on CRAN, and then the `base` PEcAn packages link those packages to the PEcAn workflow.

**Comment by bpbond** [comment]
This is a particularly tricky problem, in my experience, with the `tidyverse` packages. That team seems to not share the R community's traditional reluctance to make breaking changes.

**Comment by robkooper** [comment]
I think this is a good case of where we should look at packrat.

**Comment by ashiklom** [comment]
`renv` is the new `packrat`. I've been using `renv` a lot and it works great! Highly recommend we move to it as soon as possible.
