### ISSUE TITLE
Leverage the postGIStools package in bety spatial queries

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#1849]
Stumbled across the [`postGIStools`](https://cran.r-project.org/web/packages/postGIStools/vignettes/postGIStools-vignette.html) package, which seems to provide an interface between postGIS's geometries and R spatial analysis packages. Might come in handy if we ever need to do more advanced spatial queries.

**Comment by robkooper** [comment]
This now replaced by https://github.com/r-spatial/sf

**Comment by ashiklom** [comment]
`sf` is great --- it can be tricky to install (because of underlying GDAL dependency), but we probably need GDAL anyway if we're going to do any kind of serious spatial stuff (which we do in the met workflow, if nothing else). I still think we could replace a lot of our existing lat-lon processing code with proper spatial querying using `sf` and friends. But that's a different conversation.

Closing this.
