### ISSUE TITLE
Remove `site.id` argument from the `PEcAn.data.atmosphere::download.*` functions

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#1869]
None of the meteorology download functions actually use the site ID for anything other than naming the directory, and most of the (more recent?) functions don't have site ID as an argument at all.

This should be a quick fix, but opening an issue to remind us to do it.

The ones that need it removed are:

- CRUNCEP
- GFDL
- GLDAS
- MACA
- MSTMIP
- NLDAS

**Comment by infotroph** [comment]
Fixed for GFDL in #1927

**Comment by rahul799** [comment]
Hey @ashiklom ,I have fixed this `issue` & have made a `PR` (#2500 ). Please review it & let me know if any changes needed.

**Comment by dlebauer** [comment]
#2500 was closed but this was addressed in #2502;
