### ISSUE TITLE
ED2 documentation

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#1879]
Documentation is located in `book_source/06_reference/02_models/ed.rmd`. Sections to be filled in are:

* [ ] Introduction
* [ ] PEcAn configuration
* [ ] Model-specific inputs
* [ ] Model configuration files
* [ ] Installation notes

**Comment by infotroph** [comment]
Current documentation looks like it ticks all these boxes, so closing.  cc @ashiklom: Contradict me if needed.
