### ISSUE TITLE
Sites don't show up in the interactive map

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#1884]
When working with the interactive map the site "[Avon park](http://psql-pecan.bu.edu/bety/sites/1000025727)" isn't available when I select a specific model (only shows up for "all models").  This is only true if I'm tryin to find it with a site group ([Department of Defense sites](http://psql-pecan.bu.edu/bety/sitegroups/1000000021)). This site WILL show up if I am on "all sites" and select a specific model. 

Conversion is checked. This is true across machines. 

The only difference between Avon Park and the other sites that are listed in DoD sites is that I just associated an input with Avon. This may be a red herring though. 

@robkooper  Any ideas why this could be happening?

**Comment by mdietze** [comment]
Sites fail to show up when a model has required Inputs that are not in the database. They stay missing after "Conversion" is checked if PEcAn doesn't think it knows how to generate those required Inputs on-the-fly.  Is this happening for all models or just ED2?

**Comment by mccabete** [comment]
All models. 
but: 
1. Is there a list of what's required? A quick comparison of the sites didn't show anything missing at Avon that wasn't missing elsewhere, but you never know. 
2. This isn't true when I'm selecting from "all sites", so I suspect it isn't a model- requirements thing.

**Comment by robkooper** [comment]
Thanks, this should be fixed now. You can check at http://pecan-dev.ncsa.illinois.edu/pecan/
