### ISSUE TITLE
NA in VPD makes metgapfill fail.

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#1886]
@ankur In metgapfill, I'm getting an error: 
```
Error in VPD[VPD > es] <- es : NAs are not allowed in subscripted assignments
```  
and then it exits met.process. Looking at VPD there are 11 values in a row that are NA.  

## Context
I was doing a run at Niwot Ridge from 2003-2006 using Ameriflux and the error shows up when processing 2005.

## Possible Implementation
For solutions should I tell the user to select new dates and tell which date is problematic, or should there be fix to the code to somehow bypass the NAs?

**Comment by tonygardella** [comment]
The whole error that shows up is:
``` 
Error in VPD[VPD > es] <- es : 
  NAs are not allowed in subscripted assignments
Calls: remotefunc -> <Anonymous>
In addition: Warning messages:
1: In 12 + lc - et :
  Recycling array of length 1 in array-vector arithmetic is deprecated.
  Use c() or as.vector() instead.

2: In 12 + lc - et - tz :
  Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.

3: In sin(lat * pi/180) * sin(dec) :
  Recycling array of length 1 in array-vector arithmetic is deprecated.
  Use c() or as.vector() instead.

4: In cos(lat * pi/180) * cos(dec) :
  Recycling array of length 1 in array-vector arithmetic is deprecated.
  Use c() or as.vector() instead.
```

**Comment by ankurdesai** [comment]
I think this is an issue with R subscripting that can be fixed, probably by switching to some sort of "which statement". It turns out that is the assignment value is a vector, then NA can not be in the subset list for array subscripting. Which is too bad, because I like how clean the code looks that way.

**Comment by tonygardella** [comment]
@ankurdesai Do you have time to dive into this within the next day or two?
