### ISSUE TITLE
GFDL check for existing Files 

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#1902]
download.GFDL doesn't have a check for existing files. It tries to download files even if one already exists for the year someone wants. 
## Possible Implementation
Similair to CRUNCEP need to add a check you enter loop over years
```
   if (file.exists(loc.file) && !isTRUE(overwrite)) {
     PEcAn.logger::logger.error("File already exists. Skipping to next year")
      next
    }
```

**Comment by tonygardella** [comment]
Want to double-check with @ankurdesai and @jsimkins2 if this is right.

**Comment by ankurdesai** [comment]
Ok, will work on it .
