### ISSUE TITLE
GFDL Bug with tmp file

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#1911]
Ran into GFDL bug and tried to characterize it better. 

## Error Message
```
 fp <- file('/home/carya/output/dbfiles/GFDL_site_0-772//pecan-5d18dd8fad2326c6906437c44d2ad9', 'w')
Error in file("/home/carya/output/dbfiles/GFDL_site_0-772//pecan-5d18dd8fad2326c6906437c44d2ad9",  : 
  cannot open the connection
In addition: Warning message:
In file("/home/carya/output/dbfiles/GFDL_site_0-772//pecan-5d18dd8fad2326c6906437c44d2ad9",  :
  cannot open file '/home/carya/output/dbfiles/GFDL_site_0-772//pecan-5d18dd8fad2326c6906437c44d2ad9': No such file or directory
Execution halted
[1] 1
Warning in file(tmpfile, "w") :
  cannot open file '/home/carya/output/dbfiles/GFDL_site_0-772//pecan-5d18dd8fad2326c6906437c44d2ad9': No such file or directory
Error in file(tmpfile, "w") : cannot open the connection
Calls: <Anonymous> ... .download.raw.met.module -> <Anonymous> -> <Anonymous> -> file
```

## Context
Tried running Sipnet at Fort Peck and Niwot Ridge for 2015 with GFDL

## Possible Implementation
Seems either the file is missing on their server or the query is built wrong.

**Comment by tonygardella** [comment]
I believe the issues is the executoin of the download function from convert.inputs:
```
PEcAn.remote::remote.execute.R(script = cmdFcn, host, user = NA, verbose = TRUE, R = Rbinary, scratchdir = outfolder)
```
The scratchdir is set to what outfolder is by default where the source_site_site-id : GFDL_site_0-772
However, within the download function, the outfolder becomes: GFDL_CM3_rcp45_r1i1p1_site_0-772
This means the scratchdir does not actually exist so the tmp file is not actually available. 

To fix: We  don't keep the GFDL model/scenario/ensemble_member by default in settings so it would be hard to change the outfolder arg before the download function. However, from within the download function I don't think I can set the scratchdir that remote.execute.R is using. Not sure on a fix right now other than putting in a hack where I hard code a check for GFDL in download.raw.met.module, where outfolder is originally set, and hard code the file name to include the model/scenario/ensemble_member.

**Comment by ankurdesai** [comment]
Why not just create the scratchdir (original outdir) in download function, even if only used for tmp file. No harm in creating extra directories, no?

**Comment by tonygardella** [comment]
That's a possibility. I just wanted to avoid unnecessary bloat.

**Comment by ankurdesai** [comment]
Did a quick test here after merging in the PR. Seems to be working (in creating directories/writing). The GFDL server is not responding, so it is hanging on download, but that's a different issue. We need a way to detect servers being down at some point. I think we can close this specific issue.
