### ISSUE TITLE
Out-of-date bety entry overwriting entry fixes

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#1942]
**Describe the bug**
Our [Ameriflux format record](http://psql-pecan.bu.edu/bety/formats/5000000001/) will get overwritten by a version of the record with an extra NEE column.  In the past this was caused by the BU version of bety getting overwritten (on the order of minuets). We caught that, but I've noticed that that record gets overwritten also on the order of months. 

**To Reproduce**
Can't really be reproduced (Anne caught and fixed the extra NEE column) except that I can say that I deleted that extra NEE column in the fall of last year after we fixed the frequent overwriting problem. 

**Expected behavior** 
See if our bety version is getting overwritten by an older instance, and if yes prevent that from happening.

**Comment by annethomas** [comment]
This is specifically FLUXNET2015, and @robkooper said he would try deleting entry ID 83 in formats_variables at UIUC.

**Comment by annethomas** [comment]
My question is whether deleting that format-variable will remove NEE from the FLUXNET format altogether? Because I do need that variable for benchmarking and it's helpful if load_data can grab it.

**Comment by robkooper** [comment]
This is also related #1784

**Comment by ankurdesai** [comment]
No - it will only delete the association of the variable to the format.

**Comment by annethomas** [comment]
Is that what's been causing the duplicate to show up?

**Comment by annethomas** [comment]
The duplicate is still there. @robkooper were you able to delete that format_variables entry? Is there anything we need to do on our end? When you say delete the row added in #1784, what do you mean?

**Comment by robkooper** [comment]
```
ebi_production=# select id, format_id, variable_id, name from formats_variables where format_id=5000000001;
     id     | format_id  | variable_id |      name
------------+------------+-------------+-----------------
 5000000063 | 5000000001 |         379 | TS_F_MDS_1
 5000000064 | 5000000001 |         298 | LE_F_MDS
 5000000065 | 5000000001 |         135 | CO2_F_MDS
 5000000066 | 5000000001 |         391 | SWC_F_MDS_1
 5000000067 | 5000000001 |         299 | H_F_MDS
 5000000069 | 5000000001 |         560 | WD
 5000000049 | 5000000001 |         390 | WS_F
 5000000051 | 5000000001 |          86 | TA_F
 5000000060 | 5000000001 |         554 | PA_F
 5000000070 | 5000000001 |  1000000041 | USTAR
 5000000071 | 5000000001 |         136 | PPFD_IN
 5000000033 | 5000000001 |         561 | LW_IN_F
 5000000034 | 5000000001 |         387 | VPD_F
 5000000047 | 5000000001 |         547 | SW_IN_F
 5000000003 | 5000000001 |  5000000001 | TIMESTAMP_START
 5000000006 | 5000000001 |         555 | P_F
         83 | 5000000001 |         297 | NEE_VUT_REF
 1000000303 | 5000000001 |         297 | NEE_VUT_REF
 1000000288 | 5000000001 |  1000000206 | RECO_NT_VUT_REF
 1000000289 | 5000000001 |  1000000193 | GPP_NT_VUT_REF
```
Can see that NEE_VUT_REF is twice in the database. Deleting the row with id=83

Delete row
```
ebi_production=# delete from formats_variables where format_id=5000000001 and id=83;
DELETE 1
```

**Comment by annethomas** [comment]
Great thanks
