### ISSUE TITLE
Update bety.sql for Travis

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#1958]
**Description**

Travis tests currently install Bety from http://isda.ncsa.illinois.edu/~kooper/PEcAn/data/bety.sql, which best I can tell was last updated in spring 2017 and therefore does't contain newer entries, notably including the PFT definitions needed for full PEcAn.DB tests. 

If this is still the correct location to install from, bety.sql should be updated to at least include PFTs "Pavi_alamo" and "Pavi_all" from Bety-0. If there's a more up-to-date bety dump elsewhere, .travis.yml should be updated to point toward it.

(P.S. Would it make sense to gzip-compress bety.sql for faster copying?)

**Context** 

The above-mentioned test failures from PEcAn.DB were being masked by a change in how testthat's `reporter` argument works. I've fixed the test arguments in my [fix-tests](https://github.com/infotroph/pecan/tree/fix-tests) branch and temporarily skipped the PFT tests; I will re-enable them once the bety dump is updated.

**Comment by robkooper** [comment]
I can recreate a dump. I want to make sure we use a dump that has only public data, so we can't dump it from one of the main servers. I might be able to do this on the pecan.ncsa.illinois.edu server.

**Comment by infotroph** [comment]
@robkooper I'm testing this out in https://github.com/infotroph/pecan/tree/travis-new-betydump. Failures visible in the current-as-of-this-writing Travis build: https://travis-ci.org/infotroph/pecan/builds/394442188

**Comment by infotroph** [comment]
https://github.com/PecanProject/bety/pull/695 provides a Docker image that covers this use case better than the static dump we were discussing here.
