### ISSUE TITLE
softwareserver-0002 NARR error

### ISSUE THREAD

**Issue by yan130** [PecanProject/pecan#1964]
### CASE I
        <type>NARR</type>
        <site>US-Dk3</site>
        <lat>35.9782</lat>
        <lon>-79.0942</lon>
        <start_date>2001-01-01 00:00:00</start_date>
        <end_date>2001-12-31 23:59:59</end_date>

**Description**
Error message:
>remotefunc <- function() {PEcAn.ED2::met2model.ED2(lst=-5, lat=35.9782, lon=-79.0942, spin_nyear=NULL, spin_nsample=NULL, spin_resample=NULL, overwrite=FALSE, in.path='/home/polyglot/cache/PEcAn/NARR_CF_site_0-756', in.prefix='NARR', outfolder='/home/polyglot/cache/PEcAn/NARR_ED2_site_0-756/', start_date='2001-01-01 00:00:00', end_date='2001-12-31 23:59:59')}
> remoteout <- remotefunc()
2018-06-06 10:22:22 WARN   [PEcAn.ED2::met2model.ED2] : 
   Latitude does not match that of file 35.9782 != 35.978199005127 
2018-06-06 10:22:22 WARN   [PEcAn.ED2::met2model.ED2] : 
   Longitude does not match that of file -79.0942 != -79.0942001342773 
[1] "vobjtovarid4: error #F: I could not find the requsted var (or dimvar) in the file!"
[1] "var (or dimvar) name: mole_fraction_of_carbon_dioxide_in_air"
[1] "file name: /home/polyglot/cache/PEcAn/NARR_CF_site_0-756/NARR.2001.nc"
[1] "/home/polyglot/cache/PEcAn/NARR_ED2_site_0-756//2001JAN.h5"
Error: .onLoad failed in loadNamespace() for 'hdf5r', details:
  call: fun(libname, pkgname)
  error: Error retrieving current error handler
Execution halted
[1] 1
2018-06-06 10:22:22 INFO   [PEcAn.utils::convert.input] : 
   RESULTS: Convert.Input 
2018-06-06 10:22:22 INFO   [PEcAn.utils::convert.input] : 1 
2018-06-06 10:22:22 INFO   [PEcAn.utils::convert.input] :  
2018-06-06 10:22:22 DEBUG  [PEcAn.utils::convert.input] : 
   Processing data failed, please check validity of args:lst=-5, 
   lat=35.9782, lon=-79.0942, spin_nyear=NULL, spin_nsample=NULL, 
   spin_resample=NULL, overwrite=FALSE, 
   in.path='/home/polyglot/cache/PEcAn/NARR_CF_site_0-756', 
   in.prefix='NARR', 
   outfolder='/home/polyglot/cache/PEcAn/NARR_ED2_site_0-756/', 
   start_date='2001-01-01 00:00:00', end_date='2001-12-31 23:59:59' 
2018-06-06 10:22:22 SEVERE [PEcAn.utils::convert.input] : 
   Unable to process data using this function:met2model.ED2 
Error in PEcAn.logger::logger.severe(paste0("Unable to process data using this function:",  : 
  Unable to process data using this function:met2model.ED2
Calls: met.process -> .met2model.module -> <Anonymous> -> <Anonymous>
2018-06-06 10:22:22 WARN   [db.close] : 

### CASE II
        <type>NARR</type>
        <site>US-ORv</site>
        <lat>40.0201</lat>
        <lon>-83.0183</lon>
        <start_date>2001-01-01 00:00:00</start_date>
        <end_date>2001-12-31 23:59:59</end_date>

**Description**
Error message:

>    Begin Model Specific Conversion 
> [1] "Convert to model format"
> No geonamesUsername set. See http://geonames.wordpress.com/2010/03/16/ddos-part-ii/ and set one with options(geonamesUsername="foo") for some services to work
> Error in getJson("timezoneJSON", list(lat = lat, lng = lng, radius = 0)) : 
>   error code 10 from server: Please provide a valid username for the GeoNames Premium Web Service or use the free api.geonames.org server. Thank you for your understanding.
> Calls: met.process ... .met2model.module -> site.lst -> GNtimezone -> as.data.frame -> getJson
> 2018-06-06 10:16:07 WARN   [db.close] : 
>    Connection created outside of PEcAn.DB package 
> Execution halted

**Comment by yan130** [comment]
@dlebauer do you have any idea about 
error code 10 from server: Please provide a valid username for the GeoNames Premium Web Service or use the free api.geonames.org server. Thank you for your understanding.
?

**Comment by infotroph** [comment]
@yan130 Regarding the GeoNames errors: What version of PEcAn is this? The "no geonamesUsername" part should be fixed in #1941, though the associated "error 10..." is new to me.
