### ISSUE TITLE
Move Shiny debugging documentation to a more logical place

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#1983]
Currently, the main text on debugging Shiny is buried in a sub-sub-heading of "Coding Practices" in the developer guide, which doesn't make much sense to me. ([link](https://pecanproject.github.io/pecan-documentation/develop/coding-practices.html#testing)).

To me, a more appropriate place for it is under [Debugging / Debugging Shiny Apps](https://pecanproject.github.io/pecan-documentation/develop/debugging.html).

**Comment by ashiklom** [comment]
This is related to #1282 (which seems pretty stale and could probably be closed?).

**Comment by ashiklom** [comment]
Also, the headings on the "Debugging" page are mis-numbered because the heading levels are wrong.

**Comment by infotroph** [comment]
This looks fixed to me -- we now have [17 Shiny > 17.2 Debugging Shiny Apps](https://pecanproject.github.io/pecan-documentation/develop/shiny.html#debugging-shiny-apps). OK to close, @ashiklom?

**Comment by ashiklom** [comment]
Yeah, let's close it.
