### ISSUE TITLE
Remove dependency on RAtmosphere

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#1984]
## Description
Change [one call to RAtmosphere::SZA](https://github.com/PecanProject/pecan/blob/4bc485478dc07d0cdb21730704119b4f9279c4b1/modules/data.atmosphere/R/met_temporal_downscale.Gaussian_ensemble.R#L306) to use a PEcAn function, remove `RAtmosphere` from PEcAn.data.atmosphere DESCRIPTION file. 

## Context
The `RAtmosphere` package has been removed from CRAN, so it will be a pain to continue using it -- we'd need to install from archives every time. The reasons given for removal seem petty to me (unescaped space characters that made one link in a citation be broken to robots but not to humans), but that's not my fight to have.

## Possible Implementation

With some unit conversion we can probably use [PEcAn.data..atmosphere::cos_solar_zenith_angle](https://github.com/PecanProject/pecan/blob/4bc485478dc07d0cdb21730704119b4f9279c4b1/modules/data.atmosphere/R/solar_angle.R#L13), possibly with some code changes for flexibility -- looks like RAtmosphere::SZA may handle negative latitudes better, but I haven't tested fully.

**Comment by ankurdesai** [comment]
Yes, but is big brother watching us (or the sun)?  (sorry, couldn't resist, given issue number)
