### ISSUE TITLE
 package or namespace load failed for ‘hdf5r' in met2model.ED2.R

### ISSUE THREAD

**Issue by yan130** [PecanProject/pecan#1998]
**Describe the bug**
PEcAn.ED2::met2model.ED2 break the loading of hdf5r package. 

**To Reproduce**
open R, then
`library('hdf5r') `
everything working fine. 

close the R console and open again, 
`PEcAn.ED2::met2model.ED2(lst=-5, lat=35.9782, lon=-79.0942, spin_nyear=NULL, spin_nsample=NULL, spin_resample=NULL, overwrite=FALSE, in.path='/home/polyglot/cache/PEcAn/NARR_CF_site_0-756', in.prefix='NARR', outfolder='/home/polyglot/cache/PEcAn/NARR_ED2_site_0-756/', start_date='2001-01-01 00:00:00', end_date='2001-12-31 23:59:59')`

get 
 
> Error: package or namespace load failed for ‘hdf5r’: 
> .onLoad failed in loadNamespace() for 'hdf5r', details: 
> call: fun(libname, pkgname) 
> error: Error retrieving current error handler

after running above "PEcAn.ED2::met2model.ED2" do: 
`library('hdf5r') `
get the same "Error retrieving current error handler" message

reference: https://github.com/Novartis/hdf5r/blob/master/src/H5Error.c#L128
using develop branch. 

**Temporal Solution**
add 
`library('hdf5r') `
at 
https://github.com/PecanProject/pecan/blob/develop/models/ed/R/met2model.ED2.R#L31

**Comment by robkooper** [comment]
@infotroph do you have any ideas why this could happen? `hdf5r` is listed in DESCRIPTION of models/ed.

**Comment by infotroph** [comment]
No immediate ideas, but I can think on it. 

I can't immediately reproduce this on my machine using the CRUNCEP file I had handy:

```
PEcAn.ED2::met2model.ED2(
	lst=-5, lat=35.9782, lon=-79.0942,
	spin_nyear=NULL, spin_nsample=NULL, spin_resample=NULL, overwrite=FALSE,
	in.path='/Users/chrisb/pecan/dbfiles/CRUNCEP_site_0-753',
	in.prefix='CRUNCEP',
	outfolder='/Users/chrisb/pecan/dbfiles/CRUNCEP_ED2_site_0-753/',
	start_date='2010-01-01 00:00:00', end_date='2010-12-31 23:59:59')
2018-07-05 21:05:05 WARN   [PEcAn.ED2::met2model.ED2] : 
   Latitude does not match that of file 35.9782 != 40.0061 
2018-07-05 21:05:05 WARN   [PEcAn.ED2::met2model.ED2] : 
   Longitude does not match that of file -79.0942 != -88.2919 
[1] "vobjtovarid4: error #F: I could not find the requsted var (or dimvar) in the file!"
[1] "var (or dimvar) name: mole_fraction_of_carbon_dioxide_in_air"
[1] "file name: /Users/chrisb/pecan/dbfiles/CRUNCEP_site_0-753/CRUNCEP.2010.nc"

library('hdf5r')
```

@yan130 does this happen for you with non-NARR met files?

**Comment by yan130** [comment]
no, just for NARR.

maybe I send you my file under 
/home/polyglot/cache/PEcAn/NARR_CF_site_0-756
?

**Comment by infotroph** [comment]
Sure, send it along. I'm on vacation all week and won't be able to look at it immediately, but I'll poke at it when I get a chance.

It's weird that this seems specific to one input file, because I would have thought our first call to any `hdf5r::*` would load the namespace before it does anything file-specific.

**Comment by infotroph** [comment]
I can reproduce this on VM 1.5.3, either in RStudio as shown here or in a terminal R session (terminal session info is identical to this except YAML package is not loaded):

```
> PEcAn.ED2::met2model.ED2(lst=-5, lat=35.9782, lon=-79.0942, spin_nyear=NULL, spin_nsample=NULL, spin_resample=NULL, overwrite=FALSE, in.path='/home/carya/pecan/dbfiles/NARR_CF_site_0-756', in.prefix='NARR', outfolder='/home/carya/pecan/dbfiles/NARR_ED2_site_0-756/', start_date='2001-01-01 00:00:00', end_date='2001-12-31 23:59:59')
2018-07-18 11:12:00 WARN   [PEcAn.ED2::met2model.ED2] : 
   Latitude does not match that of file 35.9782 != 35.978199005127 
2018-07-18 11:12:01 WARN   [PEcAn.ED2::met2model.ED2] : 
   Longitude does not match that of file -79.0942 != -79.0942001342773 
[1] "vobjtovarid4: error #F: I could not find the requsted var (or dimvar) in the file!"
[1] "var (or dimvar) name: mole_fraction_of_carbon_dioxide_in_air"
[1] "file name: /home/carya/pecan/dbfiles/NARR_CF_site_0-756/NARR.2001.nc"
Error: .onLoad failed in loadNamespace() for 'hdf5r', details:
  call: fun(libname, pkgname)
  error: Error retrieving current error handler
> library("hdf5r")
Error: package or namespace load failed for ‘hdf5r’:
 .onLoad failed in loadNamespace() for 'hdf5r', details:
  call: fun(libname, pkgname)
  error: Error retrieving current error handler
> devtools::session_info()
Session info --------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.442)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Chicago             
 date     2018-07-18                  

Packages ------------------------------------------------------------------------------------------
 package               * version date       source        
 base                  * 3.4.4   2018-03-16 local         
 bit                     1.1-12  2014-04-09 cran (@1.1-12)
 bit64                   0.9-7   2017-05-08 cran (@0.9-7) 
 compiler                3.4.4   2018-03-16 local         
 datasets              * 3.4.4   2018-03-16 local         
 devtools                1.13.5  2018-02-18 CRAN (R 3.4.4)
 digest                  0.6.15  2018-01-28 CRAN (R 3.4.4)
 graphics              * 3.4.4   2018-03-16 local         
 grDevices             * 3.4.4   2018-03-16 local         
 lubridate               1.7.4   2018-04-11 cran (@1.7.4) 
 magrittr                1.5     2014-11-22 CRAN (R 3.4.4)
 memoise                 1.1.0   2017-04-21 CRAN (R 3.4.4)
 methods               * 3.4.4   2018-03-16 local         
 ncdf4                   1.16    2017-04-01 cran (@1.16)  
 PEcAn.data.atmosphere   1.5.3   2018-05-04 local (@1.5.3)
 PEcAn.ED2               1.5.3   2018-05-04 local (@1.5.3)
 PEcAn.logger            1.5.3   2018-05-04 local (@1.5.3)
 PEcAn.remote            1.5.3   2018-05-04 local (@1.5.3)
 PEcAn.utils             1.5.3   2018-05-04 local (@1.5.3)
 R6                      2.2.2   2017-06-17 CRAN (R 3.4.4)
 Rcpp                    0.12.16 2018-03-13 CRAN (R 3.4.4)
 stats                 * 3.4.4   2018-03-16 local         
 stringi                 1.2.2   2018-05-02 cran (@1.2.2) 
 stringr                 1.3.0   2018-02-19 CRAN (R 3.4.4)
 tools                   3.4.4   2018-03-16 local         
 udunits2                0.13    2016-11-17 CRAN (R 3.4.4)
 utils                 * 3.4.4   2018-03-16 local         
 withr                   2.1.2   2018-03-15 CRAN (R 3.4.4)
 yaml                    2.1.19  2018-05-01 cran (@2.1.19)
>
```

...(other shoe drops momentarily when I switch computers)...

**Comment by yan130** [comment]
we use the same:
hdf5r      * 1.0.0

**Comment by infotroph** [comment]
The good news is we can blame non-PEcAn components. The bad news is this is weeeeeird. 

Fresh R session:

```
> nc = ncdf4::nc_open("~/output/dbfiles/NARR_CF_site_0-756/NARR.2001.nc")
> ncdf4::nc_close(nc)
> hdf5r::H5File$new("foo")
Error: .onLoad failed in loadNamespace() for 'hdf5r', details:
  call: fun(libname, pkgname)
  error: Error retrieving current error handler
```

So this particular file is... corrupted in some way that breaks libhdf5 *across packages*??

**Comment by infotroph** [comment]
libhdf5 versions:
* OS X (does not reproduce), installed via Homebrew as `hdf5`: 1.10.2_1
* VM (reproduces), installed via apt as `libhdf5-dev` : 1.8.16+docs-4ubuntu1

**Comment by yan130** [comment]
libhdf5-dev:
  Installed: 1.8.16+docs-4ubuntu1

**Comment by robkooper** [comment]
ubuntu 18.04 containers libhdf5 1.10, this might fix the issue.

**Comment by infotroph** [comment]
> did you look into that NARR.2001.nc file?

Sorry: Yes, this is all with the file you sent. I haven't found any others that cause the problem.

**Comment by robkooper** [comment]
Not sure the file is corrupt, looks more like there is some weird interaction between hdf5r and ncdf libraries. All tested on 16.04 ubuntu.

This works:
```
h5 <- hdf5r::H5File$new("foo")
hdf5r::h5close(h5)
nc = ncdf4::nc_open("NARR.2001.nc")
ncdf4::nc_close(nc)
```

This does not work:
```
nc = ncdf4::nc_open("NARR.2001.nc")
ncdf4::nc_close(nc)
h5 <- hdf5r::H5File$new("foo")
hdf5r::h5close(h5)
```

**Comment by infotroph** [comment]
Proposed next step: pull apart NARR.2001.nc, try to construct the smallest possible netCDF that still causes the interaction? Running it through http://pumatest.nerc.ac.uk/cgi-bin/cf-checker.pl?cfversion=auto reports 26 CF convention errors that may be good places to start.

**Comment by robkooper** [comment]
It does seem that there is something with the netcdf files we generated, for example the file in PEcAn code base: modules/data.atmosphere/tests/testthat/data/urbana_subdaily_test.nc also fails however an example netcdf file located at https://www.unidata.ucar.edu/software/netcdf/examples/sresa1b_ncar_ccsm3-example.nc works fine.

**Comment by infotroph** [comment]
@robkooper Can you still reproduce this? I may still have a copy of the test file somewhere, but would have to dig for it.

**Comment by ashiklom** [comment]
I'd vote to close this. I've used `met2model.ED2.R` extensively and never encountered this problem. Also, I think HDF5 1.8 is old at this point -- we should probably be using >=1.10 (as the MacOS setup does above).

**Comment by robkooper** [comment]
closing until we can reproduce.
