### ISSUE TITLE
Check that geospatial information is correct in netCDF input & outputs

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#201]
A student at the flux course pointed out that the SIPNET output was not plotting in the correct location when using a netCDF visualization tool (not sure if it was ncview or something different). I suspect what happened was that it was using a default NULL location. We should check all the netCDF files we are producing to ensure that they render with the correct spatial location.

**Comment by jam2767** [comment]
I can view the coordinates for CF compliant files generated by met2cf.Ameriflux in panoply and can view variables in ncview. However I can't figure out how to display the lat/lon dimensions. The coordinates from model outputs generated using cf compliant inputs still need to be verified and the coordinates from NARR CF files need to be verified.
