### ISSUE TITLE
fix met2CF.csv tests

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#202]
Commented out test in `data.atmosphere/tests/testthat/test.met2CF.csv.R`

> d> test("../../")
> Testing PEcAn.data.atmosphere
> Loading PEcAn.data.atmosphere
> loading data from PEcAn-CF met drivers : ..........
> downscaling : .......
> testing csv import using met2CF.csv : 
> Error in ncvar_add(nc = nc, var = qair.var, verbose = nc_verbose) : 
>   unused argument (var = qair.var)

These should be revised, extended, and fixed

**Comment by Aariq** [comment]
Not only is there code commented out in met2CF.csv.R, but there's not actually any valid `testthat` tests.  Un-stale-ing

**Comment by Sweetdevil144** [comment]
It's been too long of this being open. Maybe we can add more test cases like :

```r
testthat::test_that("met2CF.csv", {
  # met2CF.csv(in.path = "data", in.file = "met2CF.csv.csv", outfolder = tempdir(), 
  #            format = format,
  #            lat = 42 + 47/60 + 30/6000,
  #            lon = 76 + 7/60 + 20/6000)
  expect_true(TRUE)
})
```

Diving more into this test file for now.

**Comment by Sweetdevil144** [comment]
It's been too long of this being open. Maybe we can add more test cases like :

```r
library(ncdf4)
# Mock data
in.path <- "modules/data.atmosphere/tests/testthat/data"
in.file <- "test.met2CF.csv.csv"
outfolder <- tempdir()
lat <- 42 + 47 / 60 + 30 / 6000
lon <- 76 + 7 / 60 + 20 / 6000

# Define start_date and end_date
start_date <- as.Date("2024-01-01")
end_date <- as.Date("2024-12-31")

test_that("met2CF.csv handles inputs correctly", {
       # Test that function runs without errors
       expect_silent(PEcAn.data.atmosphere::met2CF.csv(in.path, in.file, outfolder, start_date, end_date, format, lat, lon))

       # Test that output directory contains the expected file
       expect_true(file.exists(file.path(outfolder, paste0(gsub(".csv", "", in.file), ".nc"))))

       # Test that the output file is a valid netCDF file
       nc_file <- nc_open(file.path(outfolder, paste0(gsub(".csv", "", in.file), ".nc")))
       expect_true(!is.null(nc_file))
       nc_close(nc_file)
})

```

Diving more into this test file for now.

**Comment by Aariq** [comment]
Take a look at this article on "test hygiene" and consider using [`withr::with_tempfile()`](https://withr.r-lib.org/reference/with_tempfile.html) instead of `tempdir()`: https://testthat.r-lib.org/articles/test-fixtures.html#test-hygiene

**Comment by Sweetdevil144** [comment]
Current test file : https://github.com/Sweetdevil144/pecan/blob/develop/modules/data.atmosphere/tests/testthat/test.met2CF.csv.R

I think the format required has been changed since last times. Can anyone suggest approach for this error ?

```bash
> test_file('modules/data.atmosphere/tests/testthat/test.met2CF.csv.R')

══ Testing test.met2CF.csv.R ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]2024-05-07 15:46:45.777093 ERROR  [test.met2CF.csv.R#39: PEcAn.data.atmosphere::met2CF.csv] : 
   datetime column is not specified in format 
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]

── Error (test.met2CF.csv.R:39:8): met2CF.csv function works correctly ─────────
Error in `PEcAn.data.atmosphere::met2CF.csv(in.path = in.path, in.prefix = in.file, 
    outfolder = outfolder, format = format, lat = lat, lon = lon, 
    start_date = start_date, end_date = end_date)`: object 'alldatetime' not found
Backtrace:
    ▆
 1. └─PEcAn.data.atmosphere::met2CF.csv(...) at test.met2CF.csv.R:39:8
 2.   └─lubridate::year(alldatetime)
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]
```

**Comment by mdietze** [comment]
@Sweetdevil144 I recommend running the function line-by-line to figure out the source of the error. Also, I agree that the format in the test appears out-of-date. As the function itself says, the format comes from query.format.vars so I'd check what variables that function returns, as well as the `format` variables used within met2CF.csv to figure out what needs updating. You're definitely missing `time.row` in the test, but may be missing others. Indeed, I'd recommend also turning the currently failing test into a new test itself that expects a fail, as the function is successfully returning the error message "datetime column is not specified in format". Arguably, the function should exit at that point with an error code that later code (and testthat) can detect.  If older versions of the function didn't require this "new" (but probably many years old) column, it seems like a good thing to test for.

**Comment by Sweetdevil144** [comment]
Thanks for suggestions @mdietze . That helped. I've been trying to get an estimate of what `start_date` and `end_date` to consider for this SPECIFIC test.
As a default setting, I've been using following values of `start_date` and `end_date` :

```r
start_date <- "2000-01-01"
end_date <- "2000-12-31"

# OR

start_date <- as.Date("2004-01-01")
end_date <- as.Date("2004-12-31")
```

However, these specific timestamps give following errors :

```
── Error (test.met2CF.csv.R:43:8): met2CF.csv function works correctly ─────────
Error in `PEcAn.logger::logger.severe("Data does not contain output after start_date or before end_date")`: Data does not contain output after start_date or before end_date
Backtrace:
    ▆
 1. └─PEcAn.data.atmosphere::met2CF.csv(...) at test.met2CF.csv.R:43:8
 2.   └─PEcAn.logger::logger.severe("Data does not contain output after start_date or before end_date")
```

I also tried printing the `min` and `max` ranges but couldn't get it Printed. Seems like sone logging restrictions.
```r
print(paste("Date range in data:", min(alldatetime), "to", max(alldatetime)))
```

Any Suggestions?

**Comment by Sweetdevil144** [comment]
One thing I can't get my head around is as follow:
1. Format specified for datetime in `csv file` = `"%m/%d/%y %H:%M"`
2. However, by default, we're trying to set it to `"%Y%m%d%H%M"`. Check this out:

```R
if (datetime_units == "") {
        datetime_units <- "%Y%m%d%H%M" #assume ISO convention
      }
```

Hence we get following values of `alldatetime` and `datetime_units` on logging :

```vbnet
 alldatetime is = NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
   NA NA NA NA NA

   where datetime_units = %Y%m%d%H%M

**Comment by mdietze** [comment]
The default format has to stay ISO. 

If you're passing in data with a different time format, which the function allows, and are getting an error that suggests that either the format information is being passed in wrong or there's a bug in how that format information is being read and applied.

**Comment by Sweetdevil144** [comment]
Okay. So the issue was caused due to an improper format. Seems I made some blunders while setting formats. Suites Prepared !!
