### ISSUE TITLE
Ameriflux abbreviation changes - Maybe a bug/issue?

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#2027]
**Describe the bug**
While attempting to test the ability to run SIPNET at our selected CMS test sites I noticed that there is an issue with some of our Ameriflux records in BETYdb, that I think is related to changes on the Ameriflux side.  For example, we have a site that is part of M Goulden's tower network in California that was abbreviated "US-SCm" but is not "US-CZ3".  Similarly US-Smt (Smithsonian Research Center (SERC)) is now listed as "US-SER" http://ameriflux.lbl.gov/sites/siteinfo/US-SER

Another site "US-SSH" isnt in our AF site group.....  

So, does this just mean we need to do some cleanup/updating of site names, etc?  I dont recall how all of this information was originally scraped into BETYdb but I *dont think* we want to edit each record manually.

How should we address this, if this is an issue and not "user error"?

**Comment by serbinsh** [comment]
US-CZ3 (formally UC-SCm): http://ameriflux.lbl.gov/sites/siteinfo/US-CZ3

US-SSH: http://ameriflux.lbl.gov/sites/siteinfo/US-SSH

**Comment by mdietze** [comment]
Just fixed US-CZ3, US-SER, and US-SSH manually.

If anyone feels inspired to improve the download script I'm pretty sure it's pecan/modules/data.land/inst/LoadFLUXNETsites.R

**Comment by serbinsh** [comment]
@mdietze thanks for updating those sites....sorry I missed this reply the other day.  I can tackle any others I come across
