### ISSUE TITLE
Documentation: incorrect Installing PEcAn instruction

### ISSUE THREAD

**Issue by trotsiuk** [PecanProject/pecan#2037]
**Describe the bug**
In the documentation file, there is instruction to instal PEcAn with `./scripts/build.sh --dependencies`. Such a file does not exist in the whole project. In the `CHANGELOG.md` documented that this file was removed on 2016-12-10. 

**To Reproduce**
1. Go to 'pecan/book_source/05_developer_guide/01_setup/01_install_PEcAn/05_compile_PEcAn.Rmd'

**Machine (please complete the following information):**
 - Server [e.g. AWS, EC2 Ubuntu 16]
 - OS: [e.g.Linux]

**Additional context**
With the `Makefile` everything working well.

**Comment by mdietze** [comment]
Thanks for catching this legacy documentation bug, we really appreciate it. As you note, `./scripts/build.sh` was replaced with `make` and this is fixed in PR #2038
