### ISSUE TITLE
PEcAn.depend Shiny Loading Error - VM

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#2052]
![image](https://user-images.githubusercontent.com/8570691/44356983-e1725080-a47e-11e8-93bb-d8d712e527d0.png)
To Reproduce

1. Open Web GUI with pecan VM running by going to http://localhost:6480/ in local browser
2. Click on 'Output Visualization'
3. Click on "PEcAn.depend"
4. See error when loading.

**Comment by tonygardella** [comment]
Log:
![image](https://user-images.githubusercontent.com/8570691/44362570-649ba280-a48f-11e8-92dc-006fb0bda9fd.png)
and Further up the log:
![image](https://user-images.githubusercontent.com/8570691/44362612-8bf26f80-a48f-11e8-8a72-a8308be0413f.png)

So we need to add R packages "graph" and then  "CodeDepends" on the VM.

**Comment by robkooper** [comment]
looks like these were installed.
