### ISSUE TITLE
Develop Documentation was deleted for some reason

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#2069]
**Describe the bug**
In this automated [commit](https://github.com/PecanProject/pecan-documentation/commit/2ee5ae8196cfbe1c936b461d07547abea295918b),from the Travis Doc build, all of the `develop` directory is deleted so the documentation for the develop branch does not exist right now: https://pecanproject.github.io/pecan-documentation/develop

**Additional context**
I'm going to comb through the latest PR's and see what changes were made that could have triggered this, but that's as far as my intuition takes me. If you have any ideas please let me know. @mdietze @robkooper @dlebauer @infotroph @ashiklom @bcow

**Comment by infotroph** [comment]
@tonygardella Judging by timestamp, this happened in https://travis-ci.org/PecanProject/pecan/builds/421458231

**Comment by infotroph** [comment]
Another parallel Make gotcha. Declare all the prerequisites, everywhere!
