### ISSUE TITLE
calc.benchmarks

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#207]
Input: settings object (from start.benchmark.runs)

Output: error flag

Operation:

Query benchmarks table
For each benchmark (specifies input and variable IDs)
     Load model output for specified variable 
     Load observations
     Query Metrics table
     For each metric
          Calculate metric -> call metric.<name>(Obs, model output)
          Update database

**Comment by bcow** [comment]
Updated: ( see issue #610 )

Input: settings object (from start.benchmark.runs, database connection)

Output: results (list/dataframe) containing anything that will be reported in report.benchmarks (issue #209 )

Operation:

Query 
- query benchmark_reference_runs for benchmark_id's
- For each benchmark (specifies input and variable IDs)
  - query benchmarks for metrics, variable, sites, dates, and file paths
  - query input_id for file path
  - query formats table
  - calc.metrics ( issue #610 )
  - update database

**Comment by mdietze** [comment]
@bcow I am likewise closing this issue since, as far as I know, the only thing missing from pull request #783 was a change in the input from a settings object (which is how this was originally defined above) to passing the benchmark_ensembles.id instead.
