### ISSUE TITLE
Move host setting out of run

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#212]
In the pecan settings, the host tag is currently within the run tag. It is proposed that this tag get promoted to its own heading in the main file so that host settings can be specified independently from an individual run, for example when running a whole set of benchmarks or converting files.

**Comment by rykelly** [comment]
I'm planning to make this change in the near future as I work on getting the multi-run workflow implemented. Here's what I propose to move _out_ of `<run>`:

* **jobtemplate**: Move to `<model>`
* **dbfiles**: Move to `<database>`
* **host**: Move to its own top-level tag

The following settings would remain _in_ `<run>`:

* **start/end.date**: In an offline discussion, Mike noted there's no reason to assume all runs in a multi-run workflow would have the same start/end dates
* **site** and **inputs**: These are clearly run-specific
* **All model-specific inputs**: Just thinking of the ones used by ED2, which are all run-specific if I remember correctly. And if there are any model-specific but run-agnostic inputs, couldn't they go in `<model>`?

I think that's it... what does everyone think? 

Also, what's the best way to go about finding what these changes will break in existing code? I know we have some `testthat` tests in place but I don't know what all they cover. Is `build.sh --tests` still the way to run them?

**Comment by mdietze** [comment]
@ryankelly-uiuc what's the difference between inputs and model-specific inputs? Aren't all inputs model specific?

Yes, ```build.sh --tests``` runs the tests

Beyond that, I'd do a lot of grepping of settings$run$host, settings$run$jobtemplate, settings$run$host, etc.

**Comment by rykelly** [comment]
> @ryankelly-uiuc what's the difference between inputs and model-specific inputs? Aren't all inputs model specific?

Sorry, was just going off the gitbook / not remembering how this is set up. You're saying that inputs like ED2's pss/css/site files will be under `inputs` anyway? If so then: no difference.

**Comment by robkooper** [comment]
You can do `build.sh --check` to run the testthat tests and `build.sh --tests` to run tests in the tests folder. The latter will try and find tests that are called <hostname>*.xml and assume these are examples to run. If you look there are pecan64-sipnet.xml for example that will run on a VM.

In general if you build and you want to test everything you can use `build.sh --dependencies --check --tests`

**Comment by robkooper** [comment]
Yes all inputs should now be under inputs and there is no more pss/css/sites part of model.

**Comment by rykelly** [comment]
Ah thanks… the —check vs. —tests was the little bit of complexity I thought
I remembered...


On June 7, 2016 at 1:47:34 PM, Rob Kooper (notifications@github.com) wrote:

You can do build.sh --check to run the testthat tests and build.sh --tests
to run tests in the tests folder. The latter will try and find tests that
are called *.xml and assume these are examples to run. If you look there
are pecan64-sipnet.xml for example that will run on a VM.

In general if you build and you want to test everything you can use build.sh
--dependencies --check --tests

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/PecanProject/pecan/issues/212#issuecomment-224359181>,
or mute the thread
<https://github.com/notifications/unsubscribe/ANaCKmWlUCRvnswnmPd1F74JHLo8FlZsks5qJa6ygaJpZM4CiNyx>
.

**Comment by rykelly** [comment]
Sorry for ghosting out on everyone. I merged GH accounts and everything broke. Anyway...

One note on the reorg, which is now in process as pull request GH-887. I hadn't remembered that `<database>` is actually potentially a list of db blocks, including `<bety>`, `<fia>`, and perhaps others in the future. Adding `<dbfiles>` to `<database>` (as discussed above) is therefore somewhat incongruous, and will add a little extra ugly to any attempts to loop over all the databases listed in `<database>`. Not a big problem, and I think it only comes up currently [here](https://github.com/PecanProject/pecan/pull/887/files#diff-1e36bcbbbb6c003fe11bda49736323a1R245), but thought I'd mention it in case anyone wants to suggest an alternative.

**Comment by mdietze** [comment]
I think that's fine, the only place one loops over databases, rather than accessing them individually, is (as you point out) in read.settings, which could easily handle this with a simple if(name == "dbfiles") next

**Comment by rykelly** [comment]
No problem, and that's exactly what read.settings does currently. Just wanted to point it out.

**Comment by dlebauer** [comment]
@rykelly Rob and I have tried to maintain backward compatibility with read.settings - can you do that here, e.g. by allowing the old settings files to be passed and sending out a message?

**Comment by mdietze** [comment]
PR #887 included a function for converting old settings into the new format, so backward compatibility should be maintained. @dlebauer have you encountered errors suggesting that it's not?

**Comment by rykelly** [comment]
That's right—this update was supposed to maintain backwards compatibility. Like other examples in read.settings, it accepts old or new format. If old, it converts to new and then proceeds as normal. If both old and new are included (e.g. settings$run$database and settings$database), throws an error. 

Ditto @mdietze though—if you're finding that this doesn't work let me know.

**Comment by dlebauer** [comment]
Not yet. Just checking.

**Comment by rykelly** [comment]
Cool. It seemed pretty straightforward and I added tests to make sure it's working like I thought it should, so I don't anticipate problems.

**Comment by ashiklom** [comment]
Closing this because it seems to have been fixed (recent runs all have a `host` tag that is not inside `run`).
