### ISSUE TITLE
`ED2IN.git` is out of date

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#2143]
**Describe the bug**
New versions of ED need the following additional ED2IN tags, which are missing from the current version of ED:

```
IOOUTPUT, it must be 0 (none) or 3 (HDF5)
PLANT_HYDRO_SCHEME, it must be between -2 and 2
ISTOMATA_SCHEME, it must be between 0 and 1
ISTRUCT_GROWTH_SCHEME, it must be between 0 and 1
TRAIT_PLASTICITY_SCHEME, it must be between 0 and 2
```

**To Reproduce**
Build a fresh ED2 Docker container (which pulls from Git) and try to do a run via the PEcAn web interface.

**Expected behavior**
Model should run.

**Machine (please complete the following information):**
 - Docker

**Comment by ashiklom** [comment]
Working on this in https://github.com/ashiklom/pecan/tree/ed2in-update

**Comment by robkooper** [comment]
this is a good example of why we should use a specific commit of ED :) This was done about 2 months ago (https://github.com/EDmodel/ED2/pull/254/files)

**Comment by serbinsh** [comment]
Again this is related to https://github.com/PecanProject/pecan/issues/2081 and why we need to careful what ED2IN we call "git" etc.  But again this is a larger issue

**Comment by robkooper** [comment]
we should make sure we have one for 2.2.0, and close this issue after that. If people want to use the git version they can use the fix by @ashiklom
