### ISSUE TITLE
Dockerized Bety database points to non-existent files

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#2145]
When running the Dockerized PEcAn web interface, Bety believes it has access to a lot more files than it actually does. For instance, the only Dockerized models are SIPNET 136 and ED2 (git), but with Docker as the host, the web interface shows a lot more models. Similarly, when running ED2 (git), BETY looks for the default OGE2OLD file in a place that doesn't exist on the `pecan` Docker volume.

My best guess is that Dockerized BETY thinks it's running on the PEcAn VM, which ships with a lot more stuff than the Docker volume. One solution may be just to change the machine ID associated with Dockerized BETY so it (correctly) doesn't think the "Docker" machine has _any_ files. Another possibility is something related to the web interface PHP code (or maybe even just the `web/config.php`) -- perhaps it reads the hostname from the browser as `localhost` and then assumes it's running on the VM. This would also explain why, when running Dockerized PEcAn on `test-pecan.bu.eu`, the web interface behaved as if it was running natively on `test-pecan.bu.edu` rather than via Docker.

**To Reproduce**
Launch the PEcAn Docker web interface and look at the list of model options.

**Expected behavior**
Should only be models that are working with Docker.

**Machine (please complete the following information):**
Docker.

**Comment by robkooper** [comment]
See also https://github.com/PecanProject/pecan/issues/2128

**Comment by ashiklom** [comment]
So I looked at this more closely and it seems like the web interface is doing what it's supposed to. The problem, rather, is the way the Bety Docker database is initialized. Running the query from the PHP `get_models` shows that Bety thinks all those models really are installed on Docker:

```sql
 SELECT machines.id AS machine_id,
    machines.hostname,
    models.id AS model_id,
    models.model_name,
    models.revision
   FROM machines
     JOIN dbfiles ON machines.id = dbfiles.machine_id
     JOIN models ON dbfiles.container_id = models.id
  WHERE dbfiles.container_type = 'Model';
```

```
machine_id  |           hostname            |  model_id   |    model_name     |        revision
-------------+-------------------------------+-------------+-------------------+-------------------------
 99000000001 | docker                        |  1000000008 | LINKAGES          | R_version
 99000000001 | docker                        | 99000000003 | BioCro            | git
 99000000001 | docker                        |  5000000006 | Preles            |
 99000000001 | docker                        |  1000000011 | GDAY(Day)         |
 99000000001 | docker                        |  5000000005 | LPJ-GUESS         | 3.1
 99000000001 | docker                        |  5000000004 | MAESPA            | git
 99000000001 | docker                        | 99000000002 | Linkages          | git
 99000000001 | docker                        |  5000000003 | DALEC             |
 99000000001 | docker                        |  5000000002 | SIPNET            | 136
 99000000001 | docker                        |          10 | SIPNET            | unk
 99000000001 | docker                        |  5000000001 | ED2.2             | git
 99000000001 | docker                        | 99000000001 | ED2.2             | 82
 99000000001 | docker                        |           3 | ED2.2             | 46
```

I suspect this is because we are initializing the Bety database the same way as the VM, though I need to confirm that.

**Comment by ashiklom** [comment]
OK, so I think part of the problem is that Docker is initialized using site ID 99, which is the same as the VM. I'm going to try to create a fresh BETY instance using site ID 89 and see if that helps.

**Comment by robkooper** [comment]
I think this is due to the data container, which just says here is a list of models that might exist. Working on a heartbeat that the model sends out so we know exactly what models are online and how many.

**Comment by ashiklom** [comment]
Yeah, that's right. I was just stepping through the install process again looking at each step in detail and that's what I found.

What's interesting is that, on my older `pecan` Docker volume, only the `/data/workflows` and `/data/dbfiles` directories existed, although this script is clearly supposed to create a lot more directories. Investigating why that might be now.

**Comment by ashiklom** [comment]
But when I re-created the image locally, everything seemed to work fine.

**Comment by ashiklom** [comment]
Can confirm this works with current image on `pecan/data:develop`. Closing.
