### ISSUE TITLE
Dockerized ED2 fails with MPI error messages

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#2146]
**Describe the bug**
Dockerized ED2 crashes immediately with a bunch of cryptic OpenMPI-related error messages.

**To Reproduce**
Run Dockerized ED2 (git).

**Expected behavior**
Model should at least initialize and fail with ED-related errors. These errors come before ED logs any output.

**Machine (please complete the following information):**
Docker.

**Temporary Workaround**
Edit the `models/ed/inst/template.job` file so that the `@BINARY` is called as `@BINARY -s`. AFAICT, @robkooper added the `-s` flag to delay MPI initialization in ED, which seems to fix the problem. Note that you will then have to rebuild the `pecan/base` and `pecan/executor` images to make these changes take effect.

A nicer, more-permanent fix might be to allow users to pass additional flags to the model binary via `pecan.xml`. We already have a `<binary>` tag -- it should be easy to add an optional `<binary-flags>` tag and then change our `template.job` to call `@BINARY` as `@BINARY @BINARYFLAGS`.

**Comment by robkooper** [comment]
See also https://github.com/PecanProject/pecan/issues/2128
