### ISSUE TITLE
Add Rstudio Docker

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#2159]
**Describe the solution you'd like**
Distribute Rstudio as it's own docker container amidst the PEcAn Docker environment

**Comment by dlebauer** [comment]
Or ... build on top of pecan/depends by adding content from https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/Dockerfile

**Comment by dlebauer** [comment]
@Chris-Schnaufer can you create a PR for the updated / new dockerfile that provides rstudio on top of pecan/base?

**Comment by infotroph** [comment]
@robkooper @Chris-Schnaufer This can be closed, correct?

**Comment by robkooper** [comment]
Fixed in #2299 and #2306
