### ISSUE TITLE
Update to new `rlang` syntax

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#2172]
As of `rlang` 0.3, `UQ` is deprecated in favor of the `!!` operator. The resulting warning looks like this:

```
2018-11-02 10:03:59 INFO   [PEcAn.workflow::do_conversions] : PROCESSING:  veg
Warning: Prefixing `UQ()` with the rlang namespace is deprecated as of rlang 0.3.0.
Please use the non-prefixed form or `!!` instead.

  # Bad:
  rlang::expr(mean(rlang::UQ(var) * 100))

  # Ok:
  rlang::expr(mean(UQ(var) * 100))

  # Good:
  rlang::expr(mean(!!var * 100))
```

I'm pretty sure this affects the species-PFT matching code I wrote, and possibly a few other places.

**Comment by infotroph** [comment]
Changelog says this was fixed in 1.7.1 and the current code contains no instances of `UQ`, so I'm assuming this is done.
