### ISSUE TITLE
changing rabbitmq username/password makes runs fail

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#2185]
### Bug Description

Changing the rabbitmq username/password prevents jobs from being send to rabbitmq.

## Machine (please complete the following information):

 - Server docker

**Comment by infotroph** [comment]
@robkooper OK to close?

**Comment by robkooper** [comment]
Can be changed in .env file, see https://github.com/PecanProject/pecan/blob/develop/docker/env.example
