### ISSUE TITLE
PEcAn workflow fails if missing ensemble tag

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#2191]
### Bug Description

If running `workflow.R` with an XML file that has no `<ensemble>` section, the workflow dies. There are several bugs this triggers (e.g. `get.parameter.samples` -- "if missing, set size to 1" should be earlier in `if` statement; another bug in `input.ens.gen`), but I think the underlying cause of this is that at the bottom of `check.ensemble.settings`, an incomplete `ensemble` tag is created _even if the ensemble tag is missing_. That block should really be wrapped in the giant `if (!is.null(settings$ensemble))` block (or, better yet, the function should return early if `is.null(settings$ensemble)`). `git blame` shows that @para2x touched this last -- thoughts? 

### To Reproduce

Run `web/workflow.R` with an XML file missing.

## Expected behavior

If there's no ensemble tag, we shouldn't do any ensemble-related stuff.

## Proposed fix

Exit early out of `check.ensemble.settings` if `settings$ensemble` is missing. I.e.

```r
if (is.null(settings$ensemble)) return(settings)
```

This also has the nice side-effect of allowing us to ditch one level of `if` statement.

**Comment by para2x** [comment]
That's gonna be an easy fix ! I can make sure my `if` tests to know if the `ensemble` is there.

**Comment by infotroph** [comment]
@para2x is this still in progress?

**Comment by meetagrawal09** [comment]
This issue should be closed. [#2017](https://github.com/PecanProject/pecan/pull/2017/files#diff-bc53440c859eed528df63691cde21701d01be475ce73521bc7ec55607f4cf6bd) fixed it.
