### ISSUE TITLE
Bypass date range warning when running ED in pecan browser

### ISSUE THREAD

**Issue by bcow** [PecanProject/pecan#2193]
## Description

ED can run even if the met drivers provided don't span the entire run date range. ED will simply reuse met files to fill in the missing years. 

When running pecan through the browser, if the run date range is larger than the selected met driver date range, a warning will keep the user from continuing to the next page. 

## Proposed Solution

The easiest solution would be to have a special case for ED where the warning doesn't show up. Or perhaps a different message appears warning the user that met files will be reused to fill the entire run. 

There might be other models that also reuse met files in the same way and we should ultimately make sure that all of them are accounted for. But the quickest fix would most likely be ED specific.

**Comment by mdietze** [comment]
No model-specific hacks in the code. Given that this could potentially apply to multiple models, I'd recommend handling it via the model's registry file.
