### ISSUE TITLE
Current version of ED2 crashes when using PFT17 (lianas)

### ISSUE THREAD

**Issue by femeunier** [PecanProject/pecan#2196]
When running ED2 simulation with lianas, the current version of the code generates an error after several months of simulation (division by 0). This issue is caused by a previous version of our liana-related code that needs to be updated on Github. 

As the persons involved in the project prefer not to push the current version of the code before having a very stable version of the liana PFT, the actual fix could take some time. In the meantime, people encountering the same error can bypass it by removing lianas (PFT17) from the list of PFTs (INCLUDE_THESE_PFT in the ED2IN) or by setting all the is_liana parameters to false in init/ed_params.f90.

**Comment by infotroph** [comment]
@femeunier is this issue still active?

**Comment by ashiklom** [comment]
@femeunier or whoever gets the chance (maybe me? We'll see how the next few days shape out) should test this with the latest version of ED2 and, if possible, add that test to ED2's [automated test suite](https://github.com/EDmodel/ED2/tree/master/EDTS). That way, we will at least know that it's an ED2 problem, not a PEcAn problem.

**Comment by femeunier** [comment]
The stable version of the liana PFT is still not included in the main branch of ED2. This is definitely an ED2 problem, not a PEcAn problem. I opened this issue just in case, somebody wanted to give a try with the pft 17 in ED2. When the liana PFT will be pushed, we can definitely add an automated test example, that's a great suggestion.

**Comment by ashiklom** [comment]
Nice, thanks @femeunier! When the time comes, let me know if you need help setting up the automated test case -- I tried to document it in the repo, but it could probably be clearer.
