### ISSUE TITLE
Dockerize CTSM

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#2212]
## Description
Link to document from call about dockerizing ctsm: https://docs.google.com/document/d/1W3zg57eO2bNLWqprI8jZFl_1NhP8gdfU8KN4KYQVWTc/edit

## Proposed Solution
Build container around the modex machine configurations.
Others will follow along docker development and test on their machines.

Relevant Issues: 
#2125 
#2122

**Comment by serbinsh** [comment]
All - I am linking my thread on CIME here which has some relevant info and things I learned along the way

https://github.com/ESMCI/cime/issues/2929

**Comment by dlebauer** [comment]
Shawn nailed it https://docs.google.com/document/d/1_qsI1VfMnCdkthIb-ypdzU2A6fcHUYbIqfexOhq73ik/edit?usp=sharing
