### ISSUE TITLE
"Need a hostname" error when attempting to view workflow history during execution

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#2213]
### Bug Description

With the latest develop code, I now get an error stating "Need a hostname" when viewing run history on the web interface for running workflows.  Once the workflow completes I no longer get the error message.

![screen shot 2018-11-26 at 2 41 45 pm](https://user-images.githubusercontent.com/3067369/49108103-4e06a380-f255-11e8-97f1-4ed7510a080d.png)

@bcow has also run into this issue:

"
I have the solution for that! And I’ve been meaning to make an issue - sorry! 

Now the url requires that hostname is specified. So you can see that this works : http://pecan2.bu.edu/pecan/08-finished.php?workflowid=1000009960&hostname=geo.bu.edu but this does not http://pecan2.bu.edu/pecan/08-finished.php?workflowid=1000009960

And I’ve found that hitting back will load the url *without* hostname

I missed when this was implemented, but it seems to pop up in a lot of cases - for example, I think when clicking on a workflow id from the history list also sends you to the url without hostname
"

**Comment by robkooper** [comment]
@serbinsh or @bcow does this happen when you select a running workflow from the history page or also when you submit one?

I now allow the config.php to not have a global rabbitmq server but a rabbitmq server per host. This would allow one in theory to submit from their docker container to any rabbitmq server. To enable this feature I now pass the hostname parameter between pages so I can look in the config.php file what rabbitmq server to use.

**Comment by robkooper** [comment]
Looks like the problem is that history.php when jumping to a running workflow does not pass the hostname.

**Comment by serbinsh** [comment]
@robkooper in that case do you see what the error is or do you need me to provide more detail?

**Comment by ashiklom** [comment]
@serbinsh One quick workaround is to add `&hostname=docker` (or similar) to the end of the URL.

**Comment by robkooper** [comment]
Yes, there is actually 2 problems:
- in finished when calling back need to pass hostname
- in history when calling back need to pass hostname
- fix typo continously
