### ISSUE TITLE
Edit pecan.xml in browser error

### ISSUE THREAD

**Issue by bcow** [PecanProject/pecan#2220]
When **Edit pecan.xml** is selected through the PEcAn browser interface, the user can edit the pecan.xml through a text field in the browser window. However, the text field adds **three empty lines** at the top of the xml. 

![screen shot 2018-11-30 at 5 18 11 pm](https://user-images.githubusercontent.com/5503595/49318050-fa01f600-f4c4-11e8-87ec-f50ff315e6f0.png)

If the xml is saved without removing these lines, the xml cannot be read by `read.settings` and the workflow breaks with error message:

```
[PEcAn.settings::read.settings] : 
Loading inpufile= pecan.xml 
XML declaration allowed only at the start of the document
Error: 1: XML declaration allowed only at the start of the document
Error during wrapup: object 'settings' not found
```

This problem is also true for all files that can be edited through text fields in the browser window such as config files and job.sh. For some files like ED2IN, the additional spaces don't cause problems, but it will definitely affect all xml files.

**Comment by tonygardella** [comment]
#1484 Was the same issue but with only one space. Didn't seem to consistently occur on other machines so it wasn't high in priority but also not closed. We definitely should look into this across machines.

**Comment by tobeycarman** [comment]
I am seeing narrow window, but it is not a problem.

**Comment by infotroph** [comment]
Tracking this in #1484, don't need both open
