### ISSUE TITLE
Update documentation to cover ED2 model options related to setting PFTs

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#2238]
We need to update the documentation located here: https://pecanproject.github.io/pecan-documentation/develop/template-model-page.html#ed

to include information related to ED2 PFTs, how they are set, and the new <all_pft> tag

**Comment by ashiklom** [comment]
Basically, this involves writing more formal documentation for the changes that I implemented in https://github.com/PecanProject/pecan/pull/2203.

**Comment by ashiklom** [comment]
The relevant documentation is in [13.0.9.2](https://pecanproject.github.io/pecan-documentation/develop/pecan-models.html#models-ed). The headings need to be fixed to avoid the extra 0, and I think there may be some kinks in the implementation, but the docs are there.
