### ISSUE TITLE
extract.nc with 1x1 CF nc files

### ISSUE THREAD

**Issue by ankurdesai** [PecanProject/pecan#2241]
### Bug Description

When extract.nc.R in modules/data.atmosphere is called with a CF compliant NetCDF file with dminesions of 1x1 (lat x lon), the function fails to accurately extract data. This function is called by met.process on any file already in CFmet format (BETY format ID 33) because data.atmosphere/inst/registration lists CFmet as a "regional" format, even though we convert many site met into CFmet. Generally this is not an issue if starting from site met, since the "regional" flag is not triggered. However, if starting met process from existing converted site CFmet, then "regional" is trigger and extract is called, causing met.process to fail.

There are several possible solutions:
1. Make extract.nc work nicely and quietly with site level CF files
2. Add a new format CFsitemet that is "site" in registration xml file so that met.process does not call extract
3. Detect at met process whether CF met if site or regional
4. Do nothing, because this is not a supported case to call met process mid-stream

I think met process should work nicely with any met file Pecan knows how to use. I am a bit worried about adding a format or doing some on  the fly change to site/regional flag. So my preference is #1 - it may be a 2 line fix - the offending line is where it tried to make a materix of size nrow by ncol, but ncol is NA, since it lat and lon are each only one row long in a site CF file

**Comment by mdietze** [comment]
Agree that option 1 is preferred, and that internal fix should happen and is probably sufficient in the short term. But it doesn't solve the larger issue that the met processing is going down the wrong path. For example, if a user converted their own raw data to CF and registered it with the database, then the system wouldn't attempt to gapfill it. However, this scenario may not worth worrying about until it happens
