### ISSUE TITLE
R code chunks not showing up

### ISSUE THREAD

**Issue by KristinaRiemer** [PecanProject/pecan#2243]
The R code chunks in some of the tutorials in the PEcAn book are not showing up. For example, there are supposed to be a bunch of them in the [sensitivity analysis tutorial](https://pecanproject.github.io/pecan-documentation/master/pecan-testing-the-sensitivity-analysis-against-observations.html). They're in the underlying [.Rmd](https://github.com/PecanProject/pecan/blob/develop/documentation/tutorials/sensitivity/PEcAn_sensitivity_tutorial_v1.0.Rmd) and they show up when I knit or use preview_chapter locally. 

There's probably an easy fix, which I'm happy to do, but I don't know much about bookdown and Googling wasn't fruitful.

**Comment by infotroph** [comment]
@KristinaRiemer Can this issue be closed?

**Comment by KristinaRiemer** [comment]
Yup. This was fixed in the big documentation overhaul that Tony did.
