### ISSUE TITLE
Update query.trait.data to restrict query based on pfts.cultivar_id field

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#227]
In order to conduct a cultivar-level meta-analysis, I will need to restrict the trait data query to the cultivar associated with a PFT.

related to PecanProject/bety#144

**Comment by infotroph** [comment]
@dlebauer Am I right that #1826 (cultivars in PFTs) resolved this / OK to close?

**Comment by infotroph** [comment]
@dlebauer Closing this as probably resolved; Please reopen if needed.
