### ISSUE TITLE
ED2 gsub wrong pattern in model2netcdf

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#2279]
### Bug Description
In the ED2 model2netcdf on [line 85](https://github.com/PecanProject/pecan/blob/develop/models/ed/R/model2netcdf.ED2.R#L85) it defines the  `rundir` by using `gsub` to replace the pattern `out` with `run` in `outdir` . This causes problems when other parts of the path also have `out` in them, causing the next line to fail when looking for the `README.txt` in that `rundir` path.

Behavior:
`home/carya/output/PEcAn_900000001/out/`
is turned into:
`home/carya/runput/PEcAn_900000001/run/`
Expected to be:
`home/carya/output/PEcAn_900000001/run/`

## Machine (please complete the following information)
VM

## Additional context
Solution would probably be to parse the string after the `PEcAn_` then look for the `out` to replace with `run`. Paths after `PEcAn_` are standard so that should be safe across machines.

@serbinsh Tagging you on this because this was a line you edited last. Let me know if this doesn't make sense or was intended to work like this.

**Comment by serbinsh** [comment]
@tonygardella not sure I follow.  Also my changes in that section were mostly style cleanup based on @ashiklom's review.  Also, can you tell me where to look for this error in the logs?  I have been running ED2 successfully, albeit not in the VM.

**Comment by serbinsh** [comment]
...and specifically on line 85 I removed the trailing / but did not change the order from what @istfer had.   Perhaps there is a specific case where this fails or some other recent change is clashing with this?  Again not been having this problem....

**Comment by serbinsh** [comment]
Oh, OK.  Looking again you mean in an error message it gets the wrong info? Question I would have is what are the path names when you DONT write to the DB and get paths like SA-median.  DOes pecan append "PEcAn_" to the front too (e.g. PEcAn_SA-median/)?  I cant recall but we need to have a fix that is generic to both.

I suspect the original /out/ was meant to try and catch this but I had an issue where that wasnt working for me either......

**Comment by ashiklom** [comment]
Bump!

I think we can use something like the following:

```r
# outdir <- "/path/to/workflows/PEcAn_<workflow>/out/<run>
run_id <- basename(outdir)   # ---> <run>
workflow_dir <- dirname(dirname(outdir))    # ---> /path/to/workflows/PEcAn_<workflow>
rundir <- file.path(workflow_dir, "run")
```

@serbinsh Let me know if that looks reasonable.

**Comment by serbinsh** [comment]
@ashiklom thanks for addressing this.  I forgot about this issue.
