### ISSUE TITLE
docker-compose and .env file

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#2303]
@kzarada is testing docker setup. It is not clear in the quickstart how to pick either the develop or latest (master branch) for the docker images.

This came to light due to the error:
```
ERROR: manifest for pecan/monitor:latest not found
```

Solution from slack:
Ok BUG 1 in documentation found, in the quickstart it does not talk about the .env file.
https://github.com/PecanProject/pecan/blob/develop/docker/env.example (edited)
The default behaviour of the docker-compose file is to use the latest version of PEcAn images, which corresponds to the master branch.
You can override this in the .env file that you place next to the docker-compose file.

More documentation is needed for the .env file in quickstart:

https://pecan-katie.ncsa.illinois.edu/ works (not with a valid cert though)
if you change in your .env file the reference from pecan-docker.ncsa.illinois.edu to pecan-katie.ncsa.illinois.edu it should work.

**Comment by robkooper** [comment]
- [ ] Quickstart is missing documentation about .env file
- [ ] Describe issue with invalid certificate
- [ ] How to connect to PEcAn if running not on local machine

**Comment by ashiklom** [comment]
@robkooper Seems like we have all the necessary docs. Can this be closed?
