### ISSUE TITLE
Errors in load.bety.sh on RHEL 6.5

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#231]
Error: can't find - libjson-c.so.2

ERROR:  must be owner of extension plpgsql
ERROR:  permission denied to create extension "postgis"
HINT:  Must be superuser to create this extension.
ERROR:  extension "postgis" does not exist
ERROR:  type "geometry" does not exist
LINE 20:     geometry geometry(GeometryZ,4326),
                      ^
ERROR:  relation "sites" does not exist

RAN: 
[sserbin@test pecan]$ sudo -u postgres CREATE=YES MYSITE=2 REMOTESITE=0 scripts/load.bety.sh
[sudo] password for sserbin: 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4349k  100 4349k    0     0  4466k      0 --:--:-- --:--:-- --:--:-- 8348k
Loading schema                    : NOTICE:  drop cascades to 77 other objects

DETAIL:  drop cascades to function prevent_conflicting_range_changes()
drop cascades to function restrict_covariate_range()
drop cascades to function restrict_trait_range()
drop cascades to sequence citations_id_seq
drop cascades to table citations
drop cascades to table citations_sites
drop cascades to table citations_treatments
drop cascades to sequence counties_id_seq
drop cascades to table counties
drop cascades to sequence covariates_id_seq
drop cascades to table covariates
drop cascades to sequence cultivars_id_seq
drop cascades to table cultivars
drop cascades to table current_posteriors
drop cascades to sequence dbfiles_id_seq
drop cascades to table dbfiles
drop cascades to sequence ensembles_id_seq
drop cascades to table ensembles
drop cascades to sequence entities_id_seq
drop cascades to table entities
drop cascades to sequence formats_id_seq
drop cascades to table formats
drop cascades to sequence formats_variables_id_seq
drop cascades to table formats_variables
drop cascades to sequence inputs_id_seq
drop cascades to table inputs
drop cascades to table inputs_runs
drop cascades to table inputs_variables
drop cascades to sequence likelihoods_id_seq
drop cascades to table likelihoods
drop cascades to sequence location_yields_id_seq
drop cascades to table location_yields
drop cascades to sequence machines_id_seq
drop cascades to table machines
drop cascades to sequence managements_id_seq
drop cascades to table managements
drop cascades to table managements_treatments
drop cascades to sequence methods_id_seq
drop cascades to table methods
drop cascades to sequence mimetypes_id_seq
drop cascades to table mimetypes
drop cascades to sequence models_id_seq
drop cascades to table models
drop cascades to table modeltypes
drop cascades to table modeltypes_formats
drop cascades to sequence pfts_id_seq
drop cascades to table pfts
drop cascades to table pfts_priors
drop cascades to table pfts_species
drop cascades to table posterior_samples
drop cascades to sequence posteriors_id_seq
drop cascades to table posteriors
drop cascades to table posteriors_ensembles
drop cascades to sequence priors_id_seq
drop cascades to table priors
drop cascades to table projects
drop cascades to sequence runs_id_seq
drop cascades to table runs
drop cascades to table schema_migrations
drop cascades to sequence sessions_id_seq
drop cascades to table sessions
drop cascades to sequence sites_id_seq
drop cascades to sequence species_id_seq
drop cascades to table species
drop cascades to table trait_covariate_associations
drop cascades to sequence traits_id_seq
drop cascades to table traits
drop cascades to sequence treatments_id_seq
drop cascades to table treatments
drop cascades to sequence users_id_seq
drop cascades to table users
drop cascades to sequence variables_id_seq
drop cascades to table variables
drop cascades to sequence yields_id_seq
drop cascades to table yields
drop cascades to sequence workflows_id_seq
drop cascades to table workflows
ERROR:  could not load library "/data/software/postgresql/9.3.5/lib/postgis-2.1.so": libjson-c.so.2: cannot open shared object file: No such file or directory
GRANT
ERROR:  must be owner of extension plpgsql
ERROR:  permission denied to create extension "postgis"
HINT:  Must be superuser to create this extension.
ERROR:  extension "postgis" does not exist
ERROR:  type "geometry" does not exist
LINE 20:     geometry geometry(GeometryZ,4326),
                      ^
ERROR:  relation "sites" does not exist
ERROR:  relation "sites" does not exist
ERROR:  relation "sites" does not exist
ERROR:  relation "sites" does not exist
ERROR:  relation "sites" does not exist
ERROR:  relation "sites" does not exist
ERROR:  relation "sites" does not exist
ERROR:  relation "sites" does not exist
LINE 37:      LEFT JOIN sites ON ((traits.site_id = sites.id)))
                        ^
ERROR:  relation "sites" does not exist
LINE 37:      LEFT JOIN sites ON ((yields.site_id = sites.id)))
                        ^
ERROR:  relation "traitsview_private" does not exist
LINE 36:    FROM traitsview_private
                 ^
ERROR:  relation "traits_and_yields_view_private" does not exist
LINE 32:    FROM traits_and_yields_view_private
                 ^
ERROR:  relation "sites" does not exist
ERROR:  relation "sites" does not exist
ERROR:  relation "sites" does not exist
CREATED SCHEMA
Loading  schema_migrations         : \copy: parse error at "(DELIMITER"
ADDED 
Cleaning citations                 : DEL 0
Loading  citations                 : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   citations                 : SEQ 2000000001
Cleaning counties                  : DEL 0
Loading  counties                  : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   counties                  : SEQ 2000000001
Cleaning covariates                : DEL 0
Loading  covariates                : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   covariates                : SEQ 2000000001
Cleaning cultivars                 : DEL 0
Loading  cultivars                 : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   cultivars                 : SEQ 2000000001
Cleaning dbfiles                   : DEL 0
Loading  dbfiles                   : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   dbfiles                   : SEQ 2000000001
Cleaning ensembles                 : DEL 0
Loading  ensembles                 : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   ensembles                 : SEQ 2000000001
Cleaning entities                  : DEL 0
Loading  entities                  : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   entities                  : SEQ 2000000001
Cleaning formats                   : DEL 0
Loading  formats                   : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   formats                   : SEQ 2000000001
Cleaning inputs                    : DEL 0
Loading  inputs                    : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   inputs                    : SEQ 2000000001
Cleaning likelihoods               : DEL 0
Loading  likelihoods               : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   likelihoods               : SEQ 2000000001
Cleaning location_yields           : DEL 0
Loading  location_yields           : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   location_yields           : SEQ 2000000001
Cleaning machines                  : DEL 0
Loading  machines                  : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   machines                  : SEQ 2000000001
Cleaning managements               : DEL 0
Loading  managements               : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   managements               : SEQ 2000000001
Cleaning methods                   : DEL 0
Loading  methods                   : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   methods                   : SEQ 2000000001
Cleaning mimetypes                 : DEL 0
Loading  mimetypes                 : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   mimetypes                 : SEQ 2000000001
Cleaning models                    : DEL 0
Loading  models                    : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   models                    : SEQ 2000000001
Cleaning pfts                      : DEL 0
Loading  pfts                      : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   pfts                      : SEQ 2000000001
Cleaning posterior_samples         : DEL 0
Loading  posterior_samples         : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   posterior_samples         : SEQ 2000000001
Cleaning posteriors                : DEL 0
Loading  posteriors                : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   posteriors                : SEQ 2000000001
Cleaning priors                    : DEL 0
Loading  priors                    : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   priors                    : SEQ 2000000001
Cleaning runs                      : DEL 0
Loading  runs                      : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   runs                      : SEQ 2000000001
Cleaning sessions                  : DEL 0
Loading  sessions                  : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   sessions                  : SEQ 2000000001
Cleaning sites                     : ERROR:  relation "sites" does not exist
LINE 1: SELECT count(*) FROM sites WHERE (id >= 1 AND id <= 10000000...
                             ^
ERROR:  relation "sites" does not exist
LINE 1: DELETE FROM sites WHERE (id >= 1 AND id <= 1000000000)
                    ^
DEL 
Loading  sites                     : ERROR:  relation "sites" does not exist
LINE 1: SELECT COUNT(*) FROM sites
                             ^
\copy: parse error at "(DELIMITER"
ERROR:  relation "sites" does not exist
LINE 1: SELECT COUNT(*) FROM sites
                             ^
ADD 0
Fixing   sites                     : ERROR:  relation "sites" does not exist
LINE 1: ...ELECT setval('sites_id_seq', (SELECT MAX(id) FROM sites WHER...
                                                             ^
SEQ 
Cleaning species                   : DEL 0
Loading  species                   : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   species                   : SEQ 2000000001
Cleaning traits                    : DEL 0
Loading  traits                    : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   traits                    : SEQ 2000000001
Cleaning treatments                : DEL 0
Loading  treatments                : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   treatments                : SEQ 2000000001
Cleaning workflows                 : DEL 0
Loading  workflows                 : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   workflows                 : SEQ 2000000001
Cleaning yields                    : DEL 0
Loading  yields                    : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   yields                    : SEQ 2000000001
Cleaning modeltypes                : DEL 0
Loading  modeltypes                : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   modeltypes                : SEQ 2000000001
Cleaning modeltypes_formats        : DEL 0
Loading  modeltypes_formats        : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   modeltypes_formats        : SEQ 2000000001
Cleaning users                     : DEL 0
Loading  users                     : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   users                     : SEQ 2000000001
Cleaning variables                 : DEL 0
Loading  variables                 : \copy: parse error at "(DELIMITER"
ADD 0
Fixing   variables                 : SEQ 2000000001
Cleaning citations_sites           : DEL 0
Loading  citations_sites           : \copy: parse error at "(DELIMITER"
ADD 0
Cleaning citations_treatments      : DEL 0
Loading  citations_treatments      : \copy: parse error at "(DELIMITER"
ADD 0
Cleaning formats_variables         : DEL 0
Loading  formats_variables         : \copy: parse error at "(DELIMITER"
ADD 0
Cleaning inputs_runs               : DEL 0
Loading  inputs_runs               : \copy: parse error at "(DELIMITER"
ADD 0
Cleaning inputs_variables          : DEL 0
Loading  inputs_variables          : \copy: parse error at "(DELIMITER"
ADD 0
Cleaning managements_treatments    : DEL 0
Loading  managements_treatments    : \copy: parse error at "(DELIMITER"
ADD 0
Cleaning pfts_priors               : DEL 0
Loading  pfts_priors               : \copy: parse error at "(DELIMITER"
ADD 0
Cleaning pfts_species              : DEL 0
Loading  pfts_species              : \copy: parse error at "(DELIMITER"
ADD 0
Cleaning posteriors_ensembles      : DEL 0
Loading  posteriors_ensembles      : \copy: parse error at "(DELIMITER"
ADD 0
[sserbin@test pecan]$ psql bety
psql (9.3.5)
Type "help" for help.

bety=# \c bety
You are now connected to database "bety" as user "sserbin".
bety=# select * from covariates;
 id | trait_id | variable_id | level | created_at | updated_at | n | statname | stat 
----+----------+-------------+-------+------------+------------+---+----------+------
(0 rows)

bety=# \q

**Comment by robkooper** [comment]
@serbinsh can this be closed?

**Comment by serbinsh** [comment]
Closed
