### ISSUE TITLE
Trouble shooting multi-site runs on other computers

### ISSUE THREAD

**Issue by bailsofhay** [PecanProject/pecan#2319]
### Bug Description

The workflow.R script to run the SDA for multiple sites within a site group is not working correctly on non-BU computers. When I use a site group with +1 sites, regardless of including the site_pft.csv file, the script will not complete. Currently, the workflow.R file will not population the settings variable with all of the necessary information that is provided from the XML and there are certain settings that should be automatically set by PEcAn that are also being missed. For example, because certain settings information is not being population in the settings list variable, the output directories are not being created. Specifically, it appears ```settings <- PEcAn.settings::prepare.settings(settings, force = FALSE)``` in the workflow.R script is not working correctly, although it does not throw a fatal error at this point. The problem was identified by comparing the settings variable from the single site run vs. multi-site run.

### Expected behavior

The multi-site workflow.R file should run and output data that is the same as for a site group with 1 site, but for multiple sites within a site group.

### Screenshots

I'll add specific examples of problems in the comments. below.
## Machine (please complete the following information):

 - MODEX
 - OS: Linux

### To Reproduce

use this XML, but change your output directories and possibly the database/dbfiles if you are not using modex. Non-modex users will not need the ```<prerun>``` information.

```<?xml version="1.0"?>
<pecan.multi>
 <outdir>/data/bmorrison/sda/site_group/XMLs/test_hamze</outdir>
<database>
    <bety>
      <user>bety</user>
      <password>bety</password>
      <host>localhost</host>
      <port>5432</port>
      <dbname>bety</dbname>
      <driver>PostgreSQL</driver>
      <write>FALSE</write>
    </bety>
    <dbfiles>/data/pecan_dbfiles</dbfiles>
  </database>
 <pfts>
  <pft>
   <name>temperate.broadleaf.deciduous</name>
   <constants>
    <num>1</num>
   </constants>
  </pft>
 </pfts>
 <meta.analysis>
    <iter>3000</iter>
    <random.effects>FALSE</random.effects>
  </meta.analysis>
 <ensemble>
   <size>10</size>
   <variable>NPP</variable>
   <samplingspace>
   <parameters>
    <method>sobol</method>
   </parameters>
   <met>
    <method>sampling</method>
     </met>
   </samplingspace>
  </ensemble>
<sitegroup>
   <id>2000000006</id>
</sitegroup>
 <model>
  <id>1000000014</id>
  <type>SIPNET</type>
<revision>r136</revision>
  <delete.raw>FALSE</delete.raw>
  </model>
<run>
<inputs>
  <pft.site>
    <path>site_pft.csv</path>
  </pft.site>
  <met>
  <source>CRUNCEP</source>
  <output>SIPNET</output>
  </met>
  </inputs>
  <start.date>1980/01/01</start.date>
  <end.date>2010/12/31</end.date>
 </run>
 <host>
  <name>localhost</name>
  <rundir>/data/bmorrison/sda/site_group/XMLs/test_hamze/run</rundir>
  <outdir>/data/bmorrison/sda/site_group/XMLs/test_hamze/out</outdir>
 </host>
<prerun>module load gcc/5.4.0 jags/4.3.0 udunits/2.2.25 python/2.7.14 redland hdf5/1.8.19-gcc540 netcdf/4.4.1.1-gnu540 libtiff/4.0.8 geos/3.6.3 proj/5.1.0 gdal/2.3.1</prerun>
 <settings.info>
  <deprecated.settings.fixed>TRUE</deprecated.settings.fixed>
  <settings.updated>TRUE</settings.updated>
  <checked>TRUE</checked>
 </settings.info>
<rundir>/data/bmorrison/sda/site_group/XMLs/test_hamze/run</rundir>
 <modeloutdir>/data/bmorrison/sda/site_group/XMLs/test_hamze/out</modeloutdir>
</pecan.multi>```

**Comment by bailsofhay** [comment]
The site_pft.csv file should like this:
```site,pft
2000000023,temperate.needleleaf.evergreen
796,temperate.needleleaf.evergreen
1000000146,temperate.needleleaf.evergreen
772,temperate.needleleaf.evergreen```

**Comment by serbinsh** [comment]
Spinoff of this issue: https://github.com/PecanProject/pecan/issues/2286

**Comment by para2x** [comment]
Well... I really don't think this issue has anything to do with the SDA itself because @serbinsh was able to run my multi-site SDA example, if there is an issue it probably has to do with how a XML setting with sitegroup is being converted to multi.setting xml file.

**Comment by serbinsh** [comment]
Good point, title and label changed!

**Comment by serbinsh** [comment]
....Indeed @bailsofhay and I were both able to get multi-site SDA to run when we run each site individually then combine these into SDA xml.  I / we just havent been able to get a basic multi-site run to work here (on modex) for some strange reason.

**Comment by bailsofhay** [comment]
You're correct @para2x that the multi-site SDA isn't the problem. @serbinsh  and I were both able to run the multi-site SDA from BNL. The problem is that neither of us have been able to successfully run a multi-site run that is needed for the SDA (only running each individual site separately). This is the issue that needs to get fixed. It's looking like an issue with the settings in workflow.R

**Comment by bailsofhay** [comment]
We're also having issues with any of the outdirs getting made (the main outdir, run, pft, and out).
```
> # Write pecan.CHECKED.xml
> #dir.create(settings$outdir) ### not making an outdir at this point. added it in myself
> PEcAn.settings::write.settings(settings, outputfile = "pecan.CHECKED.xml")
Warning in file(file, if (append) "a" else "w") :
  cannot open file '/data/bmorrison/sda/site_group/XMLs/test_hamze/pecan.CHECKED.xml': No such file or directory
Error in file(file, if (append) "a" else "w") :
  cannot open the connection
Error during wrapup: cannot open the connection
>
> # start from scratch if no continue is passed in
> statusFile <- file.path(settings$outdir, "STATUS")
> if (length(which(commandArgs() == "--continue")) == 0 && file.exists(statusFile)) {
+   file.remove(statusFile)
+ }
```

settings$outdir is correct, but somehow the outdirs aren't being made so code from this point on will fail if it depends on writing a file or finding a file that is supposed to be in the outdir from the XML.

**Comment by serbinsh** [comment]
Fixed: Not entirely sure what the exact fix was, but might have been an issue with XML parsing and configuration.  Here is my current working example for SIPNET:

```
<?xml version="1.0"?>
<pecan>
  <outdir>/data/sserbin/Modeling/sipnet/multi_site/testrun.20</outdir>
  <database>
    <bety>
      <user>bety</user>
      <password>bety</password>
      <host>localhost</host>
      <port>5432</port>
      <dbname>bety</dbname>
      <driver>PostgreSQL</driver>
      <write>TRUE</write>
    </bety>
    <dbfiles>/data/pecan_dbfiles</dbfiles>
  </database>
  <pfts>
    <pft>
      <name>temperate.broadleaf.deciduous</name> 
      <constants>
        <num>1</num>
      </constants>
    </pft>
  </pfts>
   <meta.analysis>
    <iter>3000</iter>
    <random.effects>FALSE</random.effects>
  </meta.analysis>
  <ensemble>
   <size>100</size>
   <variable>NPP</variable>
   <samplingspace>
   <parameters>
    <method>sobol</method>
   </parameters>
   <met>
       <method>sampling</method>
   </met>
   </samplingspace>
  </ensemble>
  <model>
    <id>1000000014</id>
  </model>
  <sitegroup>
      <id>5000000002</id>
  </sitegroup> 
    <run>
    <multisettings>
      <multisettings>run</multisettings>
      <multisettings>ensemble</multisettings>
    </multisettings>
    <inputs>
      <met>
         <source>CRUNCEP</source>
         <output>SIPNET</output>
      </met>
    </inputs>
    <start.date>1980/01/01</start.date>
    <end.date>2010/12/31</end.date>
  </run>
  <host>
    <name>localhost</name>
    <scratchdir>/scratch</scratchdir>
    <prerun>module load gcc/5.4.0 jags/4.3.0 udunits/2.2.25 python/2.7.14 redland hdf5/1.8.19-gcc540 netcdf/4.4.1.1-gnu540 libtiff/4.0.8 geos/3.6.3 proj/5.1.0 gdal/2.3.1</prerun>
    <qsub>qsub -l walltime=36:00:00 -V -N @NAME@ -o @STDOUT@ -e @STDERR@ -S /bin/bash</qsub>
    <qsub.jobid>([[:digit:]]+)\.modex\.bnl\.gov</qsub.jobid>
    <qstat>qstat @JOBID@ || echo DONE</qstat>
    <modellauncher>
        <binary>/data/software/modellauncher</binary>
        <qsub.extra>-l nodes=2:ppn=10</qsub.extra>
        <mpirun>mpirun</mpirun>
    </modellauncher>
  </host>
  <email>
    <to>sserbin@bnl.gov</to>
  </email>
</pecan>

```

Note all of the tags used and that I am not using <pecan.multi> main tags.  We may need to revisit the actual requirements and update the documentation for this providing a concrete XML example that can run in the VM. @tonygardella or whomever can work with me on that?
