### ISSUE TITLE
Deprecate PEcAn.FATES, PEcAn.CLM45 and move functions to PEcAn.CTSM

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#2323]

**Comment by dlebauer** [comment]
started on this branch: https://github.com/PecanProject/pecan/tree/ctsm_package

Also, need to merge documentation

**Comment by tonygardella** [comment]
To deprecate, do you want me to delete the FATES package?

**Comment by mdietze** [comment]
@tonygardella don't delete the FATES package. Once it's replacement package is operational, then you mark it as .Deprecated, then after a release or two of giving fair warning you actually remove it. See for example https://ropensci.org/technotes/2017/01/05/package-evolution/
