### ISSUE TITLE
Error installing rtm module

### ISSUE THREAD

**Issue by jesusNPL** [PecanProject/pecan#2353]
### Bug Description

I have tried to install the rtm module from PecanProject however it return different errors. For example, first I tried to install in a macOS Mojave and using R 3.6 and return the following error:

ERROR: dependencies 'PEcAn.logger', 'PEcAn.assim.batch' are not available for package 'PEcAnRTM'.

Most details in the following screenshot:

<img width="720" alt="Screen Shot 2019-05-10 at 3 05 29 PM" src="https://user-images.githubusercontent.com/6001098/57633168-bd085800-7568-11e9-8818-cb5f286fdaf2.png">

Then, I have tried to install in a Windows environment with R 3.5.3. The returned error was different:

ERROR: Unix-only package
* removing 'C/Users/jpintole/Documents/R/win-library/3.5/PecAnRTM'
In R CMD INSTALL

For both cases I used the guidelines provided in the GitHub https://github.com/PecanProject/pecan/tree/develop/modules/rtm

Thanks in advance for any help.

Jesús

**Comment by ashiklom** [comment]
Currently, the RTM package depends on other parts of the PEcAn system -- namely, `PEcAn.assim.batch` and `PEcAn.logger` -- none of which are on CRAN. Those in turn have other PEcAn dependencies, so installing is a bit non-trivial.

The best way to do it currently is to download PEcAn source code, from the PEcAn root directory, run `make .install/modules/rtm`. That should automatically install all the required dependencies (of which there are many!).

At some point, I plan to invest some time in a release of PEcAnRTM that doesn't depend on other parts of PEcAn, which should make it possible to install with `install_github`.

**Comment by jesusNPL** [comment]
Thanks for your quick answer, that help a lot.
