### ISSUE TITLE
Should utils::get.results move to workflow?

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#2359]
PEcAn.utils::get.results currently calls PEcAn.uncertainty::read.ensemble.output, creating a circular (and undeclared!) dependency. For previous cases like this our approach has been to move the offending function out to a different package -- does it make sense to do that here as well?

This change originated [here](https://github.com/PecanProject/pecan/pull/2298/files#diff-94c1039826c2621a51b40bf1a5e89595R211) in #2298, which I signed off on and must have completely missed this.

**Comment by ashiklom** [comment]
I think moving it to `PEcAn.workflow` makes sense, both because of the dependency and because I think it's more of a workflow function anyway since it triggers two other modules (`sensitivity` and `ensemble`).

**Comment by infotroph** [comment]
Moved to `uncertainty` in #2830
