### ISSUE TITLE
Issues with installed netCDF on RHEL 6.5

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#236]
I ran into a number of hiccups trying to compile netCDF 4.3.xx on my RHEL system.  Here is how I was able to get it installed:

Zlib
CFLAGS=-fPIC ./configure -s --prefix=/data/software/zlib/1.2.8/

HDF4
./configure --prefix=/data/software/hdf4/4.2.10 --with-zlib=/data/software/zlib/1.2.8 --with-jpeg --enable-shared --disable-netcdf --disable-fortran

make -j$threads
make check
make install
make install-examples
make install check

HDF5
./configure --with-zlib=/data/software/zlib/1.2.8 --prefix=/data/software/hdf5/1.8.13 --enable-fortran --enable-shared --enable-build-all

make -j$threads
make -j$threads check
make install

***Now here is the key: I didn't use the release version (4.3.2) because I finally isolated the compile issues and it was something that was fixed in a later release.  It was related to the version of HDF5 (1.8.13): https://github.com/Unidata/netcdf-c/commit/435d8a03ed28bb5ad63aff12cbc6ab91531b6bc8

git clone https://github.com/Unidata/netcdf-c.git

4.3.3rc2./configure --prefix=/data/software/netcdf/4.3.3rc2 --enable-netcdf-4 --enable-shared --enable-utilities --enable-hdf4 --enable-hdf4-file-tests --enable-v2

make -j$threads
make check 1>out.txt 2>err.txt &cat out.txt err.txt |grep -i 'fail\|error'
make install
../4.3.3rc2/bin/nc-config --all

This netCDF 4.3.3-rc2 has been built with the following features: 

  --cc        -> mpicc
  --cflags    ->  -I/data/software/netcdf/4.3.3rc2/include -I/data/software/hdf5/1.8.13/include -I/data/software/hdf4/4.2.10/include -I/data/software/zlib/1.2.8/include
  --libs      -> -L/data/software/netcdf/4.3.3rc2/lib -lnetcdf

  --has-c++   -> no
  --cxx       -> 
  --has-c++4  -> no
  --cxx4      -> 

  --fc        -> 
  --fflags    -> 
  --flibs     -> 
  --has-f90   -> no

  --has-dap   -> yes
  --has-nc2   -> yes
  --has-nc4   -> yes
  --has-hdf5  -> yes
  --has-hdf4  -> yes
  --has-pnetcdf-> no

  --prefix    -> /data/software/netcdf/4.3.3rc2
  --includedir-> /data/software/netcdf/4.3.3rc2/include
  --version   -> netCDF 4.3.3-rc2

**Comment by robkooper** [comment]
@serbinsh can this be closed?

**Comment by serbinsh** [comment]
Closed
