### ISSUE TITLE
Use GitHub actions for automated CI?

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#2412]
[GitHub Actions](https://github.com/features/actions) seems like a promising choice for continuous integration. A major advantage over Travis is the _really_ generous hosting -- 6 hour runtime _per job_, and up to 20 workflows in parallel ([source](https://help.github.com/en/articles/workflow-syntax-for-github-actions#usage-limits)).

Also, it looks like if we wanted to, we could migrate to this in phases, since Travis CI has its own [GitHub action](https://github.com/travis-ci/actions).

One _really_ cool feature of GitHub actions is the ability to run specific actions only when [specific files have been changed](https://help.github.com/en/articles/workflow-syntax-for-github-actions#onpushpull_requestpaths). We could use this to, e.g., only re-build and test PEcAn R packages when R code has been updated, and only re-build documentation when that has been updated, rather than doing both all the time.

Food for thought.

**Comment by robkooper** [comment]
I asked for access to it, but have not heard anything.

**Comment by ashiklom** [comment]
I think we have access now. Or at least I do...? On the PEcAn repository, I
now see an "Actions" panel.
