### ISSUE TITLE
Revisit here::here in PEcAn.utils tests

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#2417]
`base/utils/tests/testthat/test.read_web_config.R` uses `here::here` to read two config files from the `web/` directory. This causes two issues, one trivial and the other needing more thought:

* [Need to declare](https://travis-ci.org/infotroph/pecan/jobs/580354445#L6126) the `here` import in the `PEcAn.utils` DESCRIPTION, probably in Suggests since it's used only during testing and already checks whether `here` is available.

* The test assumes it can find `web/` two levels up, so it fails with "cannot open the connection" when run during package checks (which are run in a tempdir, not in-place like devtools::test does). One possible fix would be to copy a sample config file into `base/utils/tests/testthat/data`, but there may be better solutions.

**Comment by ashiklom** [comment]
> One possible fix would be to copy a sample config file into base/utils/tests/testthat/data

I like that idea. It also lets us have fine-grained control over the test. Do both `testthat::test` and `devtools::check` (or whatever we use) run tests from the same relative path? I.e. Could we abandon `here` altogether and just use `file.path("testthat", "data", "config.php")` (or would it be something else)?

**Comment by infotroph** [comment]
> Do both `testthat::test` and `devtools::check` (or whatever we use) run tests from the same relative path? 

As far as I know yes, the tests are always run from <package_dir>/tests. The key differences are that all bets are off on paths outside `<package_dir>`, and that `check` is running inside the *built* package, so e.g.`<package_dir>/inst/data` will turn into `<package_dir>/data`.

> Could we abandon here altogether and just use `file.path("testthat", "data", "test-config.php")`

Yes, I think that's my vote. Safe, easy, and avoids a dependency.
