### ISSUE TITLE
Any way to change IED_INIT_MODE when running ED2 from the web interface?

### ISSUE THREAD

**Issue by ryankelly-uiuc** [PecanProject/pecan#243]
It seems like any ED2 run started from the pecan web interface will be set up as a bare ground run (i.e., IED_INIT_MODE=0). Is this right, or just something to do with the settings for my (limited) set of examples? If so, it would be good to be able to change this, or at least to automatically set IED_INIT_MODE=3 when pss/css/site files are supplied.

**Comment by zhangwenx** [comment]
https://github.com/PecanProject/pecan/pull/364
