### ISSUE TITLE
Infinite coefficient of variation for the orient_factor in ED2

### ISSUE THREAD

**Issue by femeunier** [PecanProject/pecan#2440]
### Bug Description

`orient_factor` is a parameter in ED2 comprised between -1 and 1 whose default value is close to 0. Therefore typical priors in PEcAn are uniform whose bounds are +/- 0.5 leading to zero mean distribution. This will cause the CV to be infinite in PEcAn sensitivity analysis and makes its comparison with other parameters useless

### To Reproduce

Just run a simple MA with orient_factor in the list of priors

## Expected behavior

I think we should use a definition of orient_factor shifted towards positive values (0-2, instead of -1-1) to avoid this behavior.

## Screenshots

![Screenshot from 2019-09-27 11-05-20](https://user-images.githubusercontent.com/8898071/65780140-1ab3d000-e117-11e9-968e-25d7b8bba9db.png)

## Machine (please complete the following information):

 All

## Additional context

If people are conceptually OK with this, the fix is pretty simple (a simple change in `write.configs.ed` coupled with new priors will do the trick). But I wanted to check out and see people's opinion first.

**Comment by mdietze** [comment]
@femeunier I'm not sure your proposed solution (change the prior) really addresses the underlying problem (how do we interpret CV when the mean is 0). Also, orient factor CAN take on values from -1 to 1 so shifting the prior to be only positive isn't realistic.

Finally, the high variance contribution of orient factor ISN'T driven by the fact that the mean is zero and CV is infinite (i.e. the variance contribution isn't calculated from the CV)

**Comment by femeunier** [comment]
Sorry, I realized haven't been very clear. Few things:

- I was actually suggesting to change the definition of `orient_factor` in PEcAn only (where it would be defined between 0-2) and not in ED2 (where it would of course still be between -1 and 1) so that the CV in PEcAn would have finite values.

- What I was proposing then was to add a few lines in `write.config.ed`, something looking like

```
if ("orient_factor" %in% names(trait.samples)) { 
    trait.samples[["orient_factor"]] <- as.numeric(trait.samples[["orient_factor"]]) -1
}
```

So the parameter would keep its original value in ED2 and would have meaningful CV in PEcAn

- I agree that the variance contribution is not driven by the high CV. I just wanted to point out how I couldn't compare CV of `orient_factor` to others with this graph.

**Comment by mdietze** [comment]
I'm not sure we want to make arbitrary changes the definition of a variable in BETY just to make a plot look better.

Perhaps a better solution would be to improve the graphing code to detect outlier CV's and not scale the limits based on the outliers

**Comment by femeunier** [comment]
That's indeed a better idea, I'll do that.
