### ISSUE TITLE
Change description of license to match CRAN standards

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#2446]
All PEcAn packages currently declare their license in the DESCRIPTION file using the string `License: FreeBSD + file LICENSE`. However, the R foundation has a [controlled terminology](https://www.r-project.org/Licenses/) for the License field and wants all packages to use one of their recognized strings.

The PEcAn license is worded identically to the one R calls "[BSD 3-clause](https://www.r-project.org/Licenses/BSD_3_clause)". Would it be acceptable to change all DESCRIPTION files to say `License: BSD_3_clause + file LICENSE`?

**Comment by robkooper** [comment]
I'm fine with this, however, I do believe you have to bring this up with all authors as well as institutions they work for. That is my interpretation of the $0.02 I spend on law on the internet.

**Comment by infotroph** [comment]
Another reason to change the description: [Apparently](https://en.wikipedia.org/wiki/BSD_licenses) "FreeBSD" usually means the 2-clause license with no non-endorsement clause, NOT the 3-clause license we provide.

I should also re-emphasize that everything I propose here is a change in DESCRIPTION wording, *not* a change in the licensing terms themselves.

**Comment by ankurdesai** [comment]
After reviewing, I don't think this is a major change and we should line up with R standard, so ok from my side.
