### ISSUE TITLE
avoid checking inheritance with ==

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#2479]
## Description

When thinking about the class of an R object, it's important to remember that class(x) might have length > 1 and that the entry you care about might not be the first one. In other words, check class membership using `inherits` or `is` and not any variant on `class(obj) == "classname"`.  On a quick check today I see about 20 instances of `class(.*==` in the PEcAn codebase, including a bunch inside `if` statements where it's doubly unsafe to assume length == 1. 

This has always been good practice, but a check and cleanup this winter would be especially timely because R 4.0 [may bring changes in matrix class inheritance](https://developer.r-project.org/Blog/public/2019/11/09/when-you-think-class.-think-again/index.html) that would break naively-written class tests.

## Proposed Solution

* Find all instances of `class(obj) == "classname"`, `"classname" %in% class(obj)`, etc.
* For most of these, convert to `inherits(obj, "classname")`. Two possible exceptions:
  - Use `is.<class>(obj)` when we're more interested in an implicit type than a stated class name. Example: `inherits(some_df, "list")` returns FALSE but `is.list(some_df)` returns TRUE, so the latter is appropriate when the input might be a data frame and the real question was "Is it safe to treat this object as if it were a list?"
  - Some S4 classes have conditional inheritance, which is checked by `is(obj, "classname")` but not by `inherits(obj, "classname")`, but I'm not aware of anywhere in the PEcAn code we'd need this.
* Try to flag future uses of `class(...==` during code review. Unfortunately I don't know of any easy way to test this programmatically, though testing with `_R_CHECK_LENGTH_1_LOGIC_` enabled should help catch the problem cases inside `if` statements.

**Comment by ashiklom** [comment]
Great summary, thanks for opening this!

One other thought: A fairly common use of `class() == ...`, at least in my older code, was in combination with `try(...)` to catch errors. It's probably safe to replace these with `inherits(x, "try-error")`, but the more "correct" solution is to use a proper `tryCatch` (which can also be used to catch and handle other output, like warnings and messages).

**Comment by rahul799** [comment]
@infotroph, @ashiklom  I will like to work on this _`issue`_. I have understood the solution that you have proposed & will work accordingly. Can you assign this to me?

**Comment by rahul799** [comment]
#2499  I have made a `PR`. @infotroph please review it & let me know if any changes I need to make.
