### ISSUE TITLE
call_MODIS "all rows bad" warning will never fire

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#2520]
Can you talk me through what this test does? It looks to me as if it will always evaluate to TRUE even when no rows are good, because `is.null()` on a length 0 vector returns FALSE.

_Originally posted by @infotroph in https://github.com/PecanProject/pecan/pull/2338_

Bumped this to a new issue to avoid holding up #2338, refers to [`if (length(good) > 0 || !(is.null(good))) {` in call_MODIS.R](https://github.com/PecanProject/pecan/pull/2338/files#diff-47227c849cd1830d9d5019a5a89bb41fR247)

Consider a simplified example case:

```
output = data.frame(
	value = c("GOOD", "GOOD", "BAD", "BAD"),
	qc = c("000", "001", "002", "003"))

# A case where all values are bad
output <- output[output$value == "BAD", ]

good <- which(output$qc %in% c("000", "001"))
print(good) # integer(0)
print(is.null(good)) # FALSE
if (length(good) > 0 || !(is.null(good))) {
	print("Some are good! Here they are:")
	output[good, ] # data frame with 0 rows
} else {
	print("All values bad") # Never prints!
}
```

I suspect deleting `|| !(is.null(good))` is enough to get the desired behavior, but check me on that.

**Comment by bailsofhay** [comment]
Will work on getting this fixed after the bigger merge today. @mdietze wants me to add in an additional filter that removes high Lai sd values, so I will also add that in here since it's in the same section.
