### ISSUE TITLE
Sporadic test failure in bt_prior

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#2546]
### Bug Description

In `modules/assim.batch/tests/testthat/test.bt_prior.R`, the check whether the BayesianTools prior functions [sample with the expected variance](https://github.com/PecanProject/pecan/blob/develop/modules/assim.batch/tests/testthat/test.bt_prior.R#L37) sometimes fails when the lognormal sample draws high tail values.

This is causing sporadic [Travis failures](https://travis-ci.org/PecanProject/pecan/jobs/659334878#L5353) in unrelated PRs. Workaround: restart the build and hope for better luck.

I suspect the failure doesn't indicate any problem with the sampler, just a limitation of the test as written. By my count a lognormal sample with n=10000 should land within 25% of the analytical variance "almost 99%" of the time:

```
> replicate(5000, var(rlnorm(1e4, 1, 1))) %>%
  map_chr(all.equal, (exp(1^2)-1) * exp(2*1 + 1^2), tolerance = 0.25) %>%
  map_lgl(~ . == "TRUE") %>%
  sum(.)/5000*100
[1] 98.82
```

...but in practice that 1.2% is enough to be pretty annoying when it causes CI failures. Could we do this check on a log scale or rewrite it to be less sensitive to outliers?

**Comment by infotroph** [comment]
@ashiklom It looks like you wrote these tests -- any thoughts on how to proceed?

**Comment by ashiklom** [comment]
Thanks for catching this. Probably the best thing to do is set an RNG seed
under which the tests pass. I think I had something similar for the RTM
module at some point.

**Comment by infotroph** [comment]
> Probably the best thing to do is set an RNG seed

That's certainly way *easier* than anything I had in mind, so I'll do it, thanks.

But I'm less sure it's *best*, so for future searchers: When test results depend on RNG state I endorse adding `set.seed` as a second resort, behind refactoring tests to be reliable without it. My reasoning it that setting the seed makes randomness-dependent tests behave *consistently* (which is a good thing!), but it does it by *narrowing* test coverage -- the intermittent behavior still exists and will still happen in the wild but not in the test suite, so the moment you notice the intermittency is a good moment to question whether the test is actually capturing function behavior as well as you thought.

**Comment by ashiklom** [comment]
Yeah, by "best", I really meant "easiest", and I agree with the comment above. Probably the best balance is, as you say, to compare `log(variance)`, since that should be way more robust to extreme values.

**Comment by infotroph** [comment]
I guess the slightly trickier part is that we're trying to apply the same test to three distributions in parallel. Is `expect_equal(log(var(sample)), log(correct_var), tolerance)` a useful test when `sample` is distributed normal or gamma?
