### ISSUE TITLE
Failed to build bety when build with docker on Windows

### ISSUE THREAD

**Issue by Yiyiyimu** [PecanProject/pecan#2554]
### Bug Description

When I follow the [documentation](https://pecanproject.github.io/pecan-documentation/develop/pecan-manual-setup.html) to build with docker, the second step - initialize BETYdb seems failed, due to the bety page could not be get in, and "docker ps" shows it's keep restarting.

### To Reproduce

Follow the steps in documentation:

1. ```docker-compose up -d postgres``` step went well and received the expected behavior.

2. ```docker-compose run --rm bety initialize``` step didn't receive expected behavior on 

   ```
   CREATED SCHEMA
   Loading  schema_migrations         : ADDED 61
   Started psql (pid=507)
   Updated  formats                   :     35 (+35)
   Fixed    formats                   : 46
   ...
   Added carya44 with access_level=4 and page_access_level=4 with id=329
   Added guestuser with access_level=4 and page_access_level=4 with id=331
   ```

   On contrary it shows the following and hangs there for about 25 minutes.

   ```
   Create new database, initialized from all data
   CREATE ROLE
   CREATE DATABASE
   ```

   Also it didn't show the expected errors related to functions and/or operators already existing, which actually appear on the third step. I followed the [troubleshooting](https://pecanproject.github.io/pecan-documentation/develop/docker-index.html#docker-quickstart-troubleshooting) step and it still didn't work.

3. ```docker run -ti --rm --network pecan_pecan --volume pecan_pecan:/data --env FQDN=docker pecan/data:develop``` went well, except showing the errors which should be appeared on last step.  The last step ```docker-compose up -d``` also went well and download everything successfully.

4. Right now get into http://localhost:8000/pecan/ would shows
![image](https://user-images.githubusercontent.com/34589752/77771680-f616c180-7081-11ea-921b-45893511401f.png)
but after push next button, the website failed to load and shows

```
Fatal error: Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "sitegroups" does not exist LINE 1: SELECT id, name FROM sitegroups WHERE public_access OR user_... ^ in /var/www/html/pecan/02-modelsite.php:51 Stack trace: #0 /var/www/html/pecan/02-modelsite.php(51): PDOStatement->execute(Array) #1 {main} thrown in /var/www/html/pecan/02-modelsite.php on line 51
```
http://localhost:8000/bety/ would also show "bad gateway".

5. At this time, "docker ps" shows bety is keep restarting while others is normal, like this
![image](https://user-images.githubusercontent.com/34589752/77772703-8b668580-7083-11ea-90cd-cf8824223c7c.png)

## Machine:

 - Server: docker
 - OS: Windows 10 pro
 - Browser: Chrome
 - Version: lastest for both pecan and bety

## Additional context

The only possible reason I could think of is there would be some compatibility problem on building in Windows. I failed to find relevant issues people have on building with docker on Windows, so it may be the problem on my side.

**Comment by robkooper** [comment]
I think the problem is that the database did not get initialized correctly. Unfortunately the way it is done right now takes a long (as in really long) time. I'm trying to see if we can put a smarter dump somewhere that we can use to start the initial version of the database.

**Comment by Yiyiyimu** [comment]
Thank you @robkooper for your help! I successfully built with VM right now and it works great!

**Comment by robkooper** [comment]
It should be possible to use `docker run --rm --network bety_bety pecan/betydb` to initialize the database. This is not an automatic process and thus the database might be out of date. The goal is to do this as part of a cronjob to make sure the database is fairly recent.

**Comment by Yiyiyimu** [comment]
Thank you @robkooper !

Somehow the next time I install PEcAn on Windows following the original guide works. But when I try it right now on Ubuntu 18.04, the same problem happens. And this time your suggestions works. I think create-container step didn't create network bety_bety, so I change it to pecan_pecan and it works.

I'm not familiar with docker, but since the problem is not related to operating system, do you think there is need to add it to the documentation?
