### ISSUE TITLE
Documentation changes for make & issue templates

### ISSUE THREAD

**Issue by Yiyiyimu** [PecanProject/pecan#2561]
### Document Change needed

Following developer guide [here](https://pecanproject.github.io/pecan-documentation/develop/developer-guide.html#recommended-workflow-a-new-branch-for-each-change) to compile with make, it stopped a dozen times due to some prerequisite package missing, including (for Ubuntu)

```libcurl4-openssl-dev, libxml2-dev, libgit2-dev, libssh2-1-dev, libnetcdf-dev, libpq-dev, libgdal-dev, librdf0-dev, jags, libglu1-mesa-dev```

I just noticed some dependency packages are listed [here](https://pecanproject.github.io/pecan-documentation/develop/workflow-modules#osinstall) and [here](https://pecanproject.github.io/pecan-documentation/develop/workflow-modules#additional-packages), but I didn't find them when I start compiling. And I think I met some new dependency package. Maybe it's a good idea to add these two links in developer guide before make step. It could save some time for new developers. I could add it to documentation if needed.

The location is in section 8.2.1.10, the 3rd step.

---

Also, the "Editing this Book"link in the github documentation issue template (below) is broken, it should change to https://pecanproject.github.io/pecan-documentation/develop/about-the-pecan-book.html#bookediting
```
### Information for those wanting to make changes

Please follow the instructions in the [Editing this Book](https://pecanproject.github.io/pecan-documentation/develop/bookediting.html) section of the documentation. 

All R-markdown files related to documentation are located within the main directory `/pecan/book_source` except for the demos and vignettes which are in `pecan/documentation/tutorials`.
```

**Comment by infotroph** [comment]
I think we were hoping the note  "This page will only list any steps you have to do to upgrade an existing system" at the [beginning of section 8](https://pecanproject.github.io/pecan-documentation/develop/developer-guide.html#updatebety) would be enough to point developers toward the installation guide without needing to repeat it for all steps below. Is there another place that note should live to become more visible?

**Comment by Yiyiyimu** [comment]
@infotroph Thank you for your reply and sorry I didn't notice that, but I do think it would be better to put that sentence before 8.1 title. 
Since the beginning of section 8 shows four links, Update BETY, Update PEcAn Code, PEcAn and Git,  Coding Practices, for me who don't need to update, I skipped two update parts and directly go to git part by mistake at first glance. Maybe someone else would fall in the same problem.

And since the name of it is "developer guide", maybe it would be better to list the link of [native install](https://pecanproject.github.io/pecan-documentation/develop/pecan-manual-setup.html#install-native) or [OS specific installation](https://pecanproject.github.io/pecan-documentation/develop/workflow-modules.html#osinstall) here for someone who need a full installation.
