### ISSUE TITLE
BASGRA dockerization

### ISSUE THREAD

**Issue by istfer** [PecanProject/pecan#2565]
## Description
I would like to dockerize BASGRA, but I have a bit of a unique case here. The BASGRA code PEcAn uses currently lives in the [PEcAn.BASGRA package](https://github.com/PecanProject/pecan/tree/develop/models/basgra/src). So my first question: does this make BASGRA automatically dockerized when pecan image is created? If yes (or partly yes), do I still need to announce it in the json files, and docker-compose to be able to run it?

If no, then I can dockerize BASGRA explicitly. But that also brings up other issues:

- I want to dockerize my version of it because I have additions to it (which I'm not sure if the original maintainers would be interested in having in the mainline, and the code in PEcAn is the one with my modifications).
Then, in [this json file](https://github.com/PecanProject/pecan/issues/2158) and dockerfile should I point to my fork of BASGRA, or should the json file point to the original version and dockerfile should point to mine? I guess in general, how do we plan to handle different versions of models in our docker approach?

- More importantly, I was using BASGRA through a [single R wrapper](https://github.com/PecanProject/pecan/blob/develop/models/basgra/R/run_BASGRA.R) to process the met, call the fortran code and postprocess the outputs without writing intermediate input/output files in the current implementation, i.e. I didn't have met2model.BASGRA and model2netcdf.BASGRA. 
Can I call the dockerized-model in the R script in a [similar manner](https://github.com/PecanProject/pecan/blob/develop/models/basgra/R/run_BASGRA.R#L238)?

**Comment by robkooper** [comment]
If it is compiled and installed in the base pecan image, you can do something similar as biocro, see https://github.com/PecanProject/pecan/blob/develop/models/biocro/Dockerfile

As for the second bullet point, I think so. Not sure how it would fit in the PEcAn workflow. The thinking of the model executors is that they do the actual running of the models, like it would do on the geo cluster. All of the other code that runs for PEcAn is executed in the executor image.
