### ISSUE TITLE
add model_info.json to models/template

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#2567]
* We now expect all models to have a `model_info.json` going forward, correct? If so, we should give an example in `models/template`
* If it's standard for `model_info.json` to live in the package root (rather than `inst/` like `register.*.xml` did), will also need to list it in `.Rbuildignore` to prevent "non-standard files /directories found at top level" note at check time

(Moved from https://github.com/PecanProject/pecan/pull/2566#issuecomment-612628000)

**Comment by robkooper** [comment]
the code that connects and wait for model runs (as well as advertises the heartbeat) is written in python (there are no RabbitMQ bindings). We can put the model_info.json in inst as well and just need to copy it to the right location when we build the docker file.
