### ISSUE TITLE
clone PFT not working

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#257]
On http://psql-pecan.bu.edu/bety/pfts, the "Clone Record" button does not work. This same button is working on ebi-forecast. I'm at a loss as to what is different between the two that it's working in one place but not the other.

**Comment by robkooper** [comment]
This is due to psql-pecan using version 2 of ruby instead of ruby 1.9. If possible ask the system admins to install version 1.9 on this machine.

**Comment by mdietze** [comment]
Rob, WE are the administrators of those machines so feel free to install (I think you have sudo). 

<iPhone>

**Comment by robkooper** [comment]
Installed version 1.9.3 and restarted apache. Please check to see if you still can not clone a PFT.

**Comment by mdietze** [comment]
Cloning works now. Thanks!
