### ISSUE TITLE
docker monitor bug

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#2571]
Here are the log files in my cases:

[OK.log](https://github.com/PecanProject/pecan/files/4468900/OK.log): when monitor container stays up (but there are still errors, e.g. `Error adding model to database`)

[NOTOK.log](https://github.com/PecanProject/pecan/files/4468902/NOTOK.log): when monitor keeps restarting. I guess in this one the main problem is:
```
  File "monitor.py", line 250, in insert_model
    if conn is not None:
UnboundLocalError: local variable 'conn' referenced before assignment
```

Looking at previous version of monitor.py there used to be a `conn = None` line. So I went ahead and inserted `conn = None` in monitor.py-Line150 and it seemed to solve this particular problem.

[FIX.log](https://github.com/PecanProject/pecan/files/4468903/FIX.log) is what I get after `conn = None` fix

Not sure what to do about this invalid port number issue:
```
monitor_1        | 2020-04-13 09:12:51,256 [MainThread     ] ERROR   : root - Error adding model to database
monitor_1        | Traceback (most recent call last):
monitor_1        |   File "monitor.py", line 155, in insert_model
monitor_1        |     conn = psycopg2.connect(postgres_uri)
monitor_1        |   File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
monitor_1        |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
monitor_1        | psycopg2.OperationalError: invalid port number: "postgres"
```
Not sure if relevant but this is what I had in my docker-compose.override.yml:
```
  postgres:
    ports:
      - 7654:5432
```
Also could be related, I'm not sure why, but after I rebuilt images my bety container name became something like `59e40a881709_pecan_postgres_1` with hash in the front:
`59e40a881709        mdillon/postgis:9.5                        "docker-entrypoint.s…"   3 days ago          Up About a minute           0.0.0.0:7654->5432/tcp                                   59e40a881709_pecan_postgres_1`

Btw, [is this](https://github.com/PecanProject/pecan/blob/develop/docker/check/Dockerfile#L4) a typo? `PGHOST=posgres` --> `PGHOST=postgres`

_Originally posted by @istfer in https://github.com/PecanProject/pecan/pull/2566#issuecomment-612827111_

**Comment by infotroph** [comment]
I can reproduce this and found two different ways to work around it:

* edit line 27 of monitor.py

```
- postgres_port = os.getenv('PGPORT', 'postgres')
+ postgres_port = os.getenv('PGPORT', 5432)
``` 

* Or, declare postgres port in `docker-compose.override.yml`

```
services:
  monitor:
    environment:
      - PGPORT=5432
```

**Comment by istfer** [comment]
I [also suspect ](https://github.com/PecanProject/pecan/pull/2566#issuecomment-613363947)that monitor.py L27 was probably meant to be `5432` 

Regardless, this could also be something to thing to add [these override tweaks](https://github.com/PecanProject/pecan/issues/2315)

**Comment by istfer** [comment]
Btw @infotroph did you pull develop image to test this or did you build the image locally? Just asking because I had an error creating the images locally, something to do with `doc`, I took it out from docker.sh (e.g. `for x in base web; do`) to move forward, I might have messed something else up but I was curious if someone else might reproduce it

**Comment by infotroph** [comment]
For this case I pulled the develop image -- for everyday use I've been trying to avoid local builds unless a posted version really isn't working for me.

**Comment by istfer** [comment]
I see thanks, I'll see if I can reproduce it myself
