### ISSUE TITLE
permission issues in docker

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#2572]
### Bug Description

@istfer would like to start the workflow from the web interface, and continue to do work from rstudio. Right now this could lead to problems due to permissions. It looks like the following permissions are in play:
- pecan/web, runs as www-data (uid=33, gid=33)
- pecan/base (rstudio) runs as rstudio (uid=1000, gid=1000)
- pecan/* runs as root (uid=0, gid=0)

Should switch all containers to run as carya/carya or rstudio/rstudio (uid=1000,1000).

**Comment by istfer** [comment]
Thanks Rob, if you point me towards right direction I'm happy to test stuff :+1:

**Comment by istfer** [comment]
I have been messing around about this..I think I was able to make things work as both 1000 and as my own UID on the server.

I first added `&& chown -R 777 /data/workflows /data/dbfiles` to `RUN` under `web/Dockerfile` so that there are no permission issues in (although I was also able to replace `www-data` uid too I think, see below)

then I added this chunk to `base/Dockerfile` as well, because when I try to submit runs via rstudio it looks for sender.py and pika:

```
RUN apt-get update \
    && apt-get install -y --no-install-recommends python3-pip \
    && pip3 install pika==1.0.0 \
    && rm -rf /var/lib/apt/lists/*
COPY docker/executor/sender.py /work/
```

and I specified user in the executor/Dockerfile as `USER rstudio`

I think this was enough for me to start the workflow from the web interface, and continue to do work from rstudio. Although I suspect that this may cause permission issues with the files written by executor previously.

In addition, following [this blogpost](https://jtreminio.com/blog/running-docker-containers-as-current-host-user/#ok-so-what-actually-works) I tried running as my UID:GID.

To do that I added the following to base/Dockerfile:

```
ARG USER_ID
ARG GROUP_ID

RUN if [ ${USER_ID:-0} -ne 0 ] && [ ${GROUP_ID:-0} -ne 0 ]; then \
    userdel -f rstudio &&\
    if getent group rstudio ; then groupdel rstudio; fi && \
    groupadd -g $GROUP_ID -r rstudio && useradd -l -u $USER_ID -r -g rstudio rstudio && \
    install -d -m 0777 -o rstudio -g rstudio /home/rstudio && \
    chown --changes --silent --no-dereference --recursive \
          --from=1000:1000 $USER_ID:$GROUP_ID \
        /home/rstudio \
;fi
```
I don't know where else I should change permissions retrospectively. My filesystem and docker system are brand new.

Then I added uid and gid to build arguments in docker.sh:

```
        --build-arg USER_ID=${UID:-1000} \
        --build-arg GROUP_ID=${GID:-1000} \
```

unless defined otherwise (e.g. UID=id -u ${USER} GID=id -g ${USER} ./docker.sh) it will run as 1000:1000

Then, I did the same for `web/Dockerfile`:

```
ARG USER_ID
ARG GROUP_ID

RUN if [ ${USER_ID:-0} -ne 0 ] && [ ${GROUP_ID:-0} -ne 0 ]; then \
    userdel -f www-data &&\
    if getent group www-data ; then groupdel www-data; fi && \
    groupadd -g $GROUP_ID -r www-data && useradd -l -u $USER_ID -r -g www-data www-data && \
    install -d -m 0777 -o www-data -g www-data /home/www-data && \
    chown --changes --silent --no-dereference --recursive \
          --from=33:33 ${USER_ID}:${GROUP_ID} \
        /home/www-data \
        /var/www \
        /usr/sbin/nologin \
;fi
```

What do you think? I can open a PR to get your input or I am happy to wait for your implementation to test.

**Comment by robkooper** [comment]
So this is tricker than I thought it would be and requires some experimentation. I'll be using the following command on all OSs: `docker run --rm -v /tmp:/foo busybox touch /foo/hello` 

## Mac

Files written in container to a volume mounted from the laptop, are owned by the user that started the docker container. e.g. if I start a container the file will be owned by me.

## Linux

Files written in the container are owned by the same user inside the container, e.g. root in the example

## Windows

If anybody has windows they can try this on, I do not.

**Comment by robkooper** [comment]
So we can start the container with `docker run --user $UID --rm -v /tmp:/foo busybox touch /foo/hello` on Linux. This will change the owner in the container to my user id. All files written to disk will be owned by me. Disadvantage is that inside the container we might not have the right permission to write to any files needed.

**Comment by istfer** [comment]
I'm surprised to hear that it differs between mac and linux. But the linux behaviour you see is compatible what I experienced earlier, and is also what is explained in the blogpost I linked above: https://jtreminio.com/blog/running-docker-containers-as-current-host-user/

Like you said,  "changing the owner in the container to my user id" also doesn't work, I can confirm that it does hit permission errors inside the container. The blogpost also confirms.

I think the post is very helpful to read, but here is the summary from it:

- root works great inside the container but is annoying to work with on the host system, and

- your local user works great on your host system, but will quickly run into permission problems inside the container.

- non-root internal user with required permissions works great inside the container but completely falters on host system with volumes.

Then it also suggests the solution (which is the way I applied above, and works for me) https://jtreminio.com/blog/running-docker-containers-as-current-host-user/#ok-so-what-actually-works

**Comment by robkooper** [comment]
Thanks @istfer, now comes the fun answer. This works on Linux, might be different on other systems. Also problem is that this should **not** be done on a shared system, as this will give others access to files in your home folder.

This will leverage of NFS to mount the file system in your local docker image, changing the files to owned by you.

First install nfs server: 
```
apt-get install nfs-kernel-server
```

Next export your home directory:
```
echo -e "$HOME\t127.0.0.1(rw,no_subtree_check,all_squash,anonuid=$(id -u),anongid=$(id -g))" | sudo tee -a /etc/exports
```

And export the filesystem.
```
sudo exportfs -va
```

At this point you have exported your home directory, only to your local machine. All files written to that exported filesystem will be owned by you (`id -u`) and your primary group (`id -g`).

Next comes docker run command, this is more complex than before:
```
docker run --rm --mount type=volume,dst=/foo,volume-driver=local,volume-opt=type=nfs,\"volume-opt=o=nfsvers=3,addr=127.0.0.1\",volume-opt=device=:${HOME}  touch /foo/hello
```

If you check the file `hello` in your home directory is now owned by you.

Finally we can do the same in a docker compose (requires docker-compose version 3.2 so you need to change that in your docker-compose.yml, will fix this in a pull request).

```
volumes:
  pecan:
    driver_opts:
      type: "nfs"
      device: ":/home/username"
      o: "addr=127.0.0.1"
```

Complex, but I believe this should work.

**Comment by istfer** [comment]
Thanks @robkooper, these were going to be my next questions.. I was hoping to set up a development environment on a server where everyone develops and for example shares a common `dbfiles` and `workflow` location, e.g. under `/data`.

In my docker-compose.override I have this:
```
volumes:
  pecan:
    driver_opts:
      type: none
      device: /data
      o: bind
```

I don't want to run other people's codes, but I want to share our dbfiles etc under `/data`.. Do I still go the NFS way and export my home directory or does what I have work?

**Comment by robkooper** [comment]
I think you can export /data as is, then for development purposes you can have multiple nfs exports that point to each users home directory. then each user can use the shared data folder, but the home directory is mounted from nfs server.

Let me play a bit with the docker-compose.dev.yaml file

**Comment by robkooper** [comment]
tested and should work as expected right now.
