### ISSUE TITLE
Migration to R 4.0

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#2577]
R 4.0 is coming out very soon, supposedly in the next few days. Here's the [full changelog](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html). Migration will require re-installing all currently installed R packages, but, considering it's a major release, updates to code should be relatively minor (any may not be necessary at all). I think the main reason to switch is to take advantage of some really nice new features, including:

- Raw strings (similar to Python) that don't need to have special characters escaped; e.g. `r"(This is a Windows path: C:\Users\my-folder)" ` and `r"("Don't believe quotes people post on the internet" -- Abe Lincoln)"`
- `stringsAsFactors = FALSE` by default.
- User-specified custom error messages in `stopifnot`
- `list2DF` for creating `data.frame`s from lists of variables
- More consistent matrix-array method inheritance (i.e. matrices now inherit from arrays).
- Lower overhead for creating PSOCK clusters for parallelization (e.g. by the `parallel` package)
- _Much_ better Windows support for compiled code and external library dependencies, thanks to [RTools 4.0](https://jeroen.github.io/rstudio2019/#1).

We definitely shouldn't migrate everything on day 1 or even in the next few months, but we should start by adding R 4.0 to our build system matrix as a non-blocking test and consider other necessary steps.

**Comment by infotroph** [comment]
> we should start by adding R 4.0 to our build system matrix as a non-blocking test

Travis's R:devel has been 4.0 prerelease for months! Cache management is an ongoing headache because C2D4U doesn't help, but the 4.0-to-be builds are [currently passing](https://travis-ci.org/github/PecanProject/pecan/jobs/677351446) with no issue.

**Comment by ashiklom** [comment]
Awesome!!! I thought I vaguely remembered this being a thing, great to know for sure!

Once 4.0 is released, we may want to consider flipping a switch to make those blocking. I guess we'll have to avoid using some of the new features for a while to preserve backwards compatibility (I was _really_ excited about the raw strings, but oh well...).

**Comment by infotroph** [comment]
> we may want to consider flipping a switch to make those blocking

In concept I favor maintaining the broadest version compatibility we can, but I don't know if we have the team bandwidth to say we support more than one R version right now. I realize I just said R 4.0 caused "surprisingly few" build changes, but for several of those I was very glad to be able to leave the devel and/or oldrel build broken for days to weeks until we could work out backwards-compatible fixes.

But perhaps with upcoming CI changes and more Docker images instead of bare-metal installs this will become easier?

**Comment by robkooper** [comment]
I think we should make sure we do a build matrix for R. Nice thing is that these do run in parallel. We can leverage of the depends image and have a `pecan/depends:develop` which is the version we will use to build the actual images and `pecan/depends:3.5-develop` `pecan/depends:4.0-develop` and build these at night.

**Comment by robkooper** [comment]
This got done to fix the build :)
