### ISSUE TITLE
Basic Ameriflux meteorology Workflow

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#259]
Migrated from Redmine issue 1904

Finalize basic site-level workflow that goes from raw Ameriflux data to CF standard to gap filling to model-specific drivers.

**Comment by mdietze** [comment]
@robkooper @jam2767 is there anything left to do on this task or can we close it? Seems like the basic Ameriflux workflow is working

**Comment by robkooper** [comment]
Only part left is writing the results to the database done by @bcow.
