### ISSUE TITLE
Drought-2018 product

### ISSUE THREAD

**Issue by istfer** [PecanProject/pecan#2594]
## Description
Interested in linking this data product to PEcAn: [Drought-2018 ecosystem eddy covariance flux product for 52 stations in FLUXNET-Archive format](https://www.icos-cp.eu/data-products/YVR0-4898)

**Comment by ayushprd** [comment]
Hi Istem, just curious when you'd be linking this product, how would you do it? Will you download this dataset entirely and ingest it or will you use the ICOS Python package or some other way?

**Comment by istfer** [comment]
Hi Ayush, I would like to do the linking as soon as I can, but my "as soon as"s are typically a couple of months :)  It's high on my priority list. When I do that, I was planning to write an R script to download & process it on demand. I wasn't aware of their python package, good catch.

**Comment by melioristic** [comment]
@istfer I saw this topic under GSOC Idea list for this year. This seems like an idea that has been floating around for some time. Can you let me know if there are any updates, or should I just start with a draft proposal and share it with you.
