### ISSUE TITLE
02-modelsite.php toggle button for input filtering of sites

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#260]
On the site selection page, if we REQUIRE all inputs to be present on the system in order to select a site then we'll never be able to leverage the input processing workflows (e.g. FIA2ED, met workflow). Therefore a user needs to be able to select a site that is missing inputs. The requirement for a complete set of inputs should only be enforced in 03-inputs.php. That said, it would be nice to have a toggle button on 02-modelsite that would impose the current filter for complete inputs.

**Comment by zhangwenx** [comment]
Created pull request #383
