### ISSUE TITLE
Extending remote data module

### ISSUE THREAD

**Issue by ayushprd** [PecanProject/pecan#2607]
## Description
Hi everyone, I am opening this issue to discuss the design and implementation of the remote data module.

## Context
The existing data.remote module supports downloading of MODIS and NLCD data. What I have planned is a larger remote data module which has GEE as one of the options but also has the option of using other tools such as AppEEARS etc.

### Module design
I think we have two options here,
1. We can have a standalone module without any PEcAn dependencies which handles the filtering, downloading, conversion of output data in a specific format and a second module which takes this data and inserts it into the PEcAn workflow.
2. A single module which has dependencies with PEcAn and does all of the above.

### Integrating the module with PEcAn workflow
Depending upon the module design we choose, the pecan.xml will have to be configured to hold a `<remotedata>` tag with the following child tags,

- source: The source of the RS data, GEE, AppEEARS etc.
- Radius: Radius of the area of interest.
- Variable: The product or dataset needed.
- Bands: The bands which are required

Date range is already available in pecan.xml and coordinates can be found out by querying the BETYdb for the site id.

Then during the execution of workflow.r, we can check for the remotedata tag in the pecan.xml
`
 if("remotedata" %in% names(settings))
{
 pass settings object and execute remotedata module
} 
`
As explained to me by @istfer this should probably come before the `do_conversions()` step.

### Outputs
The output data which would initially be in a Python dataframe can be converted into a PEcAn standard netCDF or in a format defined in BETYdb so that it is easier to use the data later on.

### Python 
As the GEE API is only available for Python, we will need  `reticulate` to work with the API. Because different versions and methods of Python installation are possible on a computer, reticulate [automatically](https://rstudio.github.io/reticulate/articles/versions.html) selects the appropriate installation based on the first Python package imported, in our case that may be GEE. It is also possible for the user to manually select the appropriate installation.

There are other points as well including the scope of parallel processing, handling of the GEE service account and credentials, which I think I would be able to elaborate more once we decide the initial structure.

**Comment by istfer** [comment]
Thanks @ayushprd, 

Indeed, a larger remote data ingest module which has GEE as one option is what we would prefer. 

### module design:
I think if the module is designed to be stand-alone it could be used by more people. Here I copy-paste an earlier discussion from @ashiklom:

> I’d say we should initially plan on having both---a small and nimble GEE module with the specific goal of downloading and processing data into a standard format, and a data ingest module that takes data in a standard format and adds it to the workflow. If it turns out we only do this for GEE and like one other case, we can merge them down the line.

This could also make it easier to divide and focus on sub-tasks.

### outputs:
I hope this will be straightforward as long as we stick to netcdf. Please check out the [PEcAn standard formats](https://pecanproject.github.io/pecan-documentation/develop/pecan-standards.html) section of the documentation and the links provided in there. 

### python:
I don't have much experience in this but happy to keep testing on my side as you implement the module. Here I copy-paste an earlier discussion from @serbinsh :

> this is a good reason for more self contained in case someone wants to use the functionality for PEcAn but needs to say run it within a conda env to get the data first before running a larger PEcAn workflow, etc

**Comment by ayushprd** [comment]
I understand. I'll focus on a creating standalone module with the GEE option initially, which can download data for a given location and time and convert them to a usable format.

**Comment by ayushprd** [comment]
I think the remote data module is now ready to be integrated and used.
