### ISSUE TITLE
Get working sipnet test for Docker environment

### ISSUE THREAD

**Issue by KristinaRiemer** [PecanProject/pecan#2615]
Currently when I try to run the `docker.sipnet.xml` as described in the **Workflow Submission** section in [DEV-INTRO.md](https://github.com/PecanProject/pecan/blob/f0771aaf6ca9cfc928ce65e7b25033d25a26d7b1/DEV-INTRO.md), it runs up to writing model configs and returns this error: 

```
2020-05-22 20:56:38 INFO   [write.config.SIPNET] :
   Writing SIPNET configs with input /home/carya/sites/niwot/niwot.clim
Error in gsub("@BINARY@", settings$model$binary, jobsh) :
  invalid 'replacement' argument
Calls: <Anonymous> ... <Anonymous> -> do.call -> write.config.SIPNET -> gsub
```

Additionally, when I run this test in localhost RStudio with `../web/workflow.R --settings docker.sipnet.xml`, it fails earlier during settings checking with the following: 
```
Error in postgresqlExecStatement(conn, statement, ...) :
  RS-DBI driver: (could not Retrieve the result : ERROR:  syntax error at end of input
LINE 1: ...arya/sites/niwot' AND file_name='niwot.clim' AND machine_id=
                                                                       ^
)
Warning in postgresqlQuickSQL(conn, statement, ...) :
  Could not create execute: SELECT container_id FROM dbfiles WHERE container_type='Input' AND file_path='/home/carya/sites/niwot' AND file_name='niwot.clim' AND machine_id=
2020-05-22 21:10:55 SEVERE [db.query] :
   Error executing db query 'SELECT container_id FROM dbfiles WHERE
   container_type='Input' AND file_path='/home/carya/sites/niwot' AND
   file_name='niwot.clim' AND machine_id=' errorcode=0 message='ERROR:
   syntax error at end of input LINE 1: ...arya/sites/niwot' AND
   file_name='niwot.clim' AND machine_id= ^ '
        2020-05-22 21:10:55     ERROR
```

I'm not sure if this entirely solves the problem, but it looks like the met file on line 51 of the [docker.sipnet.xml](https://github.com/PecanProject/pecan/pull/2610/files#diff-ccd211712e999b3b935be9a5aa5125cd) at `/home/carya/sites/niwot/niwot.clim` doesn't exist. I don't know how to get this met file, or if there's a different one that should be used for sipnet runs?

**Comment by istfer** [comment]
@robkooper can correct me if I'm wrong, but the file should physically be on the pecan volume you mounted. e.g.
```
  pecan:
    driver_opts:
      type: none
      device: '${PWD}/volumes/pecan'
      o: bind
```
is the example in the documentation. Do you see the files under `${PWD}/volumes/pecan` on your local machine? 

Or when you open up docker-rstudio (http://localhost:8000/rstudio/) do you see the file if you navigate to ` /home/carya/sites/niwot`?

**Comment by istfer** [comment]
That said, in my docker setup I am able to get sipnet run successfully, but I'm not following the steps in [PR#2610](https://github.com/PecanProject/pecan/pull/2610), unfortunately I couldn't get those to work for me. 

I'm saying this because it may help with the debugging, I feel like problem could be that the records (inputs, model binaries etc.) are not being propagated into the betydb correctly. If the file exists `/home/carya/sites/niwot/niwot.clim` (for you, for me it is `/data/sites/niwot/niwot.clim`) in docker-rstudio, but dbfile entry does not exist in the docker-betydb (unlike the ss I have below), this would be an indicator of a db problem I think.
![Screenshot from 2020-05-24 12-35-47](https://user-images.githubusercontent.com/13728388/82750776-272e1c80-9dbb-11ea-8864-d45f5e5484aa.png)

**Comment by robkooper** [comment]
as stated in the pull request it was a quick example, and not ready yet. Next step is to remove all the hard coded paths in the xml file and use the database to fill in the files. As shown in the screenshot the file is there, next is to replace it with the id and remove the path. I think that should be enough.

**Comment by robkooper** [comment]
updated example, try now.

**Comment by dlebauer** [comment]
Lets keep this issue open until someone else can reproduce and it is consistent with documentation ...

**Comment by KristinaRiemer** [comment]
I've gotten this working but with setting met = 99000000003. Still trying to get this working for @kyclark to see if he can use the docker sipnet xml as is.
