### ISSUE TITLE
Using actions/cache instead of artifacts in styler workflow

### ISSUE THREAD

**Issue by rahul799** [PecanProject/pecan#2618]
This is just to pass the names of changed files on to the check step, correct? If so I think `actions/cache` is a better fit than `actions/upload-artifact` -- artifacts are permanent (last I checked there wasn't even a way to delete them manually!) while caches are purged automatically.

_Originally posted by @infotroph in https://github.com/PecanProject/pecan/pull/2569_

**Comment by moki1202** [comment]
@rahul799  would like to take up this issue .can you please help me understand this better?

**Comment by infotroph** [comment]
@moki1202 This was resolved in a recent refactor and we forgot to close the issue. Thanks for flagging it!
