### ISSUE TITLE
model2netcdf.ED2 Fails if  output files missing "AVG_SOIL_TEMP" aka "Soiltemp"

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#2623]
### Bug Description

model2netcdf.ED2 fails if `-T-` file is missing the variable "AVG_SOIL_TEMP", known as "Soiltemp" in the pecan standard.  It fails specifically at [this line](https://github.com/PecanProject/pecan/blob/develop/models/ed/R/model2netcdf.ED2.R#L553). 

### To Reproduce

1. Run met2model.ED2() on an ED2 generated `-T-` file that has no "AVG_SOIL_TEMP" data. 

## Expected behavior

The function's assigning `Soiltemp` the value `-999` would mean that the `.nc` file it produces would have "missing values" of `-999` for Soiltemp. 

## Error message
```
2020-06-02 16:00:40 WARN   [model2netcdf.ED2.R#278: PEcAn.logger::logger.warn] : 
   Could not find AVG_SOIL_TEMP in ed hdf5 output. 
Error in array(0, ncol(soiltemp)) : 'dims' cannot be of length 0
```

## Machine (please complete the following information):

 - Server BU test-pecan, Tess' personal build. Up to date with develop. 

## Additional context

I tried an `if(soiltemp != -999){}` around the code chunk from [line 520](https://github.com/PecanProject/pecan/blob/develop/models/ed/R/model2netcdf.ED2.R#L520) to [line 579](https://github.com/PecanProject/pecan/blob/develop/models/ed/R/model2netcdf.ED2.R#L579), but it messed up the dimensions during the write-out step.

**Comment by mccabete** [comment]
This error is dependent on the output files being written out by the version of ED2 one is using. In my personal branch, I modified (this section)[https://github.com/PecanProject/pecan/blob/develop/models/ed/R/model2netcdf.ED2.R#L285] to check for FMEAN_SOIL_TEMP_PY instead of average values. 

```
CheckED2Version <- function(nc) {
    if ("FMEAN_BDEAD_PY" %in% names(nc$var)) {
      return("Git")
    }
    if ("FMEAN_SOIL_TEMP_PY" %in% names(nc$var)){
      return("Tess")
    }
  }
```

**Comment by mdietze** [comment]
@mccabete I suspect the more general, scalable solution is to check for the presence of the different output variables themselves, rather than checking which ED2 version you were running, with some priority given to one over the other (i.e. check for variable A, if it's not there check for variable B, if it's not there then skip adding that variable to the nc file). Would also be great to see a PR that includes a fix for everyone, not just your personal branch

**Comment by mccabete** [comment]
Can do
________________________________
