### ISSUE TITLE
met2model.ED2 overwites CO2 levels set in ED2IN, possibly also XML

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#2646]
### Bug Description
If you set the `INITIAL_CO2` via the ED2IN, the level of CO2 will be overwritten by the value of CO2 supplied by met2model.ED2. 

Because many met products do not have atmospheric CO2 levels, and ED2 requires atmospheric CO2 be set, the met2model.ED2()[ checks if CO2 exists in the met driver, and if not, adds a set value (380 ppm)](https://github.com/PecanProject/pecan/blob/develop/models/ed/R/met2model.ED2.R#L344). 

This bug is tricky to catch until after ED2 runs and you start plotting the output. 
## Expected behavior

ideally that any pre-set filler values are filled in only if no user-provided value exists

## Additional context

 I suspect that the met2model.ED2() value would override an XML supplied value, but I haven't tested it.

**Comment by mccabete** [comment]
@bcow @istfer @ashiklom, Are any of you feeding initial CO2 values to ED2 via the XML, an do you know if they get overwritten to 380ppm?

**Comment by mccabete** [comment]
OK, looks like CO2 isn't part of the config.xml, but I could imagine incorporating it.

**Comment by mccabete** [comment]
Possible solutions:
- Get rid of the met2model.ED2 check altogether. The ED2IN sets Initial CO2 to 370 by default anyway. (There might be a different reason for the met2model.ED2 check?) 
- Put a NULL value in the ED2IN template, have the config.xml be populated from the ED2IN or by the user, put a check in met2model.ED2 to see if there is a user-supplied value, and if not, supply 380
- add a warning to the met2model.ED2 check

**Comment by istfer** [comment]
Sorry @mccabete I was not initializing CO2 via ED2IN

**Comment by mccabete** [comment]
Hey @istem I'm pretty sure no one does
________________________________

**Comment by Aariq** [comment]
looks like this was closed by #2667
