### ISSUE TITLE
Workflow submission via API Endpoint

### ISSUE THREAD

**Issue by tezansahu** [PecanProject/pecan#2657]
## Description

Submit a PEcAn workflow to get executed using a dedicated PEcAn API endpoint

## Proposed Solution

- Create a `POST api/workflows/` endpoint to allow users to submit PEcAn workflows in the request body
- Cater to workflows submitted as XML & JSON using separate functions
- Submit XML workflows to RabbitMQ after storing them in the database

**Comment by ashiklom** [comment]
I can confirm that this works (_really_ well -- nice work!), at least for submitting workflows based on full XML files.

I am inclined to close this and make the other aspects of the functionality (e.g. workflow from JSON) separate and lower-priority issues.

**Comment by tezansahu** [comment]
The API endpoints for submitting workflow as a JSON have already been developed & merged into `develop` branch by the PR #2674.
Basically it hits the same `POST /api/workflows/` endpoint, but this time with `Content-Type = "application/json"` instead of "application/xml" (which was for the XML file submission)
