### ISSUE TITLE
Roxygen2 v7.1.0 bump

### ISSUE THREAD

**Issue by istfer** [PecanProject/pecan#2685]
We are but it may be time to change that. If someone wants to take it on before I can, the process is basically:

* pick a date for the update and warn everyone
* ideally close out as many open PRs as possible before then, to minimize merge conflicts
* install the newest Roxygen on your dev machine
* git pull, make sure your tree is clean, then `make clean && make document`
* commit all the changed Rd and DESCRIPTION files
* `grep -R 7.0.2 .` -> review, update appropriately, commit. I think at least three scripts `scripts/travis/install.sh`, `.github/workflows/styler-actions.yml`, and `docker/depends/Dockerfile` will need updating, but I may be forgetting others.
* push, review, merge
* remind everyone to update Roxygen on their own machine
* monitor PRs for merge conflicts/accidental reversions (if it edits 300 files, it's probably an accidental reversion)

_Originally posted by @infotroph in https://github.com/PecanProject/pecan/pull/2672_

**Comment by istfer** [comment]
Just created this issue so that @infotroph's helpful comment doesn't get buried. 

It would be nice if we can move from 7.0.2 to the most up-to-date version of Roxygen similar to what has been done [before](https://github.com/PecanProject/pecan/pull/2524)

**Comment by Aariq** [comment]
Currently using v7.1.2 of roxygen2 so closing this
