### ISSUE TITLE
install ssh client in rstudio image

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#2686]
## Description

Adding the ssh client libraries in the base image (or rstudio) will allow developers to push changes to github from inside the docker container (after setting up git correctly).

This will also be needed for remote executions (might need rsync as well).

**Comment by dlebauer** [comment]
@robkooper which Dockerfile? Does it go in https://github.com/PecanProject/pecan/blob/master/docker/depends/Dockerfile?
