### ISSUE TITLE
Additional changes to CSS, PSS, site files required for ED2 integration test to work

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#2696]
Currently the test works but it doesn't pass Kooper's GPP test (GPP != 0 means plants are alive). However, soil respiration is going. Outputs attached for reference: [ed2-out-sa-median_2020-09-25.tar.gz](https://github.com/PecanProject/pecan/files/5287490/ed2-out-sa-median_2020-09-25.tar.gz)

From Juian's comments in #1619:

> OK, I reverted to the EBI Farm test, added the C4 Grass PFT to the `pftmappings` file, and created a GitHub gist ([link](https://gist.github.com/ashiklom/20d6d9a2065f7d32cd5a593b62567773)) containing the revised CSS, PSS, and site files, which @robkooper will need to add to the VM.

While getting the latest ED2 (2.2.0) container working on UArizona HPC we ran into an issue with the ebifarm.lat40.0lon-88.0.site.* files downloaded from here: http://isda.ncsa.illinois.edu/~kooper/EBI/sites.tgz

In the logfile.txt:

```
+ Initializing from ED restart file. Node: 001
 [-] filelist_f: Checking prefix:  /data/sites/ebifarm/ebifarm.
                 Prefix length:       28
 +  Showing all     3 files:
   [-] File #:      1 /data/sites/ebifarm/ebifarm.lat40.0lon-88.0.css
   [-] File #:      2 /data/sites/ebifarm/ebifarm.lat40.0lon-88.0.pss
   [-] File #:      3 /data/sites/ebifarm/ebifarm.lat40.0lon-88.0.site
Using patch file: /data/sites/ebifarm/ebifarm.lat40.0lon-88.0.pss
 ISI           =       2
 CPOLY%NSITES  =       1
 IP            =       1
 CPOLY%SITENUM =       1
 Patch file    =  /data/sites/ebifarm/ebifarm.lat40.0lon-88.0.pss
 Site number  2002 
(... about 3330 lines of NULL/binary data...)
0 not found!
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
--------------------------------------------------------------
                     !!! FATAL ERROR !!!                      
--------------------------------------------------------------
    ---> File:        ed_history_io.F90
    ---> Subroutine:  read_ed10_ed20_history_file
    ---> Reason:      Error reading from patch file
--------------------------------------------------------------
 ED execution halts (see previous error message)...
--------------------------------------------------------------
STOP fatal_error
ERROR IN MODEL RUN
Logfile is located at '/data/tests/ed2/out/SA-median/logfile.txt'
************************************************* End Log 2020/09/17_19:17:05
```

When we replaced these files with the ones from @ashiklom's [gist](https://gist.github.com/ashiklom/20d6d9a2065f7d32cd5a593b62567773) it worked.

I think @robkooper might have to replace these files in the sites.tgz with the ones from the gist, but I'm out of my depth. Could @dlebauer and/or @KristinaRiemer please chime in and confirm whether this is correct, and if so create an issue which captures the true problem?

_Originally posted by @julianpistorius in https://github.com/PecanProject/pecan/pull/1619#issuecomment-699215913_

**Comment by dlebauer** [comment]
I've downloaded the sites.tgz, replaced the pss, css, site files w/ the ones in Alexy's gist, and re-compressed it to a .tgz

@robkooper all that should be required to resolve this issue is for you to replace http://isda.ncsa.illinois.edu/~kooper/EBI/sites.tgz 
with this file:
https://arizona.box.com/s/zf6avip1m94cqn7f9awfmaa9gwnxvyto

**Comment by robkooper** [comment]
please check, should be done.
