### ISSUE TITLE
broken links to documentation in the GitHub readme

### ISSUE THREAD

**Issue by zmoon** [PecanProject/pecan#2697]

**Comment by dlebauer** [comment]
thanks for reporting this @zmoon ! I've created a PR #2698 to fix this. In the meantime you can find the latest documentation here: https://pecanproject.github.io/pecan-documentation/develop/

**Comment by zmoon** [comment]
@dlebauer sorry I should have pointed them out. That was not the only one. There are more, including:
* one in "Getting started"
* one in "Installation"
