### ISSUE TITLE
Scrape Ameriflux sites -> new BETY sites

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#271]
We need to be able to grab site info (names, codes, lat/lon, etc) off the Ameriflux and FLUXNET pages and use that to create new BETY sites. This script will need to check the existing sites to make sure we don't create duplicates. It would be something that would be good to run periodically to catch new sites as they join the Ameriflux network.

Could start with something like...

library("RCurl")
library("XML")
FLUXNET_html <- getURL("http://fluxnet.ornl.gov/site_status")  ## grab raw html
FLUXNET_table = readHTMLTable(FLUXNET_html)[[1]]    ##grab first table on the webpage

It is safe to assume any site with a code starting US- is part of Ameriflux (though there are a few other non-US sites in Ameriflux). From the Fluxnet page we would have to recurse to the individual site pages to get the lat/lon. The Ameriflux sites are listed at: 

http://ameriflux.lbl.gov/sites/site-list-and-pages/

and have all the relevant site info right there, but they're formatted in a different way that's beyond my rudimentary web-scraping skills.

**Comment by robkooper** [comment]
Still need the table.

**Comment by dlebauer** [comment]
What would the sitenetworks table look like? Could it be handled by the sitename field in the sites table if network sites were consistently named, such as "<sitename>: <network> <network-ID>", which would rename "Sylvania Wilderness (US-Syv)" to "Silvania Wilderness: Ameriflux US-Syv"?

**Comment by robkooper** [comment]
no for two reasons, we should not overload the sitename with metadata, and we should also have the ability to have multiple different site network table associated with the same site.

**Comment by ankurdesai** [comment]
For example,
WillowCreek is part of ChEAS, Ameriflux, and Fluxnet, not to mention the U.S. Forest service climate tower network and within the Neon Great Lakes domain, and so on. It would be highly useful to subset sites by network/domains for various types of runs and science questions (eg observing system simulation experiments, regions, runs based on data availability). This would also be one way to make it easier to tie in data policies by network to sites. 

Ankur Desai, UW-Madison
 +1-608-218-4208 [mobile]
