### ISSUE TITLE
met data should be 3-D arrays

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#276]
Convert the internal representation of site-level meteorology (e.g. Ameriflux) to be a lat/lon/time grid rather than a vector with dimension time. At the same time, make sure the time dimension is named correctly.

**Comment by jam2767** [comment]
All site-level (Ameriflux) met variables are on a lat/lon/time grid, with three exceptions that were discussed. The variable "Time" only has dimension time. The variables for latitude and longitude also only have spatial dimensions (lat/lon) and no time dimension.
