### ISSUE TITLE
fix undeclared dependencies in /base/db package

### ISSUE THREAD

**Issue by moki1202** [PecanProject/pecan#2804]
###DESCRIPTION

Currently PEcAn.MA ( 'meta.analysis' ) remains undeclared in the /base/db package. It's being used by db functions in the following files -

1. \db\man\rename_jags_columns.Rd 
2. \db\R\rename_jags_columns.R
3. \db\tests\Rcheck_reference.log

before releasing this package to CRAN, all undeclared dependencies must be removed.

###PROPOSED SOLUTION

Move  'rename_jags_columns' to 'PEcAn.MA'

**Comment by mdietze** [comment]
I'm OK with moving rename_jags_columns to MA if that's the only package using the function

**Comment by robkooper** [comment]
I agree, i don't think it makes sense for it to be in the db package, since it does not interact with the DB.
