### ISSUE TITLE
Move read.sa.output & write.sa.configs to uncertainty package

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#2856]
Left over from #2830: We were intending to move all the functions from sensitivity.R out of utils and into uncertainty -- I want to say we only left them unfinished because the changeset was getting out of hand and we wanted to merge while it was working. @moki1202 does this match your memory?

**Comment by infotroph** [comment]
This is yet another task that's been hiding forever in the comments of #1681, which we're now very close to finishing!

**Comment by moki1202** [comment]
@infotroph just checked! silly me thought that I had already moved it. I'll get on it.

**Comment by infotroph** [comment]
@moki1202 Since #2854 touches a bunch of files in utils, I recommend starting your work on moving sensitivity from a branch started at the current tip of my 'utils-doc-tweaks' branch -- that doesn't completely remove the chance of merge conflicts but it should minimize it

**Comment by infotroph** [comment]
Fixed by #2857
