### ISSUE TITLE
update download.amerfluxLBL to new end point and JSON query

### ISSUE THREAD

**Issue by ankurdesai** [PecanProject/pecan#2860]
download.AmerifluxLBL needs to be updated with a new endpoint and some changes to JSON query, email from Ameriflux - will update as I get more info.

From: ycheah@lbl.gov 

I believe you are the contact for PEcAn given the email (professorankurdesai@gmail.com), and if not kindly point me to who is managing the PEcAn services. 

We are overhauling our Web service stack, and the download service will be available via a different endpoint, with a slightly different payload and response (nothing major). This is due in part to the support of the newer CC-By4.0 policy as well. 

The new service will be available via https://amfcdn.lbl.gov/api/v1/data_download and the payload will be something like the following (everything in the json after the -d flag in the sample curl request):

curl -X POST -d '{"user_id": <user_id>, "user_email": <email>, "data_product": <BASE-BADM|FLUXNET2015|FLUXNET-CH4>, "data_variant": <FULLSET|SUBSET> (optional for BASE-BADM), "data_policy": <CCBY4.0|LEGACY|TIER2> (Tier2 for FLUXNET products, LEGACY for BASE_BADM, "site_ids": ["site_id1", "site_id2", ...], "intended_use": <One of the intended use similar to the ones on the download page>, "description":<some description>, 
"is_test": true (optional argument for testing purposes of the service, download emails will not be sent to site teams)}' https://amfcdn.lbl.gov/api/v1/data_download 

It will probably also be necessary to let us know the request IP/domain for where the requests will be coming in so that we can identify valid sources.

Please let us know if you need further assistance and we will work with you or someone else to continue providing access to AmeriFlux data products.

**Comment by ankurdesai** [comment]
Relevant lines in modules/data.atmosphere/R/download.AmerifluxLBL

url <- "http://wile.lbl.gov:8080/AmeriFlux/DataDownload.svc/datafileURLs"
  json_query <- paste0("{\"username\":\"", username, "\",\"siteList\":[\"", site, "\"],\"intendedUse\":\"Research - Land model/Earth system model\",\"description\":\"PEcAn download\"}")
  result <- httr::POST(url, body = json_query, encode = "json", httr::add_headers(`Content-Type` = "application/json"))
  link <- httr::content(result)
 

What I don't know yet: when this changeover happens. What do to about the data policy part of the query. Emails pending.

**Comment by ankurdesai** [comment]
Hi Ankur,

Thank you for clarifying. There is another piece that I neglected to provide you to figure out which sites have what data policies. The policies are actually associated per site rather than per site year, though you can have this information both ways. The following endpoints should provide those:
https://amfcdn.lbl.gov/api/v1/site_availability/AmeriFlux/BASE-BADM
https://amfcdn.lbl.gov/api/v1/data_availability/AmeriFlux/BASE-BADM/CCBY4.0
https://amfcdn.lbl.gov/api/v1/data_availability/AmeriFlux/BASE-BADM/LEGACY 
As for identification purposes, we will just use the user_id to make an exception that it is from Pecan. The source is mainly required to send the correct emails to different mailing lists, but given that only AmeriFlux data is used in this case, we can just tie it down to the AmeriFlux side.

Apologies that this came as an oversight, but the change is quite immediate. Due to the various pieces involved with tracking and supporting the new data policy, we have had to move exclusively to the new endpoint, the previous endpoint currently just returns a message to contact ameriflux-support. We are still trying to track other intermediaries that provide data to users, since we do not maintain a list. I realized this came out of the blue, so if you need any active help in making the adjustments quickly, I am willing to work with you all so that data continues to be accessible via Pecan.

Best, -- You-Wei

**Comment by istfer** [comment]
Hi Ankur et al.,

Is there any development regarding this? I am not sure what the query should be like, as pecan do we have a `user_id`? Is it the same as `user_name`? On the [download website](https://ameriflux.lbl.gov/data/download-data/) there are only 2 sites in FLUXNET product, all the others are in BASE so I assume `data_product=BASE-BADM` for us. What is the `site_id`? For US-NR1 is it the bit at the end of the [doi](https://doi.org/10.17190/AMF/1246088), e.g. 1246088?

```
curl -v -X POST \
-F 'user_name=pecan' \
-F 'data_product=BASE-BADM' \
-F 'data_variant=FULLSET' \
-F 'data_policy=TIER2' \
-F 'site_ids=["1246088"]' \
-F 'intended_use=Research - Land model/Earth system model' \
-F 'description=PEcAn download' \
-F 'is_test=true' \
-F 'user_email=' \
'https://amfcdn.lbl.gov/api/v1/data_download'
```

**Comment by istfer** [comment]
Hi, @henrikajasilta and I will be working on this issue using the [amerifluxr](https://github.com/chuhousen/amerifluxr) package, but we weren't sure what to pass as pecan user email, do we want a generic pecan user or do we assume each user has their own credentials (then we also probably need to prompt for email on the UI)? @ankurdesai @robkooper any thoughts?

**Comment by ankurdesai** [comment]
If you look in https://github.com/PecanProject/pecan/blob/develop/modules/data.atmosphere/R/download.AmerifluxLBL.R the username is set to "pecan" - turns out no password is actually needed in the original API.

**Comment by ankurdesai** [comment]
Also re November query - yes, BASE is what we want, not sure if BASE_BADM would load just the ancillary data or both. Usually it comes all as a ZIP file. I would assume site-id is just site code like US-NR1. It may take some trial and error, but definitely feel free to reach out directly to  ycheah@lbl.gov if query is failing.
