### ISSUE TITLE
virtualbox password

### ISSUE THREAD

**Issue by fabeit** [PecanProject/pecan#290]
Hello,

I am trying to use the pecan VM version 1.4 to run ED on an area that it's outside the sites already included, so I would like to login ubuntu but the user/password combination "pecan" does not work. What is the password for the 64 bit VM?

thanks

**Comment by fabeuw** [comment]
thank you for the feedback, I have opened a specific question. I cannot find the load.sites.sh file, I only see the add.data.sh, has the name changed?
thank you

**Comment by robkooper** [comment]
Correct the file now called add.data.sh since that is more generic.

**Comment by mdietze** [comment]
The only place on the wiki that references load.sites.sh is https://github.com/PecanProject/pecan/wiki/Installing-PEcAn#install-database--data
@fabeuw are these the instructions you were following?

@robkooper could you update that page
