### ISSUE TITLE
Simplify local installation with r-universe

### ISSUE THREAD

**Issue by Aariq** [PecanProject/pecan#2941]
## Description

Currently local installation of PEcAn is difficult, even for an advanced R user.  It took me probably 4 hours to get it up and running on a blank slate server.  I believe that hosting PEcAn packages on a CRAN-like repository would simplify things and ease the transition to CRAN as well.  [r-universe](https://ropensci.org/blog/2021/06/22/setup-runiverse/) offers automatic building and hosting of R packages from GitHub to a CRAN-like repo.  I've tested this minimally with two PEcAn packages---PEcAn.logger, which has dependencies that are all on CRAN, and PEcAn.remotes which depends on PEcAn.logger.  You can see them on my personal r-universe at [aariq.r-universe.dev](https://aariq.r-universe.dev/ui#builds) and view installation instructions there:

```
# Enable repository from aariq
options(repos = c(
  aariq = 'https://aariq.r-universe.dev/',
  CRAN = 'https://cloud.r-project.org/'))
# Download and install PEcAn.remote in R
install.packages('PEcAn.remote')
```

I've tested this install and it works even though I don't have `PEcAn.logger` installed.  It finds the dependency on the r-universe and installs it with no issues.

## Steps

To get this working at an organization level I believe you'd need to follow these steps:

1. Enable r-universe to access the PecanProject organization's repos
2. Create a PecanProject/universe repo with a `packages.json` file that looks something like this:

```
[
  {
    "package": "PEcAn.logger",
    "url": "https://github.com/PecanProject/pecan",
    "subdir": "base/logger"
  },
  {
    "package": "PEcAn.remote",
    "url": "https://github.com/PecanProject/pecan",
    "subdir": "base/remote"
  }
]
```

... with all the PEcAn packages in it.  This could likely be created programmatically and updated via a github action in the monorepo (eventually).

3. Trigger re-builds of packages on pecanproject.r-universe.dev until they all work since I don't think there is a way to specify the order for r-universe to try building them.  For example, in my minimal example `PEcAn.remote` build failed because the `PEcAn.logger` build hadn't finished and wasn't yet on aariq.r-universe.dev.

I think that's it!  Then people *should* be able to install `PEcAn.all` just by using `install.packages('PEcAn.all', repos = c('https://pecanproject.r-universe.dev/', getOption("repos"))`.  You could also add the r-universe to the DESCRIPTION file YAML as an alternative repo (can't remember the exact way to do this, but I'm pretty sure it's a thing you can do).

**NOTE**: this will obviously only work if all the dependencies of `PEcAn.all` can be found and built successfully.

**Comment by Aariq** [comment]
You also get some CI testing as a bonus.  E.g. I can see that some `PEcAn.remotes` tests are currently failing on Windows: https://github.com/r-universe/aariq/actions/runs/2529528495

**Comment by robkooper** [comment]
https://github.com/PecanProject/universe

**Comment by dlebauer** [comment]
This is really awesome, thanks Eric and Rob!

**Comment by robkooper** [comment]
All credit to @Aariq 

Closing issue, see https://pecanproject.r-universe.dev/ui#packages

**Comment by dlebauer** [comment]
follow up: https://github.com/PecanProject/pecan/issues/2946
