### ISSUE TITLE
Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#298]
GitHub recognizes such a file and points new users here when they open an issue or submit a pull request (described in [this Github Blog post](https://github.com/blog/1184-contributing-guidelines))

### Motivation

The motivation of this is to support the sustainable development of PEcAn, and to provide clear guidelines for contributing. A clear, public definition of standards and expectations for contributing should make the process of contributing easier. 

The rules can be based on practices that are known to produce more reliable and useful code with less effort. For example, [Wilson and others from Software Carpentry Foundation](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745) provide a widely read "Best Practices for Scientific Computing" overview:

![image](https://cloud.githubusercontent.com/assets/464871/7591850/c28a14b6-f895-11e4-873c-68d249e7ca45.png)

I propose that the contributing guidelines be aimed to support the rules that are described in this paper: 

![image](https://cloud.githubusercontent.com/assets/464871/7592695/69205520-f89a-11e4-9cae-414f88dceee1.png)

### Proposed Contents of the PEcAn Contributing.md

Much of the proposed content is in the wiki - the Contributing.md file can provide an annotated list (outlined as draft below) with links to the documentation.

* Code of conduct ([wiki](https://github.com/PecanProject/pecan/wiki/Code-of-Conduct))
* Code review checklist, e.g. https://khmer.readthedocs.org/en/latest/dev/coding-guidelines-and-review.html
* How to report bugs and request features ([wiki](https://github.com/PecanProject/pecan/wiki/Github-issues))
* Git Flow including forking, pull requests ([wiki](https://github.com/PecanProject/pecan/wiki/Github-issues))
  * what is required for a pull request to be accepted
  * what pull requests can be marked as 'trivial' (and excused from some or all of the issues below)
  * an issue (either a github issue number or a description of the problem being solved)
    * code review by 2 or more contributors
    * naming, syntax, whitespace,  [wiki](https://github.com/PecanProject/pecan/wiki/Coding-style) based on [Hadley's guide](http://adv-r.had.co.nz/Style.html) that is supported by Rstudio v>0.99
     * under what conditions are documentation, examples, tests required  
      * documentation, examples ([wiki](https://github.com/PecanProject/pecan/wiki/Roxygen2))
      * tests ([wiki](https://github.com/PecanProject/pecan/wiki/Testing))
  * for new functions: how is it used? should it be exported / available to the public? which package does it belong in?
* License ([link][https://github.com/PecanProject/pecan/blob/master/LICENSE])
* Maintainers: Dietze, Kooper, LeBauer w/ github username and email

### Examples of other Contributing.md files:
* https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md
* Template: https://github.com/anselmh/CONTRIBUTING.md
* khmer contributing guidelines https://khmer.readthedocs.org/en/latest/dev/

**Comment by robkooper** [comment]
Please feel free to update, I really wanted to add some text on how to use the PEcAn VM and set it up so people can start to add new code. This section was the most important for me https://github.com/PecanProject/pecan/blob/master/CONTRIBUTING.md#getting-started
