### ISSUE TITLE
GitHub actions hitting rate limits because usage of PAT not configured

### ISSUE THREAD

**Issue by Aariq** [PecanProject/pecan#2986]
I keep seeing the CI tests fail because of rate limit errors with suggestions to use a GitHub PAT.  Looks like the actions aren't currently using the PAT correctly.  In actions/checkout@v3:

># Personal access token (PAT) used to fetch the repository. The PAT is configured
    # with the local git config, which enables your scripts to run authenticated git
    # commands. The post-job step removes the PAT.
    #
    # We recommend using a service account with the least permissions necessary. Also
    # when generating a new PAT, select the least scopes necessary.
    #
    # [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    #
    # Default: ${{ github.token }}
    token: ''

In our YAML files `token` is not provided and the PAT is stored in `GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}` which might be why this isn't using the PAT

**Comment by infotroph** [comment]
Can you link to some of the failing runs? We've definitely struggled with it before but I thought I'd fixed the previous round and it's been quite a few months since I noticed any CI messages about it

**Comment by Aariq** [comment]
I actually don't see any right now.  It's possible that they automatically re-run since the issue is on GitHub's end.  I'll keep an eye out.

**Comment by Aariq** [comment]
haven't seen this in a while so I'll close for now

**Comment by Aariq** [comment]
Here's an example.  Looks like the `GITHUB_PAT` environment variable isn't being accessed by `install_github()` inside of `pecan.depends.R`
![Screen Shot 2022-09-06 at 10 40 57 AM](https://user-images.githubusercontent.com/25404783/188666725-97e9b978-c273-4659-ba15-b81bd970ffa0.png)

**Comment by infotroph** [comment]
I'm a bit puzzled, but I think the error message is misleading here: Best I can tell, the token is being found and used correctly -- the 1000 request limit is [for requests _with_ a token](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#requests-from-github-actions). Maybe `remotes` just assumes any error with "rate limit exceeded" should get the PAT setup hint?

But more fundamentally: How in blazes are we managing to make 1000 requests in an hour?

**Comment by Aariq** [comment]
Yeah, I had the same thought---that maybe the error message from `install_github()` is the same if the rate limit is exceeded whether or not the PAT is set correctly.

**Comment by Aariq** [comment]
Another one, from a different script:
https://github.com/PecanProject/pecan/runs/8209891155?check_suite_focus=true
![Screen Shot 2022-09-06 at 12 16 16 PM](https://user-images.githubusercontent.com/25404783/188685537-ec4de2fb-1d76-40bd-b5bd-12380ac1007a.png)

**Comment by Aariq** [comment]
Might be good to add a caching step, whether or not that would fix this particular issue. https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

**Comment by infotroph** [comment]
I think I see it: 
* ` make install` calls `devtools::install` on every package
* `devtools::install` calls `remotes::install_deps` under the hood
* `install_deps` checks for new versions of packages, even if they're already installed and `upgrade = FALSE` (grr)
* Therefore every CI job hits every remote at least once for every PEcAn package that uses it
* But it's worse because our `make` *also* has its own dependency check step, which goes to some lengths to avoid unnecessary remote queries but `devtools::install` insists on duplicating its work.

I think we may be able to force `install` to skip the dep check by passing `dependencies = FALSE` on line 76 of the Makefile:
```
- 	-e "devtools::install('$(strip $(1))', upgrade=FALSE)"
+ 	-e "devtools::install('$(strip $(1))', dependencies=FALSE, upgrade=FALSE)"
```

**Comment by Aariq** [comment]
I think you want it to always be checking for new versions of packages.  The two problems I see are 1) packages aren't being cached so they get downloaded every time and 2) both individual packages and `make` are installing dependencies.  The second problem might be somewhat solved by caching also?

**Comment by robkooper** [comment]
I'd love to find a good way to have a requirements like file that has all the versions of the files needed. that way we can have an action that checks to see if there is a newer version of the package and make PR that will list the updated packages.

**Comment by Aariq** [comment]
The other benefit of having a .yml file for each package is that each package can have its own badge in the README

**Comment by Aariq** [comment]
I think we found where the GitHub PAT wasn't getting passed to actions in #3083.  The rate limit is being exceeded still sometimes, but it's the authenticated rate limit, so I'll go ahead and close this issue.
