### ISSUE TITLE
Don't use `testthat` inside of functions

### ISSUE THREAD

**Issue by Aariq** [PecanProject/pecan#2987]
### Bug Description

The `testthat` package is made for unit testing, not use inside of functions.  `testhat` functions appear in at least a couple of places:
- `check_ed_metheader()`
- `check_ed_metfile()`

These should be replaced with calls to `stopifnot()` or something from the `assert` or `assertthat` packages

**Comment by Aariq** [comment]
Other places:
- `PEcAn.atmosphere::check_met_input_file()`
- `PEcAn.atmosphere::check_unit()`

**Comment by Aariq** [comment]
Partially fixed by #3016

**Comment by Sarthakaga15** [comment]
Hi @Aariq , can I please work on this issue?

**Comment by moki1202** [comment]
@Sarthakaga15 there's one more instance that you can work on, in `./models/ed/R/write_ed_veg.R`. if you need any further help on this, let me know.
