### ISSUE TITLE
Edit PR template to remind to run checks locally

### ISSUE THREAD

**Issue by Aariq** [PecanProject/pecan#2988]
## Description

Now that pecanproject.r-universe.dev exists, it *should* be easier to run `devtools::check()` locally.  For `devtools` to install all the dependencies of a particular package it just needs to know about r-universe in .Rprofile (added in #2985).  `devtools::install_deps()` should work now.

## Proposed Solution

Add checkbox:
- [ ] I have run `devtools::check()` locally, e.g. `devtools::check("models/ed")` and resolved any errors and warnings.

**Comment by Aariq** [comment]
I guess this isn't in there because only *new* check problems are expected to be fixed on PRs.

**Comment by infotroph** [comment]
If you want to keep this, a local `make check` calls `scripts/check_with_errors.R` and therefore only stops on new errors/warnings/notes. So the checkbox could be something like "I have run `make check` locally..."

But TBH it seems like most of us have been completely ignoring the PR template (I sure know I have 🙈), so is it still useful to have?
