### ISSUE TITLE
Give packages their own READMEs

### ISSUE THREAD

**Issue by Aariq** [PecanProject/pecan#3043]
As part of prepping packages for CRAN and/or splitting off into their own repos it might be good to make sure each individual package has its own README.  An example pattern to add a template README with a lifecycle badge:

```
library(usethis)

with_project(path = "models/ed", {
  use_readme_md()
  use_lifecycle_badge(stage = "experimental")
}, force = TRUE)
```

**Comment by meetagrawal09** [comment]
I would like to work on this issue.
