### ISSUE TITLE
After updating to new docker-compose.yml (develop) and docker images, Pecan/BETYdb web interface is no longer available

### ISSUE THREAD

**Issue by Chris-Schnaufer** [PecanProject/pecan#3062]
### Bug Description
BETYdb web interface is no longer available on port 8000 after updating to new docker-compose.yml and docker images (pecan/*:develop, and latest for non-pecan images)

### To Reproduce
Downloaded new docker images and run using new docker-compose.yml file (https://github.com/PecanProject/pecan/commit/41a3e2fa8aa4f8688dadb71d8884eeba867bd980)

## Expected behavior

The BETYdb web interface would still be available

## Screenshots

N/A

## Machine (please complete the following information):

 - VM
 - OS: Ubuntu
 - Version: development

## Additional context
I believe this is related to the following PR: https://github.com/PecanProject/pecan/pull/2936

**Comment by Aariq** [comment]
related to #2955 ?

**Comment by Chris-Schnaufer** [comment]
> related to https://github.com/PecanProject/pecan/issues/2955 ?

Yes, I think that one as well

**Comment by robkooper** [comment]
what is the exact url you are using to access the bety website?

**Comment by Chris-Schnaufer** [comment]
http://<machine name>.cyverse.org:8000/ (gets me a `404 - page not found` message). Other approaches to the URL are ignored

**Comment by KristinaRiemer** [comment]
Hi! @robkooper & @Chris-Schnaufer, has there been any progress on figuring out why our Bety website instance isn't working?
