### ISSUE TITLE
display data use agreements

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#309]
As we start to download and process Inputs automatically, we need a mechanism to inform end users of any licenses or policies surrounding the use of data or data products, preferably before the download the data.

Extra cool would be to also drop a copy of all licenses into the output directory for future reference (and make sure this is someplace that will come up in the web interface)

**Comment by robkooper** [comment]
Do we want this to happen only in the web interface or both in the web interface and regular workflow.R?

**Comment by dlebauer** [comment]
I'd say that we should definitely make users aware of use restrictions
using workflow.R, at least both using logger.info and by placing copies
alongside the inputs.

If we are providing data that has use restrictions via BETYdb, then it
seems that each input record in BETYdb should be linked to any such
documents.

**Comment by mdietze** [comment]
I was actually more concerned about users of the web interface, since from that perspective it is much easier to download new data without visiting the page of the original source, and I think ultimately more users will be using the web page than the command line.

**Comment by robkooper** [comment]
See http://ameriflux.lbl.gov/resources/logos-acknowledgments/ for Ameriflux

**Comment by robkooper** [comment]
Add text from data agreement for both NARR and Ameriflux.
