### ISSUE TITLE
isFALSE exists in base, don't need to have our own version

### ISSUE THREAD

**Issue by Aariq** [PecanProject/pecan#3102]
https://github.com/PecanProject/pecan/blob/353b4dd2eb632f5509a4dae56b6ca388c41873d8/base/utils/R/utils.R#L417

This line should be removed as base already has an `isFALSE()` function.

**Comment by Its-Maniaco** [comment]
@Aariq can you please assign me this issue?

**Comment by abhinav52000** [comment]
Is this still open to be solved if so kindly assign it to me

**Comment by Its-Maniaco** [comment]
Sorry! Had to close #3113 Messed up pull request.

**Comment by abhinav52000** [comment]
Thank you for merging the pull request.
