### ISSUE TITLE
remove obsolete scripts/qsub_build.sh

### ISSUE THREAD

**Issue by Waer1** [PecanProject/pecan#3133]
### Bug Description

qsub_build.sh uses install.dependencies.R which is no longer there, It should use install_pecan.sh instead as I thought

https://github.com/PecanProject/pecan/blob/develop/scripts/qsub_build.sh
### To Reproduce

Steps to reproduce the behaviour:
1. Go to ' https://github.com/PecanProject/pecan/blob/develop/scripts '
2. Click on 'qsub_build.sh'

**Comment by AdarshSahani003** [comment]
I’d like to work on this issue, is anyone currently working on it?

**Comment by infotroph** [comment]
@AdarshSahani003 Go for it! I think the correct resolution is a PR that simply deletes qsub_build.sh and then states in the PR description how you confirmed that it's not used anywhere else in the repo.

**Comment by harshagr70** [comment]
@infotroph hey !! since there is no updates on this i thought to raise a PR that fixes this particular issue , kindly review it and suggest any changes if needed , i will also attach a detailed description in the PR about why the script is obsolete . Thank you !!
