### ISSUE TITLE
Pecan web interface has soil and veg inputs backwards

### ISSUE THREAD

**Issue by ryankelly-uiuc** [PecanProject/pecan#314]
Using Pecan web interface to run ED2 on pecan2.bu.edu, the soil input lists only "OGE2_" and veg lists only "FAO_". These are backwards, however. 

This somehow doesn't stop ED2r82 from running, but it does cause an error in the github version of ED.

**Comment by mdietze** [comment]
You should be able to fix that just within the database records without having to change the code.

**Comment by ryankelly-uiuc** [comment]
I thought that might be the case, but I couldn't find where these are hiding in the database (still getting some intermittent "We're sorry..." errors when searching, which didn't help)

**Comment by ryankelly-uiuc** [comment]
Wait, found them... will fix now.

**Comment by dlebauer** [comment]
@ryankelly-uiuc if you keep running into these searching errors, can you please report them as an issue in the PecanProject/bety repository?

If possible, please include the output produced in `log/production.log` (on ebi-forecast this is in  `/usr/local/ebi/log/production.log`)

**Comment by ryankelly-uiuc** [comment]
This seems to be an issue on one of the BU servers only, so we've been discussing it offline.
