### ISSUE TITLE
Merge queue creates spurious tag dirs in documentation repo

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#3152]
### Bug Description

<img width="1100" alt="Screen Shot 2023-03-29 at 11 08 37 PM" src="https://user-images.githubusercontent.com/1256435/228747921-926210be-fd3b-4d97-bbf2-5fbc80c79c50.png">

The proximal culprit seems to be [line 67 of book.yml](https://github.com/PecanProject/pecan/blob/develop/.github/workflows/book.yml#L67), which assumes any ref with a slash in it must be a tag. But it's possible we need to instead/additionally tweak the conditions under which the deployment is triggered (possibly `if: github.event_name == 'push'` instead of `if: github.event_name != 'pull_request'`?)

**Comment by chethanagopinath** [comment]
Hi, this is my first time contributing to this repo. Could I pick this one up?

**Comment by mdietze** [comment]
@chethanagopinath Yes please, that'd be great

**Comment by chethanagopinath** [comment]
@mdietze just had some context questions to start:
1. Looking at the documentation repo, is it complete setup and context documentation for each version? 
2. Also wondering when we would want to update that documentation repo?  

Thanks.

**Comment by infotroph** [comment]
1. Yes, the documentation repo contains compiled versions of the manual for the entire PEcAn system (as opposed to the R function docs for individual packages, which live in the PEcAn repo). There is a version (each in its own folder) to correspond to each tagged release of PEcAn plus the up-to-the-minute `develop` version.
2. This repo is automatically updated (By GitHub Actions via [book.yml](https://github.com/PecanProject/pecan/blob/develop/.github/workflows/book.yml)) every time we merge changes to a corresponding branch/tag of the PEcAn repo. The problem is that GitHub's new and very handy "merge queue" feature creates a lot of temporary branches that don't need  to be preserved as artifacts, so the task here is to find the cleanest way for this deployment script to ignore temporary references like the merge queue branches without missing tags that need preserving.

**Comment by harshagr70** [comment]
Hey !! i want to work on this issue .. can i proceed ??

**Comment by infotroph** [comment]
@harshagr70 Yes, please do! Let us know if you need more info.

**Comment by RohanSasne** [comment]
@harshagr70 , if you need any help, be sure to ping me on slack, also read #3216 as both are related :)

**Comment by harshagr70** [comment]
> @harshagr70 , if you need any help, be sure to ping me on slack, also read #3216 as both are related :)

Sure thing !! We can definitely discuss it !!

**Comment by infotroph** [comment]
@Sweetdevil144 Yes, I think this is the right approach. 

We do also want to deploy on every push to `develop` or `master` -- will your proposal do that already or will we ned to add those explicitly? And am I right that adding it explicitly would be a matter of matching on any of `refs/tags/`, `refs/heads/master`, `refs/heads/develop`?

**Comment by Sweetdevil144** [comment]
Hey!

You're spot on. My proposal was primarily focused on the tagging issue, but we definitely need to ensure that pushes to `develop` and `master` trigger deployments as well. To achieve this, we can extend the conditional to include those branches explicitly. Here’s how we could adjust the workflow to handle it:

```yaml
on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'
```

And for the deployment step, we could indeed match explicitly like this:

```yaml
if: >
  github.event_name == 'push' && 
  (startsWith(github.ref, 'refs/tags/') || 
  github.ref == 'refs/heads/master' || 
  github.ref == 'refs/heads/develop')
```

Now, I'm not that good when dealing with `yaml` files but this should cover our bases for both tag creation and direct pushes to `master` and `develop`. Does this align with our deployment strategy, or are there additional scenarios we need to account for? I'll need to have a complete overlook upon the workflow for more information. If I'm missing something, do correct me please.

Thanks for the guidance!

**Comment by infotroph** [comment]
@Sweetdevil144 Thanks for the detailed proposal! I think what you wrote there is very close to being the whole patch needed -- would you like to open a PR that makes those changes in book.yml?

**Comment by Sweetdevil144** [comment]
Hey @infotroph , did you confirm all the strategies. Rest of work is done and I'm ready to draft a PR !! ^^

**Comment by infotroph** [comment]
I've confirmed these are all the strategies we use at the moment, so go ahead with the PR--we can always add more later when we discover we need them.

**Comment by Sweetdevil144** [comment]
@infotroph Created a PR for the same!!
Do remind me if any further changes need to be made!!

**Comment by PoppingPixel9** [comment]
Closed
