### ISSUE TITLE
S

### ISSUE THREAD

**Issue by silver6633** [PecanProject/pecan#3182]
## Description

**Is your feature request related to a problem? Please describe.**

## Proposed Solution

**Describe the solution you'd like**

## Alternatives Considered

**Describe alternatives you've considered**

**Comment by Aariq** [comment]
I'm going to assume this issue was opened by accident and close it.

**Comment by infotroph** [comment]
No, as far as we know PEcAn is not [compatible with S](https://twitter.com/WhyDoesR/status/1640715472621694976).
