### ISSUE TITLE
Any way to indicate that jobs should be qsubbed from the web interface?

### ISSUE THREAD

**Issue by rykelly** [PecanProject/pecan#320]
When I start a job through the web interface it never receives a <qsub> tag in the pecan.xml file, so later in the workflow read.settings assumes that qsub isn't going to be used. Seems like maybe we would want certain hosts to default to using qsub though.

**Comment by robkooper** [comment]
The logic is that if you use localhost it will assume no qsub, unless you explicitly say so. If you give it a remote host it will assume qsub by default.

**Comment by ryankelly-uiuc** [comment]
Makes sense but I don't think it's working that way. As far as I can tell whether or not to use qsub gets decided in `check.settings` (read.settings.R, L572), based only on whether `settings$run$host$qsub` exists. But if I start a job from e.g. the pecan2.bu.edu web interface and select geo.bu.edu as my host, then no qsub tag gets created in pecan.xml, and the relevant code in `check.settings` doesn't get triggered.

**Comment by ashiklom** [comment]
Based on my refactor of PEcAn.remote (#1665, #1701), I think this should have been resolved, so closing.
