### ISSUE TITLE
Add ID to many-many tables

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#325]
To be able to sync correctly we need an ID field to know who added that specific row in many-many relationship tables. For example pfts_species can have pfts that are added by BU with species added at EBI.

Right now the script will only remove those rows that are added both at the remote site, and will leave those rows alone that are added by the remote site and reference a local specie.

**Comment by mdietze** [comment]
@robkooper I don't think we're going to get in another BETY migration before our 1.4.1 deadline. Is this critical to getting the database sync working or can it be pushed to 1.4.2 (along with a bunch of other small db tweaks that have on the to-do list that I also just pushed back to 1.4.2) ??

**Comment by mdietze** [comment]
@robkooper maybe to get sync'ing working for 1.4.1 we could create a BETY branch that turns off constraints on the many-many tables? Or perhaps just pft-species since that's the one that's giving me trouble too.

**Comment by robkooper** [comment]
I think I might have the answer, just need to try on a linux machine. Will try this morning and let you know.
