### ISSUE TITLE
Incomplete Code in `met2CF.R`

### ISSUE THREAD

**Issue by Sweetdevil144** [PecanProject/pecan#3289]
### Bug Description

The active file `met2CF.R` is incomplete. Some variables are not defined and the function `dbfile.input.insert` is not completed.

The code file was last changed 10 years ago.
### To Reproduce

1. Open the file `modules/data.atmosphere/inst/scripts/met2CF.R`
2. Scroll down to lines 54
3. Observe the incomplete code

## Expected behavior

The file `met2CF.R` should contain complete R code. It is observed that the end code block is missing as follow :

```r
  # insert into db as input
dbfile.input.insert <- function(filename, siteid, startdate, enddate, mimetype, formatname, con, hostname=PEcAn.remote::fqdn()) {
```

## Screenshots
<img width="1440" alt="Screenshot 2024-05-07 at 4 19 24 PM" src="https://github.com/PecanProject/pecan/assets/117591942/244f1458-438a-41a8-ae22-a334d769b8b8">

## Machine (please complete the following information):

 - Server: NaN
 - OS: MacOS
 - Version:

## Additional context

The incomplete code may be causing issues with the execution of the program. The missing variables and incomplete function need to be defined and completed respectively.

**Comment by mdietze** [comment]
This script isn't used and can be deleted. Has been superseded by met2CF.csv.R and met2CF.nc.R
