### ISSUE TITLE
CO2 gap filled values for large gaps are consistently low

### ISSUE THREAD

**Issue by jam2767** [PecanProject/pecan#332]
Values for gap filled CO2 are consistently lower than values for the rest of the year. Moving forward we will need to think of other options for filling in large gaps of this and other variables (e.g. air_pressure - which is currently a constant based on elevation for large gaps (I believe).)
![mole_fraction_of_carbon_dioxide_ in us-dk3 2001 4](https://cloud.githubusercontent.com/assets/3688280/5820125/de04a2cc-a090-11e4-9149-baefb9b0e5d9.png)

**Comment by apourmok** [comment]
Just came to mind that maybe it is better (and makes more sense) for CO2 gap filling, to use Mauna Loa data. You can make a simple relationship between available data at site with the data at Mauna Loa for the same period and then use that relationship to gap fill missing CO2 values.

**Comment by ankurdesai** [comment]
Yes, this is doable, but would need to work on getting script to download data. Default ESRL data is monthly CO2, in which case a transfer function is needed for diurnal values (i’ve done this before). Continuous data from the tall tower network has lags for when it is available and format is not clean - I have scripts that download the raw data for one of these every day and going from it to a straightforward continuous time series of CO2 is not hard, but it’s not simple either. If we included a default half-hourly time series of Mauna Loa CO2 (pre-processed), that might be a nice option. 
-------------------------------------------------
Ankur R Desai, Associate Professor
  University of Wisconsin - Madison, Atmospheric and Oceanic Sciences
  http://flux.aos.wisc.edu  desai@aos.wisc.edu 
O: +1-608-520-0305 / M: +1-608-218-4208

**Comment by mdietze** [comment]
Sounds like CO2 needs to be a whole workflow unto itself. Once we get met.process working it would be worth looking at how we can leverage our experience there in formats, database records, input records, etc to make CO2 workflow development quicker and more straightforward while also maintaining the provenance tracking that we need in PEcAn

**Comment by tonygardella** [comment]
@jam2767 after #633 is closed can you check if this is still a problem?

**Comment by tonygardella** [comment]
I believe this can be closed. #633 was related and that was fixed.

**Comment by tonygardella** [comment]
I believe this can be closed. #633 was related and that was fixed.
