### ISSUE TITLE
Broken link for get started now button

### ISSUE THREAD

**Issue by Sagar2366** [PecanProject/pecan#3343]
I noticed that link is broken for Get started now button on main page which redirects to http://pecan.ncsa.illinois.edu/pecan 

Not Found
The requested URL was not found on this server.

**Comment by dlebauer** [comment]
@Sagar2366 thank you for reporting this. However, it is not clear where this issue occurred. The new base URL would be https://pecan-dev.ncsa.cloud/, but /pecan does not exist, and I can not find the string "Get started now" in the PEcAn github repository. Closing

**Comment by dlebauer** [comment]
This - and the problem of broken links in general - would be resolved (or caught so that it could be resolved) by implementation of GH action to check for broken links proposed in #3342
