### ISSUE TITLE
Remove data.hydrology from r-universe

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#3361]
Just noticed that removal of data.hydrology in https://github.com/PecanProject/pecan/pull/3292 is causing our r-universe build to crash. Does someone know how to update the runiverse to remove that package?

**Comment by mdietze** [comment]
example: https://github.com/r-universe/pecanproject/actions/runs/10507990154/job/29110920729

**Comment by Aariq** [comment]
Edit the JSON file in this repo: https://github.com/PecanProject/pecanproject.r-universe.dev
