### ISSUE TITLE
VignetteBuilder: field of DESCRIPTION should declare all builder deps

### ISSUE THREAD

**Issue by infotroph** [PecanProject/pecan#3392]
From ["Writing R Extensions"](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file-1) (emphasis theirs):

> The ‘VignetteBuilder’ field names (in a comma-separated list) packages that provide an engine for building vignettes. These may include the current package, or ones listed in ‘Depends’, ‘Suggests’ or ‘Imports’. The utils package is always implicitly appended. See Section 1.4.2 [Non-Sweave vignettes], page 48, for details. Note that if, for example, a vignette has engine ‘knitr::rmarkdown’, then knitr (https://CRAN.R-project.org/package=knitr) provides the engine but both knitr and rmarkdown (https://CRAN.R-project.org/package=rmarkdown) are needed for using it, so _both_ these packages need to be in the ‘VignetteBuilder’ field and at least suggested (as rmarkdown is only suggested by knitr, and hence not available automatically along with it). Many packages using knitr (https://CRAN.R-project.org/package=knitr) also need the package formatR (https://CRAN.R-project.org/package=formatR) which it suggests and so the user package needs to do so too and include this in ‘VignetteBuilder’.

Since all our vignettes use `knitr::rmarkdown`, my takeaway is that we need to replace `VignetteBuilder: knitr` with `VignetteBuilder: knitr, rmarkdown` in all packages that have vignettes.

**Comment by harshagr70** [comment]
Hi @infotroph ! I’d like to work on this issue if it’s still available. Could you please assign it to me? I’m ready to get started on a fix. Thanks!

**Comment by harshagr70** [comment]
Hi @infotroph  I've opened a PR #3394 to address this issue. I believe it addresses the problem, but I'd welcome any feedback or suggestions for improvement. Thanks!

**Comment by infotroph** [comment]
Fixed by #3394. Thank you, @harshagr70!
