### ISSUE TITLE
Read new Fluxnet CSV gap-filled driver

### ISSUE THREAD

**Issue by ankurdesai** [PecanProject/pecan#340]
Fluxnet beta release and New Fluxnet Synthesis (see Pecan meetings dropbox) will provide site level half-hourly gap-filled meteorology. Format: CSV. Should be able to ingest using existing read csv code

Tasks: Define format in BETY, use readCSV to open file
Challenge: Beta release not out yet (due Spring 2015). Only have Willow Creek

**Comment by ankurdesai** [comment]
Technical release is out: http://technical-release.fluxdata.org/2015. Direct access to .zip file with gap-filled half-hourly, daily, weekly, monthly, annual meteo (from 1989 to 2013), NEE, and energy fluxes, with uncertainty calculated and propagated and QC flags is available by ftp: ftp.fluxdata.org/.fluxnet_tech2015_23568/

New goals:
Download_fluxnet_TR  - similar to Ameriflux
  download .zip file from ftp site
  unzip the half-hourly NEE, meteo, and energy files, 
  discard .zip file
fluxnetTR_CF
  read half-hourly NEE. meteo, and energy CSV files using read_csv function
  convert to CF based units and variable names
  Save in netcdf file that should be usable by rest of pecan
  register in database?

**Comment by mdietze** [comment]
If you haven't already done so, you'll want to start by creating a Formats record for this new format.

The download function should do first 3 steps you outlined (download, unzip, discard) but also insert those raw files in the database (Inputs and dbfiles).

If both those are done then in theory met.convert should be able to handle the rest using met2CF.CSV and you shouldn't have to write a format-specific fluxnetTR2CF function.

**Comment by ankurdesai** [comment]
@jsimkins2

**Comment by tonygardella** [comment]
I'm closing this because of merged pull requests: #888 and #880
