### ISSUE TITLE
USERS in load.bety.sh should always be NO

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#342]
Right now script will create default users if REMOTESITE=0 and MYSITE=99. Should always be NO so user has to explicitly set it to YES.

**Comment by robkooper** [comment]
Also update documentation https://github.com/PecanProject/pecan/wiki/Database-Synchronization

**Comment by mdietze** [comment]
@robkooper I think this is done. Am I missing something or can we close?
