### ISSUE TITLE
Show more detailed site info on 03-inputs.php

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#353]
I'm envisioning that the box that goes with the pin on the Google Map could include more information about the site that might help the user confirm that this is the site that they want and in making selections of PFTs and other settings. Based on NACP2015 feedback from Tagir Gilmanov, @ankurdesai suggested that the sites.notes be shown, but we probably want to show more (all?) of the info in a site def'n

**Comment by robkooper** [comment]
Fixed with #841
