### ISSUE TITLE
Adding attributes to met in pecan.xml

### ISSUE THREAD

**Issue by bcow** [PecanProject/pecan#356]
Mike and I were talking yesterday about changing met in pecan.xml to include database id and file path if the met is already downloaded as well as met type. I want to check with everyone before I make changes to read.settings
```
<inputs>
    <met>/fs/data1/pecan.data/input</met>
</inputs>

<inputs>
     <met>
          <id>10000000001</id>
          <path>/fs/data1/pecan.data/input/</path>
          <type>Ameriflux</type>
     </met>
</inputs>
```

**Comment by mdietze** [comment]
I think all Inputs should have a structure like this, not just met. If a record exists the ID should be required and the path filled in by a query based on the machine ID. For a record that doesn't exist the <type> should match the name of the download and convert functions for that input tag (eg Ameriflux, NARR for met, FIA for veg)

**Comment by robkooper** [comment]
The other option is to use attributes for this:

<inputs>
  <met id="10000000001" type="Ameriflux">/fs/data1/pecan.data/input/</met>
</inputs>

I think only id should be needed, the rest is recoverable from the database. If you don't specify id, but do specify type (maybe source is a better name) it means get the data from that specific source.

**Comment by robkooper** [comment]
I agree with Mike. All inputs should follow this scheme.
