### ISSUE TITLE
PEcAn/PostGIS install RHEL 6.5

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#365]
@Viskari and I noted previously that we were having issues install postgis 2.x.x with PostgreSQL version 9.3.5 or 9.4.x.  Initially the issues related to version of dependencies and associated issues stemming from the installs done by BNL ITD.  I have fixed these issues by recompiling all dependencies, including many of the geospatial libs.  By the way, I very useful resource can be found here:http://scigeo.org/articles/howto-install-latest-geospatial-software-on-linux.html

After all of the recompile (inlcuding autoconf, m4, libxml2, json-c, etc) and setting these all up as modules, I ran into another issue with postgis-2.1.5.  This issues occurs during 'make' when it is building the raster libs:

```
/data/software/gdal/1.11.2/lib/libgdal.so: undefined reference to `GTIFAllocDefn'
/data/software/gdal/1.11.2/lib/libgdal.so: undefined reference to `nc_inq_var_chunking'
/data/software/gdal/1.11.2/lib/libgdal.so: undefined reference to `nc_def_var_chunking'
/data/software/gdal/1.11.2/lib/libgdal.so: undefined reference to `nc_def_var_deflate'
/data/software/gdal/1.11.2/lib/libgdal.so: undefined reference to `GTIFFreeDefn'
collect2: error: ld returned 1 exit status
make[2]: *** [raster2pgsql] Error 1
make[2]: Leaving directory `/data/software/src/postgis/postgis-2.1.5/raster/loader'
make[1]: *** [rtloader] Error 2
make[1]: Leaving directory `/data/software/src/postgis/postgis-2.1.5/raster'
make: *** [all] Error 1
```

However, I tried making the previous version of postgis (2.1.3) and that indeed worked:

```
make[2]: Leaving directory `/data/software/src/postgis/postgis-2.1.3/extensions/postgis_topology'
make[1]: Leaving directory `/data/software/src/postgis/postgis-2.1.3/extensions'
PostGIS was built successfully. Ready to install.
```
Therefore, I suspect there may be issues with the version 2.1.5 combined with the Proj4 (4.8.0), GEOS (3.4.2) and GDAL (1.11.2) libs I have installed.

Therefore, we are moving forward with PostGIS v 2.1.3 for now.

**Comment by serbinsh** [comment]
It seems that version 2.1.5 has an issue with the raster/loader extension during compile.  I just tried making the 2.2.0dev version and that too worked OK:

...
make[2]: Leaving directory `/data/software/src/postgis/postgis-2.2.0dev/extensions/address_standardizer'
make[1]: Leaving directory `/data/software/src/postgis/postgis-2.2.0dev/extensions'
PostGIS was built successfully. Ready to install.

**Comment by serbinsh** [comment]
Another issue, and I think this is related to path problems within PostgreSQL.  The issue is finding the libs associated with PostGIS (e.g. GDAL, JSON-C, GEOS).  We have installed these in a non default location to provide capability with our cluster.  As a result I think I need to update the environment for postgres so it can find these lib locations:

[sserbin@test postgis-2.1.3]$ psql -U sserbin -d bety
psql (9.4.1)
Type "help" for help.

bety=# CREATE EXTENSION postgis;
ERROR:  could not load library "/usr/pgsql-9.4/lib/postgis-2.1.so": libjson-c.so.2: cannot open shared object file: No such file or directory

Currently Loaded Modulefiles:
  1) /gcc/4.8.0             4) /autoconf/2.69         7) /libtiff/4.0.3        10) /geos/3.4.2           13) /hdf5/1.8.14          16) /libxml2/2.9.1
  2) /gfortran/4.8.0        5) /m4/1.4.17             8) /geotiff/1.4.1        11) /gdal/1.11.2          14) /netcdf/4.3.3.1       17) /json-c/0.11
  3) /openmpi/1.6.4-gnu48   6) /proj/4.8.0            9) /libkml/devel         12) /hdf4/4.2.11          15) /nco/4.4.8

[sserbin@test data]$ sudo -u sserbin psql -d bety -c "CREATE EXTENSION postgis;"
ERROR:  could not load library "/usr/pgsql-9.4/lib/rtpostgis-2.1.so": libgdal.so: cannot open shared object file: No such file or directory


[sserbin@test data]$ ldd /usr/pgsql-9.4/lib/rtpostgis-2.1.so
	linux-vdso.so.1 =>  (0x00007fff82dff000)
	libgdal.so => /data/software/gdal/1.11.2/lib/libgdal.so (0x00007fdd9c076000)
	libgeos_c.so.1 => /data/software/geos/3.4.2/lib/libgeos_c.so.1 (0x00007fdd9be50000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fdd9bbb3000)
	libgcc_s.so.1 => /software/gcc-4.8.0/lib64/libgcc_s.so.1 (0x00007fdd9b99c000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fdd9b608000)
	libsqlite3.so.0 => /usr/lib64/libsqlite3.so.0 (0x00007fdd9b379000)
	libodbc.so.2 => /usr/lib64/libodbc.so.2 (0x00007fdd9b111000)
	libodbcinst.so.2 => /usr/lib64/libodbcinst.so.2 (0x00007fdd9af00000)
	libkmldom.so.0 => /data/software/libkml/devel/lib/libkmldom.so.0 (0x00007fdd9ac51000)
	libkmlbase.so.0 => /data/software/libkml/devel/lib/libkmlbase.so.0 (0x00007fdd9aa3a000)
	libkmlengine.so.0 => /data/software/libkml/devel/lib/libkmlengine.so.0 (0x00007fdd9a804000)
	libkmlconvenience.so.0 => /data/software/libkml/devel/lib/libkmlconvenience.so.0 (0x00007fdd9a5e7000)
	libminizip.so.0 => /data/software/libkml/devel/lib/libminizip.so.0 (0x00007fdd9a3de000)
	liburiparser.so.1 => /data/software/libkml/devel/lib/liburiparser.so.1 (0x00007fdd9a1c7000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007fdd99f9f000)
	libxerces-c-3.0.so => /usr/lib64/libxerces-c-3.0.so (0x00007fdd999fd000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fdd997e0000)
	libjasper.so.1 => /usr/lib64/libjasper.so.1 (0x00007fdd99587000)
	libnetcdf.so.7 => /data/software/netcdf/4.3.3.1/lib/libnetcdf.so.7 (0x00007fdd96235000)
	libhdf5.so.9 => /data/software/hdf5/1.8.14/lib/libhdf5.so.9 (0x00007fdd95d44000)
	libmfhdf.so.0 => /data/software/hdf4/4.2.11/lib/libmfhdf.so.0 (0x00007fdd95b20000)
	libdf.so.0 => /data/software/hdf4/4.2.11/lib/libdf.so.0 (0x00007fdd9587c000)
	libjpeg.so.62 => /usr/lib64/libjpeg.so.62 (0x00007fdd9562c000)
	libgeotiff.so.2 => /data/software/geotiff/1.4.1/lib/libgeotiff.so.2 (0x00007fdd953f9000)
	libtiff.so.5 => /data/software/libtiff/4.0.3/lib/libtiff.so.5 (0x00007fdd95186000)
	libpng12.so.0 => /usr/lib64/libpng12.so.0 (0x00007fdd94f60000)
	libpq.so.5 => /usr/pgsql-9.4/lib/libpq.so.5 (0x00007fdd94d32000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fdd94b1b000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fdd94913000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fdd9470f000)
	libpcre.so.0 => /lib64/libpcre.so.0 (0x00007fdd944e2000)
	libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00007fdd9428e000)
	libxml2.so.2 => /data/software/libxml2/2.9.1/lib/libxml2.so.2 (0x00007fdd93f32000)
	libmpi_cxx.so.1 => /software/mpi/openmpi/1.6.4-gnu48/lib/libmpi_cxx.so.1 (0x00007fdd93d17000)
	libmpi.so.1 => /software/mpi/openmpi/1.6.4-gnu48/lib/libmpi.so.1 (0x00007fdd9379a000)
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007fdd93581000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007fdd9337d000)
	libtorque.so.2 => /usr/lib64/libtorque.so.2 (0x00007fdd92aa4000)
	libstdc++.so.6 => /software/gcc-4.8.0/lib64/libstdc++.so.6 (0x00007fdd9279b000)
	libgeos-3.4.2.so => /data/software/geos/3.4.2/lib/libgeos-3.4.2.so (0x00007fdd92401000)
	/lib64/ld-linux-x86-64.so.2 (0x00000039d4600000)
	libltdl.so.7 => /usr/lib64/libltdl.so.7 (0x00007fdd921f8000)
	libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007fdd91e14000)
	libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007fdd91ba8000)
	libhdf5_hl.so.7 => /usr/lib64/libhdf5_hl.so.7 (0x00007fdd9197a000)
	libhdf5.so.7 => /usr/lib64/libhdf5.so.7 (0x00007fdd914dd000)
	liblzma.so.0 => /usr/lib64/liblzma.so.0 (0x00007fdd912bb000)
	libproj.so.0 => /data/software/proj/4.8.0/lib/libproj.so.0 (0x00007fdd9106e000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fdd90e29000)
	libldap_r-2.4.so.2 => /lib64/libldap_r-2.4.so.2 (0x00007fdd90bd1000)
	libidn.so.11 => /lib64/libidn.so.11 (0x00007fdd9099f000)
	libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007fdd9074e000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fdd90468000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fdd9023c000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fdd90037000)
	libssl3.so => /usr/lib64/libssl3.so (0x00007fdd8fdf8000)
	libsmime3.so => /usr/lib64/libsmime3.so (0x00007fdd8fbcc000)
	libnss3.so => /usr/lib64/libnss3.so (0x00007fdd8f88c000)
	libnssutil3.so => /usr/lib64/libnssutil3.so (0x00007fdd8f660000)
	libplds4.so => /lib64/libplds4.so (0x00007fdd8f45c000)
	libplc4.so => /lib64/libplc4.so (0x00007fdd8f256000)
	libnspr4.so => /lib64/libnspr4.so (0x00007fdd8f018000)
	libssh2.so.1 => /usr/lib64/libssh2.so.1 (0x00007fdd8edf0000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fdd8ebe4000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fdd8e9e0000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fdd8e7c6000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007fdd8e5b7000)
	libsasl2.so.2 => /usr/lib64/libsasl2.so.2 (0x00007fdd8e39d000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fdd8e17d000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fdd8df45000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007fdd8dccc000)

**Comment by serbinsh** [comment]
Alternatively, maintain a separate install of these libs just for PostGIS....

**Comment by dlebauer** [comment]
@serbinsh - I think you are using `...` when you should be using ``` to set off code blocks, and note that these are required before and after the code chunks

**Comment by serbinsh** [comment]
@dlebauer Can you please clarify?

**Comment by dlebauer** [comment]
easiest to point you to the Github Flavored Markdown section on ['Fenced Code Blocks'](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).

**Comment by serbinsh** [comment]
@robkooper 

Again, this is the error we are getting during make:
```
make -C loader
make[2]: Entering directory `/data/software/src/postgis/postgis-2.1.7/raster/loader'
/bin/sh ../../libtool --mode=link mpicc -g -O2  -fPIC -DPIC  -Wall -Wmissing-prototypes -I../rt_core -I../../liblwgeom -I/data/software/proj/4.8.0/include -I/data/software/gdal/1.11.2/include -I/data/software/geos/3.4.2/include   ../rt_core/librtcore.a raster2pgsql.o ../../liblwgeom/liblwgeom.la -L/data/software/gdal/1.11.2/lib -lgdal  -L/data/software/geos/3.4.2/lib -lgeos_c  -lc -lm -o raster2pgsql
libtool: link: mpicc -g -O2 -fPIC -DPIC -Wall -Wmissing-prototypes -I../rt_core -I../../liblwgeom -I/data/software/proj/4.8.0/include -I/data/software/gdal/1.11.2/include -I/data/software/geos/3.4.2/include raster2pgsql.o -o .libs/raster2pgsql  ../rt_core/librtcore.a ../../liblwgeom/.libs/liblwgeom.so -L/data/software/geos/3.4.2/lib -L/data/software/proj/4.8.0/lib /data/software/proj/4.8.0/lib/libproj.so -ljson-c -L/data/software/gdal/1.11.2/lib -lgdal /data/software/geos/3.4.2/lib/libgeos_c.so /data/software/geos/3.4.2/lib/libgeos.so /data/software/openmpi/1.8.4-gnu484/lib/libmpi_cxx.so /data/software/openmpi/1.8.4-gnu484/lib/libmpi.so -libverbs /data/software/openmpi/1.8.4-gnu484/lib/libopen-rte.so /usr/lib64/libtorque.so -lpthread -lxml2 -lz -lcrypto -lssl /data/software/openmpi/1.8.4-gnu484/lib/libopen-pal.so -ldl -lrt -lutil /data/software/gcc-4.8.4/lib/../lib64/libstdc++.so -lc -lm -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/data/software/proj/4.8.0/lib -Wl,-rpath -Wl,/data/software/geos/3.4.2/lib -Wl,-rpath -Wl,/data/software/openmpi/1.8.4-gnu484/lib -Wl,-rpath -Wl,/data/software/gcc-4.8.4/lib/../lib64
/data/software/gdal/1.11.2/lib/libgdal.so: undefined reference to `GTIFAllocDefn'
/data/software/gdal/1.11.2/lib/libgdal.so: undefined reference to `GTIFFreeDefn'
collect2: error: ld returned 1 exit status
make[2]: *** [raster2pgsql] Error 1
make[2]: Leaving directory `/data/software/src/postgis/postgis-2.1.7/raster/loader'
make[1]: *** [rtloader] Error 2
make[1]: Leaving directory `/data/software/src/postgis/postgis-2.1.7/raster'
make: *** [all] Error 1
```

Here is our environment and how we installed GDAL:

PostgreSQL - /usr/pgsql-9.4/bin/pg_config
libkml - /data/software/libkml/trunk
libtiff - /data/software/libtiff/4.0.4
geotiff - /data/software/geotiff/1.4.1
geos - /data/software/geos/3.4.2/bin/geos-config
HDF4 - /data/software/hdf4/4.2.11
HDF5 - /data/software/hdf5/1.8.14
netCDF - /data/software/netcdf/4.3.3.1

./configure --prefix=/data/software/gdal/1.11.2 --with-jpeg=external --with-jpeg12 --with-python --without-libtool --with-pg=/usr/pgsql-9.4/bin/pg_config --with-libkml=/data/software/libkml/trunk --with-libtiff=/data/software/libtiff/4.0.4 --with-geotiff=/data/software/geotiff/1.4.1 --with-geos=/data/software/geos/3.4.2/bin/geos-config --with-hdf4=/data/software/hdf4/4.2.11 --with-hdf5=/data/software/hdf5/1.8.14 --with-netcdf=/data/software/netcdf/4.3.3.1

I assumed this would give us TIFF support?

**Comment by serbinsh** [comment]
@robkooper @mdietze

gdal-config --formats
gxf gtiff hfa aigrid aaigrid ceos ceos2 iso8211 xpm sdts raw dted mem jdem envisat elas fit vrt usgsdem l1b nitf bmp pcidsk airsar rs2 ilwis rmf leveller sgi srtmhgt idrisi gsg ingr ers jaxapalsar dimap gff cosar pds adrg coasp tsx terragen blx msgn til r northwood saga xyz hf2 kmlsuperoverlay ctg e00grid zmap ngsgeoid iris map wcs wms grib bsb jpeg2000 netcdf hdf5 hdf4 gif jpeg png pcraster rik ozi pdf rasterlite mbtiles postgisraster arg

gdalinfo --formats
Supported Formats:
  VRT (rw+v): Virtual Raster
  GTiff (rw+vs): GeoTIFF
  NITF (rw+vs): National Imagery Transmission Format
  RPFTOC (rovs): Raster Product Format TOC format
  ECRGTOC (rovs): ECRG TOC format
  HFA (rw+v): Erdas Imagine Images (.img)
  SAR_CEOS (rov): CEOS SAR Image
  CEOS (rov): CEOS Image
  JAXAPALSAR (rov): JAXA PALSAR Product Reader (Level 1.1/1.5)
  GFF (rov): Ground-based SAR Applications Testbed File Format (.gff)
  ELAS (rw+v): ELAS
  AIG (rov): Arc/Info Binary Grid
  AAIGrid (rwv): Arc/Info ASCII Grid
  GRASSASCIIGrid (rov): GRASS ASCII Grid
  SDTS (rov): SDTS Raster
  DTED (rwv): DTED Elevation Raster
  PNG (rwv): Portable Network Graphics
  JPEG (rwv): JPEG JFIF
  MEM (rw+): In Memory Raster
  JDEM (rov): Japanese DEM (.mem)
  GIF (rwv): Graphics Interchange Format (.gif)
  BIGGIF (rov): Graphics Interchange Format (.gif)
  ESAT (rov): Envisat Image Format
  BSB (rov): Maptech BSB Nautical Charts
  XPM (rwv): X11 PixMap Format
  BMP (rw+v): MS Windows Device Independent Bitmap
  DIMAP (rov): SPOT DIMAP
  AirSAR (ro): AirSAR Polarimetric Image
  RS2 (ros): RadarSat 2 XML Product
  PCIDSK (rw+v): PCIDSK Database File
  PCRaster (rw): PCRaster Raster File
  ILWIS (rw+v): ILWIS Raster Map
  SGI (rw+): SGI Image File Format 1.0
  SRTMHGT (rwv): SRTMHGT File Format
  Leveller (rw+): Leveller heightfield
  Terragen (rw+): Terragen heightfield
  GMT (rw): GMT NetCDF Grid Format
  netCDF (rw+s): Network Common Data Format
  HDF4 (ros): Hierarchical Data Format Release 4
  HDF4Image (rw+): HDF4 Dataset
  ISIS3 (rov): USGS Astrogeology ISIS cube (Version 3)
  ISIS2 (rw+v): USGS Astrogeology ISIS cube (Version 2)
  PDS (rov): NASA Planetary Data System
  TIL (rov): EarthWatch .TIL
  ERS (rw+v): ERMapper .ers Labelled
  L1B (rovs): NOAA Polar Orbiter Level 1b Data Set
  FIT (rwv): FIT Image
  GRIB (rov): GRIdded Binary (.grb)
  JPEG2000 (rwv): JPEG-2000 part 1 (ISO/IEC 15444-1)
  RMF (rw+v): Raster Matrix Format
  WCS (rovs): OGC Web Coverage Service
  WMS (rwvs): OGC Web Map Service
  MSGN (ro): EUMETSAT Archive native (.nat)
  RST (rw+v): Idrisi Raster A.1
  INGR (rw+v): Intergraph Raster
  GSAG (rwv): Golden Software ASCII Grid (.grd)
  GSBG (rw+v): Golden Software Binary Grid (.grd)
  GS7BG (rw+v): Golden Software 7 Binary Grid (.grd)
  COSAR (ro): COSAR Annotated Binary Matrix (TerraSAR-X)
  TSX (rov): TerraSAR-X Product
  COASP (ro): DRDC COASP SAR Processor Raster
  R (rwv): R Object Data Store
  MAP (rov): OziExplorer .MAP
  PNM (rw+v): Portable Pixmap Format (netpbm)
  DOQ1 (rov): USGS DOQ (Old Style)
  DOQ2 (rov): USGS DOQ (New Style)
  ENVI (rw+v): ENVI .hdr Labelled
  EHdr (rw+v): ESRI .hdr Labelled
  GenBin (rov): Generic Binary (.hdr Labelled)
  PAux (rw+): PCI .aux Labelled
  MFF (rw+): Vexcel MFF Raster
  MFF2 (rw+): Vexcel MFF2 (HKV) Raster
  FujiBAS (ro): Fuji BAS Scanner Image
  GSC (rov): GSC Geogrid
  FAST (rov): EOSAT FAST Format
  BT (rw+v): VTP .bt (Binary Terrain) 1.3 Format
  LAN (rw+v): Erdas .LAN/.GIS
  CPG (ro): Convair PolGASP
  IDA (rw+): Image Data and Analysis
  NDF (rov): NLAPS Data Format
  EIR (rov): Erdas Imagine Raw
  DIPEx (rov): DIPEx
  LCP (rwv): FARSITE v.4 Landscape File (.lcp)
  GTX (rw+v): NOAA Vertical Datum .GTX
  LOSLAS (rov): NADCON .los/.las Datum Grid Shift
  NTv2 (rw+vs): NTv2 Datum Grid Shift
  CTable2 (rw+v): CTable2 Datum Grid Shift
  ACE2 (rov): ACE2
  SNODAS (rov): Snow Data Assimilation System
  KRO (rw+v): KOLOR Raw
  ARG (rwv): Azavea Raster Grid format
  RIK (ro): Swedish Grid RIK (.rik)
  USGSDEM (rwv): USGS Optional ASCII DEM (and CDED)
  GXF (ro): GeoSoft Grid Exchange Format
  HTTP (ro): HTTP Fetching Wrapper
  BAG (ro): Bathymetry Attributed Grid
  HDF5 (ros): Hierarchical Data Format Release 5
  HDF5Image (ro): HDF5 Dataset
  NWT_GRD (rov): Northwood Numeric Grid Format .grd/.tab
  NWT_GRC (rov): Northwood Classified Grid Format .grc/.tab
  ADRG (rw+vs): ARC Digitized Raster Graphics
  SRP (rovs): Standard Raster Product (ASRP/USRP)
  BLX (rw): Magellan topo (.blx)
  Rasterlite (rws): Rasterlite
  PostGISRaster (rws): PostGIS Raster driver
  SAGA (rw+v): SAGA GIS Binary Grid (.sdat)
  KMLSUPEROVERLAY (rwv): Kml Super Overlay
  XYZ (rwv): ASCII Gridded XYZ
  HF2 (rwv): HF2/HFZ heightfield raster
  PDF (rw): Geospatial PDF
  OZI (rov): OziExplorer Image File
  CTG (rov): USGS LULC Composite Theme Grid
  E00GRID (rov): Arc/Info Export E00 GRID
  ZMap (rwv): ZMap Plus Grid
  NGSGEOID (rov): NOAA NGS Geoid Height Grids
  MBTiles (rov): MBTiles
  IRIS (rov): IRIS data (.PPI, .CAPPi etc)

ogrinfo --formats
Supported Formats:
  -> "ESRI Shapefile" (read/write)
  -> "MapInfo File" (read/write)
  -> "UK .NTF" (readonly)
  -> "SDTS" (readonly)
  -> "TIGER" (read/write)
  -> "S57" (read/write)
  -> "DGN" (read/write)
  -> "VRT" (readonly)
  -> "REC" (readonly)
  -> "Memory" (read/write)
  -> "BNA" (read/write)
  -> "CSV" (read/write)
  -> "NAS" (readonly)
  -> "GML" (read/write)
  -> "GPX" (read/write)
  -> "KML" (read/write)
  -> "GeoJSON" (read/write)
  -> "Interlis 1" (read/write)
  -> "Interlis 2" (read/write)
  -> "GMT" (read/write)
  -> "GPKG" (read/write)
  -> "SQLite" (read/write)
  -> "ODBC" (read/write)
  -> "WAsP" (read/write)
  -> "PGeo" (readonly)
  -> "MSSQLSpatial" (read/write)
  -> "PostgreSQL" (read/write)
  -> "PCIDSK" (read/write)
  -> "OpenFileGDB" (readonly)
  -> "XPlane" (readonly)
  -> "AVCBin" (readonly)
  -> "AVCE00" (readonly)
  -> "DXF" (read/write)
  -> "Geoconcept" (read/write)
  -> "GeoRSS" (read/write)
  -> "GPSTrackMaker" (read/write)
  -> "VFK" (readonly)
  -> "PGDump" (read/write)
  -> "OSM" (readonly)
  -> "GPSBabel" (read/write)
  -> "SUA" (readonly)
  -> "OpenAir" (readonly)
  -> "PDS" (readonly)
  -> "WFS" (readonly)
  -> "HTF" (readonly)
  -> "AeronavFAA" (readonly)
  -> "Geomedia" (readonly)
  -> "EDIGEO" (readonly)
  -> "GFT" (read/write)
  -> "GME" (read/write)
  -> "SVG" (readonly)
  -> "CouchDB" (read/write)
  -> "Idrisi" (readonly)
  -> "ARCGEN" (readonly)
  -> "SEGUKOOA" (readonly)
  -> "SEGY" (readonly)
  -> "ODS" (read/write)
  -> "XLSX" (read/write)
  -> "ElasticSearch" (read/write)
  -> "PDF" (read/write)
  -> "Walk" (readonly)
  -> "CartoDB" (readonly)
  -> "SXF" (readonly)

**Comment by serbinsh** [comment]
The fix - install latest gcc compiler and open-mpi.  Re-compile all libs with a consistent gcc/gfortran.  Fix paths and modules.  Now everything is running.

**Comment by xros** [comment]
how did you solve this?
I met the same issue on ubuntu 14.04 after adding the deb sources to sources.list
How did you make it?

**Comment by robkooper** [comment]
In the case of Ubuntu we use the official postgres distribution, see https://github.com/PecanProject/pecan/wiki/Installing-PEcAn-Ubuntu#install-postgres

**Comment by xros** [comment]
I did followed the official distribution and same. 
I just forgot to install 'postgresql-9.4-postgis-2.1-scripts'. Now all things work! :+1:
