### ISSUE TITLE
Integrate BrowDog in PEcAn workflow

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#370]
Need to allow the user to pick using BrownDog for doing the conversions.

**Comment by mchenry** [comment]
- Add checkbox to select Brown Dog in Web interface
  - Add flag to pecan.xml to use Brown Dog
- Have Brown Dog gif run across bottom when active

**Comment by mdietze** [comment]
@mchenry I think a Brown Dog checkbox is good for the 18 month review but after that I'd love to make BD more automatic after that (e.g. kick in as the default whenever the data to be processed isn't already on the server).

Animated gif will be fun

**Comment by robkooper** [comment]
if in the config.php the variables of browndog are set, or in pecan.xml the browndog section is specified it will now use browndog for met.process.
