### ISSUE TITLE
Create Polyglot wrapper scripts for NARR conversions

### ISSUE THREAD

**Issue by mchenry** [PecanProject/pecan#371]
A similar subset as these for Ameriflux:

https://github.com/PecanProject/pecan/tree/master/contrib/browndog

See here for details on what the script needs:

https://opensource.ncsa.illinois.edu/confluence/display/BD/Adding+Conversions+to+the+DAP+and+Calling+the+DAP

Can simply add to this same repo.  Tools Catalog already pointing here (create an account to see):

http://browndog.ncsa.illinois.edu:9000/tools/54f8a37a2200002e02332b96

**Comment by mchenry** [comment]
Assuming this pull request means support for NARR data is complete?:

https://github.com/PecanProject/pecan/pull/363

**Comment by mdietze** [comment]
In the home stretch with NARR. Just waiting for Betsy to drive me a final thumbs up on the pull

<iPad>

**Comment by robkooper** [comment]
This is now part of met.process.
