### ISSUE TITLE
Create Polyglot wrapper script for ED conversions

### ISSUE THREAD

**Issue by mchenry** [PecanProject/pecan#372]
An equivalent script to this one:

https://github.com/PecanProject/pecan/blob/master/contrib/browndog/PEcAn%23Sipnet_convert.R

**Comment by mchenry** [comment]
From what I understand this may pretty straight forward, simply changing the format in the header and line 92 of the script?

**Comment by robkooper** [comment]
Added to repository https://github.com/PecanProject/pecan/blob/master/contrib/browndog/PEcAn%23ED2_convert.R
