### ISSUE TITLE
PSQL cannot find installed libraries during postGIS installation on redhat

### ISSUE THREAD

**Issue by Viskari** [PecanProject/pecan#377]
While running the create extension commands from http://postgis.net/install/ on psql, we ran in to an issue as psql gave an error command that it could not find the libraries required, even though they had all been installed as modules and loaded up. When doing this, we were logged in as superusers.

The solution this turned out to be somewhat surprising. As far as I understood, hen you are logged in on psql on redhat as a superuser, it will run it as it is someone logged in to redhat as user postgres. To solve our issue, we had to adjust the .bashrc for the user postgres to load up the modules required by the postgis. Once we did this, it ran the create extension commands without any complaints.

**Comment by mdietze** [comment]
@Viskari is this issue resolved? If so could you close it?
