### ISSUE TITLE
Problem with Postgres and Pecan

### ISSUE THREAD

**Issue by hamid4965** [PecanProject/pecan#387]
I have installed all the models and everything seems perfect except installing Database+Data section. The error comes after i create the bety user and it is as follow: 

hamid@hamid-VirtualBox:~/testrun.pecan$ sudo -u postgres CREATE=YES REMOTESITE=0      scripts/load.bety.sh
sudo: scripts/load.bety.sh: command not found

It casues problem when i want to run the Pecan testrun with SIPNET. 
Thanks

**Comment by robkooper** [comment]
Make sure you are in the pecan folder : cd ~/pecan and try again.

**Comment by gsrohde** [comment]
What if you use ./scripts/load.bety.sh instead?

**Comment by hamid4965** [comment]
Thanks, i was not in pecan folder, problem solved.
