### ISSUE TITLE
allow databases to specified in separate file

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#396]
Will use ~/.pecan.xml to store this information. This file is the same as a regular pecan.xml file but only the database information will be used. Any information specified here will only be used if the database information does not already exist.

**Comment by dlebauer** [comment]
How about .pgpass?

**Comment by robkooper** [comment]
it is not postgres specific, it should also work with mysql, or anything else.

**Comment by dlebauer** [comment]
Perhaps check .pgpass then .my.cnf then .pecan.xml? More 'DRY' this way +
after a user sets it up, they can also directly access DB from command
line. On the other hand, I now see that this could be less secure (? Maybe
not more so than ssh keys).

**Comment by robkooper** [comment]
Only problem is that we have more information in the pecan.xml file, for example we don't know what database it should be for (FIA vs BETY) and whether or not we should write to the database. I also would really like to add a userid to this section so all runs by pecan can be written with a userid to the database.

**Comment by robkooper** [comment]
This now also used for browndog. If you have a tag <browndog/> in your pecan.xml it will use those values from ~/.pecan.xml.

During read.settings these values are incorporated into the tree and will be accessible to the code normally.
