### ISSUE TITLE
read.settings.R breaks with BrownDog and met inputs

### ISSUE THREAD

**Issue by bcow** [PecanProject/pecan#398]
read.settings.R is not compatible with the two new features of pecan.xml:
```
<met>
     <id>10000000001</id>
     <path>/fs/data1/pecan.data/input/</path>
     <source>Ameriflux</source>
</met>
```
and 
```
 <browndog>
     <url>http://dap.ncsa.illinois.edu:8184/convert/</url>
 </browndog>
```

Currently in the web workflow.R I've made the hack:
```
# settings <- read.settings("pecan.xml")
settings <- xmlToList(xmlParse("pecan.xml"))
```

https://github.com/bcow/pecan/commit/77689919d79f89597e61b31df6fbcff3d55c52c5
https://github.com/bcow/pecan/commit/774996c1fade8be1d947141a06e9d893ec91e868

**Comment by robkooper** [comment]
See https://github.com/PecanProject/pecan/pull/415
