### ISSUE TITLE
passwordless ssh connection from pecan2.bu.edu to geo.bu.edu

### ISSUE THREAD

**Issue by ryankelly-uiuc** [PecanProject/pecan#428]
BU users, per Mike Dugan from the IT department:
> Passwordless ssh access from the pecan machines to geo is allowed but it is host based not key based. You just to create a file called .rhosts in your geo home directory listed the 3 machines. I did this for you.
 
For example, my .rhosts file contains:
>pecan1.bu.edu
pecan2.bu.edu
test-pecan.bu.edu

It has permission 644, in case that matters.

**Comment by bcow** [comment]
Today this stopped working for me. I checked my .rhosts file and it matches the example.

**Comment by ryankelly-uiuc** [comment]
Me too, and I haven't changed anything. Worked last time I tried, though that's been awhile. @bcow can you check with IT?

**Comment by bcow** [comment]
Will do. In the meantime maybe you should reopen the issue?

**Comment by bcow** [comment]
I just tested on pecan2 and test-pecan and passwordless ssh is working again.

Mike Dugan:
> We updated a config file this morning and forgot to add the pecan machines back in. Sorry about that. Access is now restored so you should be all set.

**Comment by ryankelly-uiuc** [comment]
Thanks, @bcow . Good to know that IT may need to be prodded for future.
