### ISSUE TITLE
More informative met names In web interface

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#453]
When the webpage finds a met data set in the inputs it just labels it as "Weather" and then the year, which gives the user no idea what the source of the different drivers are. We should use the Inputs.name and id rather than "Weather".

**Comment by ch1eroe1** [comment]
It looks like some of the inputs.name fields are blank when testing this change.  Did we possibly mean to say to use the dbfiles.file_name field?  I am just trying to make sure I populate the drop down with the proper information.  See attachment for a sample query.

![image](https://cloud.githubusercontent.com/assets/12739945/10059588/7dcf9a04-6211-11e5-87a1-dcc59fc517b7.png)

**Comment by mdietze** [comment]
Yeah, there's a bunch of old records that were created by hand that lack an
input.name but I think the solution is for us go go back and give them
meaningful names. The met workflow does fill in the input.name field. Up to
you whether you want to leave the blanks empty, substitute with the
file_name, or just use the current default 'weather' when building up the
menu names.

**Comment by robkooper** [comment]
Add a link to BETY if an input is selected, make sure to NOT link if Ameriflux, etc.

**Comment by ch1eroe1** [comment]
I can't seem to close this ticket.  Code has been merged into master repository.
