### ISSUE TITLE
Sites missing on web pecan for conversions

### ISSUE THREAD

**Issue by bcow** [PecanProject/pecan#458]
On the pecan web interface:
When you select a model, most sites on the map disappear and then if you select conversion, they should all show up again.
But they only show up again for SIPNET and DALEC, not LINKAGES and ED2. 
@robkooper

**Comment by bcow** [comment]
This is for pecan2

**Comment by mdietze** [comment]
This issue occurred because there were additional data requirements for these models that were unmet. For ED2 Rob switched pss/css/site to be optional, though a but in the ED bareground run itself remains, but sites show up.
