### ISSUE TITLE
read.settings "memory not mapped" 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#476]
read.settings fails with 'memory not mapped' error:

```r
PEcAn.settings::read.settings("settings/tests/testthat/testsettings.xml")
````

On ebi-forecast (RedHat), I get 

> 2015-05-11 13:44:52 INFO   [PEcAn.settings::read.settings] : 
>    Loading inpufile= settings/tests/testthat/testsettings.xml 
> 
 > *** caught segfault ***
> address 0x3f00000000, cause 'memory not mapped'
> 
> Traceback:
> 1: .Call("RS_XML_ParseTree", as.character(file), handlers, as.logical(ignoreBlanks),      as.logical(replaceEntities), as.logical(asText), as.logical(trim),     as.logical(validate), as.logical(getDTD), as.logical(isURL),     as.logical(addAttributeNamespaces), as.logical(useInternalNodes),     as.logical(isHTML), as.logical(isSchema), as.logical(fullNamespaceInfo),     as.character(encoding), as.logical(useDotNames), xinclude,     error, addFinalizer, as.integer(options), as.logical(parentFirst),     PACKAGE = "XML")
 2: xmlParse(inputfile)
 3: PEcAn.settings::read.settings("settings/tests/testthat/testsettings.xml")

**Comment by robkooper** [comment]
I have seen this when you use either an older version of libXML or a missmapping between the libXML and the R XML library.

**Comment by dlebauer** [comment]
I deleted the XML library and reinstalled it

```sh
rm -rf ~/R/library/XML
```

```r
PEcAn.settings::read.settings("~/dev/pecan/settings/tests/testthat/testsettings.xml")
```
