### ISSUE TITLE
What happened to Rd0 in write.configs.ed.R?

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#477]
See code block below:

```
    ## Convert leaf_respiration_rate_m2 to dark_resp_factor; requires Vcmax
    if('leaf_respiration_rate_m2' %in% names(trait.samples)) {
      leaf_resp = trait.samples[['leaf_respiration_rate_m2']]
      
      ## First scale variables to 15 degC
      trait.samples[['leaf_respiration_rate_m2']] <- 
        arrhenius.scaling(leaf_resp, old.temp = 25, new.temp = 15)
      
      ## Calculate dark_resp_factor -- Will be depreciated when moving from older versions of ED2
      trait.samples[['dark_respiration_factor']] <- trait.samples[['leaf_respiration_rate_m2']]/
        trait.samples[['Vcmax']]
      
      ## Remove leaf_respiration_rate from trait samples -- NO LONGER NEEDED
      #remove <- which(names(trait.samples)=='leaf_respiration_rate_m2')
      #trait.samples = trait.samples[-remove]
      
    } ## End dark_respiration_factor loop
```

At one time, I had modified such that we would output both DRF AND Rd0 so that we could use the correct leaf respiration (Rd0) with newer versions of ED2 (e.g. r85) as well as still be back compatible with other versions looking for DRF.  However, these fix is not longer in the PEcAn code?  Was this removed for a particular reason? While launching ED2 runs you would get an "ERROR" code saying that DRF was not in the history (for new ED2 versions) you could ignore as it didn't cause any issues with the ensemble runs....I think we need to add back in Rd0 (i.e. at 15C). 

Larger issue, putting Rd0 back into the XML in ED2.  Not at all sure why that was taken back out again!

**Comment by serbinsh** [comment]
Basically adding back in:

```
trait.samples[['Rd0']] <- trait.samples[['leaf_respiration_rate_m2']]

```

**Comment by mdietze** [comment]
@serbinsh Yes, please add it back in. I don't know when/why it was removed. Please submit a pull request then close this issue.

**Comment by serbinsh** [comment]
Okie dokie.  As soon as I have a chance I will get that added back in.  I have assigned myself to this.

**Comment by serbinsh** [comment]
Fixed
