### ISSUE TITLE
Add modeltype.id to posteriors table

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#479]
Right now you can't search/sort/select posteriors by modeltype. Would be helpful to add this column when implementing the data assimilation.

**Comment by robkooper** [comment]
what about the following query:
```
select posteriors.id, pfts.name, modeltypes.name from posteriors, pfts, modeltypes where pft_id=pfts.id and pfts.modeltype_id = modeltypes.id limit 1;
```

**Comment by mdietze** [comment]
That should work. Can we add that in to the display in BETY?

**Comment by robkooper** [comment]
Moved to BETY https://github.com/PecanProject/bety/issues/291
