### ISSUE TITLE
CRUNCEP: met2CF, download, and Brown Dog DAP functions

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#480]
A goal for Flux Course 2015 is to support at least one global met product. Based on our discussion on 4/20/15 we decided to start with CRU-NCEP. There are two options here: 1) generalize the code that @dlebauer already has #461 or 2) pull date from the MSTMIP server directly #354 

A place to start is probably to copy the files @dlebauer has already processed, register them with the Inputs table, and test if the existing EXTRACT function function works already.

Once that is successful we should push that data to the DAP server and write any required DAP wrapper functions.

Finally, to be fully functional we need to implement met2CF and download functions that will work for local, remote, and BD processing. Part of this will require testing that the permute and chunk functions are generalized to work with all regional & global met.

**Comment by dlebauer** [comment]
The CRUNCEP file in PEcAn format is at https://www.betydb.org/inputs/301/ it is 1.2 TB. 

I can use Globus if you give me access to an endpoint, or otherwise use rsync if you give me access to a server ... or if you send me a disk I can return it with the data

**Comment by tonygardella** [comment]
@ankurdesai @jsimkins2 this isn't assigned to anyone, but I assume you guys are the ones I should ask if this can be closed.

**Comment by ankurdesai** [comment]
Yes, this can be closed since we have the mostly working R function for this now running with more products on the way.
