### ISSUE TITLE
AWS Load Balancing

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#481]
sort out how to set up a PEcAn instance on Amazon AWS that uses the load balancing across multiple instances. Based on NACP failure, the approach appears to require setting up a central database VM, a central output location, and configure the web settings in the other images to point to that one database and outdir.

**Comment by mdietze** [comment]
Added documentation to the 1.4.3 Tutorial on how to launch a PEcAn instance on the AWS (currently in Dropbox, will post to website upon release). This approach doesn't require load balancing, as each individual has their own instance, so will punt this to when we need to deal with this in PEcAn 2

**Comment by robkooper** [comment]
closing issue, I'd like to propose we use docker with multiple images (or even kubernetes for this).
