### ISSUE TITLE
Add new site from within PEcAn Google Map web interface

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#482]
This will be much simpler for most users than having to leave PEcAn to go into BETY, define a citation, etc.

**Comment by dlebauer** [comment]
It would be ideal if we could create either a point, rectangle, or polygon

**Comment by mdietze** [comment]
Hand drawing an arbitrary polygon sounds messy and inaccurate. I'd vote for having this issue focus on drawing a point or rectangle (as a goal for v1.4.3) and then create a separate issue for uploading a GIS layer to define a point, set of points, or polygon(s) (which will take more time to implement). We'll have to decide how we want such layers defined internally [what formats can be uploaded directly to postGIS?], but doing GIS conversions strikes me as a nice BrownDog task.

**Comment by dlebauer** [comment]
I agree that drawing polygons is messy. It can wait, but would be great to be able to import a vector of xy or xyz points and insert a polygon. Converting these to PostGIS 3D geoms is tough (e.g. http://gis.stackexchange.com/questions/111212/how-can-i-insert-a-bounding-box-or-polygon-in-a-postgis-geometry-field)

**Comment by robkooper** [comment]
I'm gonna start with a point since most of the code has not been tested with polygon code.

**Comment by ch1eroe1** [comment]
This ajax php insertion call is hooked to the modal.  I am trying to diagnose the insert failure that I am seeing with the local-time and sand-percentage fields on the sites table.

**Comment by ch1eroe1** [comment]
I have the insert-site.php completed for the site insertion into Bety.  One piece that I could not seem to figure out is where elevation fits in.  When I tried a 3D geometry point to include lat, long and elevation the SRID 4326 gave a database insertion error.

I will commit the code today and review with Rob before making a pull request this week.

**Comment by ch1eroe1** [comment]
Created a pull request for this issue today.  If we need to add regex controls or modifications/enhancements we can open a new bug/feature issue.
