### ISSUE TITLE
Add tag for soil data inputs to settings

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#486]
I am doing a regional run and would like to use the [MsTMIP HWSD](https://www.betydb.org/inputs/303) input. 

I'd like to specify the input file. I propose creating a new tag called `<soil>` under `<run><inputs>`, e.g.:

```xml
<run>
    <....other tags...>
    <inputs>
       <met>
             <id>10000000001</id>
        </met>
       <soil>
             <id>303</id>
        </soil>
    <inputs>
</run>
```

Does that sound sensible?

Also, we should begin thinking about the fact that while each input has a 'site', the site may be a polygon and we could search for any points or polygons that fall inside that point when searching for inputs. 

In this particular case "Earth Land Surface" is a point ... but could be a polygon if that would be useful.

**Comment by robkooper** [comment]
The inputs are specified per model. You can in the database add a tag to the modeltype of type soil. If you mark it as required the check.settings code will make sure it is actually in the pecan.xml file.
