### ISSUE TITLE
Issue with rjags running from web interface - Job submission

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#509]
I am hitting a snag when testing job submission through our web interface.  When a job is started PEcAn begins running but hits a snag when loading rjags within the web interface install of PEcAn and depends libs.

```
> #-------------------------------------------------------------------------------
> # Copyright (c) 2012 University of Illinois, NCSA.
> # All rights reserved. This program and the accompanying materials
> # are made available under the terms of the
> # University of Illinois/NCSA Open Source License
> # which accompanies this distribution, and is available at
> # http://opensource.ncsa.illinois.edu/license.html
> #-------------------------------------------------------------------------------
>
> # ----------------------------------------------------------------------
> # Load required libraries
> # ----------------------------------------------------------------------
> library(PEcAn.all)
Loading required package: PEcAn.DB
Loading required package: DBI
Loading required package: PEcAn.utils
Loading required package: abind
Loading required package: plyr
Loading required package: XML
Loading required package: ggplot2
Loading required package: randtoolbox
Loading required package: rngWELL
This is randtoolbox. For overview, type 'help("randtoolbox")'.
Loading required package: ncdf4
Loading required package: udunits2
Loading required package: RCurl
Loading required package: bitops
Loading required package: PEcAn.settings
Loading required package: lubridate

Attaching package: 'lubridate'

The following object is masked from 'package:plyr':

    here

Loading required package: PEcAn.MA
Loading required package: rjags
Loading required package: coda
Error : .onLoad failed in loadNamespace() for 'rjags', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/data/software/R/library/rjags/libs/rjags.so':
  libjags.so.3: cannot open shared object file: No such file or directory
Error: package 'rjags' could not be loaded
Execution halted

```

However, rjags was install successfully in that location and I can load rjags in R terminal, using that specific install location, just fine?  This only happens when a job is launched through the web interface?  Looks like it isn't loading the jags libs properly

Has anyone seen this before? Any suggestions?

@robkooper @mdietze @dlebauer

**Comment by mdietze** [comment]
Does apache have permissions to access everything?

Do you get the same error when running through the web-based Rstudio server?

**Comment by serbinsh** [comment]
@mdietze I am not sure about apache, how would I give apache permissions?  Give the user apache permissions?

Also, how do you run the web-based Rstudio version?  I have Rstudio server running and can log in OK.  I am just not sure I know how to run PEcAn this way, other than how I would normally using the workflow.R etc. 

I guess I can try by going to the output dir and trying to launch the workflow. Trouble is, I am logging into Rstudio as me which does have the libs loaded ok.  I need to log on like I would be an annonymous or PEcAn user, like with the web interface.  Make sense?

**Comment by serbinsh** [comment]
Strange

If I log on to Rstudio server as me and use my default R lib dir, I still have errors loading PEcAn

```
[1] "/home0/sserbin/R/library" "/usr/lib64/R/library"     "/usr/share/R/library"    
> library(PEcAn.all)
Loading required package: PEcAn.DB
Loading required package: PEcAn.utils
Loading required package: ncdf4
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home0/sserbin/R/library/ncdf4/libs/ncdf4.so':
  libmpi.so.1: cannot open shared object file: No such file or directory
Error: package ‘ncdf4’ could not be loaded
Error during wrapup: object 'settings' not found
```

This time with netcdf?  Not really sure why when I log on through the web I am running into these errors?

**Comment by serbinsh** [comment]
When logged on to the server through terminal (ssh) I can load ncdf4 just fine....

**Comment by robkooper** [comment]
Check your LD_LIBRARY_PATH and see if that is set.

**Comment by robkooper** [comment]
the other option is to do `ldd /home0/sserbin/R/library/ncdf4/libs/ncdf4.so` which should point to the location of the library files.

**Comment by serbinsh** [comment]
"Check your LD_LIBRARY_PATH and see if that is set."

For which user?  Again, it works through terminal just fine for my user account.  It happens when I run the web interface.  Even if I load Rstudio server and log in as me using my R/lib folder

**Comment by robkooper** [comment]
Start with the user it works for, same as the ldd command, then run `sudo -u apache 'echo $LD_LIBRARY_PATH'` and `sudo -u apache 'ldd /home0/sserbin/R/library/ncdf4/libs/ncdf4.so'` and see if they are the same.

**Comment by serbinsh** [comment]
```
[sserbin@test web]$ $LD_LIBRARY_PATH
-bash: /data/software/jags/3.4.0/lib64:/data/software/libxml2/2.9.2/lib:/data/software/cdo/1.6.8/lib:/data/software/nco/4.4.8/lib:/data/software/netcdf/4.3.3.1/lib:/data/software/hdf5/1.8.14/lib:/data/software/hdf4/4.2.11/lib:/data/software/gdal/1.11.2/lib:/data/software/geos/3.4.2/lib:/data/software/libkml/devel/lib:/data/software/geotiff/1.4.1/lib:/data/software/libtiff/4.0.4/lib:/data/software/proj/4.9.1/lib:/data/software/json-c/main/lib:/data/software/openmpi/1.8.4-gnu484/lib:/data/software/gcc-4.8.4/share:/data/software/gcc-4.8.4/lto-plugin:/data/software/gcc-4.8.4/zlib:/data/software/gcc-4.8.4/libiberty:/data/software/gcc-4.8.4/libexec:/data/software/gcc-4.8.4/libdecnumber:/data/software/gcc-4.8.4/libcpp:/data/software/gcc-4.8.4/libbacktrace:/data/software/gcc-4.8.4/lib64:/data/software/gcc-4.8.4/lib:/data/software/gcc-4.8.4/x86_64-unknown-linux-gnu: No such file or directory
```

For my user account.  Again, it works fine.  What I want to fix is the connection between the R/libs that are used wtih the web interface and the netcdf and jags libs.  I don't understand why they work through terminal but not when running it through the web?

Maybe it has to do with the apache user

**Comment by robkooper** [comment]
Make sure the apache user has the same LD_LIBRARY_PATH.

**Comment by serbinsh** [comment]
OK.

**Comment by serbinsh** [comment]
Indeed @mdietze apache is the user running through the web, given the output permissions:
```
total 0
drwxr-xr-x. 2 apache apache  75 Jun 25 11:46 PEcAn_2000000002
drwxr-xr-x. 2 apache apache  75 Jun 25 11:47 PEcAn_2000000003
drwxr-xr-x. 2 apache apache 100 Jun 25 11:56 PEcAn_2000000004
drwxr-xr-x. 2 apache apache 100 Jun 25 12:14 PEcAn_2000000005
drwxr-xr-x. 2 apache apache  75 Jun 25 13:18 PEcAn_2000000006
drwxr-xr-x. 2 apache apache 100 Jun 25 13:42 PEcAn_2000000007

```

**Comment by serbinsh** [comment]
@robkooper 
Would I add this to the:
/etc/sysconfig/httpd

file?

That is add: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/folder_with_library/
with the same lib locations?  Or is there a better way to update the lib paths for the apache user.  I don't need to log on as that user, do I?

Sorry for my ignorance!

**Comment by serbinsh** [comment]
@mdietze @robkooper 

Did either of you update your Rstudio server file according to these instructions to enable connection with external libs?

```
External Libraries

You can add elements to the default LD_LIBRARY_PATH for R sessions (as determined by the R ldpaths script) by adding an rsession-ld-library-path entry to the server config file. This might be useful for ensuring that packages can locate external library dependencies that aren't installed in the system standard library paths. For example:

rsession-ld-library-path=/opt/local/lib:/opt/local/someapp/lib

```

This may explain my Rstudio server issues

**Comment by robkooper** [comment]
i did not. but I think this will be solved as well if you add all the directories from your LD_LIBRARY_PATH to /etc/ld.so.conf.d/pecan.conf

**Comment by serbinsh** [comment]
@robkooper OK

**Comment by serbinsh** [comment]
Having some issues getting the pecan.conf to load when running ldconfig  It shows up for my user but not for apache?!?!  very frustrating

**Comment by serbinsh** [comment]
OK, so adding pecan.conf to /etc/ld.so.conf.d fixed both Rstudio server and PEcAn web interface runs:

My files looks like this:

```
/data/software/jags/3.4.0/lib64
/data/software/libxml2/2.9.2/lib
/data/software/cdo/1.6.8/lib
/data/software/nco/4.4.8/lib
/data/software/netcdf/4.3.3.1/lib
/data/software/hdf5/1.8.14/lib
/data/software/hdf4/4.2.11/lib
/data/software/gdal/1.11.2/lib
/data/software/geos/3.4.2/lib
/data/software/libkml/devel/lib
/data/software/geotiff/1.4.1/lib
/data/software/libtiff/4.0.4/lib
/data/software/proj/4.9.1/lib
/data/software/json-c/main/lib
/data/software/openmpi/1.8.4-gnu484/lib
/data/software/gcc-4.8.4/share
/data/software/gcc-4.8.4/lto-plugin
/data/software/gcc-4.8.4/zlib
/data/software/gcc-4.8.4/libiberty
/data/software/gcc-4.8.4/libexec
/data/software/gcc-4.8.4/libdecnumber
/data/software/gcc-4.8.4/libcpp
/data/software/gcc-4.8.4/libbacktrace
/data/software/gcc-4.8.4/lib64
/data/software/gcc-4.8.4/lib
/data/software/gcc-4.8.4/x86_64-unknown-linux-gnu
```

But this is somewhat of a kludge and requires make sure this is up-to-date when updating libraries. I am going to talk with my IT guy tomorrow to try and setup an ability to easily change the libs availible to the apache user, maybe through modules.

I will update when I know more.

**Comment by serbinsh** [comment]
Turns out this is the best solution at the moment.
