### ISSUE TITLE
assim.batch requires flux_uncertainty

### ISSUE THREAD

**Issue by ankurdesai** [PecanProject/pecan#510]
flux_uncertainty.R (in /modules/uncertainty) needs to be sourced/in the library before running assim.batch/pda.mcmc.R. Web interface currently breaks trying to run MCMC because of that. I'm not 100% sure how to properly change all/ to have that included. So I'm leaving that to @ryankelly-uiuc 

@ryankelly-uiuc  Almost have MCMC running through the web interface, after running pda.mcmc line by line in rstudio based on a web-interface generated workflow and pecan.xml. Learned that if the tag iter is set to a small number (like 1, as in your example), then in pda.postprocess (in pda.utils) will fail at pda.plot.params because it tries to address the array from "0.2" to end, and the seq function in plot dies. May need to put a floor or a check if <= 1 iteration.

**Comment by mdietze** [comment]
For flux uncertainty, we need to add ROxygen documentation to the functions and make sure to include the '@export' tag. 

For the iter problem, we really should start using seq.along instead of seq precisely to avoid these issues of no iterations.

**Comment by ryankelly-uiuc** [comment]
> For flux uncertainty, we need to add ROxygen documentation to the functions and make sure to include the '@export' tag.

Does this mean that `require(PEcAn.uncertainty)` won't work until the Roxygen stuff is done?

> For the iter problem, we really should start using seq.along instead of seq precisely to avoid these issues of no iterations.

Interesting. I hadn't heard of `seq_along`. Not sure I see why it would be useful here, as opposed to a simple `ceiling`. The code in question is:

    burnin <- min(2000,0.2*nrow(params))
    params.subset <- as.data.frame(params[burnin:nrow(params),prior.ind])

**Comment by mdietze** [comment]
require(PEcAn.uncertainty) as to be there, but not all the functions you need will be in there unless they are explicitly exported. If there are just a few functions that are needed you can set up a minimal documentation with just a @name, @title, and @export

seq_along solves the classic problem of a sequence 1:length(n) returning 1:0 (and thus running backwards into invalid values) when n doesn't exists. It might not be the perfect solution for burnin:nrow(params) but I know I'd written so many hacks over > decade to solve that problem before discovering seq_along and seq_length this year
