### ISSUE TITLE
Sensitivity analysis not varying values

### ISSUE THREAD

**Issue by Viskari** [PecanProject/pecan#516]
I've been trying to figure out a problem I'm having and thought to ask it here.

So we have the pecan system now running on our server and are running the analysis pretty well on it. However, when trying to run sensitivity analysis for albedo, it uses the same radiative parameter values for all the quantiles. So for example, if I have six quantiles and am looking at how leaf_trans_vis, for example, it uses the same value for that parameter in all of the quantiles. However, when I look at the ensemble runs, there it is varying those values correctly.

This seems to only happen with the new variables involving radiative properties, so I thought to ask here if there is any thought what might be causing this?

**Comment by dlebauer** [comment]
Have you added the parameters to write.configs.ED? To the trait dictionary?
To the PFT?

Maybe this is a good time to document how to add a parameter ...

**Comment by Viskari** [comment]
The PFT contains those parameter values and, as written, for the ensemble
it does successfully vary the parameter values.

As for the trai dictionary and write.configs.ED, I thought both of those
were addressed by adding the parameter to the history file. Do I need to
add it somewhere as well? Also on write.configs.ED, it is successfully
writing those parameter values in to the config.XML, it just doesn't vary
the value in the sensitivity analysis.

**Comment by serbinsh** [comment]
David

Based on the results below, with ED2 version r81, we know that PEcAn is writing out the SA quantiles.  However with the new version of ED2 Toni seems to be have some challenges replicating these results.  Trouble is the inconsistencies between the runs where we are using the same PEcAn but different ED2 versions. 

Toni, you did indeed update the history file, correct?  I assume since it isn't giving you a "XXXX not found in trait dictionary"

![variancedecomposition albedo 2004](https://cloud.githubusercontent.com/assets/3067369/8387023/52441092-1c23-11e5-89a1-614dbc1c2018.jpg)

**Comment by Viskari** [comment]
Yeah, I updated it when we started with this. We are now using the .rgit
history file for these runs.

**Comment by Viskari** [comment]
And forgot to mention the reason we are getting inconsistent results is
that when it runs the sensitivity analsysi with ED2.r81, it is actually
giving different values to the relevant quantiles, something it is not
doing with git version of ED2. So evidently I need to add something
somewhere, but I don't quite know what and where.

**Comment by dlebauer** [comment]
Is there value in making sure that we get valid results with ED.r81? (beyond the ideal case where my original Switchgrass analyses could be reproduced).

Your comment "I need to add something somewhere, but I don't quite know what and where." seems inconsistent with marking this issue closed ...
 
If there is value in getting the particular version to work, it would be worthwhile to reopen this issue or open a separate issue (perhaps in the ED repository? if you do, please provide a link to the new issue here ...).  And then, it would be great to place a tag or branch of ED.r81 version in one of the repositories in the EDmodel organization. 

If, on the other hand, getting ED.r81 to work is worth the effort required to fix it (in addition to a few weeks I spent many years ago ... ) we can write that version off as a bug, keep this issue closed, and move on, with appreciation for GitHub and moving beyond the annual merges that occurred in the early days of ED2 during which changes were often lost and functionality was broken.

**Comment by Viskari** [comment]
Sorry about the lack of comment on the matter. It turned out to have been
an issue with ED2 and the varying versions of going around. It wasn't
actually an issue with PEcAn, which is why I forgot this issue before going
through the list today.

The current version of r81 should work fine, since there is nothing
actually added to it and the way the pecan code was adjusted was that it
will stil read in correctly the ED2.r81 outputs. What I cannot comment on,
though, is how well those results will remain consistant with the
developing version of ED2.
