### ISSUE TITLE
Minor: add.models.sh needs to update package name for Biocro

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#523]
In the add.models.sh script we have:

````
addModelFile "${FQDN}" "BioCro" "BIOCRO" "" "biocro.Rscript" "${R_LIBS_USER}/PEcAn.biocro"
```
But PEcAn installs biocro as: PEcAn.BIOCRO

@robkooper do we need to change this to:
````
addModelFile "${FQDN}" "BioCro" "BIOCRO" "" "biocro.Rscript" "${R_LIBS_USER}/PEcAn.BIOCRO"
```
?  In R it won't load unless we can the correct uppercase name.

**Comment by serbinsh** [comment]
@robkooper @dlebauer Is this an issue?

**Comment by dlebauer** [comment]
@serbinsh looks like you are correct - good catch. But I am not sure how BioCro is handled as a special case here. PR #530 provides the fix if @robkooper confers
