### ISSUE TITLE
How do add DALEC model using addModelFile?

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#524]
I am attempting to register DALEC with Bety in a location other than /usr/bin, but instead in a sandbox location so that it is available to the cluster nodes.  For both ED2 and SIPNET I have registered models like this:

```
addModelFile "modex.test.bnl.gov" "ED2" "ED2" "81" "ed_2.1-opt" "/data/software/ED2/ED2.r81"
addModelFile "modex.test.bnl.gov" "SIPNET" "SIPNET" "unk" "sipnet.runk" "/data/software/sipnet"
```
where I have model name ED2, type ED2, revision 81 or unk and binary, followed by the path to the binary.

However, attempting to do this with DALEC, such as:
```
addModelFile "modex.test.bnl.gov" "DALEC.seqMH" "DALEC" "dalec_seqMH" "/data/software/dalec_EnKF_pub"
```
gives me this error

```
ERROR:  new row for relation "dbfiles" violates check constraint "no_slash_in_file_name"
DETAIL:  Failing row contains (2000000102, /data/software/dalec_EnKF_pub, , null, null, null, 2000000001, 2015-06-30 16:14:22.75521, 2015-06-30 16:14:22.75521, Model, 2000000007).
File //data/software/dalec_EnKF_pub added to model DALEC.seqMH on host modex.test.bnl.gov.
```
Is there a special case with DALEC?  I have tried various permutations with DALEC with various errors

@robkooper @dlebauer @mdietze

**Comment by mdietze** [comment]
In the first two you have 6 arguments, in DALEC you only have 5, so you've forgotten an argument

**Comment by serbinsh** [comment]
Doh!

What worked:

```
addModelFile "modex.test.bnl.gov" "DALEC.seqMH" "DALEC" "pub" "dalec_seqMH" "/data/software/dalec_EnKF_pub"
```
