### ISSUE TITLE
Need to update ED2 r46 version (on the installing models page) so that XML char length is correct

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#537]
@robkooper You need to make sure the version folks download has corrected the: /ED/src/utility/libxml2f90.f90_pp.f90 so it accepts char length longer than 32

**Comment by serbinsh** [comment]
So that it matches char length on mainline:
https://github.com/EDmodel/ED2/blob/master/ED/src/utils/libxml2f90.f90_pp.f90

**Comment by ashiklom** [comment]
@serbinsh Since we've moved to the ED2 git version for production runs, this can be closed, right?

**Comment by serbinsh** [comment]
@ashiklom yup!
