### ISSUE TITLE
default values for CO2?

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#540]
I've got a rather small file of CO2 values from 1765-2500 (!). [rcp.csv](https://gist.github.com/dlebauer/68cdcbf031bc55ffac99) that I plan to use with BioCro. I could treat this the same as other driver files, but this seems so ubiquitous that it could be easier to provide this - at least the fixed historical values - as a dataset built into PEcAn, e.g. in PEcAn.utils or PEcAn.data.atmosphere.

Thoughts?

**Comment by mdietze** [comment]
I disagree. There are multiple alternative CO2 reconstructions and some of them vary spatially, so I don't think we should choose one as the default. 

Datasets should be loaded in the Inputs table, not built into packages.

**Comment by dlebauer** [comment]
I'll put it in the biocro package.
