### ISSUE TITLE
Sensitivity analysis crashes during ED2 workflow

### ISSUE THREAD

**Issue by Viskari** [PecanProject/pecan#545]
Hello,

 For some reason after recently updating the pecan, I started getting the following error when running the sensitivity analysis tag in the pecan workflow for ED2. It prints out a number of stats, but then crashes when moving to the ensemble analysis, at least I think it is at that point as the debug doesn't give any variable name at that point. Also for some reason this seems to be connected to the ensemble size, so for example it doesn't happen with ensemble size 5 or 10, but it does happen with ensemble size of 1 or 50, at least based on my current tests.

[1] "----- Median  Albedo :  0.114302255213261"
2015-07-02 11:58:15 ERROR  [read.output] :
   no netCDF files of model output present
[1] "Years:  2004  -  2004"
[1] "----- Mean  Albedo  :  "
[1] "----- Median  Albedo :  "
Error in sa.output[quantile, trait] <- sapply(out, mean, na.rm = TRUE) :
  replacement has length zero
Calls: get.results -> read.sa.output

Thought I should ask for advice here to begin with.

**Comment by serbinsh** [comment]
I have seen this too when testing the web interface with 1 ensemble

------------------------------------------------------------------------------
Shawn P. Serbin
Biological, Environmental & Climate Sciences Department
Brookhaven National Laboratory
Upton, NY 11973-5000

Phone: +1-631-344-3165
Fax: +1-631-344-2060
Email: sserbin@bnl.gov<mailto:sserbin@bnl.gov>
Bio:  http://www.bnl.gov/envsci/bio/serbin-shawn.php
TEST Group: http://www.bnl.gov/TEST/
Twitter: @doctorjackpine, @test_bnl
------------------------------------------------------------------------------

On Jul 2, 2015, at 12:05 PM, Viskari <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

For some reason after recently updating the pecan, I started getting the following error when running the sensitivity analysis tag in the pecan workflow for ED2. It prints out a number of stats, but then crashes when moving to the ensemble analysis, at least I think it is at that point as the debug doesn't give any variable name at that point. Also for some reason this seems to be connected to the ensemble size, so for example it doesn't happen with ensemble size 5 or 10, but it does happen with ensemble size of 1 or 50, at least based on my current tests.

[1] "----- Median Albedo : 0.114302255213261"
2015-07-02 11:58:15 ERROR [read.output] :
no netCDF files of model output present
[1] "Years: 2004 - 2004"
[1] "----- Mean Albedo : "
[1] "----- Median Albedo : "
Error in sa.output[quantile, trait] <- sapply(out, mean, na.rm = TRUE) :
replacement has length zero
Calls: get.results -> read.sa.output

Thought I should ask for advice here to begin with.

**Comment by mdietze** [comment]
You need to look further backwards in the log. "no netCDF files of model output present" means the model crashed.
