### ISSUE TITLE
PEcAn RTM Package -- Windows compatibility

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#550]
Attempting to install the package on Windows fails with the following: "Error: Unix-only package".

My guess is that the way to fix this is by tweaking the `Makevars.win` file, possibly by removing bash-isms like wildcard expansion.

**Comment by tonygardella** [comment]
@ashiklom is this still a problem?

**Comment by ashiklom** [comment]
Yes, it is. Probably can leave it open for now.
