### ISSUE TITLE
create a table to store identifier for site

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#565]
We should have a table to allow the user to specify the site specific identifier for external data stores. For example right now we have a site "Sylvania Wilderness (US-Syv)" and the last part is Amerifux specific identifier. If we want to use a different external data source with this site we might not be able to use the sitename to find the right marker.

This could be as simple as adding a new table that contains the following entries:
site-id - type - identifier

type can be Ameriflux, NARR, FACE, PALEON etc.
identifier will be US-Syv in the case of Ameriflux and example site.

**Comment by mdietze** [comment]
@robkooper is this different from the "sitenetwork" table proposed at the end of #271 ?

**Comment by robkooper** [comment]
nope this is the same, closing issue
