### ISSUE TITLE
How to use modellauncher, or otherwise bundle jobs for HPCs with limits on job number or shared nodes?

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#566]
I am using two servers. One (biocluster.igb.illinois.edu) has limits on the number of jobs that can be submitted (~200) and the other (roger.ncsa.illinois.edu) only allows one job per node. These cases seem to require bundling jobs at the level of the `job.sh` script or `start.runs` function (or otherwise at the PEcAn level). Not possible to do by simply altering the qsub command arguments. 

I am going to start by manually launching jobs but wanted to check to see 

* does `start.runs` has any functionality for handling limits on job number?
* does the launcher script handle this, and if so how do I use it?
* other options?

**Comment by robkooper** [comment]
There is some code for this, but has never been tested:
https://github.com/PecanProject/pecan/blob/master/settings/R/read.settings.R#L592

Most of it should be wired in the code for run.jobs as well. This will use a wrapper script to launch a bigjob, which will use mpi to launch lots of smaller jobs. This uses a binary called modellauncher which is included in the source code in https://github.com/PecanProject/pecan/tree/master/utils/modellauncher.

To configure this you will need to add the following to your pecan.xml:
```
<run>
  <host>
    <modellauncher>
      <binary>path to modellauncher binary on host</binary>
      <qsub.extra>any extra qsub flags such as -l ncpus=2</qsub.extra>
      <mpirun>path to mpirun, if not specified will assume it is on the path</mpirun>
    </modellauncher>
  </host>
</run>
```

If you use this, please let me know about the results since this is pretty much untested with PEcAn.

**Comment by dlebauer** [comment]
I haven't gotten around to trying the modellauncher, but have experimented with submitting batch jobs.

This script https://gist.github.com/dlebauer/fca449b81567eda4c729 will generate a `runs.sh` script for submitting all jobs (via `array.pbs`) in batches that allow one job per node and multiple jobs per core.

**Comment by dlebauer** [comment]
@robkooper do you have any examples or suggestions for setting up the modellauncher?

From the [read.settings function](https://github.com/PecanProject/pecan/blob/master/settings/R/read.settings.R) I see that it has the following tags:

* `binary` optional, default is 'modellauncher'
* `qsub.extra` required, how can I determine this?
* mpirun (optional, default is 'mpirun')

(These are used in the [`start.runs` function](https://github.com/PecanProject/pecan/blob/master/utils/R/start.model.runs.R))

Perhaps I just need to know the value for `qsub.extra`. What settings might go here?

Do I also need to compile the modellauncher.c using make? If so, should i compile and then copy it to roger?

**Comment by dlebauer** [comment]
### Answer

1. compile model launcher on HPC

    ```sh
## on HPC
rsync server.with.pecan:path/to/pecan/utils/modellauncher/modellauncher.c ./
module load mpich
make
```
2. add the following to settings file

    ```xml
<modellauncher>
    <binary>/home/dlebauer/dev/pecan/utils/modellauncher/modellauncher</binary>
</modellauncher>
```
3. Proceed as usual

**Comment by dlebauer** [comment]
opened new issue "when would a user use the `<qsub.extra>` tag?" (#618)

**Comment by dlebauer** [comment]
update: successfully finished a set of calibration runs for Miscanthus across IL on Roger using model launcher for 3500 independent jobs divided into 7 batches...

Thanks @robkooper
