### ISSUE TITLE
How to create a non-point site?

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#570]
Specifically, I'd like to create a 'site' for the NLCD dataset which has the following geographic info:

The map projection used is Albers Conical Equal Area.

Projection parameters:
Standard_Parallel: 29.500000
Standard_Parallel: 45.500000
Longitude_of_Central_Meridian: -96.000000
Latitude_of_Projection_Origin: 23.000000
False_Easting: 0.000000
False_Northing: 0.000000
Planar coordinates are encoded using row and column
Abscissae (x-coordinates) are specified to the nearest 30.000000
Ordinates (y-coordinates) are specified to the nearest 30.000000
Planar coordinates are specified in meters

The horizontal datum used is North American Datum of 1983.
The ellipsoid used is Geodetic Reference System 80.
The semi-major axis of the ellipsoid used is 6378137.000000.
The flattening of the ellipsoid used is 1/298.257222.

**Comment by dlebauer** [comment]
Does this help PecanProject/bety#129? The points are Lon Lat elevation. I think the last argument is the projection.

```sql
UPDATE sites
SET geometry = ST_Geomfromtext('POLYGON((-76.116081 42.794448 415, 
                                         -76.116679 42.794448 415, 
                                         -76.116679 42.79231 415, 
                                         -76.116081 42.79231 415,
                                         -76.116081 42.794448 415))', 4326)
WHERE
	ID = 1123
```

**Comment by mdietze** [comment]
Thanks, that helped a lot. The following seems to have worked

```
UPDATE sites
SET geometry = ST_Transform(ST_Geomfromtext('POLYGON((-130.232828 21.742308 0, 
                                         -130.232828 52.877264 0, 
                                         -63.672192 52.877264 0, 
                                         -63.672192 21.742308 0,
                                         -130.232828 21.742308 0))', 4269),4326)
WHERE
    ID = 1000000676
```

I needed to add the ST_Transform because the NLCD is in NAD83 (espg = 4269) and the database seems to be using WGS84 (espg = 4326)
