### ISSUE TITLE
Met workflow updates XML wrong?

### ISSUE THREAD

**Issue by ryankelly-uiuc** [PecanProject/pecan#585]
If I use browndog to retrieve met data, then my settings list gets a bunch of tags added under `inputs$met$path`, e.g.:
```xml
 <met>
  <source>Ameriflux</source>
  <output>SIPNET</output>
  <path>
   <file>/fs/data2/rykelly/.pecan/dbfiles/BD-61a75fcd1b1a/sipnet.clim</file>
   <host>pecan2.bu.edu</host>
   <mimetype>text/csv</mimetype>
   <formatname>Sipnet.climna</formatname>
   <startdate>2002/01/01</startdate>
   <enddate>2002/12/31</enddate>
   <dbfile.name>sipnet.clim</dbfile.name>
  </path>
 </met>
```
This doesn't seem right, right? I assume host, mimetype, etc. are all supposed to be under `met`, not `met$path`? Fortunately, `run.write.configs()` uses the first item in `met$path` and just gives a warning:
```Warning in gsub("@SITE_MET@", template.clim, jobsh) :
  argument 'replacement' has length > 1 and only the first element will be used
```
But I'm worried about this causing problems elsewhere or in the future.

**Comment by robkooper** [comment]
Correct. Only the value from file should have been copied.

**Comment by ryankelly-uiuc** [comment]
And actually, just accidentally found somewhere it breaks the code: If you try to read in an xml file that has the settings saved like that, then `read.settings()` fails (in `check.inputs()`).
