### ISSUE TITLE
Long PEcAn runs hit errors with DB sync

### ISSUE THREAD

**Issue by rykelly** [PecanProject/pecan#588]
This has been discussed elsewhere but wanted to document here. I received the following error while running 5000 iterations of PDA using SIPNET:

```
Error in postgresqlExecStatement(conn, statement, ...) :
  RS-DBI driver: (could not Retrieve the result : ERROR:  deadlock detected
DETAIL:  Process 15411 waits for RowShareLock on relation 94001 of database 25609; blocked by process 22291.
Process 22291 waits for AccessExclusiveLock on relation 94165 of database 25609; blocked by process 15411.
HINT:  See server log for query details.
)
Warning in postgresqlQuickSQL(conn, statement, ...) :
  Could not create executeINSERT INTO runs(model_id, site_id, start_time, finish_time, outdir,created_at, ensemble_id, parameter_list)values ('10','772','2002/01/01','2002/12/31','','2015-07-28 03:12:12',1000001598,'MCMC_chain._iteration.3664')
2015-07-28 03:12:13 SEVERE [utils.R#50: logger.severe] :
   Error executing db query 'INSERT INTO runs(model_id, site_id, start_time, finish_time,
   outdir,created_at, ensemble_id, parameter_list)values
   ('10','772','2002/01/01','2002/12/31','','2015-07-28
   03:12:12',1000001598,'MCMC_chain._iteration.3664')' errorcode=0 message='ERROR: deadlock detected
   DETAIL: Process 15411 waits for RowShareLock on relation 94001 of database 25609; blocked by
   process 22291. Process 22291 waits for AccessExclusiveLock on relation 94165 of database 25609;
   blocked by process 15411. HINT: See server log for query details. '
Error in logger.severe(paste("Error executing db query '", query, "' errorcode=",  :
  Error executing db query 'INSERT INTO runs(model_id, site_id, start_time, finish_time, outdir,created_at, ensemble_id, parameter_list)values ('10','772','2002/01/01','2002/12/31','','2015-07-28 03:12:12',1000001598,'MCMC_chain._iteration.3664')' errorcode=0 message='ERROR:  deadlock detected
DETAIL:  Process 15411 waits for RowShareLock on relation 94001 of database 25609; blocked by process 22291.
Process 22291 waits for AccessExclusiveLock on relation 94165 of database 25609; blocked by process 15411.
HINT:  See server log for query details.
'
```

Based on discussions with @robkooper , this is probably due to Pecan trying to access BETY during the automated database sync, which is possible any time but obviously more likely with a workflow that runs for a long time.

**Comment by ryankelly-uiuc** [comment]
Any thoughts on how to resolve this, @robkooper ? I'm still unable to reliably run a long analysis without this error occurring. I can continue to work around it, but it would definitely help my project if we could get a permanent fix in place.

**Comment by dlebauer** [comment]
Not a permanent fix, but I think we have started syncing lots of provenance
(runs) rows that are from test runs and could be deleted. Removing these
could at least speed up the sync.
>
>
Otherwise, is there a way to pause the workflow during the sync, like
'while I get this error, sys.sleep()'?

**Comment by ryankelly-uiuc** [comment]
> Otherwise, is there a way to pause the workflow during the sync, like 'while I get this error, sys.sleep()'?

Yes, I think that I could write a fix on my end along these lines. Probably we could even add something to `db.query()` that would solve it generally. But I think from previous discussions with @robkooper that he has something in mind on the DB side.

**Comment by robkooper** [comment]
My goal is to find out why this is happening, it should not anymore since I am using transactions. I will need to look. One option is to use smaller transactions.

**Comment by istfer** [comment]
hi all, I was doing some long runs with SIPNET and just wanted to let you know that this is still happening

**Comment by robkooper** [comment]
@istfer and @rykelly do you still see this?

**Comment by istfer** [comment]
I haven't been giving such long runs for a while, although I remember seeing it the last time I did, some time before AGU.. But I usually stop writing runs to the DB to get around it so I can't say for sure. I'll give one long run soon, will let you know

**Comment by rykelly** [comment]
I didn't have the issue when doing my large multisite runs. A good sign, though those hit the DB much less often than the PDA runs I was doing back in the day.

⁣[ mobile ]​

**Comment by istfer** [comment]
looks like I'm not hitting this anymore with the long PDA runs. Closing it now.
