### ISSUE TITLE
Missing file causes PEcAb crash when running a PFT with priors that have no observations

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#590]
@Viskari and I noticed a bug on his version of PEcAn yesterday. This may be a special case but we found an issue where PEcAn will crash mid-run if you are running with a PFT that has priors for traits that have no observations. I still need to check that we were using the latest build of PEcAn.

Here is the error message:

```
2015-07-28 13:26:52 INFO   [#2: run.write.configs] :
   PFT Optics.Temperate_Early_Hardwood has MCMC samples for: clumping
2015-07-28 13:26:52 INFO   [#2: run.write.configs] :
   PFT Optics.Temperate_Early_Hardwood will use prior distributions for:
   leaf_trans_vis leaf_trans_nir leaf_reflect_vis leaf_reflect_nir
2015-07-28 13:26:52 INFO   [#2: run.write.configs] :
   using 7004 samples per trait
Warning in readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '/data/tviskari/pecan/pft/Optics.Temperate_Mid_Hardwood/trait.mcmc.Rdata', probable reason 'No such file or directory'
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: run.write.configs -> load -> readChar
[1] "----------------------------------------------------------------------"
[1] "DONE"
[1] "----------------------------------------------------------------------"
[tviskari@modex tviskari]$ dir /data/tviskari/pecan/pft/Optics.Temperate_Early_Hardwood/
clumping.model.bug            ma.summaryplots.clumping.pdf  post.distns.Rdata             prior.distns.csv              species.csv                   trait.data.Rdata
madata.Rdata                  meta-analysis.log             posteriors.pdf                prior.distns.Rdata            trait.data.csv                trait.mcmc.Rdata
[tviskari@modex tviskari]$ dir /data/tviskari/pecan/pft/Optics.Temperate_Mid_Hardwood/
prior.distns.csv    prior.distns.Rdata  species.csv         trait.data.csv      trait.data.Rdata
```

I feel like we had this issue before, a few years back.  If you have at least one trait-prior combo that has some observations for a MA then you avoid this error.

**Comment by serbinsh** [comment]
@dlebauer or @ryankelly-uiuc Do you see any easy fix for this? E.g. not requiring the trait.mcmc or a special case if that doesn't exist since that will be the case without obs

@Viskari

**Comment by ryankelly-uiuc** [comment]
@serbinsh, yeah, think so. Looks like `get.samples.R` is checking that `trait.mcmc.Rdata` exists in *any* of the pft directories, then trying to load it for one pft in particular. So if any one pft is missing the file, it will error. I think if you just modify `get.samples` L55 slightly it will work. Currently:
```R    if("trait.mcmc.Rdata" %in% dir(unlist(outdirs))) { ```
try changing to:
```R    if("trait.mcmc.Rdata" %in% dir(outdirs[i])) { ```

I'd try it myself but it will probably be quicker for you to test since you have a known failing example.

**Comment by ryankelly-uiuc** [comment]
P.S. L56 (`ma.results <- TRUE`) can be deleted because `ma.results` is never used. Note also that the function does already know how to handle the case where `trait.mcmc.Rdata` doesn't exist—see L76-81. So the change suggested above shouldn't break anything.

**Comment by serbinsh** [comment]
@ryankelly-uiuc I am not having this issue anymore.  I think we can close
