### ISSUE TITLE
Copy of Benchmark Discussion from Redmine

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#592]
<p><strong>Description</strong></p>
  <div class="wiki">

(originally posted by @mdietze 2012-07-31 as [Redmine issue 1206](https://ebi-forecast.igb.illinois.edu/redmine/issues/1207) )
 
  <p>Ankur and I discussed this idea a bit at flux camp. I'm thinking about table that specifies a set of runs that can easily be run for any model using specified inputs for specific sites and tested against specific outputs.  One example would be a set of benchmarks used to regularly test the models (and the functionality of PEcAn itself) periodically and/or before large commits of new code. Another example would the ILAMB benchmarks used to evaluate model performance (<a href="/redmine/issues/1110" class="issue status-2 priority-10 priority-high4 assigned-to-me" title="Download ILAMB benchmark data sources (In Progress)">#1110</a>, <a href="/redmine/issues/1111" class="issue status-1 priority-10 priority-high4" title="Download ILAMB benchmark software (New)">#1111</a>).  One could also use this feature to set up sets of runs (e.g. the NACP site-synthesis). There may be need for a second table that stores the 'scores' for various model perforce metrics for each benchmark that can be used to generate reports (both of the outcome of a specific benchmark or set of benchmarks, and [hopefully] the improvement in model performance over time). Obviously we'll also want the ability to look at the output of any run interactively. Finally, we want it to be relatively easy to define new benchmarks as we add new sites and projects (which is why I'm thinking this should be a table, not something that's hardcoded)</p>
  </div>
</div>
<div class="attachments">

<div id="history">
<h3>History</h3>
  <div id="change-6785" class="journal has-notes has-details">
    <div id="note-1">
    <h4><a href="/redmine/issues/1207#note-1" class="journal-link">#1</a>
    
    Updated by <a href="/redmine/users/3" class="user active">David LeBauer</a> <a href="/redmine/projects/pecan/activity?from=2013-02-21" title="02/21/2013 11:56 am">over 2 years</a> ago</h4>

    <ul class="details">
       <li><strong>Assignee</strong> set to <i>David LeBauer</i></li>
    </ul>
    <div class="wiki editable" id="journal-6785-notes"><div class="contextual"><a href="/redmine/issues/1207/quoted?journal_id=6785" data-method="post" data-remote="true" rel="nofollow" title="Quote"><img alt="Comment" src="/redmine/images/comment.png?1427389109" /></a> <a href="#" onclick="$.ajax({url: &#x27;/redmine/journals/edit/6785.js&#x27;, type: &#x27;get&#x27;}); return false;" title="Edit"><img alt="Edit" src="/redmine/images/edit.png?1427389109" /></a></div><p>flush out a set of tables:</p>

	<p>notes from todays meeting:</p>

	<ul>
	<li>"scores" table to store scores benchmark dataset x for model y verzion z on this date and this is the score </li>
		<li>"benchmarks" tables with, e.g. pft, site, input dataset, result, citation, to be run at checkin? to be run at version release?  
	<ul>
	<li>this table will point to specific data sets, site, time span, inputs, which output are we looking at, what metrics are being used to assess this</li>
		<li>flag for data sets that have also been used in data assimilation</li>
		<li>quick checks vs comprehensive checks (sets of benchmarks)
	<ul>
	<li>code check in set</li>
		<li>version release set </li>
	</ul>
	</li>
		<li>citations</li>
	</ul></li>
	</ul></div>
    </div>
  </div>
  
  <div id="change-6788" class="journal has-notes has-details">
    <div id="note-2">
    <h4><a href="/redmine/issues/1207#note-2" class="journal-link">#2</a>
    
    Updated by <a href="/redmine/users/3" class="user active">David LeBauer</a> <a href="/redmine/projects/pecan/activity?from=2013-02-25" title="02/25/2013 03:06 pm">over 2 years</a> ago</h4>

    <ul class="details">
       <li><strong>File</strong> <a href="/redmine/attachments/download/676/BenchmarkTablesProposed.png">BenchmarkTablesProposed.png</a> added</li>
       <li><strong>Status</strong> changed from <i>New</i> to <i>Needs feedback</i></li>
       <li><strong>Assignee</strong> changed from <i>David LeBauer</i> to <i>Mike Dietze</i></li>
    </ul>
    <div class="wiki editable" id="journal-6788-notes"><div class="contextual"><a href="/redmine/issues/1207/quoted?journal_id=6788" data-method="post" data-remote="true" rel="nofollow" title="Quote"><img alt="Comment" src="/redmine/images/comment.png?1427389109" /></a> <a href="#" onclick="$.ajax({url: &#x27;/redmine/journals/edit/6788.js&#x27;, type: &#x27;get&#x27;}); return false;" title="Edit"><img alt="Edit" src="/redmine/images/edit.png?1427389109" /></a></div><p>First draft of proposed benchmarks tables is <a href="https://www.lucidchart.com/documents/view/49fb-db84-512bc388-a6d7-10cc0a00093e" class="external">posted here</a></p>

	<p><a href="http://www.lucidchart.com/invitations/accept/512bd0df-0f34-4caf-a865-7e6d0a005798" class="external">Version for editing is here</a><br /> (you can sign in with a google account)</p></div>
    </div>
  </div>
  
  <div id="change-6789" class="journal has-details">
    <div id="note-3">
    <h4><a href="/redmine/issues/1207#note-3" class="journal-link">#3</a>
    
    Updated by <a href="/redmine/users/3" class="user active">David LeBauer</a> <a href="/redmine/projects/pecan/activity?from=2013-02-25" title="02/25/2013 03:08 pm">over 2 years</a> ago</h4>

    <ul class="details">
       <li><strong>File</strong> <i>BenchmarkTablesProposed_small.png</i> added</li>
    </ul>
    
    </div>
  </div>
  
  <div id="change-6790" class="journal has-details">
    <div id="note-4">
    <h4><a href="/redmine/issues/1207#note-4" class="journal-link">#4</a>
    
    Updated by <a href="/redmine/users/3" class="user active">David LeBauer</a> <a href="/redmine/projects/pecan/activity?from=2013-02-25" title="02/25/2013 03:08 pm">over 2 years</a> ago</h4>

    <ul class="details">
       <li><strong>File</strong> <a href="/redmine/attachments/download/678/BenchmarkTablesProposed_small.png">BenchmarkTablesProposed_small.png</a> added</li>
    </ul>
    
    </div>
  </div>
  
  <div id="change-6791" class="journal has-details">
    <div id="note-5">
    <h4><a href="/redmine/issues/1207#note-5" class="journal-link">#5</a>
    
    Updated by <a href="/redmine/users/3" class="user active">David LeBauer</a> <a href="/redmine/projects/pecan/activity?from=2013-02-25" title="02/25/2013 03:09 pm">over 2 years</a> ago</h4>

    <ul class="details">
       <li><strong>File</strong> deleted (<del><i>BenchmarkTablesProposed_small.png</i></del>)</li>
    </ul>
    
    </div>
  </div>
  
  <div id="change-6949" class="journal has-notes">
    <div id="note-6">
    <h4><a href="/redmine/issues/1207#note-6" class="journal-link">#6</a>
    
    Updated by <a href="/redmine/users/6" class="user active">Mike Dietze</a> <a href="/redmine/projects/pecan/activity?from=2013-03-07" title="03/07/2013 09:59 am">over 2 years</a> ago</h4>

    <div class="wiki editable" id="journal-6949-notes"><div class="contextual"><a href="/redmine/issues/1207/quoted?journal_id=6949" data-method="post" data-remote="true" rel="nofollow" title="Quote"><img alt="Comment" src="/redmine/images/comment.png?1427389109" /></a> <a href="#" onclick="$.ajax({url: &#x27;/redmine/journals/edit/6949.js&#x27;, type: &#x27;get&#x27;}); return false;" title="Edit"><img alt="Edit" src="/redmine/images/edit.png?1427389109" /></a></div><p>Ok, here are some first thoughts/replies, with hopefully some more concrete suggestions to follow:</p>

	<ul>
	<li>Distinct from integration tests?  I don't think so. I think with an integration test the frequency is probably a bit higher and the first question a bit more boolean (did it run?), but they're probably just parts of a spectrum. I feel that we can achieve both aims with this one set of tools/tables.</li>
	</ul>

	<ul>
	<li>A priori identification of which tests are appropriate for which models? I don't think this is necessary and I don't want to set up barriers to running certain models at certain sites. The fact that crop model will perform poorly at a forest site seems obvious, so I trust most users would just choose not run that test for that model at that site.</li>
	</ul>

	<ul>
	<li>How to handle multiple PFTs? The runs table already knows how to do this (and btw, SIPNET can't run multiple PFTs)</li>
	</ul>

	<ul>
	<li>Summery stats for a suite of variables? This seems to introduce an unnecessary level of complexity given how rare multivariate diagnostics are. These benchmarks are not the ONLY way that we'll evaluate models, just one way that we hope will be simple and automated.</li>
	</ul>

	<ul>
	<li>General impression of the proposed set of tables: 
	<ul>
	<li>It seems too complicated. I feel like we can do this in a way that is simpler to follow</li>
		<li>There doesn't seem to be a clear separation between the definition of a benchmark (my original idea for the 'benchmarks' table) and the runs that have been executed under that benchmark. </li>
		<li>Similarly, if we're doing runs those runs HAVE to show up in the runs table, and there is no run_id here. This would eliminate the need for the benchmarks_output table.</li>
		<li>In general, there needs to be better integration with our existing tables and functionality. In addition to runs, the benchmark data should be in the inputs table, eliminating the need for the benchmarks_data table and benchmarks_runs_data</li>
	</ul></li>
	</ul>

	<ul>
	<li>The two tables I would ADD would be a "metrics" table that defined different possible skill metrics, and a benchmarks_metrics table so that  benchmarks and metrics can have a many-to-many relationship. In other words, I wouldn't pre-define that we only produce the 4 metrics listed in benchmarks_summary (though a shortcut that knew to put those 4 in if you select "Taylor diagram" would be nice).</li>
	</ul>

	<ul>
	<li>I think that we should actually use ensemble_id to link between benchmarks and runs. Most traditional metrics are based on single model run vs data set, but I think in many cases what we will more-and-more want is a comparison that includes both model and data uncertainty (e.g. imagine a Taylor diagram where both the model and data points had ensemble-based uncertainty ellipses around them).</li>
	</ul>

	<p>A few more constraints for moving forward...</p>

	<ul>
	<li>The benchmarks table, used to define the benchmark, can't involve the model explicitly else we can't compare how two models did for the same benchmark. That means that things like pfts can't be in the benchmark definition, since those vary by model.</li>
	</ul>

	<ul>
	<li>We need to think carefully about drivers, as on one level it is possible to specify the drivers in their generic format (which each model should be able to convert from), but on the other hand we eventually want the ability to generate an ensemble over the uncertainty in drivers. There's also the question of whether if you have the same site and same response data (e.g. LAI) but different met drivers whether those are actually two different benchmarks, or just 2 instances of the same benchmark</li>
	</ul>

	<ul>
	<li>It would be nice to be able to convert a previous run into the template for a new benchmark</li>
	</ul>

	<ul>
	<li>It should be easy to set up the same benchmark for multiple sites or a region</li>
	</ul>

	<ul>
	<li>I'm torn on whether there should be a separate table for all the model-specific information, or whether one should just have a 'reference' run_id that lays out what all the model-specific pfts, inputs, settings, etc are. I lean towards the latter since we already built the runs table to store all this info.</li>
	</ul></div>
    </div>
  </div>
  
  <div id="change-6950" class="journal has-notes">
    <div id="note-7">
    <h4><a href="/redmine/issues/1207#note-7" class="journal-link">#7</a>
    
    Updated by <a href="/redmine/users/6" class="user active">Mike Dietze</a> <a href="/redmine/projects/pecan/activity?from=2013-03-07" title="03/07/2013 10:22 am">over 2 years</a> ago</h4>

    <div class="wiki editable" id="journal-6950-notes"><div class="contextual"><a href="/redmine/issues/1207/quoted?journal_id=6950" data-method="post" data-remote="true" rel="nofollow" title="Quote"><img alt="Comment" src="/redmine/images/comment.png?1427389109" /></a> <a href="#" onclick="$.ajax({url: &#x27;/redmine/journals/edit/6950.js&#x27;, type: &#x27;get&#x27;}); return false;" title="Edit"><img alt="Edit" src="/redmine/images/edit.png?1427389109" /></a></div><p>One possible alternative (I haven't flushed this all out yet)...</p>

	<p><strong>benchmarks</strong><br />id<br />site_id<br />input_id<br />variable_id<br />maybe start/stop dates?</p>

	<p><strong>benchmarks_metrics</strong><br />benchmark_id<br />metric_id</p>

	<p><strong>metrics</strong><br />id<br />name<br />description<br />citation_id</p>

	<p><strong>benchmark_ref_runs</strong><br />id<br />benchmark_id<br />model_type ## duplicated in runs / ensembles<br />model_id    ## duplicated in runs / ensembles<br />run_id -> ensemble_id</p>

	<p><strong>benchmark_scores</strong><br />benchmark_id<br />model_id<br />ensemble_id<br />datetime<br />metric_id<br />score</p></div>
    </div>
  </div>
  
  <div id="change-7122" class="journal has-notes has-details">
    <div id="note-8">
    <h4><a href="/redmine/issues/1207#note-8" class="journal-link">#8</a>
    
    Updated by <a href="/redmine/users/3" class="user active">David LeBauer</a> <a href="/redmine/projects/pecan/activity?from=2013-04-03" title="04/03/2013 07:58 pm">over 2 years</a> ago</h4>

    <ul class="details">
       <li><strong>Assignee</strong> changed from <i>Mike Dietze</i> to <i>Rob Kooper</i></li>
    </ul>
    <div class="wiki editable" id="journal-7122-notes"><div class="contextual"><a href="/redmine/issues/1207/quoted?journal_id=7122" data-method="post" data-remote="true" rel="nofollow" title="Quote"><img alt="Comment" src="/redmine/images/comment.png?1427389109" /></a> <a href="#" onclick="$.ajax({url: &#x27;/redmine/journals/edit/7122.js&#x27;, type: &#x27;get&#x27;}); return false;" title="Edit"><img alt="Edit" src="/redmine/images/edit.png?1427389109" /></a></div><p>(Rob: I have made a few changes, but please take a look to make sure it matches what we discussed?)</p>

	<p>You can edit directly here: <a class="external" href="http://www.lucidchart.com/invitations/accept/5350395c-2edc-407c-8bc8-6ecf0a005fa4">http://www.lucidchart.com/invitations/accept/5350395c-2edc-407c-8bc8-6ecf0a005fa4</a></p>

	<p><img src="/redmine/attachments/download/693" alt="" /></p></div>
    </div>
  </div>
  
  <div id="change-7123" class="journal has-details">
    <div id="note-9">
    <h4><a href="/redmine/issues/1207#note-9" class="journal-link">#9</a>
    
    Updated by <a href="/redmine/users/3" class="user active">David LeBauer</a> <a href="/redmine/projects/pecan/activity?from=2013-04-03" title="04/03/2013 08:00 pm">over 2 years</a> ago</h4>

    <ul class="details">
       <li><strong>File</strong> <a href="/redmine/attachments/download/693/benchmark_tables.png">benchmark_tables.png</a> added</li>
    </ul>
    
    </div>
  </div>
  
  <div id="change-8925" class="journal has-notes has-details">
    <div id="note-10">
    <h4><a href="/redmine/issues/1207#note-10" class="journal-link">#10</a>
    
    Updated by <a href="/redmine/users/6" class="user active">Mike Dietze</a> <a href="/redmine/projects/pecan/activity?from=2014-04-15" title="04/15/2014 11:23 am">over 1 year</a> ago</h4>

    <ul class="details">
       <li><strong>Assignee</strong> changed from <i>Rob Kooper</i> to <i>Toni Viskari</i></li>
    </ul>
    <div class="wiki editable" id="journal-8925-notes"><div class="contextual"><a href="/redmine/issues/1207/quoted?journal_id=8925" data-method="post" data-remote="true" rel="nofollow" title="Quote"><img alt="Comment" src="/redmine/images/comment.png?1427389109" /></a> <a href="#" onclick="$.ajax({url: &#x27;/redmine/journals/edit/8925.js&#x27;, type: &#x27;get&#x27;}); return false;" title="Edit"><img alt="Edit" src="/redmine/images/edit.png?1427389109" /></a></div><p>Looking back over our notes from 2012, I think that the schema in comment 7 mostly works for evaluating the benchmarks and storing the scores, with one exception being that I think variable_id really does need to be in the benchmark table since many inputs store multiple variables (e.g. an Ameriflux L2 or L4 file) and we need to know which one we're using for a specific benchmark.</p>

	<p>The other thing I noticed is on the metrics table -- does't that need to be connected to the benchmarks table in addition to benchmarks_ensembles_scores? Otherwise it's not clear, for a given benchmark, what scores we <strong>want to</strong> calculate, we're just storing the metrics we did calculate. This could be done through a simple benchmarks_metrics table</p>

	<p>I'd also argue that we might want site_id in the benchmark table as well in case the scales of the site_id for the model run and the site_id for the input_id are not identical (e.g. if the input is remote sensing). I'm not hugely wed to this, but it probably does need some discussion</p>

	<p>Next, one big thing that is still missing is how we define what each benchmark run should consist of as it's drivers, initial conditions, start date, and end date. We could add start and end date to the benchmarks tables and then set up a inputs_benchmarks table that's identical to the inputs_runs table but which would contain the standardized forms of inputs (e.g. met in the CF standard rather than in the model-specific) and then we're rely on the models themselves to make the best use of those inputs that they can (e.g. ED2 might use veg plot data to set patches and cohorts, while SIPNET would just set the total AGB, and another model might just use that to decide what PFT to run and then spin-up to steady state). So that we're not converting inputs constantly, I think it's fair for the benchmark code, when run for a specific model, to check if there are already "children" from that input_id (i.e. if there's a model-specific derived input that points to the specified input as it's parent_id)</p></div>
    </div>
  </div>
  
  <div id="change-8928" class="journal has-notes">
    <div id="note-11">
    <h4><a href="/redmine/issues/1207#note-11" class="journal-link">#11</a>
    
    Updated by <a href="/redmine/users/74" class="user active">Toni Viskari</a> <a href="/redmine/projects/pecan/activity?from=2014-04-16" title="04/16/2014 10:16 am">over 1 year</a> ago</h4>

    <div class="wiki editable" id="journal-8928-notes"><div class="contextual"><a href="/redmine/issues/1207/quoted?journal_id=8928" data-method="post" data-remote="true" rel="nofollow" title="Quote"><img alt="Comment" src="/redmine/images/comment.png?1427389109" /></a> <a href="#" onclick="$.ajax({url: &#x27;/redmine/journals/edit/8928.js&#x27;, type: &#x27;get&#x27;}); return false;" title="Edit"><img alt="Edit" src="/redmine/images/edit.png?1427389109" /></a></div><p>I will admit that I had to work to understand the reason for some of the structures in the table, but I assume those to be mostly due to the format of the data structure. Thus I have limited capability of commenting on how to develop the data table format, as I wrote in the code the information I felt was needed.</p>

	<p>As for the actual information, I think the site_id is needed here and even more the location ids for the data points if available, as we are already separately indicating the time window and metrics. As we are building a structure to include different models at different locations, I think it is important to clearly specify the locations of observations.</p>

	<p>Going forward I think it is important to also start thinking how strict do we want the benchmarks to be and what need to be the standards we use. We also need to find a way to communicate those to the users efficiently.</p></div>
    </div>
  </div>
  
  <div id="change-9041" class="journal has-notes has-details">
    <div id="note-12">
    <h4><a href="/redmine/issues/1207#note-12" class="journal-link">#12</a>
    
    Updated by <a href="/redmine/users/6" class="user active">Mike Dietze</a> <a href="/redmine/projects/pecan/activity?from=2014-04-29" title="04/29/2014 08:38 am">over 1 year</a> ago</h4>

    <ul class="details">
       <li><strong>File</strong> <a href="/redmine/attachments/download/844/Benchmark%20tables%20(042914)%20-%20Benchmarks%20tables%20(revised)-3.png">Benchmark tables (042914) - Benchmarks tables (revised)-3.png</a> added</li>
    </ul>
    <div class="wiki editable" id="journal-9041-notes"><div class="contextual"><a href="/redmine/issues/1207/quoted?journal_id=9041" data-method="post" data-remote="true" rel="nofollow" title="Quote"><img alt="Comment" src="/redmine/images/comment.png?1427389109" /></a> <a href="#" onclick="$.ajax({url: &#x27;/redmine/journals/edit/9041.js&#x27;, type: &#x27;get&#x27;}); return false;" title="Edit"><img alt="Edit" src="/redmine/images/edit.png?1427389109" /></a></div><p>Ok, so I went through and tried to reconcile the previous proposed schemas, along with some new issues that popped up, and this is my currently proposed schema</p>

	<p>One thing that I did was to make the relationship between benchmarks and benchmark_ref_runs to be many-to-many since I anticipate that we will often want to evaluate a single run against multiple data sets, but that run may be done by multiple models.  So for example, a set of benchmarks might be something like</p>

	<p>site | input | variable | dates<br />Harvard Forest; MODIS; LAI; 2002-2012<br />Harvard Forest; Ameriflux; NEE; 1996 - 2012<br />Harvard Forest; Ameriflux; soil temp; 1998-2008</p>

	<p>While the benchmark reference runs might contain the settings to run N different models at Harvard Forest.</p>

	<p>I'm currently torn over whether to embed the settings file itself into the benchmarks reference runs table, or whether to put these in DBFILES. My gut tells me DBFILES, but the disadvantage to that is that all the info required to run a benchmark may live on a machine you don't have access to. Regardless, these setting files need to be defined based on the general ID's rather than the specific files (e.g. they need to say that the met input is input_id = X, not the file path, so that these can easily be run on multiple machines).</p>

	<p>So here's how I envision the typical workflow.</p>

	<p>1) The set of runs we want to do are defined by their benchmark_ref_runs ID's. For example, our integration test script might say run ED and SIPNET at Harvard by specifying those two ID's</p>

	<p>2) For each ref run, start the run (or ensemble of runs) and create a new benchmarks_ensembles that points to that ensemble</p>

	<p>3) When run is complete, look up all the benchmarks</p>

	<p>4) For each benchmark, extract from the model and the data the relevant variable over the specified time period</p>

	<p>5) For each variable, look up the metrics to be calculated and store these results in benchmarks_ensembles_scores</p>

	<p>6) An overall report for each model, site pair can be generated by reporting all the benchmarks_ensembles_scores associated with a given benchmarks_ensembles</p>

	<p>Thoughts???</p></div>
    </div>
  </div>
  
  <div id="change-10776" class="journal has-details">
    <div id="note-13">
    <h4><a href="/redmine/issues/1207#note-13" class="journal-link">#13</a>
    
    Updated by <a href="/redmine/users/12" class="user active">Rob Kooper</a> <a href="/redmine/projects/pecan/activity?from=2014-07-29" title="07/29/2014 05:12 pm">about 1 year</a> ago</h4>

    <ul class="details">
       <li><strong>Assignee</strong> changed from <i>Toni Viskari</i> to <i>Rob Kooper</i></li>
    </ul>
    
    </div>
  </div>
  

</div>

</body>

**Comment by ankurdesai** [comment]
Benchmarking is a high priority item for Pecan 2 and I’m hoping to get my new PhD student excited by the topic. Mike had defined a table once, I believe. 
-------------------------------------------------
Ankur R Desai, Associate Professor
  University of Wisconsin - Madison, Atmospheric and Oceanic Sciences
  http://flux.aos.wisc.edu <http://flux.aos.wisc.edu/>  desai@aos.wisc.edu <mailto:desai@aos.wisc.edu> 
O: +1-608-520-0305 / M: +1-608-218-4208

**Comment by mdietze** [comment]
There's lots of discussion on the benchmark design and all required open issues already on Github. Thanks for copying this over for reference, but I think keeping it open will be confusing since all tasks are already laid out

**Comment by mdietze** [comment]
Rob has actually implemented all the tables as well
