### ISSUE TITLE
better met & flux import

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#593]
In trying to get some students from the flux course up and running their own sites, I ran into a few unexpected hiccups.

1) met2CF.csv should probably be modified to parse additional variables, to automatically split files into year, and to have a more robust date parsing.

2) it would be good to set up a generalized "import met" workflow that would also handle the database insert, since it doesn't make sense to have dedicated download functions.

I'll try and recruit a few test cases from the students that had trouble

**Comment by ankurdesai** [comment]
Perhaps this would be a good first project for James (generalized met2cf.csv). Date parsing is almost certainly the trickiest, given the range of everything from DOY,HHMM (typicaly old Campbell dataloggers) to TOA5 date (date/time string in quotes) to fractional days of years to the normal ISO dates, none of which is easy to detect necessarily from the header alone and of course, figuring out timezone. But most flux and met data files fall under a handful of these and we could have arguments passed for things that are hard to figure out (like timezone). 

-------------------------------------------------
Ankur R Desai, Associate Professor
  University of Wisconsin - Madison, Atmospheric and Oceanic Sciences
  http://flux.aos.wisc.edu <http://flux.aos.wisc.edu/>  desai@aos.wisc.edu <mailto:desai@aos.wisc.edu> 
O: +1-608-520-0305 / M: +1-608-218-4208

**Comment by mdietze** [comment]
I think it would be good to keep James focused on filling in the need to support a global product -- that would immediately reduce the demand for this since models could be run anywhere, plus it will allow him to more quickly focus on the downscaling issue.  That said, I believe Gabe still has outstanding edits around this issue that still need to be pulled in before someone tackles this issue

**Comment by mdietze** [comment]
I've put the example met and code from Caitlin Moore <caitlin.moore@monash.edu> at /fs/data3/metTest on the PEcAn server. These data are not public so are not being added to the PEcAn database at this time.

**Comment by ashiklom** [comment]
I'm pretty sure the current met process workflow addresses all of these issues, so I'm going to close this. If there are specific issues that still need to be addressed in the met workflow, those should probably be their own, more-specific issues.

@ankurdesai @mdietze @bcow If any of you disagree, feel free to re-open this issue.
