### ISSUE TITLE
sensitivity analysis analysis

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#594]
Should do sensitivity analysis if text is in the box, remove check box, same for ensemble analysis.

**Comment by ankurdesai** [comment]
Agree. Missing checking the checkboxes threw a lot of people off during the tutorial. However, everyone really appreciated using that page over editing pecan.xml directly. 
-------------------------------------------------
Ankur R Desai, Associate Professor
  University of Wisconsin - Madison, Atmospheric and Oceanic Sciences
  http://flux.aos.wisc.edu <http://flux.aos.wisc.edu/>  desai@aos.wisc.edu <mailto:desai@aos.wisc.edu> 
O: +1-608-520-0305 / M: +1-608-218-4208

**Comment by ch1eroe1** [comment]
I am going to close out this issue.  Code was checked in from pull requests 637 and 638.
