### ISSUE TITLE
load.bety.sh ERROR: relation "schema_migrations" does not exist

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#600]
On the PEcAn v 1.4.3 VM, when I run

```sh
sudo -u postgres ./scripts/load.bety.sh
```

I get the error

```sh
Checking schema                    : ERROR:  relation "schema_migrations" does not exist
LINE 1: SELECT version FROM schema_migrations ORDER BY version DESC ...
                            ^
EXPECTED SCHEMA version 
Dump is from a different schema, please fix schema in database.
```

How do I either create the table or fix the schema in the database?

**Comment by robkooper** [comment]
This means the database is not created yet. Use:
`sudo -u postgres ./scripts/load.bety.sh -c YES -f YES`
see
`sudo -u postgres ./scripts/load.bety.sh -h`

**Comment by dlebauer** [comment]
thanks. 

I had read the help and but didn't realize I needed to add `YES` after the `-c` flag, and `-f` says `should not be needed`, so I had tried `sudo -u postgres ./scripts/load.bety.sh -c` but not `-c YES -f YES`.

**Comment by dlebauer** [comment]
Does this work ?

```
sudo -u postgres ./scripts/load.bety.sh -c YES -f YES
```
