### ISSUE TITLE
Difficulties running pecan with new variables

### ISSUE THREAD

**Issue by Viskari** [PecanProject/pecan#609]
I've been trying to do sensitivity analysis with new variables with pecan and I am running in to a problem I don't understand. I created the variable in the database as well as a prior for it, added it to the PFTs. This far it worked and I could run pecan without difficulties, but when I added them to trait.directionary.csv, I start getting the following error message:

015-08-27 15:14:06 INFO   [#2: run.write.configs] :
   ----- Writing model run config files ----
2015-08-27 15:14:06 ERROR  [write.config.ED2] :
   NA not found in ED history
2015-08-27 15:14:06 ERROR  [write.config.ED2] :
   NA not found in ED history
2015-08-27 15:14:06 ERROR  [write.config.ED2] :
   NA not found in ED history
2015-08-27 15:14:06 INFO   [write.config.ED2] :
   Using /home1/tviskari/R/library/PEcAn.ED2/ED2IN.rgit as template
2015-08-27 15:14:07 ERROR  [write.config.ED2] :
   NA not found in ED history
2015-08-27 15:14:07 ERROR  [write.config.ED2] :
   NA not found in ED history
2015-08-27 15:14:07 ERROR  [write.config.ED2] :

The part in trait.directionary.csv looks like:

"wood_reflect_vis";"wood VIS reflectance";"0-1";"wood_reflect_vis"
"wood_reflect_nir";"wood NIR reflectance";"0-1";"wood_reflect_nir"
"wood_trans_vis";"wood VIS transmittance";"0-1";"wood_trans_vis"
"wood_trans_nir";"wood NIR transmittance";"0-1";"wood_trans_nir"
"orient_factor";""Leaf orientation for radiative purposes";"ratio";"orient_factor"

If I remove these, pecan runs, but while pecan reads the variables from PFTs, it doesn't add them to the XML file.

Any idea what might be causing the problem?

**Comment by serbinsh** [comment]
@Toni, did you also update the history.csv file in PEcAn?

**Comment by Viskari** [comment]
Yes.

**Comment by Viskari** [comment]
Found the error.

**Comment by Viskari** [comment]
One of the description in trait.dictionary had a double "" before description.

**Comment by serbinsh** [comment]
Thanks for adding a bit more info to the solution here!


------------------------------------------------------------------------------
Shawn P. Serbin
Biological, Environmental & Climate Sciences Department
Brookhaven National Laboratory
Upton, NY 11973-5000

Phone: +1-631-344-3165
Fax: +1-631-344-2060
Email: sserbin@bnl.gov<mailto:sserbin@bnl.gov>
Bio:  http://www.bnl.gov/envsci/bio/serbin-shawn.php
TEST Group: http://www.bnl.gov/TEST/
Twitter: @doctorjackpine, @test_bnl
------------------------------------------------------------------------------

On Aug 27, 2015, at 5:27 PM, Viskari <notifications@github.com<mailto:notifications@github.com>> wrote:


One of the description in trait.dictionary had a double "" before description.

**Comment by dlebauer** [comment]
for the record, trait.dictionary is a remnant (hack) from the original
version of PEcAn 1.1. The strange tab-delimited / quoted formatting
required by R for a csv file stored in the data/ directory makes the file
cumbersome (and error-prone) to update.

Perhaps time to revisit this issue (still in Redmine as #945 from 2012)?

https://ebi-forecast.igb.illinois.edu/redmine/issues/945

**Comment by serbinsh** [comment]
Yes!  Let's get past trait dictionary once and for all.

[iPhone]

On Aug 27, 2015, at 6:10 PM, David LeBauer <notifications@github.com<mailto:notifications@github.com>> wrote:

for the record, trait.dictionary is a remnant (hack) from the original
version of PEcAn 1.1. The strange tab-delimited / quoted formatting
required by R for a csv file stored in the data/ directory makes the file
cumbersome (and error-prone) to update.

Perhaps time to revisit this issue (still in Redmine as #945 from 2012)?

https://ebi-forecast.igb.illinois.edu/redmine/issues/945
