### ISSUE TITLE
VM boot partition is full

### ISSUE THREAD

**Issue by fabeit** [PecanProject/pecan#615]
I have been using the pecan vmbox where I loaded lubuntu and where I have been installing small software. Unfortunately I think the boot partition is too small at around 300 MB. Now my boot is full and I had to manually delete old kernels. I also tried to extend boot using gparted but it is not possible to shrink the main 100 GB partition. I wonder if there is a way to shrink the main partition and extend the boot. Otherwise I tried to create a new .vdi but it does not show up on gparted when I put the live CD.
any suggestion how to work around this issue? I want to have a bigger boot partition.

**Comment by robkooper** [comment]
/boot is where the kernels are kept, and is small on purpose. There is no need to keep a lot of kernels. You can easily remove them with `apt-get purge --auto-remove`. This will show you what will be removed, and should be all the old kernels.

The 100GB is mounted at / and is where you will install all the software on.

**Comment by robkooper** [comment]
Assuming this is fixed, if not please reopen.
