### ISSUE TITLE
Document mstmip_vars and mstmip_local data sets. 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#622]
The mstmip data embedded in the utils package contains the following fields, but I can not find the documentation. What do the fields mean, and how are they used?

``` r
data(mstmip_local, package = "PEcAn.utils")
colnames(mstmip_local)
 [1] "Num"           "Group"         "order"         "Saveit"        "Variable.Name" "Units"         "Long.name"    
 [8] "Priority"      "Category"      "X3.hourly"     "Monthly"       "var_type"      "ndim"          "dim1"         
[15] "dim2"          "dim3"          "dim4"          "Description"  
```

These datasets can be documented using oxygen as described in Hadley's chapter on data in R packages. http://r-pkgs.had.co.nz/data.html

**Comment by mdietze** [comment]
http://nacp.ornl.gov/MsTMIP_variables.shtml

**Comment by dlebauer** [comment]
Here are the mstmip_vars (from MsTMIP) and mstmip_local (ad-hoc definitions) datasets. Some fields arent clearly described (e.g. 'priority', 'group', 'order', 'Saveit'). I assume 'Num' is the unique row identifier (?).

I'd suggest the following for `mstmip_local` variables.  

1. remove duplicates
2. Add human-readable versions of variable names to the Long.Name field
3. Update Category field (currently, all PEcAn additions use "Carbon Flux" as a category even though some variables belong to "Carbon Pool", "Energy Flux", or "Physical Variables"
4. add variable_id field to reference BETYdb variables table.

### MsTMIP 

|Variable.Name |Long.name                                |Units                              |Category           |
|:-------------|:----------------------------------------|:----------------------------------|:------------------|
|lon           |Longitude                                |degrees_east                       |Grid               |
|lat           |Latitude                                 |degrees_north                      |Grid               |
|lon_bnds      |Longitude west-east bounds               |degrees_east                       |Grid               |
|lat_bnds      |Latitude south-north bounds              |degrees_north                      |Grid               |
|time          |Time middle averaging period             |days since 1700-01-01 00:00:00 UTC |Time               |
|time_bnds     |Time beginning-end bounds                |days since 1700-01-01 00:00:00 UTC |Time               |
|dec_date      |Decimal date middle averaging period     |yr                                 |Time               |
|dec_date_bnds |Decimal date beginning-end bounds        |yr                                 |Time               |
|cal_date_mid  |Calender date middle averaging period    |yr, mon, day, hr, min, sec         |Time               |
|cal_date_beg  |Calender date beginning averaging period |yr, mon, day, hr, min, sec         |Time               |
|cal_date_end  |Calender date end averaging period       |yr, mon, day, hr, min, sec         |Time               |
|GPP           |Gross Primary Productivity               |kg C m-2 s-1                       |Carbon Fluxes      |
|NPP           |Net Primary Productivity                 |kg C m-2 s-1                       |Carbon Fluxes      |
|TotalResp     |Total Respiration                        |kg C m-2 s-1                       |Carbon Fluxes      |
|AutoResp      |Autotrophic Respiration                  |kg C m-2 s-1                       |Carbon Fluxes      |
|HeteroResp    |Heterotrophic Respiration                |kg C m-2 s-1                       |Carbon Fluxes      |
|DOC_flux      |Dissolved Organic Carbon flux            |kg C m-2 s-1                       |Carbon Fluxes      |
|Fire_flux     |Fire emissions                           |kg C m-2 s-1                       |Carbon Fluxes      |
|NEE           |Net Ecosystem Exchange                   |kg C m-2 s-1                       |Carbon Fluxes      |
|poolname      |Name of each Carbon Pool                 |(-)                                |Carbon Pools       |
|CarbPools     |Size of each carbon pool                 |kg C m-2                           |Carbon Pools       |
|AbvGrndWood   |Above ground woody biomass               |kg C m-2                           |Carbon Pools       |
|TotLivBiom    |Total living biomass                     |kg C m-2                           |Carbon Pools       |
|TotSoilCarb   |Total Soil Carbon                        |kg C m-2                           |Carbon Pools       |
|LAI           |Leaf Area Index                          |m2 m-2                             |Carbon Pools       |
|Qh            |Sensible heat                            |W m-2                              |Energy Fluxes      |
|Qle           |Latent heat                              |W m-2                              |Energy Fluxes      |
|Evap          |Total Evaporation                        |kg m-2 s-1                         |Energy Fluxes      |
|TVeg          |Transpiration                            |kg m-2 s-1                         |Energy Fluxes      |
|LW_albedo     |Longwave Albedo                          |(-)                                |Energy Fluxes      |
|SW_albedo     |Shortwave Albedo                         |(-)                                |Energy Fluxes      |
|Lwnet         |Net Longwave Radiation                   |W m-2                              |Energy Fluxes      |
|SWnet         |Net shortwave radiation                  |W m-2                              |Energy Fluxes      |
|fPAR          |Absorbed fraction incoming PAR           |(-)                                |Energy Fluxes      |
|z_top         |Soil Layer Top Depth                     |m                                  |Physical Variables |
|z_node        |Soil Layer Node Depth                    |m                                  |Physical Variables |
|z_bottom      |Soil Layer Bottom Depth                  |m                                  |Physical Variables |
|SoilMoist     |Average Layer Soil Moisture              |kg m-2                             |Physical Variables |
|SoilMoistFrac |Average Layer Fraction of Saturation     |(-)                                |Physical Variables |
|SoilWet       |Total Soil Wetness                       |(-)                                |Physical Variables |
|Qs            |Surface runoff                           |kg m-2 s-1                         |Physical Variables |
|Qsb           |Subsurface runoff                        |kg m-2 s-1                         |Physical Variables |
|SoilTemp      |Average Layer Soil Temperature           |K                                  |Physical Variables |
|Tdepth        |Active Layer Thickness                   |m                                  |Physical Variables |
|Fdepth        |Frozen Layer Thickness                   |m                                  |Physical Variables |
|Tcan          |Canopy Temperature                       |K                                  |Physical Variables |
|SWE           |Snow Water Equivalent                    |kg m-2                             |Physical Variables |
|SnowDen       |Bulk Snow Density                        |kg m-3                             |Physical Variables |
|SnowDepth     |Total snow depth                         |m                                  |Physical Variables |
|CO2air        |Near surface CO2 concentration           |micromol mol-1                     |Driver             |
|LWdown        |Surface incident longwave radiation      |W/m2                               |Driver             |
|Psurf         |Surface pressure                         |Pa                                 |Driver             |
|Qair          |Near surface specific humidity           |kg kg-1                            |Driver             |
|Rainf         |Rainfall rate                            |kg m-2 s-1                         |Driver             |
|SWdown        |Surface incident shortwave radiation     |W m-2                              |Driver             |
|Tair          |Near surface air temperature             |K                                  |Driver             |
|Wind          |Near surface module of the wind          |m s-1                              |Driver             |
|Tmin          |Daily Maximum Temperature                |K                                  |Driver             |
|Tmax          |Daily Minimum Temperature                |K                                  |Driver             |
|Uwind         |Northward Component of Wind              |m s-1                              |Driver             |
|Vwind         |Eastward Component of Wind               |m s-1                              |Driver             |
|RH            |Relative Humidity                        |%                                  |Driver             |
|PAR           |Photosynthetically Active Radiation      |mol m-2 s-1                        |Driver             |

### MsTMIP Local (Variables used within PEcAn following MsTMIP 'style'

|Variable.Name |Long.name                                |Units                              |Category           |
|:-------------|:----------------------------------------|:----------------------------------|:------------------|
|RootBiom      |Total root biomass                       |kg C m-2                           |Carbon Fluxes      |
|StemBiom      |Total stem biomass                       |kg C m-2                           |Carbon Fluxes      |
|CO2CAS        |CO2CAS                                   |ppmv                               |Carbon Fluxes      |
|CropYield     |CropYield                                |kg m-2                             |Carbon Fluxes      |
|SnowFrac      |SnowFrac                                 |-                                  |Carbon Fluxes      |
|Lwdown        |Lwdown                                   |W m-2                              |Carbon Fluxes      |
|Swdown        |Swdown                                   |W m-2                              |Carbon Fluxes      |
|Qg            |Qg                                       |W m-2                              |Carbon Fluxes      |
|Swnet         |Swnet                                    |W m-2                              |Carbon Fluxes      |
|RootMoist     |RootMoist                                |kg m-2                             |Carbon Fluxes      |
|Tveg          |Tveg                                     |kg m-2 s-1                         |Carbon Fluxes      |
|WaterTableD   |WaterTableD                              |m                                  |Carbon Fluxes      |
|SMFrozFrac    |SMFrozFrac                               |-                                  |Carbon Fluxes      |
|SMLiqFrac     |SMLiqFrac                                |-                                  |Carbon Fluxes      |
|Albedo        |Albedo                                   |-                                  |Carbon Fluxes      |
|SnowT         |SnowT                                    |K                                  |Carbon Fluxes      |
|VegT          |VegT                                     |K                                  |Carbon Fluxes      |
|LeafC         |LeafC                                    |kg C m-2                           |Carbon Fluxes      |
|Yield         |Yield                                    |kg m-2                             |Carbon Fluxes      |

**Comment by infotroph** [comment]
These datasets were removed in #2760
