### ISSUE TITLE
Gitter as a possible HipChat alternative

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#625]
I just stumbled across [Gitter](https://gitter.im), a free chat client with very tight GitHub integration. There is a nice overview of it on [Wikipedia](https://en.wikipedia.org/wiki/Gitter) and a bit more information on [their own website](https://gitter.im/home/learn). You set it up by linking it directly to a GitHub repository (via GitHub's own OAuth scheme), and it basically gives you all the features of GitHub's standard issue/pull request/discussion interface but over live chat. For instance, you can:
* Link to individual files in a Git repository.
* Link to GitHub issues by number (which displays a hovercard of the issue right in the chat)
* Use GitHub's markdown
* Browse and search message archives

It also has [native apps for Windows, OSX, Linux, Android, and iOS.](https://gitter.im/apps). And, since it links directly to GitHub, it doesn't require independent registration like HipChat--you just use your GitHub account!

I know HipChat is a stable, established platform that we've spent a while learning and adapting, but this seems like a really good way of integrating better with GitHub. Perhaps our fearless project manager @tonygardella could look into this further?

**Comment by dlebauer** [comment]
I just took a look and it looks promising. We should discuss at the next
teleconference
