### ISSUE TITLE
PEcAn 1.4.3 testing failures

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#628]
The Milestone for 1.4.4 is coming up and these 1.4.3 testing failures (listed on google sheet in devgroup) have not been fixed to my knowledge:

met.process: local ameriflux Ameriflux ED (run dies with nonsense CO2: 3.80000E-10)

met.process: local ameriflux Ameriflux SIPNET (Remote execution not yet supported through Browser; no remote hosts registered on VM)

met.process: BD NARR ED  (lat/lon bug)

**Comment by dlebauer** [comment]
@tonygardella which google doc are you referring to?

**Comment by tonygardella** [comment]
@dlebauer just sent you an invite to the google sheet.

**Comment by serbinsh** [comment]
Ditto @tonygardella can you send to me as well?

**Comment by tonygardella** [comment]
@serbinsh sent it to you too

**Comment by mdietze** [comment]
@tonygardella I haven't seen pull requests resolving any of this, why was the issue closed?

**Comment by tonygardella** [comment]
@mdietze I closed it because #633 and #634 were created. I figured that it would be redundant to have this and both of those.
