### ISSUE TITLE
Web interface site subselection

### ISSUE THREAD

**Issue by ankurdesai** [PecanProject/pecan#629]
As the site table grows leaps and bounds, the web Google Map interface is becoming cluttered. One can't even click on a new site without zooming significantly. Or find a specific network (Ameriflux). So the request is the to make sites subsetted in the map view by network. I wonder if we need a networks table and the ability to map a site to multiple networks or projects (NEON, Ameriflux, LTER, Mandifore, "mysites", etc...).  @robkooper @dlebauer @mdietze

**Comment by mdietze** [comment]
filtering by network depends on the creation of the site network table in #271

**Comment by robkooper** [comment]
<img width="1341" alt="screen shot 2016-04-26 at 10 54 53 pm" src="https://cloud.githubusercontent.com/assets/1580696/14841594/ed972954-0c04-11e6-8827-755ff692d791.png">
