### ISSUE TITLE
filter history

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#631]
Should have ability to filter runs by only those that are finished/running.

**Comment by dlebauer** [comment]
Perhaps also sort by run date or present runs from local machine at top
rather than current by id, descending.

**Comment by mdietze** [comment]
I agree with sorting/filtering by date and ID and would add the ability to search/filter by model, site, and notes/tags (which depends on #134 which is the ability to enter notes and tags about ensembles)

**Comment by robkooper** [comment]
simple filtering done to only show those runs that have a STATUS file (i.e. those done locally). This is part of 1.4.4, more filtering will happen in 1.4.5 and beyond.
