### ISSUE TITLE
Reading PFT names within web interface to model runs

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#632]
We need to provide either a resizable window or a hover-over option to show the full PFT name when selecting in the web interface

**Comment by serbinsh** [comment]
@robkooper I have been using this new feature and it works great!  I think either I will add or we should add a little text above the box to let folks know of the feature.  E.g. "*hover to see full name" on that page.  What do you think?  Or do we just add that the manual/instructs?

**Comment by robkooper** [comment]
I think manual, I would like to add less text to the page. Another option is to add a help page to each page and add some notes there.

**Comment by mdietze** [comment]
I agree. This behavior is pretty intuitive so I don't think it needs to be explained on the page.
