### ISSUE TITLE
Communication Platform: Necessary attributes

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#636]
This is to compile a list of attributes people would like to have in a possible new communication platform. Please comment with your thoughts.

**Comment by tonygardella** [comment]
-Integrates with github and huboard. Possibly with google products.
-Chat function

**Comment by dlebauer** [comment]
would be great if we had a place where everyone could take notes
simultaneously like google docs or etherpad. Not sure it needs to integrate
with the chat, though that could be nice.


On Wed, Sep 16, 2015 at 12:55 PM, Anthony Gardella <notifications@github.com

**Comment by robkooper** [comment]
Priority based list
1) chat
2) integration with github
3) ability to leave comments on issues from chat
4) integration with sprint board
5) ability to take meeting nodes

**Comment by mdietze** [comment]
I recall that gitter (and possibly others) listed integration with hubboard (sprint) and jenkins (the continuous build system that sends the "email of shame" when you break things) as features, but it would be worth clarifying what that actually means

**Comment by robkooper** [comment]
if you look on the right side of the gitter ui you will see issues recently modified and jenkins build information.

**Comment by mdietze** [comment]
Got it, I can see that show up now that I've addressed an issue. If we go with Gitter it appears we need to install something on Jenkins to allow that to be integrated too. Now that I see it in practice, I do see the advantages of this centralization over the non-integrated HipChat

**Comment by robkooper** [comment]
I added the hooks for jenkins

**Comment by ankurdesai** [comment]
Just general notes, perhaps with a few sub-folders - one for telecon agendas/minutes, one each for major subprojects on going. But would be nice to have email notification options for updates. Needs to be informal, unstructured, easy to edit and search.
and all of the above
