### ISSUE TITLE
Bety formats header 

### ISSUE THREAD

**Issue by bcow** [PecanProject/pecan#656]
In the formats table, the header entry is set as character, should this be boolean? This has lead to some confusion in the database: some entries have header set to 1, some have a list of variable names and some have nothing. I think it would be simplest to keep this true/false and convert all the empty entries to 0.

**Comment by robkooper** [comment]
I think this should be an int, and indicates the number of header rows. Some csv files have 2 header rows.

**Comment by mdietze** [comment]
Great point, that solves the problem Betsy and I were discussing earlier today of trying to detect when there's a second units row in the header
