### ISSUE TITLE
Issue running PEcAn+qsub with output folder other than pecan/

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#659]
Both @Viskari and I have noticed a weird issue with PEcAn through command and submitting the jobs via qsub.  If we use pecan as the main output, everything works fine.  However, if say we use pecan.1 then the runs fail.  They fail without much any info in the log, etc. the whole workflow just stops but the last log entry in the workflow.log is PEcAn waiting for runs to finish?  

Has anyone else ever seen this before?  My next test is to see if the issue is the ".1" at the end and if I change it to something other than pecan it still works OK.

**Comment by robkooper** [comment]
so you specify pecan.1 as the outdir in the pecan.xml file?

**Comment by serbinsh** [comment]
@Viskari Please add details of the issue you are having here.  It is a related issue

**Comment by serbinsh** [comment]
Yes, @robkooper in the pecan.xml file

**Comment by robkooper** [comment]
Can you paste the broken pecan.xml file. I tried to use pecan.1 and it worked.

**Comment by Viskari** [comment]
To expand on this, at the moment I am able to run the workflow without any issues if the output folder is just pecan. However, if I change it to anything else, it will run it fine the first time through, but for some reason it doesn't run the executables the second time through.

So, for example, if I set the output folder to be pecanone and the variable of interest as Albedo, it will run everything great the first time it runs. However, if I then rerun the workflow again, this time with variable of interest being NPP, the workflow completes, but it doesn't rerun the models nor does it seem to be reading the values even from the existing output files. Instead it just gives the median value for every quantile. If I remove the output folder and rerun, then everything goes great again.

**Comment by robkooper** [comment]
ok that helps. The idea is that you have a new folder for each run. If you want to overwrite the data you can try and see what happens if you remove the STATUS file in the pecan file. This file keeps track of what has been executed sofar.

**Comment by serbinsh** [comment]
OK @robkooper and @Viskari I think the next step is to see if the intended behavior still works in that if you re-run an analysis in the same folder but change the response, say from NPP to Albedo, it will skip all the steps except getting the model output and re-running the SA/VD steps.  So far, it sounds like this isn't working for you Toni.  However, it may be that you are using an older workflow.R?  Rob, has this changed in a way that might impact this behavior?  I know that Ryan K moved this our of scripts and left a single version in /web

**Comment by robkooper** [comment]
yes, it now checks to see if sensitivity analysis has been run. Can you see what happens if you remove the bottom two lines from the STATUS file.

**Comment by serbinsh** [comment]
OK, will do. @Viskari can you also try this?

**Comment by mdietze** [comment]
FYI, I was aware of this issue (rerunning SA/VD) and it's been on my to-do list since when we first put these in Advanced Edit rather than having to do the analysis in R. I just didn't make the connection between the folder name issue you were describing and what you were actually trying to do. I think the more generic solution is to move most of the ensemble, sensitivity, and uncertainty analysis figure generation into the visualization stage rather than in the workflow, so users can look at any output and time-scale on demand

**Comment by serbinsh** [comment]
OK @robkooper @mdietze and @Viskari I was just able to run the latest workflow.R from command using an output folder of pecan.1  I might have fixed this particular issue with some updates to the torque system as well as using the newer workflow.R file.  

After this finishes I want to see if I still the issue Mike mentioned regarding re-running analyses.  I will also see if I have issues trying to re-run over the existing files (i.e. clobbering the existing output).
