### ISSUE TITLE
Add model/selected PFTs (when applicable) following "Model Type" on history page?

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#660]
For tracking run history on the web interface I was thinking it might be nice to have an additional column that shows the selected PFTs for each run (when applicable).  Right now, all you see is the location, name, type, run stats, completion info and delete.  Maybe that would make the page too busy? 

I know that when I am running a couple of jobs it would be helpful to have a little more info to help discriminate between them rather than go into each one until I find the one I am looking for.  Maybe it is on me to write down the run ID!

Separate issue, but I suppose if we start running jobs by user we could add the user name there too.

**Comment by mdietze** [comment]
@serbinsh there are already open issues to add the user.id and notes to the History table. I tend to think that adding PFTs would make this too busy. Plus PFTs are a property at the Run level, not the Workflow, which is what the History table is displaying. I'm going to close but feel free to reopen after those two other features have been implemented and you've had a chance to play with them a bit.

**Comment by robkooper** [comment]
I would like to add a search box that would go across properties such notes, users, sites, pfts etc. To allow you to easily search in the history for a specific workflow execution.

**Comment by mdietze** [comment]
@robkooper I'd second that. If that's not an open issue, could you create a new issue for it?

**Comment by robkooper** [comment]
See #631

**Comment by serbinsh** [comment]
Thanks guys, this was helpful.  And yes a search box would be a great feature!
