### ISSUE TITLE
where do I find pecan.utils package for R?

### ISSUE THREAD

**Issue by fabeit** [PecanProject/pecan#661]
I have found this https://pecanproject.github.io/pecan//utils/inst/web/PEcAn.html but no download.

I need it for the met2model.ED script which requires them.

**Comment by mdietze** [comment]
https://github.com/PecanProject/pecan/tree/master/utils

**Comment by fabeit** [comment]
@mdietze thanks, I thought it was that folder, and I tried to install it as a package in R by zipping the utils folder, but it doesn't work. How do you actually import it in R?

**Comment by mdietze** [comment]
easiest is to us the R devtools package's install_github function

install_github("PecanProject/pecan/modules/utils")

**Comment by dlebauer** [comment]
Note that `PEcAn.utils` has `ncdf4` as a dependency, which, in turn, has NetCDF-4 as a dependency. 

... @mdietze @robkooper can we move `ncdf4` from depends to suggests? (perhaps also `udunits2`). Otherwise, it is hard to install utils.

**Comment by fabeit** [comment]
@mdietze @dlebauer 
install_github("PecanProject/pecan/modules/utils")
Downloading GitHub repo PecanProject/pecan@master
Error: Does not appear to be an R package (no DESCRIPTION)

**Comment by dlebauer** [comment]
devtools::install_github("pecanproject/pecan", subdir = 'utils')

**Comment by fabeit** [comment]
@dlebauer I still can't install the utils, problems with ncdf4, I tried with both the 32 and 64 R.
Downloading GitHub repo pecanproject/pecan@master
Installing PEcAn.utils
Skipping 1 packages not available: ncdf4
** testing if installed package can be loaded
*** arch - i386
Error : package 'ncdf4' is not installed for 'arch = i386'
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Program Files/R/R-3.2.2/library/PEcAn.utils'
Error: Command failed (1)

**Comment by mdietze** [comment]
looks like you need to install the R package ncdf4 first. Offline @dlebauer has suggested that we move the ncdf4 package from "Depends" to "Suggests" for the utils package, which would probably get you past this point. However, it won't solve your ultimate problem, since you'll ncdf4 for met2model.ED as well

**Comment by ankurdesai** [comment]
According to James, ncdf4 R package doesn’t work yet on Windows. So yes, to use pecan not net cdf utils on Windows will require removing the dependency. James can provide more details.

**Comment by bpbond** [comment]
The ncdf4 package can in fact be installed on Windows; see http://cirrus.ucsd.edu/~pierce/ncdf/. It's just not available via CRAN.

**Comment by ankurdesai** [comment]
Cool! I love Ben’s occasional wisdom showing up here!

**Comment by fabeit** [comment]
I already had installed ncdf4, but I reinstalled it following the above link, I tried to install both the 32 and 64 version, but I still get the same error, either package 'ncdf4' is not installed for 'arch = i386' or package 'ncdf4' is not installed for 'arch = x64'. I am on Windows. I have used ncdf4 previously so I know it works fine.

**Comment by bpbond** [comment]
Hmm, I'm not on Windows but several people here are and use ncdf4; if useful I can go check with them. What version of R? So it installs correctly, but then you get an error when you try load (`library()`) it?

**Comment by fabeit** [comment]
@bpbond I am on the latest version of R. ncdf4 loads just fine but I can't install pecan.utils. I am using this command devtools::install_github("pecanproject/pecan", subdir = 'utils') and it tells me 
Downloading GitHub repo pecanproject/pecan@master
Installing PEcAn.utils
Skipping 1 packages not available: ncdf4
** testing if installed package can be loaded
*** arch - i386
Error : package 'ncdf4' is not installed for 'arch = i386'
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'


I tried to use R 32 and also 64, same issue.

**Comment by mdietze** [comment]
We discussed this at the PEcAn meeting this AM and @dlebauer said he'll update the dependencies, which should get you through compilation, and then hopefully you won't hit any issues with using the package. Not sure why it's halting on a package that you're able to load from the command prompt.

**Comment by fabeit** [comment]
@mdietze yes i am not sure what is the problem, I guess i can load ncdf4 manually after I loaded the utils. Thanks

**Comment by fabeit** [comment]
@dlebauer I am just wondering when you might be able to update the dependencies, I would like to try to convert this data I have. Thanks!

**Comment by dlebauer** [comment]
I have a draft but it breaks the ED integration tests. I didn't think it
was a priority since you can remove the offending packages from DEPENDS in
the utils/DESCRIPTION file and then re-build the package. But to step back:
what are you trying to do? It might not work anyway if you need the ncdf4
or udunits2 packages.

**Comment by fabeit** [comment]
@dlebauer I am trying to convert ERA-I reanalysis data which comes in either netcdf or grib format into hdf5 ED format. ncdf4 loads fine in my R.

**Comment by mdietze** [comment]
@fabeit sorry for the delays. I don't know if you got the PEcAn packages working for you yet, but I just applied the changes discussed above. Let me know if they work for you now so I know whether to close this issue.

**Comment by fabeit** [comment]
@mdietze let me test this and get back with you

**Comment by fabeit** [comment]
@mdietze it looks like I am able to install the utils, I think it's ok to close this for now. Thanks
