### ISSUE TITLE
move notes earlier in web workflow

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#679]
Should allow a user to add notes without selecting advanced setup. Maybe at inputs, maybe earlier. 

@PecanProject/pecan-developers  Do people know beforehand what run they will do, does it make sense to make it the very first step in the workflow so people can capture their thoughts.

**Comment by mdietze** [comment]
@ch1eroe1 is this done now?

**Comment by ch1eroe1** [comment]
Yes.  This issue should be closed unless there is a bug I never seen.
