### ISSUE TITLE
Photosynthesis install broken

### ISSUE THREAD

**Issue by Viskari** [PecanProject/pecan#689]
I pulled the latest version of pecan, but when I am running the build for it, it gives me a broken installation due to photosynthesis with the following line:

----------------------------------------------------------------------
INSTALL modules/photosynthesis BROKEN
----------------------------------------------------------------------
Error: contains a blank line

Any help appreciated?

**Comment by mdietze** [comment]
just did a push that should fix this

**Comment by serbinsh** [comment]
I think this is fixed and can be closed.  I no longer get errors during build. Others?  @mdietze @dlebauer @bcow?

**Comment by dlebauer** [comment]
Me either
