### ISSUE TITLE
Ameriflux Vapor Pressure Deficit(VPD) - CF standard unit error

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#692]
Ameriflux currently has mol m-2 s-1 as the unit for VPD. It should be using the CF standard unit: Pascal (Pa)

**Comment by tonygardella** [comment]
https://github.com/PecanProject/pecan/blob/master/modules/data.atmosphere/R/met2CF.Ameriflux.R#L205 is the line that needs to be changed

**Comment by mdietze** [comment]
@tonygardella will you be submitting a PR with a fix on this?
