### ISSUE TITLE
Installing packages with complex dependencies 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#71]
On Stampede, I was unable to install ncdf4, udunits2, rjags, MCMCpack, and rgdal.

These will all require local installation of dependencies. Has anyone done this? Is the best approach to build all of the dependencies from source? Are there tricks to identifying and loading the correctly configured modules? I currently have this in my `.bashrc` but am still testing it out:

```
module load gsl hdf5 parallel-netcdf/4.2.1.1 netcdf nco udunits/2.1.24 R_mkl/3.0.1
```

In general, it seems that it might be useful to share libraries on such a machine rather than have everyone fiddle around. e.g. if I set `/home1/02014/dlebauer/lib/R` to read-only, and people put `libPaths("~/lib/R/", "/home1/02014/dlebauer/lib/R")` it in their `.Rprofile`, they wouldn't have to install any dependencies, but could if they wanted to (e.g. a different version of PEcAn etc).

**Comment by dlebauer** [comment]
on roger ....

```r
install.packages("udunits2", configure.args='--with-udunits2=/sw/udunits-2.1.24/ --with-udunits2-include=/sw/udunits-2.1.24/include')
```

**Comment by ecn620** [comment]
I had the same issue with udunits, and it turns out there is a typo in the error message. I suggest using:

install.packages('udunits2',configure.args='--with-udunits2-include=/usr/include/udunits2')

(the error message had "configure-args" instead of "configure.args")
