### ISSUE TITLE
Add ability to plot met driver data in web interface

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#712]
Enable visualization of driver data on results page.  This would be handy in general ( and may already be a working issue) but particularly for situations when using CRUNCEP.  You could then investigate the driver data used for a specific run.  I know it would be nice to "see" what the met drivers look like for a NCEP run.

Would also be great if we could plot model output BY driver inputs, say GPP vs T or VPD for example. Maybe this is too much functionality for the web interface and would be best served for end user interrogations?  

For now, we can can probably harness the existing visualization code.

**Comment by serbinsh** [comment]
@robkooper if this is something already in the works, which I missed, feel free to delete or archive this issue.

**Comment by dlebauer** [comment]
I've seen a number of utilities that exist for visualizing netcdf files in web pages, and it will certainly help that both our met drivers and output have CF-compliant dimensions. If there isn't too much overhead, this may be a good place to leverage existing tools. 

Here is an extended list: http://www.unidata.ucar.edu/software/netcdf/software.html

**Comment by mdietze** [comment]
We've definitely discussed this in the past, but I couldn't find an open issue. Extending the current plot function to include inputs shouldn't be hard **if** those inputs were generated by the workflow (i.e. A netcdf cf version exists). Model-specific met would be too hard, unless we had models output their own met (which is actually not a bad idea, this has illuminated a lot on basic errors in past MIPs). The other advantage of models outputting their own met is that it ensures you look at the variables actually used by a particular model and with any transformations or aggregations performed. 

Generic netcdf web visualization tools might be part of a broader issue of upgrading the vis tools across the board -- definitely needed but never anyone's priority.

**Comment by mdietze** [comment]
This feature was requested by Flux Course 2016 students. Realistically we probably won't get it done before Camp PEON (1.4.8) but I'd like this On Deck for Fall 2016. Should probably go straight into the new Shiny visualizations.

**Comment by dlebauer** [comment]
Can we also add ability to download met driver data from the user interface?

**Comment by mdietze** [comment]
You can already download model-specific met driver data for models that put that met in the /run directory. Doesn't seem like it should be hard to put those symlinks in all /run directories for all models
