### ISSUE TITLE
Which MET product should be added next?

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#715]
Ankur was interested in getting feedback about MET products in order to prioritize the next MET addition. This issue is to gather that feedback. NLDAS and CMIP5 were mentioned

Relevant issues:
#203 -NLDAS Forcing in pecan
#234 -R package for CMIP5 met / output
#323 - Canadian Met station data
#339 - Use daymet as met driver
#461 - Add global met download / convert scripts to data.atmosphere

**Comment by mdietze** [comment]
I'd favor CMIP5 over additional global products until such time that someone specifically asks for or needs additional global met products. Beyond that I think the bigger issue is downscaling and uncertainty

For station met, the new FLUXNET product met is the top priority. Beyond that we still need to improve the gapfilling.

**Comment by tonygardella** [comment]
@ankurdesai I assigned you so you can reference this easier if necessary.

**Comment by istfer** [comment]
CORDEX downscaled the CMIP5 outputs to 0.44 resolution http://www.cordex.org/ but I'm not sure whether all the outputs are available at 3-hourly timesteps (or whether all the outputs are available for all the domains at all)
