### ISSUE TITLE
Failed with error: ‘package ‘X’ required by ‘Y’ could not be found’

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#718]
_(Transferred from https://gitter.im/PecanProject/pecan/DevGroupRoom)_

Tried running download.CRUNCEP today and received this error:

> Loading required package: PEcAn.utils
Failed with error: ‘package ‘abind’ required by ‘PEcAn.utils’ could not be found’
Loading required package: lubridate
Error in download.CRUNCEP("C:/Users/James Simkins/Downloads", "2008-01-01 00:00:00", :
could not find function "year"
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
there is no package called ‘lubridate’
Any ideas as to why this is happening?

**Comment by dlebauer** [comment]
Did it work before?

Try the following and summarize the result (and post errors)

* `libPaths()` (paste output - is it where you think it should be?
*  at command line: `./scripts/install.dependencies.R`
* in R: `install_github(‘pecanproject/pecan/utils’)`? 

If you don't have time, brain power, or patience to debug, you can always just brute-force install any package that R complains does not exist.  `install.packages(‘abind’); install.packages('install.packages(‘lubridate’)`

**Comment by robkooper** [comment]
If possible add OS and R version.

**Comment by jsimkins2** [comment]
Running ./scripts/install.dependencies.R at the command line worked just now! The R version is 3.2.1 and the OS is Linux. I haven't tried to run scripts in a week or two, so perhaps there was an update of sorts.

**Comment by dlebauer** [comment]
Glad it is working again.

But to clarify, this bit of the output looks like Windows:

> download.CRUNCEP("C:/Users/James Simkins/Downloads"`

which is not currently supported by PEcAn, though I'd be impressed if you got that far!
