### ISSUE TITLE
met.process bug with extract.nc argument order/naming

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#720]
When running  PRELES I ran into an issue with met.process where it would trip up at extract.nc and could not find end_date. The function looks like this:
`extract.nc <- function(in.path, in.prefix, outfolder, out.prefix, start_date, end_date, slat, slon, overwrite=FALSE, verbose=FALSE,...)`

It was called from convert.input, within met.process, passing in arguments like this:
`extract.nc('/fs/data4/NARR_CF_Permute/','NARR','/fs/data1/pecan.data/dbfiles/NARR_CF_site_0-768/','2004/01/01','2004/12/31',slat = 38.7441,slon = -92.2,newsite = 768)`

The arguments do not line up with what is expected, creating said error. The out.prefix argument seems to not be passed to extract.nc so I am currently experimenting with adding it in or taking it out altogether. Still no luck. @robkooper @mdietze

**Comment by bcow** [comment]
These aren't real functions. They were never fully written because the functions need to be run on the cluster and we never really figured out how to deal with that. That's why I had the functions turned off.

**Comment by tonygardella** [comment]
Nevermind! I think I just didn't refresh my r session after I loaded the package. The run worked when I took out out.prefix and replaced any instance of it with in.prefix.

**Comment by mdietze** [comment]
Nice. ready for a pull request?

**Comment by tonygardella** [comment]
Soon. The CRUNCEP problem was just a wrong path in bety. Im going to do another round of tests before I make a pull request for everything.
