### ISSUE TITLE
"Could not find requested var" in file error when running both versions of Ed 2.2 with CRUNCEP

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#725]
I ran ED2.2(82) and (46) at Niwot Ridge(US-NR1) on the VM, using the met product CRUNCEP. I received the same error with both
```
[1] "vobjtovarid4: error #F: I could not find the requested var (or dimvar) in the file!"
[1] "var (or dimvar) name: mole_fraction_of_carbon_dioxide_in_air"
[1] "file name: /home/carya/output/dbfiles/CRUNCEP_site_0-772/CRUNCEP.2004.nc"
Error in vobjtovarid4(nc, varid, verbose = verbose, allowdimvar = TRUE) : 
  Variable not found
Error in asec[rng] : only 0's may be mixed with negative subscripts
Calls: remotefunc -> <Anonymous>
Execution halted
[1] 1
[1] "RESULTS: Convert.Input"
[1] 1
NULL
Error in result$file : $ operator is invalid for atomic vectors
Calls: <Anonymous> ... convert.input -> dbfile.input.insert -> basename -> dirname
> proc.time()
   user  system elapsed 
  5.264   4.544  62.700 
```
This did not happen with Ameriflux and NARR gave a different error (I'll make another issue for this). I'm not sure who to ping about this one. @mdietze @ankurdesai  @jsimkins2

**Comment by dlebauer** [comment]
I just got this today when my met file had the wrong variable name (lat/ lon instead of latitude / longitude) 

Try `ncdump -h /home/carya/output/dbfiles/CRUNCEP_site_0-772/CRUNCEP.2004.nc` and see if the `mole_fraction_of_of_carbon_dioxide_in_air` variable exists.

**Comment by mdietze** [comment]
So if, as David suggests, the variable is just misnamed then you can easily fix the CRUNCEP functions.

On the otherhand, if it's just missing then you should add the same functionality you added to some of the other model to the ED met -- put a try() on the CO2 read and if it comes up as an error then insert a default value.

More generally, if there are met products that don't have CO2 we should think about augmenting the met workflow to merge CO2 data into the met products for the models that need it. There are a number of data sets out there that we could support, though I'd like to make this flexible and not just hard-code one of them as the default.

**Comment by tonygardella** [comment]
@dlebauer @mdietze thanks for the advice. Although CO2 is not in CRUNCEP function, the ```try()``` function is used in the met2model script so it should be there. 

I found that is was looking for the CRUNCEP met file in the ```CRUNCEP_ED_site_0-772``` directory, not in ```CRUNCEP_site_0-772```. I could either have the met file be in the model specific directory or leave it in the general site specific directory(where it is now) and change the final outfolder in met.process. I think it should be in the model specific directory so I'll do that and make a pull request. If you think it should the other way, let me know.

**Comment by tonygardella** [comment]
The issue ended up being with the ```Error in asec[rng] : only 0's may be mixed with negative subscripts```. CRUNCEP is off slightly on the time dimension so adjustments have to be made in met2model when building the time dimension. @mdietze pointed out to me that he made a change to SIPNET to account for this and that would work similarly with ED2. I made the changes and so far running met2model works. I'm going to see if it still holds up when I do a run from start to finish normally.
