### ISSUE TITLE
"dbfile file not found" during met.process when running both versions of ED with NARR

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#726]
I ran into a bug when running both versions of ED on the VM with NARR during met.process. A certain dbfile wasn't found, and an "outfolder2" object wasn't found. 

```
 Begin change to CF Standards 
[1] "start CHECK"
[1] "end CHECK"
data frame with 0 columns and 0 rows
2016-02-17 14:21:57 INFO   [convert.input] : 
   Convert.Inputs met2CF.NARR 99000000019 localhost 
   /home/carya/output/dbfiles/NARR_CF CF Meteorology application/x-netcdf 
   772 2004/01/01 2004/12/31 
[1] "start CHECK"
[1] "end CHECK"
data frame with 0 columns and 0 rows
2016-02-17 14:21:57 ERROR  [convert.input] : 
   dbfile not found 99000000019 
[1] "start CHECK"
[1] "end CHECK"
data frame with 0 columns and 0 rows
Error in paste("Convert.Inputs", fcn, input.id, hostname, outfolder, formatname,  : 
  object 'outfolder2' not found
Calls: <Anonymous> ... convert.input -> logger.info -> logger.message -> paste -> paste
```

If this is just a problem of pointing to the wrong directory/file, I think I can fix this one. @mdietze @bcow If you think it might be something else, let me know.

**Comment by bcow** [comment]
I never used a variable called outfolder2

**Comment by tonygardella** [comment]
Talked about this with @bcow and @mdietze. My error for forgetting that NARR can only be used if NARR already exists on the machine. The permute and rechunk function isn't automated/integrated in met.process yet. 

To avoid future issues with this, Mike and Betsy suggested adding a tagging/warning message that gets prompted when this part of the process is called, telling the user for now that NARR shouldn't be downloaded and processed. In the future though, there should be a tag/warning message that gets prompted when doing the permute/rechunk of NARR because it takes so long and takes up a lot of file space.

**Comment by tonygardella** [comment]
The warning will be added in #969
