### ISSUE TITLE
method="halton" is harcoded in the workflow

### ISSUE THREAD

**Issue by istfer** [PecanProject/pecan#730]
Right now sampling method halton is hardcoded in the workflow

```
run.write.configs(settings, write=settings$database$bety$write, ens.sample.method="halton")
```

We should be able to choose a sampler from settings.

**Comment by mdietze** [comment]
Specifically, not only should the sampling method be made part of the setting object, but the downstream code needs to be modified to make sure this value is passed to the right functions (currently the ens.sample.method variable has no effect).
