### ISSUE TITLE
Rename "settings" to "invert.options" in PEcAn-RTM

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#731]
In the invert.* functions

To avoid any confusion with larger PEcAn "settings" object

**Comment by ashiklom** [comment]
Addressed this issue in #798 -- whoever has the authority can close this (but, make sure you make changes in all of your scripts that use `PEcAnRTM`!)

**Comment by tonygardella** [comment]
Cool! I'll close this when #798 is merged.

**Comment by ashiklom** [comment]
@tonygardella You can close this one. #798 was merged.
