### ISSUE TITLE
Add Maespa Model

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#733]
This issue will correspond with the work being done to couple the Maespa Model http://maespa.github.io/ to PEcAn.

**Comment by tonygardella** [comment]
- [ ] Get Maespa to work on BU server
- [ ] Get it to execute through write.configs
- [ ] Write met2model and model2netcdf 
- [ ] Get it to run through workflow using example parameterizations
- [ ] Update database with Maespa traits and let pecan write .dat files.

**Comment by mdietze** [comment]
I'd split the 3rd step, as model2netcdf is required (higher priority) but met2model is optional.

**Comment by tonygardella** [comment]
write.configs works. Next step is to write met2model and have workflow run met2model and write.configs.

**Comment by mdietze** [comment]
@tonygardella is there a pull request coming for write.configs.MAESPA?

**Comment by tonygardella** [comment]
Oh, yep I can do that now.

**Comment by tonygardella** [comment]
Talked with @mdekauwe more about MAESPA. Here is an updated list of what needs to happen:
- [ ] Rewrite met2model using Remko's Maespa R package. It is a package that makes writing input files a lot easier
- [ ] Martin will find/write a function to find the closest meridian
- [ ] We will identify exactly which input files/values can be left as defaults and which can be handed over to PEcAn.
