### ISSUE TITLE
ED write configs.xml -- defaults, constants, and the history.csv

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#734]
The behavior of the `write.configs.ED2` script is strange, specifically the section responsible for writing the `config.xml` file. I'm not entirely sure what the role of the arguments `defaults` vs. `trait.values` is and how the information in these arguments is being used.

From discussions with @serbinsh and @mdietze , my understanding of how the ED `config.xml` *should* be generated is as follows:

1. The full set of default parameters for each PFT is read from the `history.r<revision>.csv` file. I know this is a temporary hack and should really be read from the database (as @robkooper recommends), but that shouldn't be a difficult fix once we figure this out.
   
    - Question: How do we know what PFTs to load from the `history.csv`? Is this where `defaults` comes in? Is it something in the `settings`? Is the assumption that every PFT that you use will be represented in `trait.values`? Or is the `config.xml` file just going to be populated with every PFT by default, and ED is told which of those PFTs to use somewhere else?

   - Looking at the [blame](https://github.com/PecanProject/pecan/blame/master/models/ed/R/write.configs.ed.R#L184), I think some of the confusion here stems from code introduced by @rykelly while he was working on parameter data assimilation (PDA). As Shawn and I understand it, Ryan's changes allow the user to use `defaults` to set parameters that have different values from those in `history.csv` but that are constant and not varied by the PDA code. We should have some discussion about the right place to do this: Should these independent constants be set in `trait.values` by the PDA code, or should they be set independently through `defaults` or `settings`? @istfer may want to weigh in on this as well, since she's working on PDA now.

2. Once the default values are set, `trait.values` is used to modify specific parameters for specific PFTs.

    - I'm a bit hazy on the proper format for `trait.values` -- I know it's a list of PFTs, but how are the names of the PFTs specified? I.e. Which of the following is correct? 
```
    trait.values <- list(early_hardwood = list(SLA = x), late_hardwood = list(SLA = y)) # ... or ....
    trait.values <- list(pft = list(SLA = x, name = early_hardwood), pft = list(SLA = y, name = late_hardwood))
```

   - The code has some references to either approach.

Any thoughts on this? @dlebauer may also want to weigh in.

**Comment by mdietze** [comment]
1. I think "defaults" should be dropped as an argument to write.configs.[model] because any defaults are actually being passed via settings and none of the models I've implemented are using this argument. At a minimum it should come last and be optional rather than being first and required.
 * We know what PFTs to load/use from trait.values. We definitely are NOT populating every PFT
 * Ryan's code should be easy to modify to allow defaults to be passed via settings as well

2. My understanding is that the first is correct. The second is how ED's config is formatted, not trait.values

**Comment by ashiklom** [comment]
@mdietze By the numbers, I meant the stages of the workflow -- as in, first
the defaults are set (1) and then trait values modify them (2). Is that
right?

Also, if trait values determine the PFTs used, does that mean you have to
modify a trait for every PFT even if you only want to perturb one? Like,
what if I wanted to do a sensitivity test for just hardwood SLA -- do I
have to still list every PFT that ED run is using in trait values?

**Comment by mdietze** [comment]
I think Ryan's logic was the other way around -- defaults could over-rule trait.values.

No, you don't have to modify a trait for every PFT just to perturb one, you should be able to pass a PFT with just a name. The idea is that trait.values is how PEcAn is passing on the information about which PFTs were selected. That said, PEcAn is also assuming that **IT** is determining the parameter values -- by design it makes data-informed posteriors the standard choice (rather than a model's hard coded defaults) and forces the user to explicitly declare any deviation from that.

**Comment by istfer** [comment]
you can set the constants within the settings via pecan.xml file for that I think, e.g. 

`<pfts>
   <pft>
      <name>PFT1</name>
      <constants>
         <mort2>...</mort2></constants>
   </pft>
   <pft> 
      <name>PFT1</name>
    </pft>
</pfts> 
`

whatever you hold constant won't go into the sensitivity test, here mort2 for PFT1 won't, if I get it right.. don't know if that helps

**Comment by ashiklom** [comment]
@mdietze That's only for Ryan's `defaults` though, right? As in, first the parameters from `history.csv` should be set, then some are modified by `trait.values`, and *then* we modify the rest via `defaults` (or `settings`).

@istfer Thanks, that is helpful! That means that we should be able to deprecate the `defaults` in this script since the same functionality can be achieved thorugh PEcAn's settings. Do you know how to access those values? E.g. In your example, would it be `settings$pfts$PFT1$constants$mort2`? Just so I can start thinking about how to ditch the defaults.

**Comment by ryankelly-uiuc** [comment]
Just to weigh in— @ashiklom , I also found `write.configs.ed2` code to be confusing, and admit I didn't try to suss the whole thing out. What I wanted—and it seemed to me that one way or another this had been someone else's original intent too—was a way to fix parameters at some value and not let Pecan change them. If I remember right, Pecan's MO is to override any parameter for which it has data with a prior median? Something like that. Well that makes sense in a way but it means that you have to pay attention to whether all the parameters have data in BETY, if the data's any good, what the priors are, etc. Whereas if you have some ED2 defaults that already "work" you might want to just leave them alone, except for a select group of them that you'd like to target for Pecan analysis. At least, that was my rationale. Obviously there are other good reasons you might want to be able to set parameters to specific values and have them stay put. 

My changes to the code were meant to "fix" that functionality for my purposes, while hopefully not breaking whatever other functionality was intended. But I totally agree that the code's confusing and apologize for probably adding to it.

**Comment by istfer** [comment]
>  In your example, would it be` settings$pfts$PFT1$constants$mort2`? 

yep.

**Comment by ashiklom** [comment]
Per the PEcAn skype call on 3/1, here is the pseudocode for the way this script should work. I'll take the lead on implementing that:

```
Inputs: settings, trait.values
defaults.from.history <- Get default values from correct history.csv / database
for(pft in trait.values):
    if(!pft.number %in% settings$constants) pft.number <- pftmapping(pft)
        If can’t find PFT, kill workflow with intelligent error message -- “here’s how you update the pft mapping”
        Also modify web app to not default to 1 
    vals <- defaults.from.history[[pft.number]]
    converted.trait.values <- convert(trait.values[[pft]])
    vals[matched names in trait.values[[pft]]] <- converted.trait.values
    vals[in constants] <- defaults.from.settings[[pft]]
    append.xml(xml, vals, name =pft, num = pft.number)
```
