### ISSUE TITLE
Camp PEON 2016

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#735]
What do we need working in PEcAn before the PalEON summer course (Aug 14-20) that goes above and beyond what we need working for the Flux Course?

For the flux course we'll need the main workflow and PDA code stable.

For PalEON we also need the state data assimilation (SDA) code that @araiho is working on

Along those lines we should probably also update the tree ring stats code, especially if @jam2767 makes any additions or modifications for his dissertation tree ring chapter.

More aspirational, I think it would be really cool to be add the Paleon met drivers to the list of met that we support remotely, either via Brown Dog like NARR or via setting up THREDDS on our own servers as part of the REST API that @robkooper is tasked with

The real reach goal would be to get #492 done to support the NEOTOMA database so that users could query, visualize, and (possibly?) assimilate paleo data.

Anything else on the wish list?

**Comment by mdietze** [comment]
Here's the minimum set of tasks left before Camp PEON
- [ ] Update Demo 1 and Demo 2 for v1.4.8: soil PFT, use load.data, metrics in validation
- [ ] Update PDA demo: soil, multiple chains / convergence, summary stats, updating
- [ ] Updated tree ring code
- [ ] Updated SDA code
- [ ] Updated SDA tutorial
- [ ] Updated lectures
- [ ] HF SDA figure for Puff Piece
- [ ] PalEON met in DB for UNDERC

Wishlist (mostly trying to get ahead of student project ideas):
- [ ] THREDDS PalEON met (backup: site met on webserver and download function in PEcAn)
- [ ] LPJ-GUESS and LINKAGES: test runs on paleo timescale
- [ ] demo fcomp validation against raw NEOTOMA pollen %
- [ ] example STEPPS 1 or 2 extractions for sites, model validation plots
- [ ] example LINKAGES SDA against NEOTOMA or STEPPS (1 or 2)

**Comment by araiho** [comment]
I think the PalEON met is in the DB for UNDERC? https://psql-pecan.bu.edu/bety/inputs/1000000535

**Comment by mdietze** [comment]
@robkooper there are a few additional things that need to be installed on this VM to support Camp PEON:

1. R libraries neotoma and R2jags
2. Clone the following repo into the home directory: https://github.com/PalEON-Project/Camp2016
 + Within that repo, run testInstall.R to run some tests
3. BACON: http://chrono.qub.ac.uk/blaauw/bacon.html
4. CLAM: http://chrono.qub.ac.uk/blaauw/clam.html

**Comment by tonygardella** [comment]
Camp PEON 2016 has passed so I'm closing this.

**Comment by ashiklom** [comment]
Closing this because Camp PEON happened almost 2 years ago.
