### ISSUE TITLE
Can not select host or model in web interface on 1.4.5 VM

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#755]
I tried to see if I could reproduce #754 with the 1.4.5 VM, but on the second page (http://localhost:6480/pecan/02-modelsite.php) I was unable to select either a host or a model. The dropdown boxes had no options other than "All Sites" or "All Models" respectively.

In the screenshot below I am trying to select models:

<img width="456" alt="screen shot 2016-03-17 at 4 24 47 pm" src="https://cloud.githubusercontent.com/assets/464871/13861714/d29fc0a6-ec5c-11e5-9af6-a95ea64fb302.png">

(also, it is not clear why the 'host' selector would say 'all sites' rather than 'all hosts' by default)

**Comment by mdietze** [comment]
Same here.  @tonygardella I thought you tested the VM exhaustively??  @robkooper we need to pull the VM off the download, rebuild, and then test before re-releasing an update. Preferably sooner rather than later

**Comment by tonygardella** [comment]
Have you guys edited the config.php? From the release notes:

## config.php changes

A major change has been done to the web interface configuration files. Please make sure to update your config.php, without these changes your web interface will not allow you to do any runs!

The variables $hostlist, $qsuboptions and $qsublist have been merged into a single variable called $hostlist. This list has a list of all hosts that are shown in the host pull down list, as well as any options for qsub. This now also allows you to specify a folder on the remote system to use. All runs will use this remote folder! Please see the example.config.php

The following variables are no longer used : $qsuboptions, $qsublist, $ed_soil, $ed_inputs and can be safely removed from you config.php (after fixing the above).

**Comment by tonygardella** [comment]
After using config.example.php to make the edits, you should see hosts and models and be able to execute runs.

![pecan32](https://cloud.githubusercontent.com/assets/8570691/13862306/bbfd8f66-ec68-11e5-93b9-482698961fd2.PNG)

**Comment by robkooper** [comment]
But that should have happened automatically before the user downloads the VM. Will remove from download and tag it 1.4.5.1 when I push it back up. Hopefully tonight.
