### ISSUE TITLE
Stop after model run step if model fails

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#761]
The code that runs the model should throw an error if a model crashes or if there are no netCDF files in the output directory. In doing so it should also produce an clear error message to this effect. Right now the code keeps going until it hits the ENSEMBLES step, and then throws an error that lots of people are misinterpreting (e.g. telling me "but the model's running" just because it gets past the model run step).

**Comment by robkooper** [comment]
This solves the problem for ED, I tested sipnet. If this fails for any specific models please open a new ticket and add there which model it fails for and an example so I can recreate it.
