### ISSUE TITLE
Ameriflux multiple year met.process bug

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#769]
@ashiklom and I ran into a bug when running Dalec for multiple years at Willow creek. It fails at the met.process/CF standardization step.

**Comment by mdietze** [comment]
What years, what's the error message, and what's the ensemble?  It's far more likely that you're running into an issue with a specific year (missing data on the server, gaps to big to gapfill) than you are running into a generic issue with Dalec met not liking multiple years

**Comment by tonygardella** [comment]
ID: 1000001427
start year: 1998 
end year: 2004

```
2016-03-29 14:25:51 INFO   [convert.input] : 
   Convert.Inputs met2CF.Ameriflux 1000000744 localhost 
   /fs/data1/pecan.data/dbfiles/Ameriflux_CF_site_0-676 CF Meteorology 
   application/x-netcdf 676 1998/01/01 2004/12/31 
[1] "start CHECK"
[1] "end CHECK"
data frame with 0 columns and 0 rows
2016-03-29 14:25:51 ERROR  [convert.input] : 
   dbfile not found 1000000744 
2016-03-29 14:25:51 INFO   [PEcAn.data.atmosphere::met.process] : 
   Finished change to CF Standards 
2016-03-29 14:25:51 INFO   [PEcAn.data.atmosphere::met.process] : 
   Begin Standardize Met 
2016-03-29 14:25:51 INFO   [PEcAn.data.atmosphere::met.process] : Gapfilling 
Warning in postgresqlExecStatement(conn, statement, ...) :
  RS-DBI driver warning: (unrecognized PostgreSQL field type geometry (id:92093) in column 18)
2016-03-29 14:25:51 INFO   [convert.input] : 
   Convert.Inputs metgapfill localhost 
   /fs/data1/pecan.data/dbfiles/Ameriflux_CF_gapfill_site_0-676 CF 
   Meteorology application/x-netcdf 676 1998/01/01 2004/12/31 
[1] "start CHECK"
Warning in is.na(parentid) :
  is.na() applied to non-(list or vector) of type 'NULL'
Error in if (is.na(parentid)) { : argument is of length zero
Calls: <Anonymous> -> convert.input -> dbfile.input.check
> proc.time()
   user  system elapsed 
  4.538   0.498  18.682 
```
In /fs/data1/pecan.data/input/Ameriflux_CF_gapfill_site_0-676 only netcdf files for 2002 to 2005 and then 2010 and 2011 exist so I think when it looks for the id of met files of all the years it can't find them.

**Comment by mdietze** [comment]
Assuming you didn't just delete the dbfiles record, the other thing notable here is that an inputs record exists for this site/met but that record doesn't have any dbfiles associated with it. That would explain the "dbfile not found" error more than the folder having some, but not all, files.

**Comment by tonygardella** [comment]
related to #969
