### ISSUE TITLE
Update version of Git on everything

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#781]
The latest version of Git is 2.8 (2.5 is the latest one in the base Ubuntu repositories). The one running on the VM is 1.9, and the one on pecan2 is 1.7. It's not imperative that we keep up with every minor release, but we should update through the latest major release (2.0) since it has [important changes](http://blogs.atlassian.com/2014/06/happened-git-2-0-full-goodies/) that we can take advantage of.

None of these changes should break anybody's workflow. The biggest change is to default `git push` mechanics, but this only causes a long and informative warning to be thrown, which can be resolved with a single `git config --global` setting.

**Comment by bcow** [comment]
It looks like updating git on centos 6 is a bit more involved. 
http://tecadmin.net/how-to-upgrade-git-version-1-7-10-on-centos-6/#
I'd be happy to do it if you all think it's a good idea.

**Comment by dlebauer** [comment]
To clarify:  

1. will failing to update cause any issues (other than warnings)?
2.  does 2.x offer any improvements or changes to current workflow?

**Comment by ashiklom** [comment]
@dlebauer 

1. No, at least not for basic git (which is most of what we do).
2. Some advanced Git functionality is either worse or entirely absent from earlier git versions. In leading some advanced Git tutorials, I've come across commands that don't work in pre-2.0 versions of Git. These commands are not a part of the standard workflow, but are very helpful in resolving Git issues (e.g. accidentally committing large files, history re-writes). I unfortunately can't think of any off the top of my head, but I can dig around my notes and see what they were. I also suspect newer versions of git play much better with git large file storage, which we have discussed using elsewhere.

**Comment by ashiklom** [comment]
A good example of a command that is better post 2.0 is `git add <path`. Before 2.0, it ignores file moves/removals. After, it includes them. This is a significant benefit to the basic workflow because telling git to stage file deletions is notoriously counter-intuitive (at least to me).

**Comment by robkooper** [comment]
On the VM I tend to stay with the version of software that comes with the OS, that way I don't have to mess with the updates myself and all dependencies. Could you like the tutorial and maybe some of the advanced use cases?

**Comment by ashiklom** [comment]
@tonygardella This isn't all that important, and doesn't seem to have much enthusiastic support from our community, so you can probably close it.
