### ISSUE TITLE
Browndog and NARR

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#787]
@seanmcm tried to run ED2 at Harvard Forest from 2010 to 2015 using Brown Dog NARR with a basic setup and ran into an error. ED2 Met is not being created. 

NARR is the only met product we have integrated that covers those years. This needs to be understood and fixed asap.

**Comment by robkooper** [comment]
Ingested data, should work now

**Comment by seanmcm** [comment]
Hi Rob, 
Thanks much. 

Sorry to email broadly, but I’m trying to understand how to debug this platform.  

Attached is the results, but don’t know how to figure out what’s wrong. So looks like met data works, but don’t know why the ‘ensemble’ would fail.  Not trying to do anything special with ensemble models (yet).  Could you look into this?  Be glad to chat.  

Thanks, 

sean

**Comment by mdietze** [comment]
Sean,

* No attachment came through to Github
* The error message at the ensemble step is a known issue -- this can occur when the model itself fails, but that fail doesn't get caught by PEcAn, so PEcAn then later fails when it's trying to read the model output, which doesn't exist (a single run in PEcAn is actually an ensemble of n=1 so the ensembles step is always called).
* You should be able to look at the ED2 log messages on the results page, which should give you some idea where/how ED itself failed.
* One known issue with ED is that it doesn't like to start deciduous systems on Jan 1 because it causes weird issues in the phenology -- you might try starting Jun 1 instead.

**Comment by seanmcm** [comment]
Thanks Mike,

i’ll give this a go.  I essentially did the same setup that ran on jan 1 2004 to dec 31 2004, but changed the years.  I’ll let you know how it goes.  

Sean

**Comment by seanmcm** [comment]
Mike, Sorry to bother the list  more.  Here’s log output … it’s pretty emphatic!



[+] Init_Met_Drivers...
==================================================
 Polygon lies outside the met driver domain!!!
==================================================
 + Polygon: 
   - Longitude :  -7.21715E+01
   - Latitude  :   4.25378E+01
 + File: :  /home/carya/output/dbfiles/BD-76d144e11c50
 + Meteorological data boundaries: 
   - West      :  -7.20805E+01
   - East      :  -7.10805E+01
   - South     :   4.22327E+01
   - North     :   4.32327E+01
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
------------------------------------------------------------------
                     !!! FATAL ERROR !!!                          
------------------------------------------------------------------
    ---> File:        ed_met_driver.f90
    ---> Subroutine:  init_met_drivers
    ---> Reason:      Polygon outside the domain of the meteorological drivers
------------------------------------------------------------------
 ED execution halts (see previous error message)...
------------------------------------------------------------------
STOP fatal_error

**Comment by mdietze** [comment]
Hmm, that's odd -- the met data boundaries should be centered on the site (polygon) lat/lon but in this case the site longitude is outside the met boundaries, which means either the wrong grid cell was extracted or the lat/lon got messed up in translation somewhere. @tonygardella could you look into this today?

**Comment by dlebauer** [comment]
@tonygardella perhaps check
https://github.com/PecanProject/pecan/blob/1743b942fdba4adb7cd6cc7716f2f3ae258eb2c0/modules/data.atmosphere/R/closest_xy.R

One suspect: f it ends up with > 1 closest points at the end it takes the
first one and gives a warning.

**Comment by tonygardella** [comment]
Should the lat/lon in ```ED_MET_DRIVER_HEADER``` match the site(polygon) lat/lon?

**Comment by mdietze** [comment]
Lat/Lon in the met header needs to box the site Lat/Lon

**Comment by robkooper** [comment]
One thing to look at is the NC file and make sure it has the right lat/lon in it. See the code at: https://github.com/PecanProject/pecan/blob/master/models/ed/R/met2model.ED2.R#L89-L103, before this was using meters instead of degrees, but we might run into the same problem again. What are the values in the MET_HEADER and what site lat/lon should it be (also what is the site).

**Comment by robkooper** [comment]
Looking at the values, the area extracted is really small (0.1 degree). I think we use 1 degree in other places around the site.

**Comment by mdietze** [comment]
But that shouldn't make a difference, the box should just be the site Lat/Lon +/- 0.5 * box size

**Comment by tonygardella** [comment]
The MET_HEADER had: -71.5805130004883,  42.7327003479004
and the site lat/lon is: -72.1715, 42.5378 which is Harvard forest.

Ill take a look at met2model

**Comment by bcow** [comment]
@robkooper could you look at 
https://github.com/bcow/pecan/blob/master/models/ed/R/met2model.ED2.R#L110-L111

It should look like this 
```
  lat  <- eval(parse(text = lat))
  lon  <- eval(parse(text = lon))
```
and the function should have lat and lon as arguments. 

This problem came up before in pull request #468 and the changes I made seemed to work for our local builds of pecan

**Comment by bcow** [comment]
Specifically commit https://github.com/PecanProject/pecan/pull/468/commits/10bf7e1163f00bd4802b056e5cf36ed070829795

**Comment by robkooper** [comment]
This seems to come up, but the met_header claims to be using 1 degree around the lat/lon: https://github.com/bcow/pecan/blob/master/models/ed/R/met2model.ED2.R#L303

Also do we see any of the following when the data is generated:
https://github.com/pecanproject/pecan/blob/master/models/ed/R/met2model.ED2.R#L94

**Comment by tonygardella** [comment]
Consulted with @mdietze about this and added this commit to make sure the lat lon in the extracted nc file match the site lat/lon: https://github.com/PecanProject/pecan/pull/784/commits/ac859982042060cd8a31397bd08d77f97f6c0203

It made a test run work if I used the existing NARR we have on our server. We'll have to do further tests with Browndog and other sites to close this issue.

Sorry I tacked commit onto my other pull request. I was making a flurry of commits/pull requests and got my branches mixed up.

**Comment by robkooper** [comment]
This should be resolved, if not could you open a new issue and we can look at it.

**Comment by seanmcm** [comment]
Thanks Rob.  I’ll set aside some time to test again. 

Sean

**Comment by mdietze** [comment]
@seanmcm while this bug is resolved, ED2 is still failing after 1 month #808 and we haven't yet had a chance to dig into what ED2 doesn't like about the met drivers it's getting. Will keep you posted.

**Comment by seanmcm** [comment]
Is there another model that can run HF for the years 2011 to 2014? 

And if there comes a time when I might help without ‘getting in the way’, let me know.  

thanks,

Sean

**Comment by mdietze** [comment]
Just successfully ran SIPNET and DALEC on this VM http://54.164.131.188/pecan and you can grab the results from the History table. There's are a few other models I could try, but it will require a work around to #773

Sean, you're definitely not getting in the way -- finding bugs is very helpful, and I just wish we were closing them quicker so you could be up and running.

Semester's finishing up so let's find a time to chat about plans
