### ISSUE TITLE
ERROR Messages when PEcAn fails

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#789]
We need to make PEcAn more informative when a run fails. For first time users it is not very clear as to where to start troubleshooting from.  A general solution is to direct the user to workflow.Rout, the model execution log file (logfile.txt), and the stdout and stderr file in output. I think a simple message telling the user to look at these files in the drop-down menu would suffice for now. 

@tonygardella Troubleshooting needs to be updated in the gitbook as well.

**Comment by tonygardella** [comment]
@robkooper Could you add a message that appears to the user after a run fails directing people to workflow.Rout and other files they could troubleshoot from?

**Comment by mdietze** [comment]
In particular, if @robkooper can modify the php to detect the error and display ANYTHING then @tonygardella can update the text

**Comment by robkooper** [comment]
Added some text,feel free to modify.
