### ISSUE TITLE
Are the units in Ensemble / sensitivity analysis graphs labeled incorrectly?

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#792]
Graph with the histogram on the left and the boxplot on the right

It is my understanding that the units are Kg C / ha / year

But they are labeled as kg C / m2 / s

@Viskari @dlebauer @ashiklom @tonygardella Am I wrong?

**Comment by tonygardella** [comment]
@serbinsh I believe it should be  kg C / m2 / s. We agreed that the MsTMIP output variable names/units were what we would use and all carbon fluxes have kg C / m2 / s as units.

**Comment by serbinsh** [comment]
Hmmm...but my resulting values are really really high.  I am properly putting them into kg C / m2 / s when converting to netCDF and the values are as expected (very small) but the values on the PDFs are around like 7000+ units. Maybe if this was added over a year it would make sense but per second doesnt

**Comment by serbinsh** [comment]
[ensemble.analysis.NOENSEMBLEID.GPP.2005.2005.pdf](https://github.com/PecanProject/pecan/files/213640/ensemble.analysis.NOENSEMBLEID.GPP.2005.2005.pdf)

**Comment by serbinsh** [comment]
sorry actually higher, like 72K+

**Comment by tonygardella** [comment]
@serbinsh I went and looked at a bunch of runs with other models and all have the same mismatch. The time series of NPP and GPP is many orders of magnitude smaller than what the histogram shows. The magnitude of the histogram is definitely off.

**Comment by serbinsh** [comment]
OK, thanks for the feedback @tonygardella. At least I know I am not going crazy!  Maybe an extra call to unit conversions somewhere int he plotting that is causing "units gone wild" ?

**Comment by mdietze** [comment]
Yes, there's a built in conversion in there. You can get rid of it if you want

**Comment by Viskari** [comment]
As Mike said there is currently a built-in conversion in pecan/utils/read.output.R which converts both NPP and GPP from kg m-2 s-1 to kg ha-1 yr-1

**Comment by serbinsh** [comment]
kg ha-1 yr-1 is fine we just need to make sure we are putting the correct units in the ensemble and SA graphs.

**Comment by mdietze** [comment]
Folks definitely questioned UNITS at flux course -- need this fixed in v1.4.8
