### ISSUE TITLE
Ignore file types within web interface?

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#793]
@robkooper Is it possible to ignore additional file types within the web interface such that they do not show up as an option in the drop down?  Sometimes my mac computer will create those .DS_Store hidden files that show up in the PEcAn Files menu.  Low priority but I thought I might ask if this is possible.

<img width="372" alt="screen shot 2016-04-12 at 8 30 09 am" src="https://cloud.githubusercontent.com/assets/3067369/14459996/2d2a7cba-0089-11e6-945d-3ff08ba3d180.png">

**Comment by robkooper** [comment]
Should ignore all files that start with a period.
