### ISSUE TITLE
Mac OSX users: Install XCode from developer downloads not App Store

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#833]
A lesson learned.  I just updated my home desktop to El Capitan and was spending time this morning trying to get it up and running to work on some PEcAn code.  However I made the mistake of installing XCode (needed for ports, gcc, command line tools, etc) through the App Store.  I never do this but I figured, "why not I don't then have to login somewhere else".  Bad choice.  

This post says it all: http://ericasadun.com/2016/03/22/xcode-upgrades-lessons-learned/

My favorite is: "When Apple’s servers are overwhelmed they begin delivering artisanal teaspoons of hand-curated data via authentically indigenous pack animals to your computer. Apple has taken its passion for the slow data delivery movement beyond its products and introduced it into its upgrade practices."

Thus just use the developer downloads:
https://idmsa.apple.com/IDMSWebAuth/login?appIdKey=891bd3417a7776362562d2197f89480a8547b108fd934911bcbea0110d07f757&baseURL=https://developer.apple.com/&path=%2Fdownloads%2F&rv=1

This could be parsed to documentation if anyone else thinks this is helpful.

**Comment by serbinsh** [comment]
An the folks who use Linux at home or on a laptop, I know what you are going to say (e.g. @ashiklom) but I like also being able to run other programs like Adobe Lightroom.....

**Comment by robkooper** [comment]
That being said, keep the following in mind as well when downloading software: http://9to5mac.com/2015/09/20/xcode-ghost-app-store-malware-malicious-apps/

People downloaded xcode from a site to get fast download and ended up with a special version of xcode that added a virus to code you compiled.

**Comment by serbinsh** [comment]
@robkooper understood however the Xcode developer tools site (link above) is legit.
