### ISSUE TITLE
Missing dependency for R Linkages (git)?

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#837]
When I tried to run this:

https://github.com/PecanProject/pecan.book/blob/9512cc450022e43ff30ea5431ee5f50dde6edca5/developers_guide/Installing-PEcAn.md

#R Version
git clone https://github.com/araiho/linkages_package.git
R CMD INSTALL --no-multiarch --with-keep.source linkages_package

I received a missing dependency error for **_microbenchmark_**  I checked and did not see it in install_dependencies.  Just checking that this package is meant to be required for Linkages before I add it to the install_dependencies script.  @araiho 

Thanks!

**Comment by serbinsh** [comment]
If it wasnt clear, installing that R package allowed me to install R linkages.

**Comment by araiho** [comment]
@serbinsh I'm working with some tech folks at BU to help me make the R version of LINKAGES faster. They are using that package to check code speed. I'll probably take it out eventually, but it'll be in there for a little while longer. Does that answer your question?

**Comment by serbinsh** [comment]
Hi @araiho Yes, it does thanks! I wonder if we should add this as a dependency until it is optimized, just in case someone else hits the same issue as me?

**Comment by robkooper** [comment]
I think you can add Depends to the DESCRIPTION file which will tell R you need this when you try to install the package. Then when you try to install it, I believe it should try and download it when it is not installed.

**Comment by araiho** [comment]
@serbinsh  Should be fixed now. Let me know if you have any other problems.

**Comment by araiho** [comment]
@tonygardella I think you might be able to close this issue
