### ISSUE TITLE
Issue installing BayesianTools from Dropbox

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#838]
I was working on upgrading packages and ran into an issue attempting to pull Bayesian Tools from Dropbox.  

```
> library(devtools)
> devtools::install_url("https://dl.dropboxusercontent.com/s/hy9l6mokresqyel/BayesianTools_0.0.0.9000.tar.gz")
Downloading package from url: https://dl.dropboxusercontent.com/s/hy9l6mokresqyel/BayesianTools_0.0.0.9000.tar.gz
Error in download(bundle, x$url, x$config) : Unauthorized (HTTP 401).

```

I am getting a 401 error.  Does it still exist in this location?  Is there a new location?  Is there something else I should be doing @istfer? This is how it is defined in the install_dependencies.R

Thanks!

**Comment by istfer** [comment]
yes, it has changed recently, they're getting prepared to move the package to CRAN. the new location is this for now:
```
library(devtools)
install_url("https://github.com/florianhartig/bayesianTools/releases/download/v0.0.9.0/BayesianTools_0.0.9.0.tar.gz")
library(BayesianTools)
```
I'll revise the code that uses BayesianTools in general on Tuesday (because they made other changes too)

**Comment by serbinsh** [comment]
OK, great.  Thanks!

S
On May 15, 2016, at 9:42 AM, istfer <notifications@github.com<mailto:notifications@github.com>> wrote:


yes, it has changed recently, they're getting prepared to move the package to CRAN. the new location is this for now:

library(devtools)
install_url("https://github.com/florianhartig/bayesianTools/releases/download/v0.0.9.0/BayesianTools_0.0.9.0.tar.gz")
library(BayesianTools)


I'll revise the code that uses BayesianTools in general on Tuesday (because they made other changes too)

**Comment by istfer** [comment]
until the repo is made public the new location for the file in dropbox is this:

`install_url("https://dl.dropboxusercontent.com/s/ccvpnvblf3vzuvs/BayesianTools_0.0.0.9000.tar.gz")`

**Comment by serbinsh** [comment]
Thanks!
