### ISSUE TITLE
Web interface error after latest pull

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#852]
Just pulled latest code to a clean VM and when trying to do a run from the web interface I ran into this error on 02-modelsite.php:

```
Invalid query: ERROR: relation "sitegroups" does not exist LINE 1: SELECT id, name FROM sitegroups WHERE public_access OR user_... ^
```
@istfer ran into something similar and I was trying to recreate the error.

**Comment by dlebauer** [comment]
@tonygardella did you update the database to 4.9?

**Comment by tonygardella** [comment]
I remembered you announcing a new version a minute after I wrote this. Do I just need to run ```update-bety.sh``` in the bety directory?

**Comment by serbinsh** [comment]
No dont run that @tonygardella 

https://github.com/PecanProject/bety/wiki/Updating-BETY#update-the-rails-app-and-schema

**Comment by ankurdesai** [comment]
Tony, use these steps for updating VM: https://pecan.gitbooks.io/pecan-documentation/content/users_guide/advanced_users_guide/Upgrading-pecan-vm.html

**Comment by tonygardella** [comment]
@ankurdesai @serbinsh Are these two sets of instructions supposed to do the same thing? 

I haven't touched the pecan gitbook page so I know those are old. The first file in the instructions you're supposed to remove doesn't exist.

In the PecanProject/bety wiki it points to bety in the /usr/local/bety directory which is not correct. The bety directory is in /home/carya. Other than that though it works.

**Comment by serbinsh** [comment]
@tonygardella Apologies, I just sent the link but it is a little specific to the install.  I typically:

git pull upstream master within the main BETYdb dir

then run

bundle install --without test

or in my case 

RAILS_ENV="production" bundle exec rake db:migrate

then run

touch tmp/restart.txt

To clarify, you are just trying to migrate BETYdb to 4.9 correct?  These are the only instructs you should need.

**Comment by tonygardella** [comment]
going through the instructions on gitbook leave me with an error after trying to install ruby:
```
E: Unable to locate package passenger-common1.9.1
E: Couldn't find any package by regex 'passenger-common1.9.1'
```

The gitbook page is 2 years old and the bety wiki is newer so I'll link to those ones in the the gitbook and erase the existing instructions.

@serbinsh thanks Shawn! I was checking things on a VM because the latest build had broken things on our test-pecan server and we realized we just need to update bety. The instructions on the bety wiki worked fine for the VM.

**Comment by tonygardella** [comment]
I got rid of the old instructions in gitbook and added a link to the bety wiki. Pull request for change is here: https://github.com/PecanProject/pecan.book/pull/23
