### ISSUE TITLE
Rerwite met2CF.csv to work with web workflow

### ISSUE THREAD

**Issue by ankurdesai** [PecanProject/pecan#882]
modules/data.atmosphere/R/met2CF.csv is the function that allows conversion of arbitrary CSV files to the Pecan CF met format, written by Mike and David once upon a time. Based on mimetype (test/csv) - met.process, written by Betsy and Mike, will call a met2CF mimetype based function if no format specific function is defined and convert to CF is set to TRUE (based on file type registration in XML file). As it is written, this actually will not work from met.process, and will require a coordinated set of changes to met.process, utils/convert.inputs, db/query.format.vars, and maybe others to play nicely. I am taking a stab at doing this, perhaps with guidance from @dlebauer and @bcow and @mdietze , with the primary flux course goal of getting this to work first and foremost with Fluxnet2015 and AmerfluxLBL (and I will need @robkooper once we get to web integration stage), but I have a few design philosophy questions on handling of datetime, searching for variables by header name or column number, and so forth.

Things I have committed on my fork: correcting mimetype matching of function name in met.process (right now it will call met2text/csv.R - wrong!), modifying query.format.vars to allow either input.id or format.id (since new inputs to be downloaded and converted do not yet have a input.id), calling query.format.vars in met.process (which has a open connection to bety) and passing that information optionally to convert.inputs (which if running on remote does not), which will now optionally pass that to the given function, and finally making met2CF.csv function arguments the same that convert.inputs expects.

Things I (think I) need to do: if input.id is given, query.format.vars should try to get lat/lon from site.id for format and add that to format definition passed to met.process (assuming input is linked to a site).  Add a ... to all other met2CF functions to allow silent pass-through of unused arguments. Deal with the fact that multiple BETY names exist for standard variables, and that formats_variables may use any of these, while currently met2CF expect only certain ones.

Questions I have

1) met2CF assumes there is a bety named variable "datetime", which as far as I know does not exist (start_date is the closest). Nor have any of the data formats been defined with time stamp as a variable, only the data variables.So how do we decide which column is time stamp? And is our current use case the one where timestamp is only in one column (e.g., not files that have year,month,day)?

My proposal - is format passes something called "datetime" - use that. If not, assume first column is datetime and is in format of one of YYYY-MM-DD HH:MM or YYYY/MM/DD HH:MM or YYYYMMDDHHMM (ISO standard and fluxnet standard). To do for later: deal with CSV files that have separate columns for Year, Month, Day, ... 

2) This chunk of code pasted below somehow calls a unit conversion function based on time stamp units - how are time stamp units defined and which library has these functions?
    ## Get datetime vector
    datetime_index <- which(format$bety == "datetime")
    datetime_raw <- dat[, datetime_index]
    datetime <- do.call(format$units[datetime_index], list(datetime_raw))

3) How much do we want to rely on header name to identify which column relates to which variable and how much on column_number? Right now, it is based on header column names match the mapping of header name to bety name in Formats Variables table. My proposal is that if column number is passed, use that. If not, search by name.

4) Many variables are mapped multiple times in Bety variables. How much should I just select one in the selection of met vars and give up if the Format record doesn't link the CSV column to that variable (e.g., if column says it is downwelling_shortwave instead of solar_radiation) and how much to define a dictionary (so if column = solar_rad or downwell_shortwave or ..., then convert this to CF downwelling...). This partly depends on the speed at which we do the variable clean up.

5) Should we also go ahead and grab NEE,LE,H if these are in the fluxnet files, or only the met needed for running models (as it does now).Doing the former would allow for the NC met file to be easily used for comparison to model output without needing to resort to load.data. 

Sorry for the long issue, but want to make sure everyone who cares about this function has their say.

**Comment by mdietze** [comment]
1) on datetime, I think some column or columns HAS to be the date. Assuming it's the first column strikes me as unsafe. FYI @istfer is struggling with this too in adding the new read functions to the PDA code, so you might take a peek at here recent PR with that. Should add that to the discussion in tomorrow's telecon, but I think we need some sort of flag in formats_variables that flags a variable as part of the date/time

2) I'm not 100% sure, but I suspect that the idea was that the date time 'units' is supposed to be the name of the lubridate function that will parse the date. This is definitely something that could be discussed

3) Column number is there for files that lack headers. If I understand correctly, the root of the question is that if a file has a header AND column numbers, which gets precedence if they don't agree with one another?  I'd lean toward that being an error, and my second choice would be to go with the column names (assuming that if file formats are not 100% conforming, or if someone miscounted, then the name is more likely to be correct)

4) My preference would be to post these and we clean them up ASAP.  Also, when it comes to met variables I was unaware of duplicates (this hadn't come up in any of the other met functions) -- I thought that the official met variables and the records associated with the correct BETY var were already defined in the gitbook.

5) No, don't grab NEE, LE, and H as they have no use in a met file and will just waste space. Other code is responsible for reading these files when we're doing benchmarking, visualization, and data assimilation and that code won't be looking in the CF derived files.

**Comment by ankurdesai** [comment]
Thanks. I agree we should talk about dates in formats. I now better understand the convert function for datetime, too. I agree on your column number point -> use if no header.

Proposal for datetime: Create bety variable “datetime”.  Require formats to have a column that maps to that variable and the units = lubridate function for reading

Regarding the variable name: consider these:
  Variable 86 is AirT
  Variable 573 is air_temperature
-or-
Variable 547 solar_radiation
Variables 564 surface_downwelling_shortwave_flux_in_air

According to https://pecan.gitbooks.io/pecan-documentation/content/developers_guide/Adding-an-Input-Converter.html <https://pecan.gitbooks.io/pecan-documentation/content/developers_guide/Adding-an-Input-Converter.html>
  The correct BETY variable is airT and solar_radiation, which will map to the CF name air_temperature in conversion and shortwave_downwelling.... But that is confusing to someone defining a format (like me!)

We also have cases where the GitBook does not mention the BETY name, such as mole_fraction_of_carbon_dioxide_in_air, which should map to 135 co2atm I think.

So we have two options:
  enforce that. met2CF.csv will only look for variable tied to bety variable 86/547, not to 573/564, and convert that to air_temperature and shortwave_downwelling... in the NC file. 
  Include a which statement that accepts either of those in case a format is defined for the wrong one (like I did with the flunet)

On a side note, the web interface to modify formats_variables in formats doesn’t allow for changes (in units, name, or column #) once an association is defined (changes don’t update for me) - have to delete the entry and recreate it. Small annoyance, but maybe issue worthy if others see the same problem. Could be browser specific. 

-ankur

**Comment by mdietze** [comment]
datetime: sounds good

variables: you are right to be confused!!  Someone (I can't tell who) incorrectly created the later variables at some point after we had the met workflow working and documented, thus creating the redundancies  you see. This should not have happened -- given the serious mess that the variables table is I'm tempted to say that we should set that table to require admin privileges for creating/editing.  I'd stick to the old variables (lower ID number) for now and not code up a which statement to accept either. These variables need to be high on the clean-up list.

Yes you want co2atm. @tonygardella could you update the gitbook

@dlebauer @gsrohde could one of you create a BETY issue about fixing formats_variables? Ankur says edit doesn't work.

**Comment by gsrohde** [comment]
> @dlebauer @gsrohde could one of you create a BETY issue about fixing formats_variables? Ankur says edit doesn't work.

Done.
