### ISSUE TITLE
google map now requires key

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#884]
Google changed their terms of services for the map and now requires a key. See also: https://www.latecnosfera.com/2016/06/google-maps-api-error-missing-keymap-error-solved.html

**Comment by robkooper** [comment]
Added new configuration flag $googleMapKey. If not set it will run without a key. This is fine for sites that have been using a google map before, but for those that are new (i.e. Amazon AWS and others) they will need to create a key and set it in the configuration file. To do this goto https://console.developers.google.com/apis/credentials and create a new credential.

**Comment by mdietze** [comment]
Do we want to ship the VM with a default key? If the key's allowed hundreds of thousands of hits per day I can't imagine we'd run through that even if the whole PEcAn community is using one key.

**Comment by robkooper** [comment]
Free until exceeding 25,000 map loads per 24 hours
https://developers.google.com/maps/documentation/javascript/usage

**Comment by robkooper** [comment]
Added default key to google maps.
