### ISSUE TITLE
Change build.sh to only install core modules by default, or by a particular argument

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#886]
I often have trouble installing PEcAn modules on my systems, especially new ones or those under active development, even when integration tests pass.

In many cases, I am not actually using these packages. On one hand it is good if people run into errors and report them. On the other, it makes it difficult to pick back up with the most recent version of PEcAn on my local machine.

I'd suggest either only installing core modules by default and having an `--extras` flag or having a `--core` flag to make it easy to install a subset of packages.

For model-specific packages, most users currently are using only one or a few models, and it shouldn't be necessary to install all of these.

**Comment by ashiklom** [comment]
At a recent PECAN call, we discussed moving from `bash` to `make`, which would dramatically accelerate the typical install by  only installing changed packages and their dependents. With `make`, arguments are also really easy -- it's very straightforward to implement the functionality @dlebauer describes. 

@robkooper Any reasons you can think of for sticking with `bash` over `make`?

Apologies if this was already discussed elsewhere.

**Comment by robkooper** [comment]
Nope no specific reason.

Rob

**Comment by bpbond** [comment]
We use `make` for a big (~100 scripts, ~1000 data objects) data pipeline system in R. It has the advantages mentioned by @ashiklom above, but it's worth noting that one of `make`'s fundamental assumptions is that each step produces a single target (e.g. there may be many source code files but they produce a single executable). This is not true in our case, where a script may produce many data outputs, each of which could be used in subsequent steps. We've found that this makes it tricky to have an efficient `make` system. There are workarounds, but consider whether this applies to PEcAn.

Also, FYI the [remake package](https://github.com/richfitz/remake).

**Comment by mdietze** [comment]
@bpbond thanks for the suggestions 😄   -- useful general info about options for workflows. In this particular case @ashiklom is referring to the build of the system software itself. Right now we have a build script that rebuilds every single R package in the system, even if 95% of those packages haven't been touched. Since they're R packages, they do have a single target. Having ```make``` check if a package has been touched or not before building it seems like it shouldn't be too hard.

**Comment by robkooper** [comment]
One option is to have a makefile in the root, and a makefile in each subfolder. These subfolders will use the R/inst files to see if it needs to be rebuild

The makefile in the root just call all the subfolders.
