### ISSUE TITLE
Add GFDL, Fluxnet2015, and AmerifluxLBL to web scrip

### ISSUE THREAD

**Issue by ankurdesai** [PecanProject/pecan#889]
@robkooper Fluxnet2015, AmerifluxLBL, and GFDL should be three more choices in the web workflow for selecting conversion met. As long as settings$run$inputs$met$source = one of these, at least Fluxnet2015 and AmerifluxLBL should work. GFDL download is being fixed to allow default options, which will also allow it to work, but the assumption is that advanced edit is needed to add tags in inputs$met on experiment and scenario. James is looking into modifying met.process to pass those forward.

**Comment by robkooper** [comment]
Couple of things that are needed, any of them have any licenses that people need to agree with?
Any restrictions, for example Fluxnet2015 and AmerifluxLBL do they have limited subset of sites?

Eventually this should come from the sitegroups_sites table.

**Comment by ankurdesai** [comment]
Ameriflux LBL should show same license as Ameriflux:
http://ameriflux.lbl.gov/data/data-policy/
Fluxnet2015 should be the Tier 1 policy at:
http://fluxnet.fluxdata.org/data/data-policy/
GFDL - haven't found it yet

On Fri, Jul 8, 2016 at 9:41 PM, Rob Kooper <notifications@github.com> wrote:

> Couple of things that are needed, any of them have any licenses that
> people need to agree with?
> Any restrictions, for example Fluxnet2015 and AmerifluxLBL do they have
> limited subset of sites?
>
> Eventually this should come from the sitegroups_sites table.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PecanProject/pecan/issues/889#issuecomment-231510372>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC8PlziGBUKxRQWRZ3kHHSmOrp3xWdy7ks5qTwptgaJpZM4JCgFq>
> .
>



-- 
Ankur Desai
UW-Madison
+1-608-218-4208
desai@aos.wisc.edu

**Comment by robkooper** [comment]
reopen if I need to modify any of the items/data policy
