### ISSUE TITLE
Flushing out Site Groups

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#900]
Add Fluxnet, Mandifore, ForestGeo, LTER, and NEON to site groups pull down menu in the web interface.

**Comment by mdietze** [comment]
Need to add PalEON site network and then remove PALEON site tags from the site names. This is currently causing a bug at Howland, because download.Ameriflux is parsing he PalEON tag for the site name rather than the Ameriflux tag.

**Comment by mdietze** [comment]
Got all of these done, just missing the separation of the general FLUXNET sites from the FLUXNET2015 Tier 1 sites (i.e. those sites which we can download met for)
