### ISSUE TITLE
Duplicate Model records

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#906]
There's a number of duplicate records in the Models table. To solve this the person responsible for the duplicate has to do the following steps:

1. Edit their own Model record and delete the dbfile associate of their executable with that record
1. Edit the correct Model record to associate their executable's dbfile record with that Model record
1. Delete their duplicate Model record

Here are the duplicates:
- [x] ED2 v42 Illinois -- no executables associated, can be deleted @robkooper 
- [x] ED2 v46 BNL @serbinsh 
- [x] ED2 v80 Illinois -- no executables associated, can be deleted @robkooper 
- [x] ED2 v82 BNL @serbinsh  and Wisc @ankurdesai should be associated with BU version
- [x] ED2 vUNK BU -- no executables, can be deleted (Dietze)
- [ ] DALEC Wisc @ankurdesai 

Note: more involved database updates may be required if those models have been used in runs -- that will probably require some command-line PSQL to do record updates.

**Comment by dlebauer** [comment]
Note that Scott wrote a function for removing duplicates PecanProject/bety#185

Not sure if it works across databases

**Comment by mdietze** [comment]
Thanks for the suggestion David. I think in all cases each individual just needs to update records that are on their own databases, rather than needing to update records on someone else's machine

**Comment by robkooper** [comment]
There are 61 workflows that depend on ED v80, all of them from BU, most of it seem to from @bcow and @apourmok. If you goto history and use "ED2.2 80" as search term and make sure that you enable "unknown state" you should be able to see all those runs.

**Comment by mdietze** [comment]
@robkooper I just deleted all those ED2.2 80 runs, but I don't have permissions to delete the Model record on betydb.org. Could you do that?

**Comment by serbinsh** [comment]
BNL has now complied with the changes
