### ISSUE TITLE
sensitivity filename function throwing errors

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#916]
During the Flux Course a number of students encountered errors in the SENSITIVITY post-processing because the function creating the filenames is occasionally generating an invalid path. This needs additional testing and testthat build tests to ensure the bug doesn't return.

**Comment by robkooper** [comment]
Any specific settings that people had?

**Comment by mdietze** [comment]
Demo 2 of the tutorial (Niwot Ridge, Ameriflux met)
