### ISSUE TITLE
Database constraint conflict in parameter DA

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#922]
When doing PDA with multiple years of data, if those data are entered as separate inputs in the XML it causes a database table conflict. Specifically, the Likelihood table has a constraint on (run, variable, input) which fails if the same input has multiple years.  Probably need to have multiple ```<path>``` entries within a single ```<file>``` block. Not sure if that's how it's supposed to work right now -- how to set up the PDA xml for that isn't well documented (or if it is, I didn't find it)

**Comment by istfer** [comment]
I'm on my way to UNDERC, I'll take a look at it when I'm by my computer. But the example in the vignette was for multiple years of the same input and it is exactly set up the way you described I think https://github.com/PecanProject/pecan/blob/master/modules/assim.batch/vignettes/AssimBatchVignette.Rmd

**Comment by mdietze** [comment]
Got it. Let's update the tutorial and the gitbook: https://pecan.gitbooks.io/pecan-documentation/content/users_guide/advanced_users_guide/PEcAn-Configuration.html
