### ISSUE TITLE
PDA demo: summary, burnin, chains

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#931]
In the PDA demo, we need to show clearly how to get the summary statistics of the parameter estimates. Perhaps a posterior summary(), cov(), and cor() should be written out in ASCII form by default? 

Related, the demo needs to show folks how to remove the burn-in -- perhaps we should be doing that automatically for the figures and stats?

Likewise, we should probably be writing out BGR stats. To do that we'd also need to set up the demo to run > 1 chain. Is that possible with the emulator code right now? Obviously we can just run the mcmc multiple times and then merge the outputs post-hoc.

Oh, and it would also be good for the demo to show them how to run the MCMC longer if it hasn't converged.

**Comment by dlebauer** [comment]
The broom package auto formats lots of r model summary objects as tables. I
recall at least one other similar package

**Comment by bpbond** [comment]
+1 on using `broom`.

**Comment by dlebauer** [comment]
Also, note that the meta-analysis follows Gelman's recommendations to remove the first half of each MCMC chain; this is done before any plots or statistics are computing. 

This could be a good place to ensure that methods such as how much to burn in and what the GBR threshold is are consistent (to the degree that consistency is appropriate) across packages.

**Comment by istfer** [comment]
@dlebauer @bpbond I haven't used the package before, does tidyMCMC{broom} give anything else besides the estimate, std.error, conf.low, conf.high? it doesn't spit our cov() or cor() I guess right?

for the burnin: we were discarding 20% of the chain if not specified, @mdietze would you like this threshold to be 50%?

**Comment by mdietze** [comment]
No, I think the 50% recommendation is silly. I'd prefer that we check for convergence and burn in explicitly. I've got some code for that floating around (I think in the forecast class activities) but I know that's also in some of the newer R packages as well -- @ashiklom and @bcow mentioned this at one point recently

**Comment by ashiklom** [comment]
Martyn Plummer has a new runjags package that seems very promising, but
it's in relatively early stages of development and has some bugs. I forked
it back in June and fixed a few minor things (github.com/ashiklom/runjags),
but that fork is probably out of date by now.
