### ISSUE TITLE
data.atmosphere installation fails

### ISSUE THREAD

**Issue by Viskari** [PecanProject/pecan#956]
[tviskari@modex pecan]$ R CMD INSTALL PEcAn.data.atmosphere_1.4.7.tar.gz
- installing to library ‘/data/home/tviskari/R/library’
- installing _source_ package ‘PEcAn.data.atmosphere’ ...
  *\* R
  Even after going through with Shawn the pecan dependencies, my data.atmosphere installation still fails with the following error message. Any suggestions what is happening?

*\* inst
*\* preparing package for lazy loading
*\* help
**\* installing help indices
  converting help for package ‘PEcAn.data.atmosphere’
    finding HTML links ... done
    download.Ameriflux                      html
    download.AmerifluxLBL                   html
    download.CRUNCEP                        html
    download.FACE                           html
    download.Fluxnet2015                    html
    download.FluxnetLaThuile                html
    download.GFDL                           html
    download.PalEON                         html
    met2CF.FACE                             html
    met2CF.csv                              html
    metgapfill                              html
*\* building package indices
*\* testing if installed package can be loaded
Error in namespaceExport(ns, exports) :
  undefined exports: AirDens, cfmet.downscale.daily, cfmet.downscale.subdaily, cfmet.downscale.time, closest_xy, download.MsTMIP_NARR, download.NARR, exner, extract.nc, get.es, get.lv, get.ncvector, get.rh, get.vpd, lightME, load.cfmet, met.process.stage, met2CF.NARR, par2ppfd, permute.nc, qair2rh, read.register, rh2qair, solarMJ2ppfd, sw2par, sw2ppfd, wide2long
Error: loading failed
Execution halted
ERROR: loading failed
- removing ‘/data/home/tviskari/R/library/PEcAn.data.atmosphere’

**Comment by dlebauer** [comment]
did you try updating the documentation:
devtools::document('modules/data.atmosphere')?

**Comment by serbinsh** [comment]
@dlebauer do you think the namespace needs updating?  It does look like there are several "unknown" functions listed.....

**Comment by tonygardella** [comment]
Package currently can be installed independently using R CMD INSTALL
