### ISSUE TITLE
New issue in meta-analysis: missing ending parenthesis?

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#958]
```
2016-08-04 17:22:50 INFO   [FUN] :
   1 observations of clumping_factor
2016-08-04 17:22:50 INFO   [FUN] :
   191 observations of SLA
Error: unexpected '{' in "if(!is.null(settings$meta.analysis) {"
2016-08-04 17:22:50 INFO   [FUN] :
   SLA gamma 5.1300 0.2340 593
2016-08-04 17:22:50 INFO   [FUN] :
   number of observations per trait for Optics.Temperate_Early_Hardwood
2016-08-04 17:22:50 INFO   [FUN] :
   1 observations of clumping_factor
2016-08-04 17:22:50 INFO   [FUN] :
   191 observations of SLA
Error: unexpected '{' in "if(!is.null(settings$meta.analysis) {"

```

**Comment by serbinsh** [comment]
This was during an ED2 PEcAn run.

**Comment by serbinsh** [comment]
it looks like this is due to a missing ) in the call:

if(!is.null(settings$meta.analysis)

where it needs a ) after like

if(!is.null(settings$meta.analysis)) {

...

}

**Comment by mdietze** [comment]
Are you pushing a fix or are you going to tell us where the error is?

**Comment by serbinsh** [comment]
I am working on the fix right now (I hope).  It was in the web workflow.R file, which I realized after grep

**Comment by serbinsh** [comment]
After making the change I hit this

2016-08-04 17:30:29 INFO   [FUN] :
   191 observations of SLA
Error: could not find function "runModule.run.meta.analysis"
