### ISSUE TITLE
host vs. hostname again

### ISSUE THREAD

**Issue by rykelly** [PecanProject/pecan#986]
The `hostname` argument [here](https://github.com/PecanProject/pecan/blob/master/utils/R/convert.input.R#L158) needs to be a host object, because otherwise `remote.execute.R()` can end up passing just a string to `remote.copy.to`/`remote.copy.from`, both of which are looking for a host object. 

Can someone more familiar with `convert.input` (@bcow?) fix this without breaking the many other uses of `hostname` (as a string) within that function?

**Comment by bcow** [comment]
I'm not entirely sure I understand the host object - where is it defined? If there is a specific host class object then I should make sure it's properly defined in `met.process` as well as `convert.input`. @rykelly @mdietze

**Comment by rykelly** [comment]
I think it would be good if there was a formal `host` class, but no there's not. It's just the list of host settings that you normally find in a PEcAn settings list. (i.e. `settings$host`).

**Comment by bcow** [comment]
oh ok got it

**Comment by robkooper** [comment]
The host section in PEcAn contains: hostname, username, tunnel and are used for remote actions.

**Comment by bcow** [comment]
I can't close the issue.

**Comment by dlebauer** [comment]
@bcow I assume you want it closed? So I'll close it.

Since GitHub restricts closing an issue, one way is to just add the 'done' tag to indicate doneness.
