### ISSUE TITLE
Github Issue submission from Web interface

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#989]
Being able to submit an issue straight from the web interface was a feature requested at the PEcAn workshop. @mdietze added a button to the interface to do this but it requires the user to have a github account. @mdietze found a solution to this problem [here](https://gist.github.com/SimonGoring/5377ecbc5d30c0a1ad12885b52471ed7). It integrates google forms with github issues.

**Comment by tonygardella** [comment]
I imagine the form will have two options: 
1. Report a Bug
     -    Paste last lines of workflow.R.out 
     -    Ask for Model, Site, Years ( or automatically paste in pecan.xml)
2. Request a feature
     -    Description of feature
Then a section to add Name and email address.

**Comment by rahul799** [comment]
@dlebauer, I will like to work on this issue. Please assign this to me.

**Comment by mdietze** [comment]
@rahul799 PR to the webpage repository achieves this for the PEcAn webpage. Great job @rahul799 👍 

Now that the hard work is done, would be good to embed that same link in the PEcAn GUI web interface, replacing the current "Bug Report" link that takes you the the Github Issues (see bottom of example screenshot)

![image](https://user-images.githubusercontent.com/3081466/72344641-be61c580-369f-11ea-8cb7-c8aa7d07b6a1.png)

**Comment by rahul799** [comment]
@mdietze Thank you for the appreciation. I have made a PR #2516 . Please let me know if you want any more changes, I will be happy to solve it.

**Comment by mdietze** [comment]
PR #2516 closes this issue. Thank @rahul799
